### ISSUE TITLE
"util" as dependency while installing from NPM, instead of "text-encoding"

### ISSUE THREAD

**Issue by pgAdmin** [sinonjs/sinon#1003]
Github shows the following in "package.json"

  "dependencies": {
    "formatio": "1.1.1",
    "lolex": "^1.4.0",
    "samsam": "^1.1.3",
    "text-encoding": "0.5.2"
  }

But on NPM, it shows the following:
Dependencies (4)
samsam, lolex, util, formatio

Since, util is a core module of Node, why do we need it separately?
Also, requiring it as dependency is breaking the Meteor application.

**Comment by tarun-batra** [comment]
+1

**Comment by mantoni** [comment]
This has (or had) to do with browser support. With the next major release of Sinon, we're moving to Browserify and that is why this dependency was already removed in the `package.json` on master.

I don't know whether it's easy to remove it also from the current 1.x line. If this is important for you, maybe you can look into an alternative approach?

**Comment by fatso83** [comment]
@pgAdmin : try out the coming 2.0 version and see how that works for you. This will probably not be fixed in the 1.17.x branch.

`npm install --save-dev sinon@next`

**Comment by pgAdmin** [comment]
I just pointed my npm to take from the github repo.
