### ISSUE TITLE
How to Mock Object local to function  ?

### ISSUE THREAD

**Issue by sohimankotia** [sinonjs/sinon#1007]
I have following files :

preference.js

```
var xdb = require("./XDB");
// This is to generate default preferences

function Preference() {

}


Preference.prototype.getCSVData = function(){

    var arr = ["1,2,3,4","123333"];
    return arr ;
};


Preference.prototype.getUser = function(){

    var db = new xdb.XDB();
    return db.getUser();

};

exports.Preference = Preference ;
```

XDB.js

```
function XDB(){

}


XDB.prototype.getUser = function(){
    return "Sohi";
};



exports.XDB = XDB ;
```

Following is the test cases :

```
var sinon = require("sinon");
var chai = require("chai");
var assert = chai.assert ;
var p = require("../preference.js");
var XDB = require("../XDB");


describe("Preference Converter",function(){



    it("should get user from xdb",function(){


        var stub = sinon.stub(XDB.prototype, 'getUser');
        stub.returns('Google');

        var pref = new p.Preference();
        var name = pref.getUser();

       // expect(xdb.getUser).to.have.been.calledOnce;
        assert.equal(name,'Google');
        stub.restore();

    });



});

```
While running this test case I am getting following error :

**TypeError: Should wrap property of object at Object.wrapMethod (/home/user/node_modules/sinon/lib/sinon/util/core.js:67:23) at Object.stub (/home/user/node_modules/sinon/lib/sinon/stub.js:67:26) at Context. (From NodeJs in Action/test/prefTest.js:17:26)**

I am new to nodejs and sinonjs and trying to find out how to stub XDB object inside method of Preference's getUser .

Thanks in advance .

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
----

That being said, you are not using CommonJS right. Reading the error message makes this obvious.

Change this
```
exports.XDB = XDB ;
```

into this
```
module.exports = XDB ;
```

and it should work.

**Comment by sohimankotia** [comment]
Thanks for pointing to right forum .
