### ISSUE TITLE
Sandbox useFakeXMLHttpRequest returns a Server

### ISSUE THREAD

**Issue by jridgewell** [sinonjs/sinon#1008]
This is a bit unexpected, since `sinon.useFakeXMLHttpRequest` returns the Fake XHR object.

**Comment by mantoni** [comment]
Yes, I agree. I think this is for historic reasons. There is [this line in the current sandbox implementation](https://github.com/sinonjs/sinon/blob/master/lib/sinon/sandbox.js#L138):

```js
sinonSandbox.useFakeXMLHttpRequest = sinonSandbox.useFakeServer;
```

We are currently in the process of re-shaping the [API for Sinon 2.0](https://github.com/sinonjs/sinon/issues/1000). The current draft only lists `useFakeServer` on the sandboxes.

Do you think there should be `useFakeXMLHttpRequest` support on sandboxes or did you just want to point out the inconsistency?

**Comment by jridgewell** [comment]
> Do you think there should be useFakeXMLHttpRequest support on sandboxes or did you just want to point out the inconsistency?

The inconsistency mainly. We had switched from using `sinon.useFakeXMLHttpRequest` to the sandbox and couldn't figure out why `#onCreate` wasn't being called anymore.

If there's only a fake server and not a fake XHR anymore, it would have been a little easier to figure out.

**Comment by mantoni** [comment]
Related PR: https://github.com/sinonjs/sinon/pull/1010
