### ISSUE TITLE
IE8 issue with Object.getOwnPropertyDescriptor

### ISSUE THREAD

**Issue by james-simpson** [sinonjs/sinon#1009]
In IE8 we get a failure when trying to stub a non-DOM object. This is because IE8 does not support Object.getOwnPropertyDescriptor on non-DOM objects. See https://msdn.microsoft.com/en-us/library/dd548686(v=vs.94).aspx

Could this be changed in some way to solve this? I have included a code sample to reproduce the issue and below that a suggested fix.

More generally sinon states that it supports IE6+ but this issue demonstrates it doesn't. Also note that the usage of Object.getOwnProperty() or Object.getPrototypeOf() in sinon.js would also fail on IE8 or below. Is sinon still intended to work in IE6+?

Issue sample (tested using sinon 1.17.3):

```
// This fails in IE8 - "Object doesn't support this action".
var a = { key : "value" };
var b = Object.getOwnPropertyDescriptor(a, 'key');
console.log(b);

// This fails in IE8 - "Object doesn't support this action".  
// Note - sinon.stub() calls sinon.getPropertyDescriptor() which calls Object.getOwnPropertyDescriptor().
var c = { key : "value" }
var d = sinon.stub(c);
```

A possible fix might be to conditionally allow sinon.getPropertyDescriptor to follow a slightly different execution path where it did e.g.:
(Note - untested.  Unsure if this is at all viable.)

```
sinon.getPropertyDescriptor = function getPropertyDescriptor(object, property) {
            return {
              configurable : true,
              writable : true,
              value : object[property],
              enumerable : true
            }
        }

      var c = { key : "value" }
      var d = sinon.stub(c);
(Because IE8 doesn’t support Object.getOwnProperty() or Object.getPrototypeOf()).
```

**Comment by PeteST** [comment]
Also an issue for us.  Any contributors please able to advise?

**Comment by rodneyrehm** [comment]
It seems IE9 has similar issues:

```js
// This works in IE9
var a = { key : "value" };
var b = Object.getOwnPropertyDescriptor(a, 'key');
console.log(b);

// This fails in IE9 - "Object doesn't support this action".
var c = Object.getOwnPropertyDescriptor(console, 'log');
console.log(c);
```

The IE9 issue with console is likely related to #386.

**Comment by PeteST** [comment]
Anyone able to update?  Thanks.

**Comment by fatso83** [comment]
The code provided by @james-simpson could be an alternative to try out. If anyone would like to submit a PR with a testcase that fails in IE8 that would be great. Seems like we might need to add a browser version to our sauce labs test.

**Comment by jakerella** [comment]
Same issue here. I'll try to submit a PR with a test case some time soon, but here is the line I'm trying that fails:

`sinon.stub(window.console, 'info');`

**Comment by mroderick** [comment]
Legacy IE doesn't like it when you mess with globals (nor does legacy Firefox).

If you need to stub out globals, I'd recommend using a thin wrapper around them, and then make the wrapper the target of your stubbing.

Shameless self-promotion: I've created a [generic wrapper named `wrapple`][wrapple] for exactly this purpose.

[wrapple]: https://github.com/mroderick/wrapple

This doesn't solve this isssue #1009, but it might be a solution for @jakerella's use case with stubbing console methods.
