### ISSUE TITLE
sinon.test eats errors thrown in the first tick of an async test

### ISSUE THREAD

**Issue by RobertWHurst** [sinonjs/sinon#1015]
Throwing an error in an async function does not get re thrown by sinon.test.

For example, the following mocha test times out instead of failing with an error.
`it('should do something', sinon.test((done) => throw new Error('should have blown up'))`

I'm using
- Node v5.5.0
- Sinon v1.17.3
- Mocha

**Comment by RobertWHurst** [comment]
After investigating the issue further, it seems this issue is caused by mocha. Mocha uses the length of the arguments from the test function to see if it takes a callback. The sinon sinon.test method returns a function that has a length of 0. Mocha then assumes the test is synchronous and doesn't pass a callback.

**Comment by RobertWHurst** [comment]
Read a bit more of the source. Seems like the library should check for and handle this case. I'll look into it further...

**Comment by fatso83** [comment]
This is fine, but would you mind moving the issue to the [sinon-test](https://github.com/sinonjs/sinon-test) project? `sinon-test` has been moved out of core for Sinon 2 to focus on the core issues here.

**Comment by RobertWHurst** [comment]
Sure thing
