### ISSUE TITLE
stub.restore() is forcing the underlying method to execute

### ISSUE THREAD

**Issue by cludden** [sinonjs/sinon#1024]
**info**
- node (v5.5.0),
- sinon (v1.17.3),
- other libraries: 
  - mocha,
  - sinon-chai

**issue**
I have a service with a method I need to stub
```javascript
// in services/vault.js
{
    // ..
    encrypt(plaintext, context, cb) {
        console.log('encrypt called');
        // ..
    }
    // ..
}
```
the stub works correctly, however, when I call the stub's `restore` method, it is causing the underlying method to be executed. example:
```javascript
it('should fail if there is an error validating the password', function(done) {
    this.timeout(10000);
    sinon.stub(Users, 'findOne').yieldsAsync();
    sinon.stub(Validate, 'password').yieldsAsync(badRequest);
    sinon.stub(Validate, 'phoneNumber').yieldsAsync(null, '');
    sinon.stub(Vault, 'encrypt').yieldsAsync(null, '');
    console.log('calling method');

    User.createNewUser(userData, function(err) {
        expect(Validate.password).to.have.been.called;
        expect(err).to.have.property('status', badRequest.status);
        expect(err).to.have.property('title', badRequest.title);
        Users.findOne.restore();
        Validate.password.restore();
        Validate.phoneNumber.restore();
        console.log('about to restore');
        Vault.encrypt.restore();
        setTimeout(function() {
             console.log('done restoring');
             done();
         }, 1000);
     });
});
```
**expected output**
```javascript
calling method
about to restore
done restoring
```
**actual output**
```javascript
calling method
about to restore
encrypt called // this should not be here
done restoring
```

**Comment by fatso83** [comment]
Hmm ... AFAIK there is nothing I know of in [`restore`](https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/restore.js) that should do this. Maybe there is something in [`./walk`](https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/walk.js) that does this? It would be a lot simpler to investigate this if you could provide some executable code that displays the problem, like a gist or a jsfiddle.

**Comment by cludden** [comment]
After further testing, I don't think this is an issue with `restore`. It actually appears to be an issue with `async.js`. The method under test has a top level `async.auto` with a nested `async.auto`. like so:
```javascript
createNewUser(data, options, cb) {
    let Vault = mycro.services.vault;
    console.log(Vault.encrypt); // stubbed function
    async.auto({
        // ..
        process: ['previousTask', function(fn, r) {
            async.auto({
                 encryptPhone: function(fn) {
                      console.log(Vault.encrypt); // not stubbed function
                 }
            });
        }],
        // ..
    });
}
```

If i call the stubbed method directly from the nested `async.auto`, it is not stubbed, but if i store a reference to the stubbed method outside of the top level `async.auto` and execute it directly in the nested one, it works as expected.
