### ISSUE TITLE
Sinon.xhr progress events do not fire if attached before send()

### ISSUE THREAD

**Issue by tarjei** [sinonjs/sinon#1027]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.
- Sinon version : 1.17.2
- Environment   : Linux, phantomjs 2.1 / Chrome
- Example URL   : 
- Other libraries you are using:
  Babel, node etc.

**What did you expect to happen?**
Progress events should fire

**What actually happens**
Progress events does not fire

**How to reproduce**

``` javascript
    xhr.addEventListener('progress', this.updateProgress, false)
    xhr.addEventListener('load', this.transferComplete, false)
    xhr.addEventListener('error', this.transferFailed, false)
    xhr.addEventListener('abort', this.transferCanceled, false)

    xhr.open('POST', this.file.url)
    xhr.setRequestHeader('X-XSRF-TOKEN', readCookie('XSRF-TOKEN'))
    xhr.send(formData)
```

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress shows calling `addEventListener` before the `open()` call.

After some fiddling, I got the following sequence to work:

``` javascript
    var xhr = new XMLHttpRequest()
    var formData = new FormData()
    formData.append('files[]', this.file.file)
    console.log("upload(): POST", this.file.url, this.dispatch)

    xhr.responseType = 'json'

    //xhr.addEventListener('progress', this.updateProgress, false)
    xhr.addEventListener('load', this.transferComplete.bind(this), false)
    xhr.addEventListener('error', this.transferFailed.bind(this), false)
    //xhr.addEventListener('abort', this.transferCanceled, false)

    xhr.open('POST', this.file.url, true)
//    xhr.setRequestHeader('X-XSRF-TOKEN', readCookie('XSRF-TOKEN'))
    xhr.send(formData)

```

Now, I'm not quite sure what happens here and why one fires the events and another does not so please enlighten me :)

**Comment by mroderick** [comment]
I am not sure I understand. The expectation is that progress events fire, but in the example you got to work, you're not listening to progress events. If we're not listening to progress events, how can I determine if they fire or not?

**Comment by fearphage** [comment]
Could you setup a jsbin/jsfiddle showing the broken behavior?

**Comment by mroderick** [comment]
Hey @tarjei, would you mind setting up a runable example to show the broken behaviour?

**Comment by mroderick** [comment]
This has seen no repsonse from @tarjei in more than a year, I am closing it

**Comment by tarjei** [comment]
@mroderick I'm sorry!

I got swamped with other stuff. 

I seem to remember that after some more work on this I ended up understanding that it had to do with the content type of the request, but I cannot recall how.

**Comment by mroderick** [comment]
> @mroderick I'm sorry!
> 
> I got swamped with other stuff.
> 
> I seem to remember that after some more work on this I ended up understanding that it had to do with the content type of the request, but I cannot recall how.

No worries, life happens to all of us.

There's a record of a potential bug here, so future contributors can find the discussion and pick it up if the bug shows up again :)
