### ISSUE TITLE
stubbing request object

### ISSUE THREAD

**Issue by svlungade** [sinonjs/sinon#1028]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version :latest

**What did you expect to happen?** - Stub the call of request method

**What actually happens** - gives an error

**How to reproduce**
----------------------------------------------------------------------------------------------------------
var helloWorld = exports.helloWorld = function(){
var request = require("request");
var url = "localhost:3000/helloWorld"
  request(url, function(error, response, body) {
    if (!error && response.statusCode === 200) {
       // do something
    }
  });
}

how do i stub the request call.

**Comment by mroderick** [comment]
See https://github.com/sinonjs/sinon/issues/753#issuecomment-103659325, it applies perfectly to this question.

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by fatso83** [comment]
@mroderick Maybe we should leave room for some more elaborate examples on the upcoming new documentation site?

@svlungade you could also find a quite relevant example of what you are trying to accomplish [here](https://gist.github.com/fatso83/329da40002d45533b1e74db825f2bf54) (multi-file gist).

**Comment by mroderick** [comment]
> @mroderick Maybe we should leave room for some more elaborate examples on the upcoming new documentation site?

Agreed. I've been thinking about creating a section with recipes

**Comment by svlungade** [comment]
@fatso83 yes, the issue is resolved now, I have used mockery for it.

1.	Always have the declaration of module - e.g. require(‘module’) - statement inside the method which you are trying to unit test. If you don’t have it inside method, nothing can be stubbed, it is already declared!!

**The unit test code - 
**
var mockery = require('mockery');
describe("executing unit test case for request module stubbing ", function(done) {
       var requestStub;
       it("gets sample method name ", function() {
              //Initialize mockery
              mockery.enable();

              //Prepare the stub, and its return values
              var response = {};
              response.statusCode = 200;
              var bodyObj = {sampleOutputGoes : "here" };
              requestStub = sinon.stub().yields(null, response, bodyObj);
              
              //Now replace the request call with stub
              mockery.registerMock('request', requestStub);
              
              //Actual method call
              unitTestFileName.methodNameforUnitTest('http://localhost:3000',{abcd:1234},'dummy',function(err,result){
                     if(err){
                           console.log('ERROR::' + err);
                           done(err);
                     }
                     //validate the results
                     requestStub.called.should.be.equal(true);
                     result.should.not.be.empty;
                     result.should.have.property(statusCode);
                     done();
              });
              //disable mockery
              mockery.disable();
       });
});
