### ISSUE TITLE
Unable to stub a ES6 constructor mocking the return

### ISSUE THREAD

**Issue by samuelcastro** [sinonjs/sinon#1035]
After stub a es6 class, I want to mock the return value when instantiating it. Is there a way to use something like:

`ResourceStub = sinon.spy(() => sinon.createStubInstance(class {constructor() {}}))`
`ResourceStub.constructor.returns({test: true})`

So whenever ResourceStub be instantiated the return will be `{test: true}`

**Comment by fatso83** [comment]
I really do not understand what you are trying to do, but I do see you are misunderstanding what the constructor property in ES6 does. Please [read and understand this thread](https://github.com/sinonjs/sinon/issues/831) on a similar issue. It might shed some light on what you are trying to do.

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
