### ISSUE TITLE
object arguments passed to stubs should be cloned or otherwise preserved

### ISSUE THREAD

**Issue by minispeck** [sinonjs/sinon#1044]
* Sinon version : 1.17.2
* Environment   : node
* Other Modules: chai, sinon-chai, sinon-promise

**What did you expect to happen?**
myStub.firstCall.args would accurately reflect the exact arguments myStub was called with

**What actually happens**
myStub.firstCall.args[0] is a *reference* to the object provided as the first argument in the first call of myStub

when that object changes later in code, the reference changes too, and no longer accurately reflects what myStub was called with

**How to reproduce**
```
var myStub = sinon.stub();
var o = {};
myStub(o);
o.something = true;
expect(myStub.firstCall.args[0]).not.to.have.property('something');
```

**Comment by mantoni** [comment]
This was discussed in #583 and #571. The outcome of those discussions was that this is basically an unsolvable problem.

**Comment by mantoni** [comment]
Also worth noting: There is another related discussion with a proposal that takes an interesting approach in #665.

**Comment by minispeck** [comment]
I disagree that the 'problems' with cloning mentioned in those threads cannot be overcome:

>However, the problem is not only that creating a copy is close to improssible to get right, 

lodash.cloneDeep would like a word with you for objects at least, and there are other ways around this issue for arrays

>you might also want to do strict equality checks which you couldn't do anymore.

you already can't do that with arrays and objects as in javascript {} !== {} and [] !== [].
to.deep.equal still works on copies

>solving" it would even go against the grain of the language.

this just isn't true. making a clone doesnt go against the grain of the language, especially when you would expect the args[] array to capture a moment in time so to speak.

it feels like this was given an early death in those threads for fairly poor reasons.
