### ISSUE TITLE
[Feature request] stub emits

### ISSUE THREAD

**Issue by perrin4869** [sinonjs/sinon#1045]
In addition to `returns`, `yields`, `throws`, etc, when stubbing a method, i.e., `stub(obj, 'method')`, it would be useful to specify an `emits` behavior, such as, for example:

```js
const obj = require('obj');
const stub = sinon.stub(obj, 'method').emits('some event', arg1, arg2);
const spy = sinon.spy();

obj.on('some event', spy);
obj.method();
expect(spy.calledOnce).to.equal(true);
expect(spy.firstCall.args).to.deep.equal([arg1, arg2]);
```

Does this seem feasible? I could try to make an implementation of this, just not sure how feasible it is realistically.

**Comment by mantoni** [comment]
You can use any event emitter for that. Either stub `on` or even better, simply call `emit` on the emitter in your test code.

**Comment by mantoni** [comment]
Here are two ways how you can do it in your particular example:

```js
const stub = sinon.stub(obj, 'method', function () {
  obj.emit('some event');
});
```

Alternatively:

```js
const stub = sinon.stub(obj, 'method');
// ...

obj.method();
obj.emit('some event');
```

It would be out of scope for Sinon to add library or environment specific logic for something like event emitters.

If you have more questions about best practices on how to use Sinon with event emitters, please post questions on the  [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

**Comment by perrin4869** [comment]
Got it, thanks!!

**Comment by aleung** [comment]
Another approach, if you have to use `sinon.createStubInstance` for some reason: make use of npm module [extend](https://www.npmjs.com/package/extend):

``` js
import * as extend from 'extend';
import * as events from 'events';

const stub = sinon.createStubInstance(MyClass);
extend(stub, events.EventEmitter.prototype);

stub.on('event', () => { /* do something */ });
stub.method();
stub.emit('event');
```
