### ISSUE TITLE
IE shim may break Chrome 50?

### ISSUE THREAD

**Issue by andrewplummer** [sinonjs/sinon#1048]
- Sinon version : 1.17.3/4
- Environment   : Chrome 50.0.2661.102
- Example URL   : http://codepen.io/andrewplummer/pen/JXQNGd

Apologies in advance if I'm missing something major, but it seems a bug was introduced in the newest version of Chrome where if you add the IE shim, the global Date object loses all properties. I believe it's essentially being set to the noop function in the shim and the line `Date = sinon.timers.Date;` is not managing to set the global object.

I had been using the same version of both sinon.js and sinon-ie.js (loaded one directly after the other in the source) for a quite a long time and they suddenly stopped working in Chrome. Firefox seems to be working properly.

For now planning on working around by wrapping sinon-ie.js in a conditional comment.

**Comment by fatso83** [comment]
Thanks for the heads up. If this is the case, then we will soon start seeing more of this ...

**Comment by fatso83** [comment]
If we are able to find a decent patch for this, a doable hack might be to do browser sniffing and refuse to load (return early) in non-ie browsers.

**Comment by andrewplummer** [comment]
Poking around a bit more, it seems to have appeared somewhere between v48 and v49.

**Comment by jhartikainen** [comment]
Ran into this as well. Possibly related to https://github.com/sinonjs/sinon/pull/858
