### ISSUE TITLE
withArgs(sinon.match()) doesn't use last defined return definition

### ISSUE THREAD

**Issue by jishi** [sinonjs/sinon#1053]
- Sinon version : 1.17.4
- Environment   : OS X
- Example URL   : 
- Other libraries you are using:

**What did you expect to happen?**

I would expect that the last withArgs return declaration to to have precedence when multiple declarations would match the invocation.

**What actually happens**

The first one seems to have precedence opposed to when you are using strict values instead of sinon.match

**How to reproduce**

```
var x = sinon.stub().returns(1);
x.returns(2);

x() // -> 2

var x = sinon.stub();
x.withArgs(1).returns(1);
x.withArgs(1).returns(2);

x(1) // -> 2

var x = sinon.stub();
x.withArgs(sinon.match('1')).returns(1);
x.withArgs(sinon.match('1')).returns(2);

x('1') // -> 1 (wat?)
```

Probably due to that "strict" declarations actually overwrite the withArgs precondition, and that is not possible with match-objects. However, if they were applied on the opposite order (last defined, first matched), it would match the normal behavior, I think.

**Comment by fatso83** [comment]
Thanks for reporting. I am unsure if this should be fixed in v1.17 in case anyone relies on this behavior, but a fix for this could be put into `master` for the upcoming 2.0 release which features some breaking changes.

**Comment by jishi** [comment]
Yeah, since the behavior seem to be undocumented, there is no "fact" to base it on. In an ideal world, it would be even better if it would work like css selectors, meaning most detailed match would have precedence but I have no idea on how that would actually be implemented...

**Comment by fatso83** [comment]
"Most detailed" would be very hard, especially given javascript's dynamic typing and type conversion rules. If you could patch the basic case (the one submitted) then that would be a candidate for 2.0.

**Comment by fatso83** [comment]
@jishi : do you think you could supply us with a patch? seems you have a good idea on solving this.

**Comment by jishi** [comment]
I can look into it. It should go in the master branch then?

**Comment by fatso83** [comment]
Help is always welcome. `master` is the right branch. We might backport it, of course. 

This might be related to #817.

**Comment by mroderick** [comment]
Hey @jishi, any chance of getting a PR for this issue?

**Comment by jishi** [comment]
I haven't had time to look at it, but I'll free up some time before end of the week.

**Comment by jishi** [comment]
Seemed easier than anticipated, made a pull request for review
