### ISSUE TITLE
Calling different callbacks for stub on firstcall and second call

### ISSUE THREAD

**Issue by rnagpal** [sinonjs/sinon#1058]
I'm looking for a way in sinon to call different functions in first and second call to the stub method.

Here is an example:

var func1 = function(connectionPolicy, requestOptions, callback) {
                callback({ code: 403 });
            }
            
var func2 = function (connectionPolicy, requestOptions, callback) {
                callback(undefined);
            }

var stub = sinon.stub();
// Something of this form
stub.onCall(0) = func1;
stub.onCall(1) = func2;

request.createRequestObjectStub = stub;

So that when request.createrequestObjectStub gets called internally(when calling a public API), I see this behavior.

Regards,
Rajesh

* Sinon version : 1.17.4
* Environment   : Node JS
* Example URL   : 
* Other libraries you are using:

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
