### ISSUE TITLE
Unable to use sinon due to fake server unsafe cookie checks

### ISSUE THREAD

**Issue by andpor** [sinonjs/sinon#1061]
Hi,

Currently sinon seems to have hardcoded logic to check http requests for unsafe cookies and rejects the headers should they match what is considered unsafe. There is no way to disable this check in case there is a need for it which renders the fake server with http request unusable.

It would be great to make this configurable, enabled by default.

I implemented a code change where unsafeCookieCheckEnabled property is added to sinon, defaulting to true but overridable by user code. The code in FakeXMLHtppRequest then checks this property value before engaging in unsafeCookie check.

2 lines of code change. Backward compatible and safe.

Should I go ahead and create a PR for this?

P.S. I have a React Native PR outstanding for a few days. Are you planning on merging it in or you se issues with the code or not finding the functionality particularly useful?

**Comment by fatso83** [comment]
This seems useful, but try to make it a non-global change. In other words, change the factory method creating the server to accept such an option. I haven't looked at the code, so details may be off... 

ReactNative your pull request : this happens. We only do this voluntarily so things can take some time. Your team could always just use your fork while waiting.
