### ISSUE TITLE
[Feature request] called, calledOnce return promises for better async testing

### ISSUE THREAD

**Issue by perrin4869** [sinonjs/sinon#1067]
When it comes to integration tests, async calls are inevitable. The issue is clearly shown [here](https://gist.github.com/virtualandy/8e3665068469524357f7). Transcribing:

```js
import Promise from 'bluebird';
import chai, { expect } from 'chai';
import sinon from 'sinon';

chai.use(require("sinon-chai"));

async function asyncHello(name, delay, cb) {
  await Promise.delay(delay);
  console.log("running after ", delay);
  cb("hello " + name);
}

describe('Mega Suite', function(){
  it("tests async hello", function() {
    test('should call the callback', function(done) {
      var cb = sinon.spy();
      asyncHello("foo", 500, cb);

      expect(cb).to.have.been.called(); // Fails unless you wait 500ms
      done();
    });
  });
});
```

What I propose is to have spies properties like `called`, `calledOnce`, etc, be promises, or have promise counter-parts, which resolve when the spy is called. This would allow for the following syntax:

```js
chai.use(require("chai-as-promised"));

describe('Mega Suite', function(){
  it("tests async hello", function() {
    test('should call the callback', async function(done) {
      var cb = sinon.spy();
      asyncHello("foo", 500, cb);

      await cb.called;

      // or checking the args with chai-as-promised
      await expect(async.called).to.eventually.have.property('args').and.eql(['running after 500']);

      // or a better syntax, not use it's possible with sinon-chai
      expect(cb).to.evetually.have.been.calledOnceWith('running after 500');

      done();
    });
  });
});
```

I don't know about the feasibility of this feature in sinon, but it would greatly improve async test writing as usually found in integration tests. For your consideration.

**Comment by perrin4869** [comment]
The above can be solved very elegantly using bluebird's `Promise.fromCallback` - closing this.

**Comment by fatso83** [comment]
You could also check out [Sinon As Promised](https://www.npmjs.com/package/sinon-as-promised)

**Comment by perrin4869** [comment]
hm... `sinon-as-promised` deals more with stubs as far as I know, and not with spies, which is what I addressed in this issue
