### ISSUE TITLE
FakeServer.respond() provides no indication of bad response body when respondWith() is given bad json data

### ISSUE THREAD

**Issue by almightywiz** [sinonjs/sinon#1070]
Sinon Version: 1.7.3

When using the FakeServer.respondWith() feature, I am a little confused as to why an invalid JSON string response body is "allowed"; although I use the word "allowed" loosely.  Basically, if I pass in something other than a String value to the response body argument of FakeServer.respondWith(), there is an immediate validation that occurs stating that a String value is expected.  However, if I pass in a String value of JSON data, no exception is thrown if that JSON data is malformed.  This makes debugging very difficult if one small issue exists in the JSON data, and there is no indication as to why the response never succeeds.

Why does the below function catch the JSON parsing exception and swallow it instead of throwing the exception?  This seems like bad practice, especially when no notification is given to the consuming tests signalling that their body is invalid.

```
function convertResponseBody(responseType, contentType, body) {

    // ...

    } else if (responseType === "json") {
        try {
            return JSON.parse(body);
        } catch (e) {
            // Return parsing failure as null
            return null;
        }
    } else if (supportsBlob && responseType === "blob") {

    // ...

    throw new Error("Invalid responseType " + responseType);
}
```

**Comment by fatso83** [comment]
Hi, and thanks for the report. While I do agree that this might be confusing, it is closely following [the XHR spec] which says that when the browser is unable to decode the content according to the response type it should return null. And we are trying to follow the XHR spec.

[This old article by Mathias Bynens](https://mathiasbynens.be/notes/xhr-responsetype-json) explains it in a bit more detail.
