### ISSUE TITLE
Sandbox resetBehaviour and resetHistory

### ISSUE THREAD

**Issue by Gudahtt** [sinonjs/sinon#1072]
My understanding of issue #806 is that the behaviour of `reset` for stubs was changed to reset both the call history and the stub behaviour. It was decided that `reset` would reset both, `resetHistory` would reset just the call history, and `resetBehaviour` would reset just the stub behaviour.

It would be very convenient for me if these two functions, `resetHistory` and `resetBehaviour`, were made available through the sandbox API. That is, I would like them to be added to `lib/sinon/collections.js` alongside `reset` so that you could reset the history or behaviour of an entire sandbox at once.

Thoughts?

**Comment by mantoni** [comment]
That sounds perfectly reasonable. Care to make it a pull request?
