### ISSUE TITLE
Fake XHR does not work in IE11

### ISSUE THREAD

**Issue by haishengwu-okta** [sinonjs/sinon#1091]
- Sinon version : 1.17.4
- Environment : window server 2012, IE 11
- Other libraries you are using: jasmine-2.4, jquery-1.11

**What did you expect to happen?**
to be able to mock XHR

**What actually happens**
failed to mock XHR

**How to reproduce**

``` javascript
it('test mock xhr', function () {
  var ss = sinon.sandbox.create();
  ss.useFakeServer();

  ss.server.resondWith('GET', '/path/to/test', ...);

  $.ajax({
    url: '/path/to/test', 
    xhr: function(){
                       var xhr = $.ajaxSettings.xhr() ;
                        xhr.upload.addEventListener('progress', self.onProgress, false);
                        xhr.upload.addEventListener('load', self.onComplete, false);
                        return xhr ;
                      }
 });
  ss.server.respond();
});
```

**Comment by jonnyreeves** [comment]
@haishengwu-okta it would be super helpful if you could:

1. Try the code out in another browser (eg: Firefox) to see if you can reproduce the issue.
2. Provide a complete testcase, with assertions that I can run locally to reproduce the issue.

Many thanks.

**Comment by haishengwu-okta** [comment]
@jonnyreeves  
please check this project https://github.com/hw-hello-world/hello-sinon

1. clone the project
2. npm install
3. open `/test/jasmine-sinon.html` in IE Edge
4. test failed (though expect to be successful)
5. switch to IE10 and it succeed.

**Comment by fatso83** [comment]
I have no access to Windows boxes with relevant IE versions, so I cannot look into this, but I think I remember something about stuff breaking in IE11 that ran in previous versions. If you are able to find out what breaks we can perhaps conditionally skip running sinon-ie for newer versions.

**Comment by fatso83** [comment]
@haishengwu-okta I think you missed a step where you start a webserver? Like `python -m SimpleHTTPServer`.

**Comment by haishengwu-okta** [comment]
@fatso83 webserver is not mandatory here.

**Comment by haishengwu-okta** [comment]
This line seems not right for IE11.

```
sinonXhr.GlobalActiveXObject = global.ActiveXObject;
```

http://stackoverflow.com/questions/19638981/window-activexobject-difference-in-ie11

**Comment by fatso83** [comment]
@haishengwu-okta You are probably right about the ActiveX thing, but why should it affect XHR? And does _not_ loading sinon-ie fix things for you in IE11?

**Comment by haishengwu-okta** [comment]
@fatso83 

- It's even worse when adding `sinon-ie-1.17.4.js`

![screen shot 2016-08-01 at 10 57 22 am](https://cloud.githubusercontent.com/assets/13139863/17303743/d29e01f4-57d6-11e6-8918-a1d41ec0eb35.png)

- I tried `sinon-2.0.0-pre` along with `sinon-ie-2.0.0-pre.js`. same error.

**Comment by fatso83** [comment]
Aha, I was assuming `sinon-ie` was loaded all along, as it was previously required for testing XHR using IE. (Assuming you loaded `sinon-ie` _after_ loading sinon-1.17.5.) I will see if I can get hold of a IE box somehow.
