### ISSUE TITLE
calledOnce should fail given extra arguments (to reduce accidental belief of calledWith behavior)

### ISSUE THREAD

**Issue by ClintFMullins** [sinonjs/sinon#1093]
Not really a bug, more of an issue that causes us to create bugs.
* Sinon version : latest
* Environment   : running through node with karma test runner inside sinon-chai
* Example URL   :  -
* Other libraries you are using: - 

**What did you expect to happen?**

We've had the following accident happen many times over the past couple years in our codebase:
`assert.calledOnce(someStub, wrongArg1) // will pass when given wrong args.`

Proposal:
`assert.calledOnce()` should not accept extra arguments, and should fail when they are given like so:
'calledOnce only accepts one argument, did you mean to use calledWith?'

ideally we'd also have a
`calledOnceWith`
`calledTwiceWith`
etc

with the behavior of asserting the stub is called X many times, with the given arguments.

**What actually happens**
`calledOnce(someStub, wrongArg1, wrongArg2)` silently fails given wrong arguments, as currently expected from sinon. 

**How to reproduce**

assert.calledOnce(someStub, wrongArg1) // will pass when given wrong args.

<details>
   none necessary
</details>

I would be happy to add an asserting function that would get called inside function mirrorPropAsAssertion. This function would go to some case statement keying off the method name and given arguments. If you are interested in a PR let me know. If you have a better idea of how to fix (if you agree this is broken) feel free to let me know or fix yourself. I'd like to contribute though :)

**Comment by ClintFMullins** [comment]
`function mirrorPropAsAssertion(name, method, message) {
    if (arguments.length === 2) {
        message = method;
        method = name;
    }

    assert[name] = function (fake) {
        verifyIsStub(fake);

        var args = slice.call(arguments, 1);
        var failed = false;

        if (typeof method === "function") {
            failed = !method(fake);
        } else {
            failed = typeof fake[method] === "function" ?
                !fake[method].apply(fake, args) : !fake[method];
        }

        if (failed) {
            failAssertion(this, (fake.printf || fake.proxy.printf).apply(fake, [message].concat(args)));
        } else {
            assert.pass(name);
        }
    };
}`

**Comment by fatso83** [comment]
Just to clear up some confusion, I think you have mixed up fail and pass in your descriptions.

You *expected* this:
> assert.calledOnce(someStub, wrongArg1) // will pass when given wrong args.

This is what _is_ happening, so nothing wrong.

What actually happens (_according to you_):
> `calledOnce(someStub, wrongArg1, wrongArg2)` silently fails given wrong arguments, as currently expected from sinon.

No, this is not what is happening. This test passes if `someStub` has been called once, no matter the arguments. You might have _wanted_ it to fail (throw an error).

Other than that, I think I understand _your intentions_ 😄 

<hr />

So there are two suggestions: 
1. Calling a new function `verifyIsValidAssertion` that would check the name of the assertion and do additional checks.
2. Add more API methods. 

I think the first suggestion is fine. Just create a PR with the additional checks you think should be in place.

As to the second, I find it a bit unclear what this means:
> asserting the stub is called X many times, with the given arguments.

I think there are at least three interpretations of `calledTwiceWithArguments(foo, 1, 2, 3)`:

```javascript
/* Called twice, and one of those calls was using those arguments */
foo(1);
foo(1,2,3);
``` 

```javascript
/* Called twice, using those arguments in each call*/
foo(1,2,3);
foo(1,2,3);
``` 

```javascript
/* Called at least twice, of which those arguments were used in at exactly two calls*/
foo();
foo(1,2,3);
foo();
foo(1,2,3);
``` 

Other than the ambiguity in naming, we are trying to keep the API surface from growing much more, and I am not certain they are that useful ...

**Comment by mantoni** [comment]
I remember that we decided against this additional API earlier for the same reasons as @fatso83 stated. It's clearer to just have two assertions, one for the call count and one for the argument checks. This allows to specify if the arguments have to be provided in one of the calls or in all of the calls (via `alwaysCalledWith`).

As for the verification of `calledOnce` I agree. I ran into this as well. I'm not sure this needs a generic solution, but a pull request to discuss the feature would be nice.

**Comment by ClintFMullins** [comment]
Thanks guys, I'll open up a PR with the check and we can discuss more there.

**Comment by ClintFMullins** [comment]
(For the record I think `calledTwiceWithArguments(foo, 1, 2, 3)` would undoubtably be asserting that the function foo is called twice with the given arguments. But I understand wanting to keep the API tight.)

**Comment by ClintFMullins** [comment]
Ready for review when you guys get a moment @fatso83, @mantoni

**Comment by fearphage** [comment]
The fix for this was already merged. Thank you, @ClintFMullins.
