### ISSUE TITLE
Sourcemap error in sinon. Has this been seen before?

### ISSUE THREAD

**Issue by TheSavior** [sinonjs/sinon#1094]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version: 1.17.4
* Environment: CI
* Other libraries you are using: karma, karma-source-map-support (source-map)

**What did you expect to happen?** 
No failures

**What actually happens**
```
Uncaught TypeError: Column must be greater than or equal to 0, got -1
      at /tmp/81a76371d25387d45b5b0db72f6d0195.browserify:50990 <- ../node_modules/sinon/lib/sinon/spy.js:187:0
```

**How to reproduce**
I haven't been able to consistently reproduce this, or narrow it down directly to sinon. I'm mostly opening this ticket to put out a feeler if anyone has seen this before. The actual error message comes from [mozilla/source-map](https://github.com/mozilla/source-map/blob/7bc77b042582196e1bc7e950a7f4b4254bbabcd7/lib/source-map-consumer.js#L543) but surprisingly it lists this line in spy.js

```
push.call(this.exceptions, exception);
push.call(this.returnValues, returnValue);
push.call(this.stacks, new Error().stack); // this one
```

**Comment by fatso83** [comment]
I don't think we are the right receiver of this issue. Source mapping is often the source of pointing the finger in the wrong direction, so the evidence of this having anything to do with sinon is vague at best. 

If you are able to dig out some more info that makes it clearer what is exactly happening and why Sinon would be to blame, feel free to reopen.
