### ISSUE TITLE
Progress events from non-200 responses should have `e.loaded = 0`

### ISSUE THREAD

**Issue by fearphage** [sinonjs/sinon#1105]
Non-200 requests now trigger the `load` event now (in `master` and maybe soon in `v1.17.*` - #1102). However the progress events triggered have several incorrect properties -- `loaded`, `total`, and `lengthComputable`. Here is an explanation in code:

## Expected progress event from non-200 response

```js
var progressEvent = {
  loaded: 0,
  total: 0,
  lengthComputable: false
};
```

## Actual progress event from non-200 response

```js
var progressEvent = {
  loaded: 100,
  total: 100,
  lengthComputable: true
};
```  

I spotted the bug here:

https://dl.dropboxusercontent.com/u/2400/tc/sinon/xhr-browser-test.htm

We've got the events correct now but not the properties of the triggered event.

Related: #1040

**Comment by fearphage** [comment]
I have a proposed solution (fearphage/Sinon.JS#1). It's branched from #1102 (my own branch) is why I couldn't send a normal PR here. I believe I'll have to wait for #1102 to get merged and then rebase or at least remake the PR.

**Comment by fatso83** [comment]
This is great. Thanks for your work, Phred!
