### ISSUE TITLE
How to test call order of async methods?

### ISSUE THREAD

**Issue by eGavr** [sinonjs/sinon#1106]
* Sinon version : 1.17.x
* Environment   : node@4.x, npm@2.x, mocha@2.x, chai@3.x

Hi! I'm sorry if I do not just follow the contributing guide, but I'll try to explain my problem exhaustively.

Consider I want to test the next piece of code (method `getOrientationInNativeContext`):

```js
const wd = require('wd');

exports.getOrientationInNativeContext = () => 
    wd.context('NATIVE_APP').then(() => wd.getOrientation());
```

so I try to test the call order of methods `wd.context` and `wd.getOrientation` in my method `getOrientationInNativeContext`:

```js
const q = require('q');
const sinon = require('sinon');
const wd = require('wd');

const moduleToTest = require('../../lib/my-module');

describe('getOrientationInNativeContext', () => {
    const sandbox = sinon.sandbox.create();

    beforeEach(() => {
        sandbox.stub(wd, 'context');
        sandbox.stub(wd, 'getOrientation');
    });

    afterEach(() => sandbox.restore());

    it('should get orientation in `NATIVE_APP`', () => {
        const contextStub = wd.context.withArgs('NATIVE_APP').named('context').returns(q());
        
        return moduleToTest.getOrientationInNativeContext()
            .then(() => assert.callOrder(contextStub, wd.getOrientation));
    });
});
```

Unfortunately, such test DOES NOT guarantee that `wd.getOrientation` was called after `wd.context` was RESOLVED! I mean, when I rewrite my code this way:

```js
const wd = require('wd');

exports.getOrientationInNativeContext = () => {
    wd.context('NATIVE_APP');

    return wd.getOrientation();
};
```

the test will pass too :(

How can I test such cases? Have I read the docs inattentively or it is impossible?

Thanks!

**Comment by mantoni** [comment]
Well, both of the examples you provided call `context` first and then `getOrientation`. You didn't really change the order which is why there is no test failure.

**Comment by eGavr** [comment]
But how can I test such cases?

**Comment by eGavr** [comment]
I do not say that their is a bug in `sinon`. I wanna to understand how to test that one stubbed method was called after another was resolve?

**Comment by mantoni** [comment]
`sinon.callOrder` is the right thing to test call order. In your case, the call order does not change. You want to test that the second function is only executed after the promise of the first completed. As there is no promise support in Sinon, you would have to find a solution that suits the promise library you're using.

You may want to post this question on the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your question.

**Comment by eGavr** [comment]
Thanks.
