### ISSUE TITLE
Protect `master` branch

### ISSUE THREAD

**Issue by jonnyreeves** [sinonjs/sinon#1117]
@fatso83 @mantoni Do you think the `master` branch should be protected to avoid accidental pushes and/or ensure that the test-suite is always run before landing changes?

**Comment by fatso83** [comment]
@jonnyreeves: the current release doc is not consistent with that approach, so we would have to change the procedure somewhat. I think that is why it is currently unprotected. I updated the `lolex` [release docs](https://github.com/sinonjs/lolex/blob/master/RELEASE.md) for just this reason a few weeks ago. I do think it is a bit bothersome though, when making new releases, as the the new commits with the updated changelog and `package.json` must go through a PR just to update the version number. 

Is it possible to have a version where we push code directly, but where the push will break if the tests fail? Currently, it is easy to forget merging the code after creating a PR, ending up with a release that is just on NPM, and not in the repo (until you discover you forgot).

**Comment by mantoni** [comment]
What we could do already is protect master against force-pushes. I managed to screw up history once and it was a real pain to get straight again.

**Comment by mroderick** [comment]
I've disabled force-pushes to `master` and `v.1.17` branches, and have left the other options as they were. We can re-visit this in the future if we need to.

![2016-11-10 at 10 24](https://cloud.githubusercontent.com/assets/20321/20171234/084d1c92-a730-11e6-9f9b-cb90889af8ed.png)

**Comment by mroderick** [comment]
Is this enough, or do we need more protections? Can we close this issue?

**Comment by fatso83** [comment]
No objections.
