### ISSUE TITLE
sinon.test restores the sandbox before a promise-based async test is completed

### ISSUE THREAD

**Issue by joelmukuthu** [sinonjs/sinon#1119]
- Sinon version : 1.17.5
- Environment   : node.js
- Example URL   : https://gist.github.com/joelmukuthu/155fe6734282f6366dfce66947ecb020
- Other libraries you are using: none

**What did you expect to happen?**
That the sandbox would not get restored until the test is completed

**What actually happens**
The sandbox is restored before the promise is fulfilled/rejected. Since it works with a callback-based async test, I would expect it to work with promise-based async tests as well.

**How to reproduce**
Run this snippet in mocha: 

``` js
it('restores the sandbox when the promise is fulfilled', sinon.test(function () {
    var sandbox = this;
    return Promise.resolve()
        .then(function () {
            var mySpy = sandbox.spy(); // TypeError: sandbox.spy is not a function
        });
}));
```

See [this gist](https://gist.github.com/joelmukuthu/155fe6734282f6366dfce66947ecb020) for a comparison with a callback-based async test.

**Comment by fatso83** [comment]
Thanks for reporting this. This does seem like an omission in the Sandbox API. I see you are using the `sinon.test` utility function (which has a [repo of its own](https://github.com/sinonjs/sinon-test) for Sinon 2 and onwards); does the same error surface if you manually create and restore a sandbox too? I would assume so, but just checking.

**Comment by joelmukuthu** [comment]
Right, it seemed to be an omission since the callback case is special cased. If I were to manually create a sandbox this wouldn't be an issue since I would control when to restore the sandbox, for instance in a final `then` block. What I'm more concerned about is someone managing to stub something in a `then` block (by storing a reference e.g. `var stub = this.stub`) and assuming that it would be restored by `sinon.test`, which wouldn't happen.

And from looking at the code in the new sinon.test module, it seems that the fix would have to be ported there too. I can go ahead and open a PR for this :)

**Comment by fatso83** [comment]
That would be awesome! 

Ping @sinonjs/sinon-test-maintainers

**Comment by vellotis** [comment]
Ping?

**Comment by mroderick** [comment]
Hey @joelmukuthu, any chance of getting a PR for this?

**Comment by joelmukuthu** [comment]
@mroderick, this was already fixed by @fearphage in [sinon-test](https://github.com/sinonjs/sinon-test) via https://github.com/sinonjs/sinon-test/pull/20. What remains to be done here is porting that code over but as I understood there were issues with getting the tests to pass with the buster setup. Is this correct @fearphage? 

// cc @fatso83

**Comment by kevinjsuh** [comment]
i am running into this issue as well -- is there an update?

**Comment by mroderick** [comment]
Since this has been implemented in the standalone `sinon-test` module and stable `sinon@2.x` is on the horizon, I don't think it would be wise to risk destabilising `sinon@1.x`.

@joelmukuthu have you tried `sinon-test` with `sinon@next`? Does it solve the use case for you?

**Comment by joelmukuthu** [comment]
Sorry for the super slow response but I believe this was fixed in [sinon-test](https://github.com/sinonjs/sinon-test) since v1.0.0 via https://github.com/sinonjs/sinon-test/pull/20. I've verified the gist via my original bug report. 

**PS:** the fix was not backported to sinon v1.x
