### ISSUE TITLE
Why？ Faketimer seems did not overwrites global setTimeout function?

### ISSUE THREAD

**Issue by shenrenguo** [sinonjs/sinon#1137]
* Sinon version : 2.0 pre2
* Environment   : webpack + karma + mocha + sinon + phantomjs
* Other libraries you are using: react-toolbox, react

it('should trigge the onTimeout properly', () => {
const clock = sinon.useFakeTimers();
const callback = sinon.spy();
TestUtils.renderIntoDocument(
 <Snackbar
          action='Dismiss'
          active
          icon='question_answer'
          label='Snackbar action cancel'
          timeout={2000}
          onTimeout={callback}
          type='cancel'/>);

clock.tick(2000);
expect(callback).to.have.been.called; 
//failed, expected spy to have been called at least once, but it was never called

clock.restore();
});

[Snackbar](https://github.com/react-toolbox/react-toolbox/blob/dev/components/snackbar/Snackbar.js) is reactjs component from react-toolbox

**Comment by shenrenguo** [comment]
I got it

**Comment by fearphage** [comment]
@shenrenguo What was the solution in case others with your problem end up finding this ticket?
