### ISSUE TITLE
sinon.test removed from 2.0

### ISSUE THREAD

**Issue by tomitrescak** [sinonjs/sinon#1146]
According to your changelog for 2.0.0

* Remove `sinon.test()` and `sinon.testCase` and `sinon.assert`

What is the replacement strategy now?

[EDIT] 
I have found the sinon-test repo

But what about the sinon assert?

Thanks

**Comment by tomitrescak** [comment]
Nevermind, all solved.

**Comment by fearphage** [comment]
In case anyone else ends up here:

https://github.com/sinonjs/sinon-test
