### ISSUE TITLE
sinon.assert.match documentation missing

### ISSUE THREAD

**Issue by robertknight** [sinonjs/sinon#1147]
sinon has a useful `match()` assertion method to test whether a value matches another using `sinon.match()`. This was added in https://github.com/sinonjs/sinon/pull/410 but is not documented in http://sinonjs.org/docs/#assertions-api

@ropez I assume this was intended to be a public API?

A secondary issue is that when sinon's assertions are exposed on the same `assert` object as chai's assertions, this conflicts with chai's `assert.match` which is a regexp match. Perhaps it should be renamed before making it public?

**Comment by fatso83** [comment]
@robertknight : the state of documentation is less than optimal at the moment, but hopefully we will push a new site soon. Documentation is kept up-to-date in the `docs` directory in this repo. You can find [plenty of docs on matchers](https://github.com/sinonjs/sinon/blob/master/docs/current/matchers.md) there.

As to what other people/libraries are doing with sinon's assertions, that is up to them, and if some naming collision arises, that is frankly for them to fix. It is out of scope for us IMHO, unless I am misunderstanding what you describe.

**Comment by robertknight** [comment]
Thanks @fatso83 . Although there is decent documentation for matchers themselves, `sinon.assert.match` is not mentioned on https://github.com/sinonjs/sinon/blob/master/docs/current/assertions.md

**Comment by mroderick** [comment]
@robertknight I've created a PR to add the missing documentation: https://github.com/sinonjs/sinon/pull/1180

**Comment by robertknight** [comment]
Thanks @mroderick , much appreciated.
