### ISSUE TITLE
Test event emitter in HTTP with sinon

### ISSUE THREAD

**Issue by Chintanvpatel** [sinonjs/sinon#1148]
Hello,

I have this function to download file
```
var http = require('http');
var fs = require('fs');

var download = function(url, dest, cb) {
  var file = fs.createWriteStream(dest);
  var request = http.get(url, function(response) {
    response.pipe(file);
    file.on('finish', function() {
      file.close(cb);  // close() is async, call cb after close completes.
    });
  }).on('error', function(err) { // Handle errors
    fs.unlink(dest); // Delete the file async. (But we don't check the result)
    if (cb) cb(err.message);
  });
};
```

Now how can I test events like "finish" and "error" of http.get object.

Thanks & Regards,
Chintan Patel

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by Chintanvpatel** [comment]
Ok I posted it in [Mailing list](https://groups.google.com/forum/#!topic/sinonjs/5q5xkwElsvM).
