### ISSUE TITLE
Feature request - window events

### ISSUE THREAD

**Issue by motanelu** [sinonjs/sinon#1152]
Hi,

Currently sinon does not offer the possibility to trigger fake window events, while there are several use cases that would justify the need for such calls:

```
window.onfocus = function () {
  // start polling the API, start the video, etc.
}

window.onblur = function () {
  // stop polling the API, stop the video, etc.
}
```

My suggestion is to provide an interface to trigger programatically these events in order to make sure that applications are testable.

```
sinon.blur()
```

Thank you

t.

**Comment by mantoni** [comment]
We are currently in the process of making the Sinon core environment independent. This means that the XHR stuff is moved out of the Sinon core into a separate project. Therefore I think that fake events should also be implemented in a separate library.

Having said that, there is a way to trigger events in [bean](https://github.com/fat/bean), which I used successfully for that use case before.

You could try this:

```js
bean.fire(window, 'focus');
```

Alternatively, you can try and work with [dispatchEvent](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) directly.
