### ISSUE TITLE
Matcher being called when setting up stub behavior

### ISSUE THREAD

**Issue by DullReferenceException** [sinonjs/sinon#1154]
- Sinon version : 1.17.6
- Environment   : Node
- Other libraries you are using: `chai`, `sinon-chai`

I am setting up two behaviors for a stub using a custom matcher:

``` js
fs.readFile = sinon.stub();

fs.readFile
  .withArgs(sinon.match(function (fileName) { return endsWith(fileName, 'suffixa'); }))
  .yields(null, 'contents A');
fs.readFile
  .withArgs(sinon.match(function (fileName) { return endsWith(fileName, 'suffixb'); }))
  .yields(null, 'contents B');
```

For some reason, when that second `.withArgs` is called, that first matcher's function is invoked and is passed the matcher object. This is before the stub itself is ever called.

**Comment by mroderick** [comment]
Could you provide a code example that shows how this fails?

We have an issue template for good reasons.

**Comment by DullReferenceException** [comment]
That was my code example that fails. Here it is slightly reworded with some blanks filled in:

```es6
const { match, stub } = require('sinon');

const readFile = stub();

readFile
  .withArgs(match(fileName => endsWith(fileName, 'suffixA')))
  .yields(null, 'contents A');

readFile
  .withArgs(match(fileName => endsWith(fileName, 'suffixB')))
  .yields(null, 'contents B');

function endsWith(str, suffix) {
  return str.indexOf(suffix) + suffix.length === str.length;
}
```

Error:

```
  return str.indexOf(suffix) + suffix.length === str.length;
             ^

TypeError: str.indexOf is not a function
    at endsWith (/Users/jpage/Code/sinon-1154-repro/repro.js:14:14)
    at Object.readFile.withArgs.fileName [as test] (/Users/jpage/Code/sinon-1154-repro/repro.js:6:31)
    at deepEqual (/Users/jpage/Code/sinon-1154-repro/node_modules/sinon/lib/sinon/util/core.js:194:26)
    at Object.deepEqual (/Users/jpage/Code/sinon-1154-repro/node_modules/sinon/lib/sinon/util/core.js:243:26)
    at Function.matches (/Users/jpage/Code/sinon-1154-repro/node_modules/sinon/lib/sinon/spy.js:287:27)
    at matchingFake (/Users/jpage/Code/sinon-1154-repro/node_modules/sinon/lib/sinon/spy.js:50:30)
    at Function.withArgs (/Users/jpage/Code/sinon-1154-repro/node_modules/sinon/lib/sinon/spy.js:249:33)
    at Object.<anonymous> (/Users/jpage/Code/sinon-1154-repro/repro.js:10:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

Again, what's happening is the matcher function is being called during setup, even though the stub itself wasn't actually called.

**Comment by DullReferenceException** [comment]
Just reproduced with that code using the reported version and the latest, `1.17.6`, as well.

**Comment by mroderick** [comment]
Right, that is confusing indeed!

I think you've uncovered a bug that we introduced when we merged https://github.com/sinonjs/sinon/pull/873

@fearphage you worked on this a while back, do you think we need a case in `deepEqual.use`, that examines if both `a` and `b` are matchers, and compares them, instead of trying to execute one to match the other?

https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/deep-equal.js#L97-L99

**Comment by fearphage** [comment]
@DullReferenceException What is `str` in this instance? Can you provide a failing test case? I'm looking at the code and I don't see why it's failing, but I'll look into it.

**Comment by DullReferenceException** [comment]
I'm not 100% sure; str resembles a matcher object to me, but I don't know for sure, only that it's not a string and it's not expected that that `withArgs` is even calling the matcher function.

**Comment by mroderick** [comment]
It's a matcher, the second call to `withArgs` passes it along, and it ends up in `deepEqual.use` at https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/deep-equal.js#L97-L99

**Comment by mroderick** [comment]
I've restructured the example a bit, to try and reduce it further.

Here's my version

```javascript
const { match, stub } = require('sinon');
const readFile = stub();

function endsWith(str, suffix) {
    return str.indexOf(suffix) + suffix.length === str.length;
}

function suffixA(fileName) {
    return endsWith(fileName, 'suffixa');
}

function suffixB(fileName) {
    return endsWith(fileName, 'suffixb');
}

const argsA = match(suffixA);
const argsB = match(suffixB);

readFile
  .withArgs(argsA);

readFile
  .withArgs(argsB);
```

Running that, gives the same error 

```
return str.indexOf(suffix) + suffix.length === str.length;
               ^

TypeError: str.indexOf is not a function
```

**Comment by mroderick** [comment]
Anyway, it is near midnight here, I should go to bed
