### ISSUE TITLE
returnValue throws undefined.

### ISSUE THREAD

**Issue by laumair** [sinonjs/sinon#1157]
* Sinon version : 1.17.5
* Environment   : Mocha
* Other libraries you are using: Enzyme, sinon-chai, chai

**Method under test**
```
  getContainersByHostId(containers) {
    return _.chain(containers)
      .groupBy('hostId')
      .toPairs()
      .map(currentItem => _.zipObject(['hostId', 'containers'], currentItem))
      .value();
  }
``` 
**Test**
```
  let sandbox;
    beforeEach(() => {
      sandbox = sinon.sandbox.create();
    });

    afterEach(() => {
      sandbox.restore();
    });
it('should call getContainersByHostId', () => {
        const containers = [{
          id: 'c_01',
          hostId: 'h_01',
          hostIp: 'IP',
          name: 'NAME'
        }];
       const transformedJson = [{
          hostId: 'IP',
          containers: [{
          id: 'c_01',
          hostId: 'h_01',
          hostIp: 'IP',
          name: 'NAME'  }]
       }];
        const wrapper = shallow(<Groups {...props} />);
        const instance = wrapper.instance();
        sandbox.stub(instance, 'getContainersByHostId');
        instance.getContainersByHostId(containers);
        expect(instance.getContainersByHostId.calledWith(containers)).to.equal(true); // Pass
         // **returns undefined**
        expect(instance.getContainersByHostId.returnValue(transformedJson)).to.equal(true); 
      });
```
I get undefined on the return value. I've tried this with spies as well. Still the same. The method is a class method that simply returns a transform json array. It works fine otherwise, but I am not sure what I am missing in the tests. Am I missing something here?

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue). 
--

For some help, you are using returnValue as a function, not a property. A user error. I assume you might be mixing up `returnValue` and `returns()`. See the [docs](http://sinonjs.org/docs/#spycall).
