### ISSUE TITLE
how to use sinon js with Express js unit testing

### ISSUE THREAD

**Issue by apmeena** [sinonjs/sinon#1158]
[http://stackoverflow.com/questions/39747397/how-to-use-sinon-js-with-express-js-unit-testing/](http://stackoverflow.com/questions/39747397/how-to-use-sinon-js-with-express-js-unit-testing/)

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
