### ISSUE TITLE
Spy on built-in Node constructors

### ISSUE THREAD

**Issue by SVasilev** [sinonjs/sinon#1159]
Hello,
I am trying to spy on built-in constructor function, for example ArrayBuffer in Node.js. Is there a way to do that with sinon, because I've read the docs and didn't find such functionallity.
Best regards,
Stefan

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
