### ISSUE TITLE
TypeError: sinon.assert is not a function

### ISSUE THREAD

**Issue by marcelpanse** [sinonjs/sinon#1160]
* Sinon version : sinon@1.17.6
* Environment   :  osx
* Other libraries you are using:

Somehow sinon.assert doesn't work for me:

    const sinon = require('sinon')
    describe('Testing AddUser.js', () => {
      describe('#handle()', () => {
        it('success flow', () => {
          sinon.assert(true)
        })
      })
    })

output:

    TypeError: sinon.assert is not a function
        at Context.it (lambda-functions/functions/accounts_add_user/test/AddUserTests.js:58:13)

Other sinon functions like sinon.sandbox and sinon.test are working as expected.
Is there something obvious I'm doing wrong?

**Comment by mantoni** [comment]
`sinon.assert` is not a function. It is an object with a collection of functions that help assert all sorts of things around fakes. Read all about them in the docs: http://sinonjs.org/docs/#assertions

**Comment by i474232898** [comment]
@mantoni yeah, but there is "assert(spy.calledWith(message));" at documentation [here](https://sinonjs.org/releases/latest/spies/)

**Comment by mantoni** [comment]
In this case `assert` refers to an assertion library function, not `Sinon.assert`. `spy.calledWith` returns a boolean. Most assertion libraries expose an assert function that throws if a falsy value is passed.

**Comment by i474232898** [comment]
Thanks for explanation @mantoni
