### ISSUE TITLE
Not loading via Webpack

### ISSUE THREAD

**Issue by jrgleason** [sinonjs/sinon#1165]
* Sinon version : 1.17.6
* Environment   : OSX > Webpack > Karma

**What did you expect to happen?**

`window["sinon"] = require('../dependencies/sinon-1.17.6');` (typescript) should work. The js file described here was the published full js file at the site per AMD requirements and not the NPM one.

**What actually happens**
```

Chrome 53.0.2785 (Mac OS X 10.12.0) ERROR
  Uncaught Error: Cannot find module './sinon/util/core'.
  at src/main/typescripts/test.ts:21878
```

seems like it should be similar to this... https://github.com/sinonjs/sinon/issues/541

**Comment by mroderick** [comment]
This is a known issue with Sinon 1.x branch, see https://github.com/sinonjs/sinon#important-sinon-v1x-does-not-work-with-amdcommonjs-bundlers

Instead, either download a single file version from http://sinonjs.org, or use one of the pre-release versions like `2.0.0-pre.3`.
