### ISSUE TITLE
Feature proposal: spy.calledWithValueOfType()

### ISSUE THREAD

**Issue by fogine** [sinonjs/sinon#1167]
Hello,

Thank you for your work, it's been very useful!

As the title says, it would be really cool if I could check that a spy has been called with value of given type.

Eg.:

```javascript

var spy = sinon.spy();

doSomeStuff(spy);

spy.calledWithValueOfType(Number); // would perform instanceof Number & typeof arg === 'number'
spy.calledWithValueOfType(Object);
spy.calledWithValueOfType(ObjectConstructor);


function ObjectConstructor() {
}
```

Maybe `calledWithTypeOf` would be better name for the method.

What do you think about this feature?

**Comment by mantoni** [comment]
You can do this with a matcher like so:

```js
sinon.match.calledWith(spy, sinon.match.number);
```

There are a few built in matchers and you can also create your own. Check the docs and look for "matchers" to lern more.
