### ISSUE TITLE
sinon.getConfig is deprecated and will be removed from the public API in a future version of sinon.

### ISSUE THREAD

**Issue by tomitrescak** [sinonjs/sinon#1169]
- Sinon version : 2.0.0-pre.2
- Environment   : MAC + Mocha
- Other libraries you are using:

"@kadira/storybook": "^2.24.0",
    "apollo-connector-mongodb": ">=0.0.1",
    "apollo-module-authentication": ">=1.0.0",
    "apollo-module-date": ">=1.0.1",
    "apollo-modules": ">=0.0.1",
    "apollo-server": ">=0.2.4",
    "bcrypt-nodejs": ">=0.0.3",
    "body-parser": ">=1.15.2",
    "connect-history-api-fallback": ">=1.3.0",
    "cors": ">=2.8.0",
    "dataloader": ">=1.2.0",
    "express": ">=4.14.0",
    "forever": ">=0.15.2",
    "graphql": ">=0.7.0",
    "graphql-tools": ">=0.6.4",
    "import-to-commonjs": ">=0.0.1",
    "json-loader": ">=0.5.4",
    "jsonwebtoken": ">=7.1.9",
    "meteor-random": "0.0.3",
    "meteor-sha256": ">=1.0.0",
    "mongodb": "^2.2.10",
    "morgan": ">=1.7.0",
    "nodemailer": "^2.6.4",
    "remove": ">=0.1.5",
    "semanticui-react": "^0.2.3",
    "typescript": "^2.1.0-dev.20161004"

```
dev
```

   "@kadira/react-storybook-addon-info": ">=3.2.1",
    "@kadira/react-storybook-decorator-centered": ">=1.0.0",
    "@kadira/storybook": ">=2.11.0",
    "@types/chai": "^3.4.34",
    "@types/isomorphic-fetch": "^0.0.31",
    "@types/node": "^6.0.45",
    "@types/react": "^0.14.41",
    "apollo-authentication-semantic-ui": ">=0.0.1",
    "apollo-client": ">=0.4.11",
    "apollo-mantra": ">=1.1.0",
    "apollo-module-authentication": ">=0.0.1",
    "babel-plugin-rewire": "^1.0.0",
    "babel-preset-es2015-node6": "^0.3.0",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-stage-2": ">=6.13.0",
    "brace": ">=0.8.0",
    "chai": ">=3.5.0",
    "chai-enzyme": "^0.5.2",
    "chokidar": "^1.6.0",
    "date-format-lite": ">=0.9.1",
    "enzyme": ">=2.4.1",
    "es2015-i18n-tag": "^1.1.0",
    "espower-source": "^1.1.0",
    "eventobject": ">=1.0.1",
    "graphql-tag": ">=0.1.11",
    "i18n-client": ">=0.0.6",
    "inject-loader": "^2.0.1",
    "jquery": ">=3.1.0",
    "jsdom": "^9.6.0",
    "jss": ">=5.4.0",
    "jss-nested": ">=2.1.0",
    "jss-preset-default": "^0.5.0",
    "jss-vendor-prefixer": ">=3.0.0",
    "jsx-control-statements": "^3.1.5",
    "local-storage": "^1.4.2",
    "marked": ">=0.3.6",
    "meteor-random": ">=0.0.3",
    "mocha": ">=3.0.2",
    "moment": ">=2.14.1",
    "morgan": ">=1.7.0",
    "nwb": ">=0.12.x",
    "nyc": "^8.3.0",
    "power-assert": ">=1.4.1",
    "proxyquire": "^1.7.10",
    "raw-loader": ">=0.5.1",
    "react": ">=15.3.1",
    "react-ace": ">=3.5.0",
    "react-addons-test-utils": ">=15.3.1",
    "react-addons-update": ">=15.3.0",
    "react-apollo": ">=0.4.7",
    "react-dom": ">=15.3.0",
    "react-helmet": ">=3.1.0",
    "react-hot-loader": "^3.0.0-beta.2",
    "react-redux": ">=4.4.5",
    "react-router-redux": ">=4.0.5",
    "react-router": "^4.0.0-alpha.5",
    "react-s-alert": ">=1.1.4",
    "redux-mock-store": "^1.2.1",
    "redux-thunk": ">=2.1.0",
    "semantic-ui-css": ">=2.2.4",
    "semantic-ui-react": ">=0.0.1",
    "semanticui-react": ">=0.0.1",
    "sinon": "^2.0.0-pre.2",
    "sinon-test": "0.0.1",
    "storybook-addon-specifications": ">=1.0.15",
    "style-loader": ">=0.13.1",
    "sweetalert2": ">=4.1.9",
    "ts-babel-node": "^1.0.0",
    "ts-node": "^1.3.0",
    "typestyle": "^0.2.0"

**What did you expect to happen?**

Sinon is reporting `sinon.getConfig is deprecated and will be removed from the public API in a future version of sinon.` although I am using the latest version. I never actually call sinon.getConfig.

Any idea what can cause this issue?

**Comment by montogeek** [comment]
This is not an issue, it is a deprecation warning published to npm.
You don't need to use `getConfig` to get the warning, deprecation warnings are _general_ for the package

**Comment by fatso83** [comment]
It is due to you using sinon-test and [probably not configuring it per the README](https://github.com/sinonjs/sinon-test/blob/master/README.md#usage). 

See sinonjs/sinon-test#33
