### ISSUE TITLE
[QUESTION] Stubbing `function returns 'false'`

### ISSUE THREAD

**Issue by rodoabad** [sinonjs/sinon#1172]
This is more of a question than a bug report. I was wondering how do you stub a `function returns 'false'` I've tried doing `sandbox.stub(someObject, 'method').returns(() => false)` but it still says `function() {}`. Thanks!

**Comment by mroderick** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
