### ISSUE TITLE
Expected arguments to be called with diff

### ISSUE THREAD

**Issue by jdgreenberger** [sinonjs/sinon#1179]
Using sinon 1.17.6 in Node.JS with sinon-chai. When expecting function arguments (i.e. expect(stub).to.have.been.calledWith) if a test fails, the thrown error contains the entire set of function arguments. If these arguments are big, it can be difficult to trace down the diff. Would be happy to submit my own PR, but was wondering if there is intention to improve this error by iterating through function arguments and specifying the exact diff which causes the expectation to fail.

Example sinon response: https://gist.github.com/jdgreenberger/b7ade89cda2762a2c02944e81457f62e
Ideal sinon response: https://gist.github.com/jdgreenberger/4f84c3803bc376c55a4b772fb68455a6

**Comment by mroderick** [comment]
In to help reviewers to better understand what you're asking, could you add a few examples to this issue?

**Comment by jdgreenberger** [comment]
Updated @mroderick

**Comment by mroderick** [comment]
I think I better understand what you're after now.

Check out http://unexpected.js.org, they have really excellent diffs.

If I read their `package.json` correctly, then they're using https://github.com/kpdecker/jsdiff#readme

A contribution that uses a stable module like that would be most welcome.
