### ISSUE TITLE
2.0.0-pre.4 mistakenly published as latest

### ISSUE THREAD

**Issue by billyjanitsch** [sinonjs/sinon#1185]
**What did you expect to happen?**

2.0.0-pre.4, being a prerelease, should be tagged on npm as `sinon@next`.

**What actually happens**

2.0.0-pre.4 was mistakenly tagged as `latest`. `npm view sinon` yields:

```
{ ...
  'dist-tags': {
    latest: '2.0.0-pre.3',
    next: '2.0.0-pre.4'
  },
  ...
}
```

As a result, `npm install sinon` installs the prerelease.

This can be fixed by someone with npm privs running:
```sh
$ npm dist-tag add sinon@2.0.0-pre.4 next
$ npm dist-tag add sinon@1.17.6 latest
```

**Comment by mroderick** [comment]
@billyjanitsch that was me, being a doofus with npm.

I have verified the problem, and using your very clear instructions fixed the issue.

Thanks! 💐

**Comment by pghalliday** [comment]
This just happened again with pre.6 :o
