### ISSUE TITLE
How to test calledAfter(<nth call of another spy/stub>)?

### ISSUE THREAD

**Issue by llwt** [sinonjs/sinon#1199]
We have some logic in our code where we would like to test that a method is called in between multiple calls to another stub. 

```js
public someMethodUnderTest() {
  this.app.use(someMiddleware());
  this.app.use(anotherMiddleware());

  this.configurationHookThatWeWantToTest();

  this.app.use(postConfigurationMiddleware());
  this.app.use(finalMiddleware());
}
```

If `this.app.use` and `this.configurationHookThatWeWantToTest` are stubs, is there a way with the current api to test that `this.configurationHookThatWeWantToTest` is called after the second call to `this.app.use`? Additionally, is there a way to test in the other direction, i.e. `this.app.use`'s third call is made after the call to `this.configurationHookThatWeWantToTest`?

If not would it make sense to add something like an optional parameter to `spy.calledAfter` that asserts the call was made after the nth call to the passed in spy?

**Comment by llwt** [comment]
Here is where we landed as a temporary work around, using the `callIds` array of the spies.
```js
      it('should call the configure middleware hook', () => {
        assert.ok(configureMiddlewareStub.calledOnce, 'kernel.configureMiddleware() was called');

        assert.isAbove(
          configureMiddlewareStub.callIds[0],
          mockExpressApp.use.callIds[3], // fourth call
          'the configure middleware hook was used after the swagger validator middleware',
        );
      });
```

**Comment by mroderick** [comment]
> `sinon.assert.callOrder(spy1, spy2, ...)`
> Passes if the provided spies where called in the specified order.

See http://sinonjs.org/docs/#assertions-api

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
