### ISSUE TITLE
stub with custom return

### ISSUE THREAD

**Issue by wilkerlucio** [sinonjs/sinon#12]
Hi, I need to create a stub for a function, this stub should replace original function and use my stub function instead, for example:

s = sinon.stub(obj, "hello");
s.return(function(a) { return a; });

In current API I can't found anything to do something like this... the "return" of stub only accepts a final value...

There is anyway to accomplish it? Maybe on future versions?

**Comment by ahamid** [comment]
This does not appear to work with mocks, using the `.return` method.  Is there a way to supply a custom mock method or return value?
