### ISSUE TITLE
called once with

### ISSUE THREAD

**Issue by piotr-s-brainhub** [sinonjs/sinon#1200]
I would like something like that:
```javascript
expect(create).to.be.calledOnceWith(4); // calledOnceWith does not exist, maybe it has a different name
expect(create.withArgs(4)).to.be.calledOnce(); // I want it to pass only when function is called once but this passes also when called once with specified arguments and again with different arguments
expect(create).to.be.calledOnce(); // it does not check passed arguments
```
It should pass only when the function is called exactly once and with specified arguments.
Is it possible?
If not it would nice to create such a feature.

**Comment by mantoni** [comment]
This has been suggested before. The issue that is not resolved is the ambiguity in the naming. Does it mean "Called exactly once and also with these args" as if it was two checks, one for "once" and one for "withArgs", or is it "called once with these args but might have been called with other args".

Hope the message come across. One can really see both meanings in there.

**Comment by fatso83** [comment]
Closing due to lack of response

**Comment by piotr-s-brainhub** [comment]
`expect(create.withArgs(4)).to.be.calledOnce();` - checks if it was called once with these args

I need an assertion which should check if the stub was called exactly once and with the specified arguments.

Maybe it should have a better name.
`expect(create).to.be.calledOnceAndWith(4);`

Moreover I need an assertion to check exact arguments:
`expect(create).to.be.calledOnceAndWithExactly(4);`

**Comment by fatso83** [comment]
I think the new names are less ambigious. Moreover I think it would demand very little to implement, given all tge existing code. Would you like to take a stab at it, Piotr? Pull requests are always welcome. The maintainers are mostly concerned with fixing bugs amd integrating features.

**Comment by mvujovic** [comment]
I had this same issue and I solved it using:
```
assert(myStub.withArgs(myArg).calledOnce);
```

**Comment by c1moore** [comment]
If ambiguity is the issue, what about something like

```
// Called once and that once time was called with 4.
expect(create).to.be.calledOnce().with(4);
```

```
// Called with 4 only once.
expect(create).to.be.calledWith(4).once();
```
