### ISSUE TITLE
Stubbing a call for a http request using fakeServer in karma tests for reactjs

### ISSUE THREAD

**Issue by tejpowar** [sinonjs/sinon#1231]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : 2.0.0-pre.2
* Environment   : Chrome / MAC OS X
* Example URL   :
* Other libraries you are using:

**What did you expect to happen?**
When a fakeServer is created pointing to a production server we need a way of mocking the response. I would expect that when the endpoint is run within the karma test it should intercept the call and then return the mocked json.

**What actually happens**
The endpoint gets hit but the response is not the JSON file
**How to reproduce**
Create a fakeserver hitting a valid endpoint. It would be a GET method. The return would be a json object which is required into the test using require.

<details>

describe.only('Default layout', () => {
       
        it('Renders the result when searching', () => {
            const server = sinon.fakeServer.create();
            const event = new Event('input', { bubbles: true });
            const endPoint = 'https://someserver/test?q=test`';
            const searchInput = document.querySelectorAll('.theInput')[1];
            
            server.respondWith('GET', endPoint,
                   [200, { 'Content-Type': 'application/json' },
                    responseFile]);

            searchInput.value = 'test ';
            searchInput.dispatchEvent(event);
            sinon.fakeServer.respond();
            server.restore();
            console.log(document.querySelector('.renderedPanel'));

        });
    });
</details>

**Comment by fatso83** [comment]
The attached code is hardly a unit test: it has lots of quite opaque bits where it isbhard to know what is going on, and therefore I'll just have to do a few educated guesses 😉 My guess is that your event is triggering a normal submit using some form. That is not something fakeServer will help you with: 
> High-level API to manipulate FakeXMLHttpRequest instances.

So, unless your event is triggering some callback, which in turn is creating an XHR, this is not a bug in Sinon. Feel free to reopen if my guesses were wrong or if you have additional input!
