### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by Floby** [sinonjs/sinon#1240]
Hello,

I've been using sinon for years and it's always be one of my best friends when writing code. This year I'm trying to get my employer to donate money to several open source projects.
Sinon.js doesn't seem to have any sort of donation system set up. Is this intentional?

**Comment by mroderick** [comment]
We do not currently have any way of receiving donations.

It is something that I have been thinking about, but I haven't found any good solutions that would justify the increase in workload.

Perhaps we can join https://js.foundation or jQuery Foundation, I don't know how that works yet.

If there's sufficient traction for this idea, I'll put effort into looking into this.

Please use the emoji reactions or leave a comment, if you think this is a good idea

**Comment by lucasfcosta** [comment]
Hi Friends, I just wanted to share my personal experience on this matter. I think it might help you.

A while ago in Chai we started receiving donations by using OpenCollective. You can see [our discussion here](https://github.com/chaijs/chai/pull/732). In that PR many of our doubts were answered and there's useful information there. If you're interested maybe you could get in touch with @piamancini and see what they can do for you.

**Comment by piamancini** [comment]
Thanks @lucasfcosta <3
Hi @mroderick more info about Open Collective [here](https://opencollective.com), [here](https:medium.com/open-collective) and other [open source projects](https://opencollective.com/opensource) on the platform. Happy to chat.

**Comment by mroderick** [comment]
@piamancini I've signed us up for Open Collective :)

**Comment by piamancini** [comment]
@mroderick awesome! will review and activate. in the meantime you can edit content / upload expenses.

**Comment by mroderick** [comment]
I've merged the PR that adds Open Collective to `README.md`, so you can now become a backer / sponsor of Sinon

❤️

**Comment by Floby** [comment]
great news !
