### ISSUE TITLE
Behaviour of twice() not the same as atLeast(2)?

### ISSUE THREAD

**Issue by zephinzer** [sinonjs/sinon#1246]
* Sinon version : 1.17.6
* Environment   : OS X El Capitan 10.11.6, Node v6.9.2
* Example URL  : N/A
* Other libraries you are using: karma-chai-sinon@0.1.5, karma-sinon@1.0.5, sinon-chai@2.8.0

**What did you expect to happen?**
Using a sandbox, we expect a function to be called two times (it's the `dispatch` of a Redux store):
```
const args = { transform: function transform() {}, type: "FETCH_JSON_STARTED", url: "/expected" };
const sandbox = sinon.sandbox.create();
const mockStore = sandbox.mock(reduxStore).expects('dispatch').twice().withArgs(args);
/*inside a sub-function*/ reduxStore.dispatch(args);
/*inside a sub-function*/ reduxStore.dispatch(args);
mockStore.verify();
```

The above expectation causes the following error message:
```
Unexpected call: dispatch({ transform: function transform() {}, type: "FETCH_JSON_STARTED", url: "/expected" })
          Expectation met: dispatch({ transform: function transform() {}, type: "FETCH_JSON_STARTED", url: "/expected" }[, ...]) twice
```

If we substitute `twice()` with `atLeast(1)`, test passes, with `atLeast(2)`, test passes, with `atLeast(3)`, the following error message shows: 

```
Expected dispatch({ transform: function transform() {}, type: "FETCH_JSON_STARTED", url: "/expected" }[, ...]) at least thrice (called twice)
```

Is there something I'm missing about the differences in `atLeast` and `twice`?

**Comment by mantoni** [comment]
`twice()` means it expects exactly two calls. Any more or less is an error. Likewise, if you actually call it twice and say `atLeast(3)`, you're not calling it often enough. If you use `atMost(3)`, it should work as expected.
