### ISSUE TITLE
TypeError: Cannot call method 'create' of undefined. When calling sinon.fakeServer

### ISSUE THREAD

**Issue by tomkoptel** [sinonjs/sinon#125]
I`m trying to initialize fakeServer instance while I have sinon required in my env. Here goes my setup:
 
helper.js
```javascript
 window = require("jsdom").jsdom().createWindow();
 $ = require('jquery');
 require('expectThat.mocha');
 expect = require('chai').expect;
    
 sinon = require("sinon");
```

In my spec I call:

my_test.coffee
```coffeescript

require('./helper.js')


describe "Given form to submit", ->
  server = undefined

  beforeEach ->
    server = sinon.fakeServer.create()

```

When I`m executing code `sinon.fakeServer` returns `undefined`. How can I manage to force fake server feature to work?

P.S. I`m newbie in the JS testing. Please, don`t judge me:)

**Comment by andrewdonskikh** [comment]
I have the same problem  - sinon.fakeServer == undefined (removing var from fake_server.js didn`t help)

**Comment by jonnyreeves** [comment]
If I understand the root cause of this issue correctly, this should be resolved as part of the CommonJS-ification of the Sinon internals that is being undertaken as part of the v2.0 release.  See #966.

**Comment by fatso83** [comment]
Verified to be working in the node shell:

```
> sinon = require("./lib/sinon");
> server = sinon.fakeServer.create()
> Object.keys(server.__proto__)
[ 'create',
  'configure',
  'addRequest',
  'getHTTPMethod',
  'handleRequest',
  'logger',
  'logError',
  'log',
  'respondWith',
  'respond',
  'processRequest',
  'restore',
  'xhr' ]
```
