### ISSUE TITLE
Sinon spy didn't work in case when function has property function which call origin function.

### ISSUE THREAD

**Issue by rozaev** [sinonjs/sinon#1250]
* Sinon version : 1.17.6
* Environment   : any
* Example URL   : http://jsbin.com/vuceqagiwu/1/edit?html,console
* Other libraries you are using: None

**What did you expect to happen?**
spy.called should be true.

**What actually happens**
spy.called is false.

**How to reproduce**
See http://jsbin.com/vuceqagiwu/1/edit?html,console

<details>
See:
http://jsbin.com/vuceqagiwu/1/edit?html,console
</details>

**Comment by rozaev** [comment]
@fatso83 Hello. Did I expect wrong behavior? Or you didn't think what it is a real use-case?

**Comment by fatso83** [comment]
This is a user error.

The spy is _wrapping_ the function, returning a _new_ function.

```javascript
function myFunc(a,b){ return a+b; }
var spy=s.spy(myFunc);

myFunc(1,2) // => 3
spy.called // => false
spy(1,2) => 3
spy.called // => true
```

(And I was writing this while you commented 😄 )

**Comment by rozaev** [comment]
@fatso83 Thank you very much. I will read documentation more accurate now.
