### ISSUE TITLE
Add throwsArg(index) to mocks

### ISSUE THREAD

**Issue by pimterry** [sinonjs/sinon#1270]
Sinon supports `returnsArg(index)` to easily pass on a value that was passed in, and `callsArg(index)` to callback to an arg that was passed in, but not `throwsArg(index)` to rethrow an error argument that was passed in. This is useful for functions which rethrow a provided error, e.g. when mocking error handlers and hooks.

Would you accept a PR for this?

**Comment by mroderick** [comment]
That seems like a reasonable expansion of the API

**Comment by pimterry** [comment]
It looks like this was added in 2.3.0, so this can indeed be closed (though that means the wontfix label isn't super accurate).
