### ISSUE TITLE
sinon@next fails on text-encoding import

### ISSUE THREAD

**Issue by melinath** [sinonjs/sinon#1272]
* Sinon version : `sinon@2.0.0-pre.5`
* Environment   : Mac OS X
* Other libraries you are using: `jest@18.1.0`, `babel-core@6.23.1`

**What did you expect to happen?**
A fix for #878

**What actually happens**
test run fails.

<img width="604" alt="screen shot 2017-02-21 at 1 46 35 pm" src="https://cloud.githubusercontent.com/assets/299979/23186493/3447e7d4-f83c-11e6-9145-73b54c5d4252.png">

**How to reproduce**
```
import sinon from 'sinon'
```

Fails immediately with the above traceback.

**potential fix?**
It seems like this could be potentially fixed by upgrading sinon's text-encoding dependency, which is currently hard-coded to 0.6.2 (current release being 0.6.4). Don't know what the story is there, but they did change their export structure between those releases.

**Comment by melinath** [comment]
Attempted to force an upgrade of text-encoding via `npm shrinkwrap` - new error is:

```
 TypeError: _sinon2.default.test is not a function
```

**Comment by melinath** [comment]
Resolved new error by installing [`sinon-test`](https://github.com/sinonjs/sinon-test) - confirmed working now.

**Comment by fatso83** [comment]
Closed as user error
