### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by salsaly4** [sinonjs/sinon#1275]
* Sinon version : 1.17.7
* Environment   : Node v7.4.0
* Other libraries you are using: karma/mocha/enzyme, webpack@2.2

**What actually happens**
Getting
`Uncaught TypeError: Cannot read property 'call' of undefined`

**How to reproduce**
```javascript
const Button = props => (
  <button className="btn" onClick={props.onClick} disabled={props.disabled}>
    {props.children}
  </button>
);
```

```javascript
import { expect } from 'chai';
import { shallow } from 'enzyme';
import sinon from 'sinon';
import React from 'react';
import Button from './Button';

describe('Button component', () => {
it('should call onClick handler', () => {
    const mockOnClick = sinon.spy();
    const wrapper = shallow(<Button onClick={mockOnClick}>Test</Button>);

    expect(wrapper.exists()).to.equal(true);
  });
});
```

If i remove the line with the call to sinon.spy(), everything works.

Somehow it is connected to webpack, since it breaks on line
```javascript
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```
in the webpack bundle.

**Comment by mroderick** [comment]
Are you using Sinon from source perhaps?

**Comment by mroderick** [comment]
You might want to try the next version of Sinon, which has much wider support for module systems

```
npm install sinon@next --save-dev
```

**Comment by salsaly4** [comment]
No, I've installed it with npm. I'll try the beta later today and let you know if the problem persists.

**Comment by mroderick** [comment]
https://github.com/sinonjs/sinon#important-sinon-v1x-does-not-work-with-amdcommonjs-bundlers

**Comment by salsaly4** [comment]
Thanks, it worked. Sorry for inconvenience.

**Comment by mroderick** [comment]
👍
