### ISSUE TITLE
Fix sinon.js and/or sinon-server.js bundle content

### ISSUE THREAD

**Issue by mantoni** [sinonjs/sinon#1278]
The current Sinon 2.0 bundle contains the sinon-server code as well. There is a separate `sinon-server.js` file being generated as part of the release process which is (almost) identical to the main `sinon.js` file. The `sinon-server.js` file should contain the fake XHR code while the `sinon.js` file shouldn't.

There are two questions:

- Should the `sinon-server.js` file contain everything, like the current `sinon.js` file, or should it be an add-on?
- If we eventually want to split out the XHR code into a separate project, should the core `sinon.js` project pull in XHR as a dependency, like it's currently happening with `lolex`?

**Comment by mantoni** [comment]
As discussed with @sinonjs/owners, we're going to remove the separate `sinon-server.js` file and just include everything in the `sinon.js` file.

**Comment by cjohansen** [comment]
Fixed in #1294 👏
