### ISSUE TITLE
yo aio-angular is not successful since it depends on sinon 1.15.0 js file

### ISSUE THREAD

**Issue by rahulmr** [sinonjs/sinon#1306]
The resolution could be posting the 1.15.0 js in the releases link
http://sinonjs.org/releases/ like below
http://sinonjs.org/releases/sinon-1.15.0.js

* Sinon version : Cannot verify this, as I don't know how to.
* Environment   : Windows 7, node 7.5.0 and npm 4.1.2
* Example URL   : https://github.com/PinkyJie/generator-aio-angular
* Other libraries you are using: aio-angular and bower with angular-mocks

**What did you expect to happen?**
`yo aio-angular` should successfully run and there should not be any error for installing bower components

**What actually happens**
Getting error while perform `yo aio-angular`

```
bower sinon#*                            resolve http://sinonjs.org/releases/sinon-1.15.0.js#*
bower sinon#*                           download http://sinonjs.org/releases/sinon-1.15.0.js
bower sinon#*                              EHTTP Status code of 404
```

**How to reproduce**
Refer site - https://github.com/PinkyJie/generator-aio-angular
install yeoman generator and aio-angular generator
create a folder / directory and cd to that directory and perform below steps.

```
npm install -g yo
npm install -g generator-aio-angular
yo aio-angular
```

**Comment by mantoni** [comment]
I think the `aio-angular` thingy should take the releases from the zip files associated with the GitHub tags, and not from the homepage. We might even decide to rename that folder. It's not reliable.

**Comment by GordonMohrin** [comment]
same thing problem at bard.js:
https://github.com/wardbell/bardjs/pull/46/commits/daac0f97ffc0ffde391615a4bb86d4e451ee0bef

**Comment by mantoni** [comment]
Thanks. Using npm is even better.

**Comment by fatso83** [comment]
This is an issue with flaky setup of external projects, not sinon itself. Closing as tips for fixing this has been given and there is not much we can do here.

**Comment by rahulmr** [comment]
Bit confused, what should be my take here? How should I fix this locally? Ask whom to fix it? :)

**Comment by mantoni** [comment]
@rahulmr As you stated in the aio-angular issue, they should use the npm dependency instead of the website URL.

**Comment by mantoni** [comment]
The files have been restored in #1308.
