### ISSUE TITLE
Broken link in docs at website

### ISSUE THREAD

**Issue by VynceMontgomery** [sinonjs/sinon#1314]
The link to explanation of sinon.match 404s. Note that the link works OK when viewing the docs on Github, so presumably this is an error in how the markdown is being converted to the sinonjs.org website.

* Sinon version : 
I'm reading published documentation for v1.17.7 but a glance through the repo suggests the code behind this error exists in the docs for many versions (including 2.0.0)

* Environment   :
published sinonjs.org website

* Example URL   :
http://sinonjs.org/releases/v1.17.7/assertions/

**What did you expect to happen?**
I expected to find documentation for sinon.match. 

**What actually happens**
404 at URL: 
http://sinonjs.org/releases/v1.17.7/assertions/matchers.md
apparent correct URL is: 
http://sinonjs.org/releases/v1.17.7/matchers/

**How to reproduce**
link is near bottom of page, generated by 
https://github.com/sinonjs/sinon/blob/b315b19163d6c741e9d06bc3136eb494f02c06d2/docs/_releases/v1.17.7/assertions.md#L152

**Comment by VynceMontgomery** [comment]
So, I don't know if it matters, but this change breaks the link within github, i.e., when looking at: 

https://github.com/sinonjs/sinon/blob/421c869a171e5c27b93b777ad58adaf69941f9b2/docs/_releases/v1.17.7/assertions.md the link now doesn't work there.

**Comment by fatso83** [comment]
We can't have it both ways unfortunately.
