### ISSUE TITLE
Update sinon spy api documentation

### ISSUE THREAD

**Issue by ckwong90** [sinonjs/sinon#1317]
I was looking a way to spy on an objects setter and getter function and noticed that it's not in the docs http://sinonjs.org/releases/v2.0.0-pre.6/spies, but the api is burried in an issue https://github.com/sinonjs/sinon/issues/917.

Add api docs for 
```
sinon.spy(object, "method", ["type"]);  //Where type is either "setter" or "getter"
```

**Comment by fatso83** [comment]
That is because we are reworking the API for that, and that it is currently undergoing a change. It is currently not possible with the release candidate. See #1297 for background info.

**Comment by fatso83** [comment]
This is now on http://sinonjs.org/releases/v2.0.0/stubs/. See get and set methods.
