### ISSUE TITLE
No sinon.assert.returns?

### ISSUE THREAD

**Issue by apowers313** [sinonjs/sinon#1324]
Is there some reason why there isn't a `sinon.assert.returns(spy, obj)` call for testing that a spy got the expected return value?

**Comment by mantoni** [comment]
Seems like an inconsistency in the API to me. Care to make a pull request?

**Comment by apowers313** [comment]
Is that as simple as just adding a `mirrorPropAsAssertion` call? Also, should I create a PR against 1.17.7 or 2.0.0-rc?

In the interest of identifying other gaps, put together the [attached spreadsheet](https://github.com/sinonjs/sinon/files/836355/Sinon.Cross-API.Mapping.20170311.xlsx) and looks like there might be other clean-up that could happen.

One idea I had (if it's not overstepping my bounds and not too late) is to rename the APIs semantically for 2.0. By "semantically" mean name everything for what it does: "observe" functions would return true; "expect" would throw an error; and "get" would get a specific version of a call. So `observeCalled` would return true if a spy was called, `observeThrew` would return true if a function threw. `expectCalledOn` would be like `observeCalledOn`, but it would be clear that it's going to to `throw` rather than returning `false`. This would also help with mocks where `withArgs` might become `expectWithArgs` for a mock, and it wouldn't be confused with `getWithArgs` from stub.

I think all the documentation could be arranged into "observe / expect", "fake", and "selection" (or whatever synonyms you like) which would really help with the learning curve. And of course, all the existing calls could be aliased to new names for backwards compatibility.

Of course, this is all a bit more than the original issue... :)

**Comment by mantoni** [comment]
It would be great if we could stick to the one change here. It's too late to change things for 2.0 as we're only waiting for a single regression before it goes out. There are other changes planned for later major releases and your suggestions could be either added there or you could open another issue where we can discuss.

Re the original issue: Yes, it might be very simple. Make sure to add a unit test :)

I suggest you add it on the main line first, which is 2.0, and then it can be backported to 1.17.

**Comment by apowers313** [comment]
As I'm digging in to this, it looks like there's no `spy.returned()` call that operates on an individual spy, just one that operates on all the spies. Am I correct in assuming that `mirrorPropAsAssertion("returned", ...)` would require `spy.returned()` for single spies to exist first?

**Comment by apowers313** [comment]
By the way, here is what I was thinking for more consistent APIs:
https://apowers313.github.io/candy-wrapper/

**Comment by apowers313** [comment]
Still happy to put together a PR with a little help -- is there some way to mirror a property for `spy.returned` where `returned` is for the plural sense of the spy?

**Comment by mroderick** [comment]
I am finding it a bit difficult to get a clear picture of how this would be used.

@apowers313 would you mind posting a usage example to help me understand it better?

**Comment by mantoni** [comment]
@mroderick As I understand it, it's to assert the return value of a spy. Doesn't make much sense for stubs, of cause.

**Comment by mroderick** [comment]
> @mroderick As I understand it, it's to assert the return value of a spy

Asserting the return value of a function is just about the most basic thing an assertion library can do. Do we need to add a specialised helper for this, just because the function is wrapped in a spy?

```javascript
function greet(name) {
    // implementation
}

const name = 'morgan';
const expected = `hello ${name}`;
```

```javascript
// sinon.assert.returns
const greetSpy = sinon.spy(greet);

greetSpy(name);

sinon.assert.returns(spy, expected);
```

```javascript
// this works in any assertion library
const actual = greet(name);

assert.equals(actual, expected);
```

Considering the usage scenario above, I think this would just add more noise and increase cognitive load of reading tests for the casual contributor that might not know Sinon.

Am I missing something?

**Comment by mantoni** [comment]
Basically, you're right and this is how I'd assert a return value too. However, two things cone to my mind why it would make sense:

- The sinon assertions produce nice output, especially when using matchers.
- If the spy is injected and the return value is used in the tested code internally, you'd have to retrieve the value with `spy.firstCall.returnValue`.
