### ISSUE TITLE
Assert.calledWith seems not work when parameter is modified afterwards by reference

### ISSUE THREAD

**Issue by DamienGallet** [sinonjs/sinon#1328]
Hi !

I'm working in NodeJs with mocha, and the latest version of Sinon (1.17.4 at least).
I try to stub some methods in a class, but I've a problem in the assert when I want to check that the function has been called with the good parameters, especially when parameters are modified below in the tested function.
Here you'll find a sample of code which isn't apparently working properly : 
```javascript
class TestedClass {

    testedFunction() {
      const paramForMock = {};
      this.mockedFunc(paramForMock);
      paramForMock.modified = true;
    };

    mockedFunc(param) {
      console.log('Should not appear');
      return true;
    };

  }


  describe.only('Test sinon', () => {
    it('should work', () => {
      const testedClass = new TestedClass;
      sandbox.stub(testedClass, 'mockedFunc').returns(false);
      testedClass.testedFunction();
      sinon.assert.calledWith(testedClass.mockedFunc, {});
    });
  });
```

Final output is the following
```
  AssertError: expected mockedFunc to be called with arguments {  }
      mockedFunc({ modified: true }) => false at TestedClass.testedFunction
```

Don't hesitate to contact me for any further information !

**Comment by mantoni** [comment]
This was discussed in #583 and #571 and there is a proposal for a solution in #665. Closing as duplicate.
