### ISSUE TITLE
Little bug in spy.printf "%*" formatter

### ISSUE THREAD

**Issue by eauc** [sinonjs/sinon#1332]
First of all, many thanks for all your hard work on sinon ;)

* Sinon version : v2.0.0
* Environment   : all ? found in node v4
* Example URL   : n/a
* Other libraries you are using: sinon-chai, chai

**What did you expect to happen?**
In the spy.printf(format, args...) function,
when using the "%*" formatter, and passing a list of strings as arguments,
I'd expect all the string to be unquoted.

**What actually happens**
the first string is unquoted,
all the others ones are quoted.

**How to reproduce**
npm install sinon@2.0.0
$ node
> const sinon = require("sinon")
> const spy = sinon.spy()
> spy.printf("%*", "a","b","c")
a, "b", "c"

**The Bug**

In lib/sinon/util/core/format.js:
```
var formatter = formatio.configure({
    quoteStrings: false,
    limitChildrenCount: 250
});

module.exports = function format() {
    return formatter.ascii.apply(formatter, arguments);
};
```
you're calling formatio.ascii with all the arguments of your sinonFormat function.

In lib/sinon/spy-formatters.js
```
module.exports = {
    ....
    "*": function (spyInstance, args) {
        return args.map(sinonFormat).join(", ");
    }
};
```
You're calling sinonFormat directly with map.
- sinonFormat is called with (value, index, collection)
- formatio.ascii is thus called with (value, index, collection)
- formatio.ascii expect (value, processedFlad, indentValue)

the index masquerade as the processedFlag, resulting in the first string being correctly unquoted (index 0 == false) and all the others being quoted (index>0 == true)

**Context**

I tried to make the sinon-chai module work with sinon@2.0.0.
I ran the tests for sinon-chai, and the only error is in the format of the expectation messages.
I traked it down to this little bug in sinon.

**Comment by fatso83** [comment]
Thanks for your detailed investigation. That helps a lot! Do you have any chance of fixing this with a small PR?
