### ISSUE TITLE
feature: create a way to pull args set with `withArgs`

### ISSUE THREAD

**Issue by tswaters** [sinonjs/sinon#1335]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : ^1.16.1 
* Environment   :  n/a
* Example URL   :  n/a
* Other libraries you are using:  n/a

Consider the following:

There is an asynchronous function that calls into a few different async calls.  You can't really verify the order in which they fire... The code under test:

```js
module.exports.test = (arg1, args2, cb) => {
  async.auto(
    next => service.act('some-paramter', {args1}, next),
    next => service.act('other-paremter', {args2}, next)
  ), cb)
}
```

(Of course, I've glossed over that args1 and args2 are modified somehwat before making their way to service hence the need for the test and assertions on the arguments)

So to test, 

```js
it('should work properly with foo:bar', done => {
  actStub = sinon.stub(service, 'act')
  actStub.withArgs('some-paramter').callsArgWith(2, 'first-response')
  actStub.withArgs('other-paramter').callsArgWith(2, 'second-response')
  test({foo: 'bar'}, null, () => {
    // how to test that args1 and args2 were provided properly?
    done()
  })
})
```

So the goal here is to assert that `args1` and `args2` are passed properly to the service.

Someone will need to correct me if I'm wrong, but as it stands, the only way to get at the call details from the stub is through `actStub.args`, or `firstCall` and the like.  But because async runs in `setImmediete` I don't think it can be relied upon that the order of calls will always be the same.

Is it possible to create an api method that can be used to retrieve calls based upon the same conditions provided to `withArgs`.... in the above example this would make it possible to assert `arg1` was provided properly to the function with something like the following: 

```js
assert.deepEqual(actStub.callsWith('some-paramter')[1], {foo: 'bar'})
```

I guess my question is am I missing something that makes this already possible with the current API?  It seems like it's missing.

I suppose I could write my own wrapper that scans `actStub.args`  for whatever argument provided and return the full arguments, but it seems like sinon should be able to do this.

**Comment by mantoni** [comment]
You can either

```js
assert(actStub.calledWith('some-parameter', { foo: 'bar' })
```

or for slightly better failure messages

```js
sinon.assert.calledWith(actStub, 'some-parameter', { foo: 'bar' })
```

Both will only succeed if both arguments match, so you don't need to pre-select the correct call. `calledWith` matches any call with the given arguments.

**Comment by tswaters** [comment]
Thanks
