### ISSUE TITLE
Sinon v2 spy.printf's %* only quotes strings in the second-onward argument

### ISSUE THREAD

**Issue by domenic** [sinonjs/sinon#1342]
* Sinon version : 2.0.0
* Environment   : Node.js
* Example URL   : https://runkit.com/582a9986f5baa400148ace47/58cf607cedfee80014e6890c
* Other libraries you are using: None in isolated example

**What did you expect to happen?**

This should have printed the arguments as `"a", "b", "c"`

**What actually happens**

It printed the arguments as `a, "b", "c"`, stripping the quotes from the first one

**How to reproduce**

https://runkit.com/582a9986f5baa400148ace47/58cf607cedfee80014e6890c, or simply:

```
const sinon = require("sinon");
const spy = sinon.spy();
console.log(spy.printf("%*", "a", "b", "c"));
```

**Comment by fatso83** [comment]
Thanks, this was fixed a few days ago - we just need to ship a patch.  See #1333. Sorry for your unneeded troubles of submitting this, but thanks anyway! 🙏
