### ISSUE TITLE
Document calledImmediatelyBefore/After

### ISSUE THREAD

**Issue by domenic** [sinonjs/sinon#1349]
* Sinon version : 2.1.0
* Example URL   : http://sinonjs.org/releases/v2.1.0/spies/

**What did you expect to happen?**

In the changelog for 2.1.0 two new methods were introduced. I am unsure whether they are officially supported though as they do not appear in the docs.

I would expect these methods to either be documented, or for the changelog to note that they are experimental and unsupported.

I'll hold off from supporting these in Sinon-Chai until I hear back.

**Comment by fatso83** [comment]
Not sure how we missed that in #1337. Would you mind adding some simple docs, @timcosta?

**Comment by timcosta** [comment]
Will do first thing this morning when I get in. About two hours till you have a PR.

**Comment by fatso83** [comment]
Closed by #1350

**Comment by fstoerkle** [comment]
Follow-up question for this: I would have expected to find documentation for `calledImmediatelyBefore/After` here: http://sinonjs.org/releases/v2.1.0/spies/

However, I can't find it here. Am I looking in the wrong place?
Or might it be that the documentation changes were not published on the website?

**Comment by timcosta** [comment]
http://sinonjs.org/releases/v2.2.0/spies/

Documentation can be found here.

**Comment by fstoerkle** [comment]
Alright, everything in place now. It was not there before the `2.2.0` release this morning, but never mind :) thanks 👍
