### ISSUE TITLE
Enhancement: Add ability to override global promise library

### ISSUE THREAD

**Issue by blacksun1** [sinonjs/sinon#1354]
* Sinon version : 2.1.0
* Other libraries you are using: Bluebird

Hi,

I want to be able to override the default promise library with an external library such as Bluebird or Q.

We don't want to override the Global Promise library (which is the native Promise library) but instead import/require it when needed.

Would you be interested in me providing a Pull Request for this or would I have to create a fork.

Thanks in advance,

**Comment by mantoni** [comment]
Can you please elaborate why you think your use case needs a change in Sinon?

**Comment by mroderick** [comment]
How do you imagine using it?

Like [`sinon-as-promised`](https://github.com/bendrucker/sinon-as-promised/blob/master/examples/bluebird/test.js) does it?

**Comment by Kynde** [comment]
Use case is that our code uses Bluebird additions like .tap() and .finally(). Stubbing with the native Promises does not really work.

We used to use sinon-as-promised and that allowed using Bluebird.  Now I have horrible kludge in test suites that add such missing functions to the native Promise prototype and I would really like to get rid of that.

**Comment by blacksun1** [comment]
Yes, that is our issue as well.

At the moment, our code looks like this

```js
sinon.stub(someObject, 'someMethod').callsFake(() => return bb.Promise.resolve({}));
```

I would want to work like this though.

```js
const bb = require('bluebird');
const sinon = required('sinon');

sinon.promiseLibrary = bb.Promise
sinon.stub(someObject, 'someMethod').resolves({});
sinon.stub(someObject, 'someOtherMethod').resolves({});
```

or

```js
const bb = require('bluebird');
const sinon = required('sinon');

sinon.stub(someObject, 'someMethod').resolves({}); // Would default to global promise
sinon.stub(someObject, 'someMethod').resolves({}, bb.Promise); // World use included promise
```

I think it would be important to be able to select the specific library you want to resolve with as sometimes we work with various libraries that return various promise types.

**Comment by fatso83** [comment]
We could add a `configure` call like `sinon-test`? https://github.com/sinonjs/sinon-test#usage

**Comment by blacksun1** [comment]
Or

```js
sinon({ promiseLibrary: bb.Promise }).stub();
```

**Comment by fatso83** [comment]
Yeah, as long as we configure an instance of Sinon, and not set defaults globally I don't mind either way. We fought long and hard to get rid of globals before the release of version 2, so let's not introduce more 😄

**Comment by blacksun1** [comment]
Please see https://github.com/sinonjs/sinon/pull/1364

Documentation hasn't been written yet as I wanted to run past with you guys the interface first.

The reason I used `.setPromise` was so that it didn't muck with any of the other interfaces and so it is absolutely clear as to what it is doing.

I thought that I could probably implement setPromise on a sandbox or sinon object as well.

**Comment by blacksun1** [comment]
@fatso83 @Kynde @mantoni

**Comment by blacksun1** [comment]
Hi @fatso83 @Kynde @mantoni @mroderick,

This should be ready to go unless someone has any other comments?


Thanks in advance,

**Comment by fatso83** [comment]
@blacksun1 Your contribution is probably fine, but I am travelling around Japan untill May (with just a cheap cell phone), so someone else needs to dig into this. We are poorly paid for these efforts, so we need to take turns when we have some spare time :-)

**Comment by fatso83** [comment]
Never mind my previous comment - I was able to get at this anyway :-)

**Comment by fatso83** [comment]
Maybe someone else in @sinonjs/sinon-core would like to publish a new version?

**Comment by lumaxis** [comment]
Any chance of getting a release with this soon? 🙂

**Comment by mroderick** [comment]
@lumaxis `sinon@2.2.0` is now on `npm`

**Comment by lumaxis** [comment]
@mroderick Thanks a lot! 🙏 🎉
