### ISSUE TITLE
Missing documentation on how to create a fake server for Node.js applications

### ISSUE THREAD

**Issue by bennyn** [sinonjs/sinon#1367]
**Sinon version:** Sinon v2.1.0

**Environment:** Node.js v7.7.3

**Other libraries you are using:**
- [Jasmine](https://github.com/jasmine/jasmine)
- [request](https://github.com/request/request)

I always used Sinon in combination with Jasmine and a Karma test runner (to execute Browser tests). Now I want to use Sinon in a Node.js environment and I want to mock server responses. 

In my Node.js application I don't use jQuery, so I cannot make use of `sinon.spy(jQuery, 'ajax');`. In [your documentation](http://sinonjs.org/releases/v2.1.0/fake-xhr-and-server/) I read that I can fake the `XMLHttpRequest` object (if not using jQuery), but it also looks like Node.js doesn't make use of the standard `XMLHttpRequest`. 

So do I need a wrapping module for Node.js requests like [node-XMLHttpRequest](https://github.com/driverdan/node-XMLHttpRequest) to make it work?

Here is the code I have written so far:

```js
const sinon = require('sinon');
const EndpointValidator = require('./../src/EndpointValidator');

let server = undefined;
let validator = undefined;

beforeAll(() => {
  server = sinon.fakeServer.create();
  server.autoRespond = true;
  server.respondWith('GET', 'http://www.mypage.com/online', [
    200, {
      'Content-Type': 'application/json'
    }, JSON.stringify({
      "status": "online"
    })
  ]);
});

beforeEach(() => {
  validator = new EndpointValidator();
});

afterEach(() => {
  server.restore();
});

describe('EndpointValidator', () => {
  it('checks for a valid endpoint', (done) => {
    validator.isValidEndpoint('http://www.mypage.com/online')
      .then((data) => {
        const json = JSON.parse(data);
        expect(json.status).toBe('online');
        done();
      })
      .catch(done.fail);
  });
});
```

**EndpointValidator.js**

```js
const request = require('request');

class EndpointValidator {
  constructor() {
  }

  isValidEndpoint(url, minimumBodyLength = 0) {
    return new Promise((resolve, reject) => {
      request.get(url, function(error, response, body) {
        if (response.statusCode !== 200) {
          reject(new Error('Service is temporarily unavailable.'));
        } else {
          if (response.body.length > minimumBodyLength) {
            resolve(body);
          } else {
            resolve(false);
          }
        }
      });
    });
  }
}

module.exports = EndpointValidator;
```

**Comment by vkhv** [comment]
![2017-10-02 9 55 35](https://user-images.githubusercontent.com/6794386/31066775-dfef1fe2-a757-11e7-9c17-69aea7c13e33.png)

**Comment by fatso83** [comment]
@v0lkan Please don't dump errors without context in a random issue. File a new issue if you have a reproducible case. Deleting your comment.

**Comment by fatso83** [comment]
This issue was moved to sinonjs/nise#56
