### ISSUE TITLE
Missing breaking change in stub reset behaviour from migration guide

### ISSUE THREAD

**Issue by antiBaconMachine** [sinonjs/sinon#1370]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : 2.x
* Environment   : All
* Example URL   : http://sinonjs.org/releases/v2.0.0/migrating-to-2.0/
* Other libraries you are using: node assert

**What did you expect to happen?**
Hi all, thanks so much for your great work on Sinon 2.

I just noticed the documentation on breaking changes doesn't include a description of the new granular stub reset behaviour.

**What actually happens**

There should probably just be a note explaining that `stub.reset` now also resets behaviour.

**How to reproduce**

```
#! /usr/bin/env node
const sinon = require('sinon')
const assert = require('assert')

const foo = sinon.stub.create().returns('foo')
foo.reset()                  // In sinon 2 we want foo.resetHistory();
assert.equal(foo(), 'foo')   // Pass in sinon 1, fail in sinon 2
```

I'd be happy to PR the documentation if that is appropriate? Having not contributed to this project before, I don't want to step on anyones toes.

Thanks again

**Comment by jroitgrund** [comment]
Ran into the exact same issue, but doing `reset` with `resetHistory` didn't unbreak my tests. Any ideas?
