### ISSUE TITLE
onCall does not work properly on mocks

### ISSUE THREAD

**Issue by guygeva** [sinonjs/sinon#1381]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : 2.10.
* Environment   : node.json ubuntu
* Other libraries you are using: Jasmine

**What did you expect to happen?**
I tried to use onCall to determine different return values for different call

**What actually happens**
First call works fine, second call returns undefined

**How to reproduce**
This test fails:

class C {
        public f() {return 1111; }
    }

    it('test', () => {
        let c = new C();
        let mock = sinon.mock(c);
        mock.expects('f').onCall(0).returns(0);
        mock.expects('f').onCall(1).returns(1);
        expect(c.f()).toBe(0);
        expect(c.f()).toBe(1);
    });

**Comment by mantoni** [comment]
I think you should store the result of calling `expects` in a variable and reuse the same instance, like this:

```js
it('test', () => {
    let c = new C();
    let mock = sinon.mock(c);
    let stub = mock.expects('f')
    stub.onCall(0).returns(0);
    stub.onCall(1).returns(1);
    expect(c.f()).toBe(0);
    expect(c.f()).toBe(1);
});
```

Also, consider using `var stub = sinon.stub(c, 'f')` in a simple case like this.

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
