### ISSUE TITLE
Add callThrough() to documentation

### ISSUE THREAD

**Issue by peteringram0** [sinonjs/sinon#1382]
There is no mention of callThrough() within any of the documentation however i found this method within the commits.

https://github.com/sinonjs/sinon/commit/f36196d702cafce2d8c0fba768a0fb9c60f85b9e

Its a useful thing that people coming from Jasmine would like to know about.

Thanks,

**Comment by mantoni** [comment]
It's documented here including a code example: http://sinonjs.org/releases/v2.1.0/stubs/
