### ISSUE TITLE
What is the recommended way to both invoke an argument and return the result of that invocation?

### ISSUE THREAD

**Issue by kurttheviking** [sinonjs/sinon#1384]
### Environment

* Sinon version: 2.1.0
* Environment: Ubuntu 16.04, Node 6.9.1, NPM 3.10.8
* Other libraries you are using: chai (expect), mockery

### What did you expect to happen?

I am attempting to stub a module that only exports a function. I would like to invoke **and** return an argument, effectively equivalent to:

```js
sinon.stub().callsArg(1).returnsArg(1);
```

### What actually happens?

One cannot chain `callsArg` and `returnsArg` this way, and that makes sense. Instead, if the test had access to the full the following would work:

```js
var stub = sinon.stub(object, "method", function (arg1, arg2) {
  return arg2();
});
```

However, in this particular case, the source module *only* exports a function and thus there is no `Object` or "method" available to stub. Moreover, the following is invalid:

```js
var stub = sinon.stub(function (arg1, arg2) {
  return arg2();
});
```

What is the recommended way to both **invoke** an argument and **return** the result of that invocation? I am happy to work on a PR if you are open to this feature (something like the last example would suffice).

**Comment by mantoni** [comment]
I think you have two issues here:

- The module you're trying to stub only exports a function. Follow the instructions provided in [How to use Link Seams with CommonJS](http://sinonjs.org/how-to/link-seams-commonjs/) for a possible solution.
- You correctly stated that `sinon.stub(function () {})` is invalid. You want `sinon.spy(function () {})` 😉

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
