### ISSUE TITLE
callCount nor called are not registered on a stub

### ISSUE THREAD

**Issue by keligijus** [sinonjs/sinon#1385]
* Sinon version : 2.1.0
* Environment   : Mac
* Example URL   : https://github.com/keligijus/vue-stub-demo/
* Other libraries you are using: 'mocha', 'sinon-chai', 'chai-lodash'

**What did you expect to happen?**

Get correct callCount of a stub (or correct .called boolean)

**What actually happens**

Only get a correct callCount of the first call of it. Count (or the fact that it's called) of other calls seems to not registered

**How to reproduce**

Please use the repo I created for this https://github.com/keligijus/vue-stub-demo/

`npm install` and `npm run unit` should do the trick.

Sorry for no JSBin or similar, I'm not sure how to replicate my set up there.

p.s. I am still confused if a stub has properties of a spy. From other tests I can see that whatever is available for a spy, is also available for a stub.

**Comment by mantoni** [comment]
There are no tests in the provided repository.

**Comment by keligijus** [comment]
Hey @mantoni, sorry, the only spec file is here https://github.com/keligijus/vue-stub-demo/blob/master/src/components/messages/_tests/MessageComposer.spec.js

**Comment by mantoni** [comment]
There is too much going on. Please reduce the example to a single case where things don't behave as you expect.

**Comment by keligijus** [comment]
Sounds good. Doing that.

**Comment by keligijus** [comment]
Removed all unnecessary stuff. Here's the branch https://github.com/keligijus/vue-stub-demo/tree/trimmed

I think I've identified the problem. Adding Vue mixins to the component breaks the desired behaviour. The mixin I added is very simple, only has one method.

To get desired behaviour, you can remove this line: https://github.com/keligijus/vue-stub-demo/blob/trimmed/src/components/messages/MessageComposer.vue#L21

Once there're no mixins, `callCount` works as expected.

**Comment by mantoni** [comment]
Well, I guess the mixin creates a new type on the fly and you're installing the stub on the "original" type. Given that the call count works as expected when you remove the mixin this does not seem to be an issue with Sinon. Closing.

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. If you have further questions, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

**Comment by keligijus** [comment]
Hey @mantoni, I just realised that this may be a problem with Sinon. The problem is that the `callCount` only works on the first test, but breaks for other tests. So your theory above may not be fully correct. 

Also, the original function is not run for any of the tests. This tells me that the stub is actually installed, but callCount and called are not working as expected. Again, only works for the first test, breaks for others (says 0)

**Comment by mantoni** [comment]
@keligijus I consider it very unlikely that this core part of Sinon has a critical bug like this. I'm happy to reopen this issue if you can extract a simple reproducible case that is free of side effects from other libraries. Otherwise, I don't think any of the maintainers will find the time to look into this.

**Comment by keligijus** [comment]
Ok thanks @mantoni. As you suggested, I've posted on the mailinglist, will see if anyone had a similar problem. Do you think going on Stackoverflow for this is wise?
