### ISSUE TITLE
Documentation confusing for spy.withArgs

### ISSUE THREAD

**Issue by unphased** [sinonjs/sinon#1386]
https://github.com/sinonjs/sinon/blame/master/docs/_releases/v2.1.0/spies.md#L160

**What did you expect to happen?**

example to use the return value of `spy.withArgs()`.

**What actually happens**

example code does not do so and generated confusion in the mind of the reader, requiring reader to write a test program to test it.

**Testing of the functionality**

```javascript
var sinon = require('sinon');
var assert = require('assert');
var object = { method: function () {}  };
var spy = sinon.spy(object, "method");
var spy42 = spy.withArgs(42);

// these statements will do nothing
spy.withArgs(1);
spy.withArgs(2);
spy.withArgs(3);

object.method(42);
object.method(1);

assert(spy.withArgs(42).calledOnce);
assert(spy42.calledOnce);
assert(spy.withArgs(42) === spy42);
assert(spy.calledTwice);

console.log("spy.args", spy.args);
console.log("spy42.args", spy42.args);
console.log("spy.withArgs(1).args", spy.withArgs(1).args);
console.log("spy.withArgs(42).args", spy.withArgs(42).args);
```

```
$ node test.js
spy.args [ [ 42 ], [ 1 ] ]
spy42.args [ [ 42 ] ]
spy.withArgs(1).args [ [ 1 ] ]
spy.withArgs(42).args [ [ 42 ] ]
```

**Comment by mantoni** [comment]
Can you be more specific about where exactly you think the documentation is confusing? What you stated here is all obvious and clear to me. I don't see the issue.

**Comment by unphased** [comment]
Sure, yeah sorry i wasnt being clear and also being kind of smug. Heres the doc i referenced: 

```
157  "should call method once with each argument": function () {
158    var object = { method: function () {} };
159    var spy = sinon.spy(object, "method");
160    spy.withArgs(42);
161    spy.withArgs(1);
162
163    object.method(42);
164    object.method(1);
165
166    assert(spy.withArgs(42).calledOnce);
167    assert(spy.withArgs(1).calledOnce);
168  }
```

Lines 160 and 161 are complete no-ops...

**Comment by mantoni** [comment]
Ah, yes, now I see. Yeah, you're right. These two lines there are no-opts and should be removed. Can you send a pull request?

**Comment by unphased** [comment]
I'd be happy to! @mantoni the file in question would be `docs/release-source/release/spies.md`?

**Comment by mantoni** [comment]
Thank you!
