### ISSUE TITLE
Sandbox doesn't work with simple stub functions

### ISSUE THREAD

**Issue by SCdF** [sinonjs/sinon#1387]
* Sinon version : 2.0.0
* Environment   : MacOS

**What did you expect to happen?**
When you create a sinon sandbox, all stubs you create from that sandbox are reverted to their default state if `sandbox.restore()` is called.

**What actually happens**
Raw stubs (`sandbox.stub()`) are not reverted.

**How to reproduce**
```
$ cat node_modules/sinon/package.json | jq .version
"2.0.0"
$ node
> const sandbox = require('sinon').sandbox.create();
undefined
> const stub = sandbox.stub();
undefined
> stub();
undefined
> stub.callCount
1
> sandbox.restore();
undefined
> stub.callCount
1 <-- this should be undefined / 0
> sandbox.reset();
undefined
> stub.callCount
1
```
This is just for raw stubs. `restore()` works if the stub is against something (which is the example used in the documentation):
```
> const fakeApi = { afunct: () => {} };
undefined
> sandbox.stub(fakeApi, "afunct")
...snip...
> fakeApi.afunct()
undefined
> fakeApi.afunct.callCount
1
> sandbox.restore();
undefined
> fakeApi.afunct.callCount
undefined
```

**Comment by mantoni** [comment]
Uh, nice one. I can reproduce and will fix.

**Comment by mantoni** [comment]
While hacking the "fix", I re-discovered that this is by design. You're looking for `sandbox.reset()`, which resets the call count and other properties. `sandbox.restore()` does not reset the stubs. This is in line with `sinon.stub()` behavior. Consider this example:

```js
const sinon = require('sinon')

const object = { test: function () {} }
const stub = sinon.stub(object, 'test')

object.test()
object.test.restore()

stub.callCount // <- 1

stub.reset()

stub.callCount // <- 0
```

**Comment by SCdF** [comment]
Oh. Confusing.

So `sandbox.restore()` works on stubs attached to objects (my second example) because it's restoring the object to no longer being stubbed, which is different (though achieves a similar effect) to resetting a stub's various counts etc.

**Comment by mantoni** [comment]
It's not similar. They're distinct operations. `restore` removes the stub, but does not change the counts. `reset` changes resets the counts but does not remove the stub.
