### ISSUE TITLE
useFakeTimers and spying on Date constructor

### ISSUE THREAD

**Issue by dualcyclone** [sinonjs/sinon#1394]
I haven't found a clear example of this; essentially I have a production app that can do a couple of things; one is to persist a Date object given a certain setter is called, and one is to create a new Date given a certain object parameter is set, I'll try and create an example of the class below:

```
var someDateSingleton = (function () {
    var self = this;   
    var privateEnv = 'default';
    var privateDate = null;

    Object.defineProperty(self, 'someEnvironment', {
       enumerable: true,
       get: function() { return privateEnv; },
       set: function(val) { privateEnv = val; }
    });

    Object.defineProperty(self, 'someDate', {
       enumerable: true,
       get: function() { return privateDate; },
       set: function(val) { privateDate = val; }
    });

    self.getSpecificDate = function () {
        if (privateEnv === 'default' && privateDate !== null) {
            return privateDate;
        }
        return new Date();
    }

    return self;
}());
```

In this example, I can test to see if the response from a call to ```new Date()``` is expected using ```useFakeTimers``` by testing the output from ```someDateSingleton.getSpecificDate()```. This also works if I say ```someDateSingleton.someDate = new Date(2011, 1, 1);``` - all good.

If I change the env, eg: ```someDateSingleton.someEnvironment = 'blah';```, then in an ideal world, I'd like to test the response not only responds with that provided as part of ```sinon.useFakeTimers```, but also that the main ```Date``` constructor was called.

Any idea how I may do this? Otherwise it'd be good to have some core method inside Sinon, eg...

```
var clock = sinon.useFakeTimers();

var blah = new Date();

expect(clock.constructor).to.have.been.called;
```

**Comment by mantoni** [comment]
How about this:

```js
var sandbox = sinon.sandbox.create();

sandbox.stub(window, 'Date'); // Or global, if you're on node

sinon.assert.calledWithNew(Date);
```

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
