### ISSUE TITLE
Stubs for ES6 imports are not working

### ISSUE THREAD

**Issue by burnall** [sinonjs/sinon#1396]
I have troubles with some basic cases of using `stub` for ES6 modules.
Basically, only `export function` is stubbable .
```
// try-sinon.js
export function foo() {
    return 22;
}

export const bar = () => 44;

function aa() {
    return 'aa';
}

export {
    aa
}

// test.spec.js
import * as all from 'try-sinon';

stub(all, 'foo').returns(1000); // This stub works: all.foo() === 1000
stub(all, 'bar').returns(1001); // No luck: all.bar() === 44 
stub(all, 'aa').returns('aab'); // Too bad: all.aa() === 'aa'
```
I use sinon 2.2, webpack 2.5.0.
See [full example on Github](https://github.com/burnall/sinon-webpack-es6-modules).
The issue is related to the way how Webpack generates bundles with `babel-preset-es2015-webpack`. In order to enable tree-shaking, `modules` should be set `false` what means that transformation of ES6 module syntax to another module type is disabled.

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
