### ISSUE TITLE
Problem with useFakeTimers: Promise are freeze when resolve it from setTimeout

### ISSUE THREAD

**Issue by Qoter** [sinonjs/sinon#1397]
* Sinon version : 2.2.0
* Environment   : Node.js v6.10.2
* Other libraries: mocha 3.3.0

**Code example**
```javascript
it('promise freeze', () => {
    let clock = sinon.useFakeTimers();
    let p = Promise.resolve()
        .then(() => new Promise(resolve => setTimeout(resolve, 5)));
    clock.tick(1000);
    return p;
});
```

I expect that test will pass.  
But test fail with **timeout** and promise are frozen.  
Without sinon.useFakeTimers() this test will pass.

**Comment by lucasfcosta** [comment]
Hi @Qoter, I believe this happens because you either gotta use a timmer from the `clock` variable you assigned `useFakeTimers` to or you need to call the `install` method.

This is one of the possible fixes for your test:

```js
let clock = fakeTimers.useFakeTimers();
let p = Promise.resolve()
  .then(() => new Promise(resolve => fakeTimers.timers.setTimeout(resolve, 5)));
clock.tick(1000);
return p;
```

The other one, using `install` to replace the global `setTimeout` function can be used by installing the `lolex` module, as you can see in [this section at Lolex docs](https://github.com/sinonjs/lolex#faking-the-native-timers).

**Comment by Qoter** [comment]
Hello @lucasfcosta)))
Your test works!)  
But when i use ```lolex.install()``` to replace global ```setTimeout``` promise still frozen.

Examples:  

1. It works (use ```lolex.timers.setTimeout```)
```javascript
let clock = lolex.install();
let p = Promise.resolve()
    .then(() => new Promise(resolve => lolex.timers.setTimeout(resolve, 5)));
clock.tick(1000);
return p;
```

2. It fails with timeout
```javascript
let clock = lolex.install();
let p = Promise.resolve()
    .then(() => new Promise(resolve => setTimeout(resolve, 5)));
clock.tick(1000);
return p;
```

3. btw it also works when i didn't return ```promise``` from ```then```
```javascript
let clock = lolex.install();
let p = new Promise(resolve => setTimeout(resolve, 5000));
clock.tick(1000);
return p;
```  
  
I really do not understand why this happens.  
Thank you!

**Comment by mroderick** [comment]
Has this stalled?

**Comment by Qoter** [comment]
@mroderick 
Sorry, i didn't understand you(
What do you mean?

**Comment by fatso83** [comment]
Are you using any Promise libraries? They often use timers to create polyfills, which might be affected by faking time.

**Comment by Qoter** [comment]
@fatso83 No, I use default Promise from node.js

**Comment by macdonaldr93** [comment]
+1 I'm having this issue too. Just using native Promise

**Comment by robertstettner** [comment]
+1 I'm having this issue too.

**Comment by fatso83** [comment]
We should probably move this to lolex, to get it fixed.

**Comment by fatso83** [comment]
This issue was moved to sinonjs/lolex#194
