### ISSUE TITLE
 TypeError: Attempted to wrap undefined property handleBlu as function

### ISSUE THREAD

**Issue by wangling900226** [sinonjs/sinon#1402]
describe('调用Demo组件中的handleBlu方法',()=>{
    let spy=sinon.spy(Demo,"handleBlu")
    it.only("检查是否被调用", function () {
        const wrapper = mount(<Demo {...props} />);
        wrapper.find('input').simulate('blur', { target: { value: 'bar' } });
        expect(spy.callCount).to.be.equal(1)
    })
})

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
