### ISSUE TITLE
Sinon stubs don't clone the arguments, causing some assertions to fail

### ISSUE THREAD

**Issue by marcogrcr** [sinonjs/sinon#1404]
* Sinon version : 2.2.0
* Environment   : Node 6.10.2

**What did you expect to happen?**

Sinon stubs should make a clone of the arguments, so if an argument is modified after the stub call, the assertions about the passed parameters wont fail.

**What actually happens**

Sinon stores references of the passed arguments, so if an argument is modified after the stub call, the assertions about the passed parameters fail.

**How to reproduce**

**package.json**

```json
{
  "dependencies": {
    "sinon": "2.2.0"
  },
  "name": "sinon-bug",
  "private": true,
  "version": "1.0.0"
}
```
**index.js**

```js
"use strict";

const sinon = require("sinon");

let stub = sinon.stub();

let param = { foo: "foo" };
stub(param);

param.bar = "bar";
stub(param);

/*
 * FAIL
 *
 * Expected : { foo: 'foo' }
 * Actual   : { foo: 'foo', bar: 'bar' }
 */
console.log(stub.firstCall.args[0]);

/*
 * OK
 *
 * Expected : { foo: 'foo', bar: 'bar' }
 * Actual   : { foo: 'foo', bar: 'bar' }
 */
console.log(stub.secondCall.args[0]);
```

**Comment by mroderick** [comment]
This has been discussed a few times already:

* https://github.com/sinonjs/sinon/issues/583
* https://github.com/sinonjs/sinon/issues/571

We are trying very hard not to go against the grain of the language
