### ISSUE TITLE
Consider emphasizing createStubInstance more heavily in docs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sinonjs/sinon#1421]
Right now there are only two sentences describing `sinon.createStubInstance(constructor);` without an actual code sample. For folks using ES6 classes, it can be very useful to have one-liners to create instances of classes. 

Would you be up for a third sentence mentioning this is useful for classes, along with a code snippet showing it in use?

**Comment by fatso83** [comment]
Sure, any improvement that makes it more obvious for folks how to do a certain thing, and that let's us keep the noise level down in the issue tracker is an obvious boon.
