### ISSUE TITLE
Mocha.js and useFakeTimers giving global leak errors

### ISSUE THREAD

**Issue by camwest** [sinonjs/sinon#143]
I get this error when running Mocha 1.1.0 and sinon 1.3.4

Error: global leaks detected: setTimeout, setInterval, clearTimeout, clearInterval

``` javascript
beforeEach(function() { this.clock = sinon.useFakeTimers(); });
afterEach(function() { this.clock.restore(); });
```

**Comment by mightyiam** [comment]
Is it possible to mitigate this by only setting `window.setTimeout` and friends if a feature that requires them is used?

I'm assuming that most of Sinon's features do not require this.
