### ISSUE TITLE
 How to restore $?

### ISSUE THREAD

**Issue by sdejanovic** [sinonjs/sinon#1439]
* Sinon version : I am using Sinon.JS 2.3.2, 2017-05-26
* Environment   :
* Example URL   :  http://sdejanovic.sitesstage.com/QUnitTest.html
* Other libraries you are using: QUnit 2.3.0

**What did you expect to happen?**
I want to restore $ because I have more unit tests.

**What actually happens**
When I add $.restore(); in the end of unit test and receive an error "$.restore is not a function".

I have unit test:
<details>

```
QUnit.test('DisplayToastMessage - testing CalculateAdditionalHeight function call', function (assert) {
    var $alert = $($.parseHTML(HTMLInjectorAlertHelperTestsModalNotification())).clone();

    var mock = sinon.mock(AlertHelper);

    $ = sinon.stub();
    $.withArgs('body > .modal.small').returns({ "length": 42 });
    $.withArgs('.header').returns({ outerHeight: function() { } });
    $.withArgs('body > .notification-wrapper').returns({ append: function () { } });

    var expectationCalculateAdditionalHeight = mock.expects("CalculateAdditionalHeight");
    expectationCalculateAdditionalHeight.once();

    AlertHelper.DisplayToastMessage($alert);

    mock.verify();
    assert.ok(mock.verify(), "CalculateAdditionalHeight function is called once");
       
    mock.restore();
});
```

</details>
I added $.restore(); in the end of unit test and receive an error "$.restore is not a function". Do you know why?

**Comment by mroderick** [comment]
This usage question has already been posted to the mailing list. Please don't waste everyone's time by cross posting this everywhere.

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
