### ISSUE TITLE
Sandbox stubbing static function property throws error

### ISSUE THREAD

**Issue by raulmatei** [sinonjs/sinon#1445]
* Sinon version : 2.3.2
* Environment: Node
* Other libraries you are using: Mocha

**What did you expect to happen?**
Should be able to stub a function static property. It worked with v2.2.0

**What actually happens**
Throws an error:
`TypeError: Attempted to wrap object property content as function`

**How to reproduce**

```js
// code
const fn = () => false;

fn.content = {
  a: 'A',
  b: 'B',
};
```

```js
// test
before(() => {
  sandbox = sinon.sandbox.create();
  
  sandbox.stub(fn, 'content').value({
    a: '__A__',
    b: '__B__',
  });
});

after(() => {
  sandbox.restore();
});
```

**Comment by fatso83** [comment]
Seems like we have a regression. Could it be related to the new getter/setter stubbing functionality, @lucasfcosta?

**Comment by raulmatei** [comment]
It looks to me that this was introduced with this commit https://github.com/sinonjs/sinon/commit/278c2ce66cb88e81e3752c672ed630369f15fc34#diff-048fb1194de4b43f7f7e45758f900749R21, changing that check to:

```js
var isStubbingNonFuncProperty = (typeof object === "object" || typeof object === "function")
                                    && typeof property !== "undefined"
                                    && (typeof actualDescriptor === "undefined"
                                    || typeof actualDescriptor.value !== "function")
                                    && typeof descriptor === "undefined";
```

seems to make it work.

Thanks,
Raul

**Comment by lucasfcosta** [comment]
@fatso83, yup! Good catch @raulmatei.

I missed a check to see if the passed object itself was a function.

That should indeed solve the problem.

**Comment by raulmatei** [comment]
@lucasfcosta will come with a PR later this week. Hope it won't be to late for others.

Raul.

**Comment by lucasfcosta** [comment]
Hi folks. I can't close issues but I believe this one is done.
