### ISSUE TITLE
Deprecate spy.reset() in favor of the more explicit spy.resetHistory()

### ISSUE THREAD

**Issue by fearphage** [sinonjs/sinon#1446]
Spy currently has a `reset` method which functions as `resetHistory`. It would make the intention and functionality of the method more clear if it were named appropriately.

**Comment by fearphage** [comment]
The idea for this ticket started in #1424.

**Comment by GCHQDeveloper500** [comment]
Picked this one up as it was marked as "Help Wanted" - hope that's okay.

**Comment by mroderick** [comment]
This was done with #1630
