### ISSUE TITLE
Add a way to convert an existing spy to a stub

### ISSUE THREAD

**Issue by gajus** [sinonjs/sinon#1451]
I'd like spy everything by default and be able to convert a spy into a stub.

I cannot find a way in the documentation how to do it. I am assuming it is not possible with the current API.

If this is possible, how?

If not, it would be a "nice to have" feature.

**Comment by fatso83** [comment]
spy everything? not sure what that would mean. not everything can be spied upon (say `window`). please describe with pseudo code how this would look. my gut feeling says this is unfocused testing and unneedingly resource intensive.

**Comment by gajus** [comment]
Sorry, by "spy everything" I meant "spy everything thats playing an important role in the process" and selectively stub to test non-standard behaviour.

Anyway, I've ended _stubbing_ everything, e.g.

```js
beforeEach(() => {
  stub(createPayment, 'fromGlobalId')
    .callsFake((sguidPublicKey, namespace, name, value) => {
      return value;
    });

  stub(createPayment, 'getSeatIdsByReservationId')
    .returns([
      {
        id: 30
      }
    ]);

  stub(createPayment, 'getTicketIdsByReservationId')
    .returns([
      {
        id: 40
      }
    ]);

  stub(createPayment, 'getReservationFeeById')
    .returns({
      fee: 30,
      id: 50
    });

  stub(createPayment, 'selectSeatsForUpdate');
  stub(createPayment, 'authorizePayment');
  stub(createPayment, 'insertPaymentRecord');
  stub(createPayment, 'capturePayment');
  stub(createPayment, 'updatePaymentPaymentGatewayPaymentAuthorizationId');
  stub(createPayment, 'updateReservationPaymentId');
  stub(createPayment, 'updateSeatsStatus');
  stub(createPayment, 'updateReservationReferenceCode');
});

```

This allows me to create a simple test that asserts that all key methods have been invoked, e.g.

```js
test('creates payment', async (t) => {
  const parameters: any = {
    ...creteDefaultParameters()
  };

  const context: any = {
    ...createDefaultContext()
  };

  const payment = await createPayment(undefined, parameters, context);

  t.true(createPayment.getSeatIdsByReservationId.calledOnce, 'gets reservation seat IDs');
  t.true(createPayment.getTicketIdsByReservationId.calledOnce, 'gets reservation ticket IDs');
  t.true(createPayment.getReservationFeeById.calledOnce, 'gets reservation fee');
  t.true(createPayment.selectSeatsForUpdate.calledOnce, 'selects seats for update');
  t.true(createPayment.authorizePayment.calledOnce, 'authorizes a payment');
  t.true(createPayment.insertPaymentRecord.calledOnce, 'creates a record about the payment');

  // @todo makes booking
  t.true(createPayment.capturePayment.calledOnce, 'captures the payment');
  t.true(createPayment.updatePaymentPaymentGatewayPaymentAuthorizationId.calledOnce, 'updates payment with information about the payment gateway authorization ID');
  t.true(createPayment.updateReservationPaymentId.calledOnce, 'updates reservation with payment ID');
  t.true(createPayment.updateSeatsStatus.calledOnce, 'updates seats status');
  t.true(createPayment.updateReservationReferenceCode.calledOnce, 'updates reservation reference code');

  t.true(payment.id === 10, 'returns payment ID');
});

```

The other tests are then testing the implementation of the individual procedures.

**Comment by fatso83** [comment]
Stubbing every method on an object has been a standard feature since Sinon was created. [See the docs](http://sinonjs.org/releases/v2.3.2/stubs/#properties):

> `var stub = sinon.stub(obj);`
> 
> Stubs all the object’s methods.
> 
> Note that it’s usually better practice to stub individual methods, particularly on objects that you don’t understand or control all the methods for (e.g. library dependencies).
> 
> Stubbing individual methods tests intent more precisely and is less susceptible to unexpected behavior as the object’s code evolves.
