### ISSUE TITLE
Proposal: Expanding spies API functionality with callbacks

### ISSUE THREAD

**Issue by elad-nach** [sinonjs/sinon#1455]
Hi everyone,

A quick suggestion for a small feature that might be helpful (I will happily take the task upon myself).

Scenario:
At certain points when testing with Mocha, I would like to be able to spy on a real function (not a mock/stub) with the possibility of passing a callback to the spy when initialised (or Ideally - to emit events with an EventEmitter) , and that the callback/event will be called after the spy gets triggered. 

once the callback has been called, certain assertions could be made on the test level, before allowing the code to optionally continue executing or calling the done() callback (if the test should just be testing for the certain function spied upon to be called).

This allows a possibility to create interactive spies that can allow one to know not just **_if_** a spy was called but also **_when_** (immediately). 

This also saves on stubbing functions just in order to achieve the spy API functionality (when one creates a stub in order to mark the end of a certain function call sequence or in order to stop/block further code from executing, de-facto using it as a callback as in this case). Allowing callbacks over spies can in turn simplify testing and allow more granular sequence testing without the need to blank certain pieces of code just in order to .

More info and diagrams explaining the concept can be given upon request.

**Comment by mroderick** [comment]
> More info and diagrams explaining the concept can be given upon request.

If you could illustrate it with pseudo code, I think it would be easier to understand what you want to accomplish.

**Comment by elad-nach** [comment]
Assume the following:

```
Class A       Class B
+             +
|             |
+--->FuncA    +--->FuncC(spied)
|
+--->FuncB
```

FuncA calls FuncB which in turn calls FuncC.
Now, assuming that I want to know from within the test _**when**_ FuncC is called - there is not such possibility without stubbing it.

Assume that you would like to assert the state of an object which is passed to FuncC after the function runs but before the next function executes (as part of more complex, E2E tests - we're not talking about unit test scenarios here).

Another situation that I came across this kind of requirement is when building Socket.IO apps - when working with sockets the paradigm shifts - when you want to transmit messages blindly (datagram style) the socket does not behave as a classic API - it doesn't necessarily return a response/ack immediately, nevertheless you would like to assert that the message came through but when there's no ACK coming back through the socket client - there's no way for the test to know **_when_** to assert if the spy has been called - it would just hang. clearer?

**Comment by mroderick** [comment]
Thank you for elaborating ✌️ 

I think what you're proposing *is* possible to do by expanding `spy`.

So the usage would look something like this:

```javascript
describe('FuncA', function() {
    it('should pass some data to FuncC', function(done) {
        const classB = new ClassB();
        const classA = new ClassA(classB);

        sinon.spy(classB, 'FuncC', function() {
            assert(something);
            done();
        });

        // trigger the action that we want to test
        classA.FuncA();
    });
}};
```

However, I am not sure if it is a good practice to use in tests. If you don't care about the response that comes back from `FuncC`, then I'd advise that you just use a `stub`. That will reduce the side effects on systems from running your tests.

```javascript
describe('FuncA', function() {
    it('should pass some data to FuncC', function(done) {
        const classB = new ClassB();
        const classA = new ClassA(classB);

        sinon.stub(classB, 'FuncC').callsFake(function() {
            assert(something);
            done();
        });

        // trigger the action that we want to test
        classA.FuncA();
    });
}};
```

If you DO care about the response that comes back from `FuncC`, shouldn't that provide a mechanism to let you know when it's ready (i.e. a `Promise` or a callback)?

If you're doing end to end testing, shouldn't you be measuring at the other end? Can you somehow get a testing seam at the other end of the system and measure there?

I am not against expanding `spy`. I want to make sure that we are not duplicating solutions, that we then have to maintain for years to come.

**Comment by elad-nach** [comment]
Hi Morgan,

Thanks for replying. I know you're not against and I completely understand the discussion about the implementation - it is always a blessed one.

Indeed I agree that this might not always be a best practice and might allow 'shortcuts' when testing.

To shift the discussion back to what you wrote - the assumption about the response from FuncC works for a REST state of mind but not necessarily when testing on other frameworks and use cases (Electron? SocketIO? Not a classic API behaviour and not always a response schema for function return values is at hand, if necessary at all).

Also, as I mentioned before - stubbing in order to achieve signalling that a method was executed is also a doubted best practice since one starts to mess around with another layer of implementation that obscures the underlying code that was stubbed (what happens when the code that was obscured by the stub breaks? assuming not extra test coverage on that specific method).

Another possible use case of this would be to solve the long time problem of errors that [don't get raised by ExpressJS](https://github.com/expressjs/express/issues/2447) router when mocking time with sinon due to the [usage of setImmediate() inside the router](https://github.com/expressjs/express/blob/master/lib/router/index.js#L196) - you just simply can't know when to tell sinon to tick time because you don't know _**when**_ setImmediate was called thus cannot do an E2E test with mocked time. However if you could spy on setImmediate with a callback.... you could tick the mocked system timers. Mocking setImmediate would be something that I'm assuming most developer wouldn't put themselves through.
