### ISSUE TITLE
Possible to stub `this` reference? 

### ISSUE THREAD

**Issue by zellwk** [sinonjs/sinon#1463]
Is it possible to stub the entire object and change the reference of `this`? I want to test my endpoints with Mongoose and mongomem (an in-memory database). But because I'm creating different Mongoose instance per test, I need to change Mongoose models in my js files to an instance of Mongoose within each test. 

Here's what my test file looks like: 

```
import test from 'ava'
import mongoose from 'mongoose'
import request from 'supertest'
import { MongoDBServer } from 'mongomem'
import { createFixtures } from '../../fixtures/'
import app from '../../server'

const setupMongoose = async _ => {
  const db = new mongoose.Mongoose()
  db.Promise = global.Promise
  await db.connect(await MongoDBServer.getConnectionString())

  for (const name of mongoose.modelNames()) {
    db.model(name, mongoose.model(name).schema)
  }

  return db
}

test.before('start server', async t => await MongoDBServer.start())

test.beforeEach(async t => {
  const db = await setupMongoose()
  require('../../models/Course')
  require('../../models/User')
  const User = db.model('User')
  const Course = db.model('Course')
  await createFixtures(Course, User)

  t.context.db = db
})

test('Pass POST v1/users/testing', async t => {
 // This hangs.
  const res = await request(app)
    .post('/api/v1/users/testing')
    .send({
      email: 'testing@email.com'
    })
  t.is(res.status, 400)
})

test.after.always('cleanup', t => MongoDBServer.tearDown())
``` 

And here's what my endpoint looks like: 
```
exports.testing = async (req, res) => {
  const { email } = req.body
  const r = await User.findOne({email})
  res.json(r)
}
```

So the challenge now is to stub out `User` to be an `t.context.db.model('User')`. 

Is it possible? Or am I doing it wrong?

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), or on StackOverflow using the `sinon` label, so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
