### ISSUE TITLE
Stack size exceeded when using withArgs with complex objects

### ISSUE THREAD

**Issue by mpienkowski** [sinonjs/sinon#1470]
* Sinon version : 2.3.5
* Environment   : linux
* Other libraries you are using: karma + mocha + sinon + chai + phantomJS + node 6.6.0

**What did you expect to happen?**
Should return the value from a stub only if specific arguments are provided to stubbed method.

**What actually happens**
```
Maximum call stack size exceeded.
	toString@my.app.ts:22973:45
	deepEqual@node_modules/sinon/pkg/sinon.js:3057:49
	deepEqual$matcher@node_modules/sinon/pkg/sinon.js:3110:25
	deepEqual@node_modules/sinon/pkg/sinon.js:3083:45
	deepEqual$matcher@node_modules/sinon/pkg/sinon.js:3110:25
	deepEqual@node_modules/sinon/pkg/sinon.js:3083:45
(...)
```

**How to reproduce**
```
mockedService = {get: sinon.stub()};
mockedService.get
        .withArgs('/first_arg', new RequestOptions({some: 'options'}))
        .returns(Observable.of(someResponse));
```
If I take out `withArgs()` it works fine. The same if I replace `RequestOptions` object with something simpler (like `{a: 'b'}`). `RequestOptions` is https://angular.io/api/http/RequestOptions

**Comment by fatso83** [comment]
Could you create a working example that we can download and run on our own computers? A simple gist or something? When the amount of work involved in reproducing this become too great, stuff like this never gets touched, so a quick repro with minimal code is preferable.
