### ISSUE TITLE
stub#firstCall seems broken on sinon v2.3.6

### ISSUE THREAD

**Issue by HugoMuller** [sinonjs/sinon#1476]
Hello,

First of all, thanks for the work done :)

Today, one of our unit tests has failed after the update of sinon. (v2.3.5 -> v2.3.6)
We think the latest release introduced a regression.

* Sinon version : 2.3.6
* Environment   : Debian Jessie, Node v6.11.0

**What did you expect to happen?**
I expect both stub.getCall(0) and stub.firstCall to return the same thing, even with a stub created with withArgs.

**What actually happens**
When I create a stub responding to particular arguments with stub.withArgs, this stub can't be inspected with firstCall.
stub.getCall(0) works fine but stub.firstCall returns null. In the previous release (v2.3.5), calling stub.getCall(0) and getting stub.firstCall produced the same result. 
The same issue can be observed with secondCall and thirdCall as well.

**How to reproduce**
```javascript
const sinon = require('sinon');
const stub = sinon.stub();

stub.withArgs('broken').returns(42);
stub('broken');

stub.withArgs('broken').callCount; // 1
stub.withArgs('broken').calledOnce; // true
stub.withArgs('broken').returnValues[0]; // 42
stub.withArgs('broken').getCall(0) // the first call
stub.withArgs('broken').firstCall; // null
```

**Comment by mroderick** [comment]
Thank you for the easy to follow regression report!

With a slightly modified version of your test (below) and `git bisect`, I've been able to find the first failing commit: https://github.com/sinonjs/sinon/commit/0e77b31bdc7381ead058bc6dc4c7657f0f1be08c

```javascript
// test/issues/issue-1476-test.js
"use strict";

var assert = require("referee").assert;
var refute = require("referee").refute;
var sinon = require("../../lib/sinon");

describe.only("Issue #1476 - withArgs.firstCall, when stub has been called", function () {
    it("must not be null", function () {
        var stub = sinon.stub();

        stub.withArgs("broken").returns(42);
        stub("broken");

        refute.equals(stub.withArgs("broken").firstCall, null);
    });
});
```

I have yet to determine why it is failing

**Comment by fatso83** [comment]
@HugoMuller, could you check if the issue above is fixed by checking out #1478?

**Comment by HugoMuller** [comment]
Hello,

sorry for the delay :(
I run my test with your patch and it seems to work perfectly now.
Thank you

**Comment by mroderick** [comment]
This has been published as `v2.3.7`, thank you all!

**Comment by jvanoostveen** [comment]
Hmm it seems with this patch (in 2.3.7) withArgs().lastCall is broken.
`TypeError: Cannot read property 'lastCall' of undefined`

**Comment by HugoMuller** [comment]
Hello @jvanoostveen. 
Can you explain a little bit? What are the steps to reproduce this? 
withArgs() always returns a fake (stub or spy), or eventually throws an error when called after onCall().
