### ISSUE TITLE
Spy.calledWithMatch fails when calling with function parameter.

### ISSUE THREAD

**Issue by haydenmcp** [sinonjs/sinon#1482]
* Sinon version : 1.17.1
* Environment  :
    - OS: Ubuntu 16.04 LTS
    - Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
    - Polymer-included sinon library.

* Other libraries you are using:

This is my bower.json along with the contents of my bower_components dir.

```json
{
  "name": "lazy-imports-handler-behavior",
  "description": "Handler behavior for lazy imports",
  "main": "lazy-imports-handler-behavior.html",
  "dependencies": {
    "polymer": "Polymer/polymer#^1.9 || ^2.0",
    "paper-button": "PolymerElements/paper-button#^2.0.0",
    "lazy-imports": "Polymer/lazy-imports#^2.0.0"
  },
  "devDependencies": {
    "paper-button": "PolymerElements/paper-button",
    "lazy-imports": "Polymer/lazy-imports",
    "iron-component-page": "PolymerElements/iron-component-page#^1.0 || ^2.0",
    "iron-demo-helpers": "PolymerElements/iron-demo-helpers#^1.0 || ^2.0",
    "web-component-tester": "Polymer/web-component-tester#^6.0.0",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0"
  },
  "variants": {
    "1.x": {
      "dependencies": {
        "polymer": "Polymer/polymer#^1.9.0",
        "lazy-imports": "Polymer/lazy-imports#^2.0.0"
      },
      "devDependencies": {
        "iron-component-page": "PolymerElements/iron-component-page#^1.0.0",
        "iron-demo-helpers": "PolymerElements/iron-demo-helpers#^1.0.0",
        "webcomponentsjs": "webcomponents/webcomponentsjs#^0.7.0"
      },
      "resolutions": {
        "webcomponentsjs": "^0.7.0"
      }
    }
  },
  "resolutions": {
    "webcomponentsjs": "^1.0.0"
  }
}
```

**What did you expect to happen?**
I expected the calledWithMatch function to return true.

**What actually happens & How to reproduce**

I was writing a unit test for polymer to verify that an event was correctly attached. All variables have been declared as needed. The concept follows:

```js
beforeEach( (done) => {
              // Force attachment event
              parent.removeChild(element);
              addEventListenerSpy = sinon.spy(element, 'addEventListener');
              parent.appendChild(element);
              flush(done);
});

it('should add import-lazy-group event listener to parent node', () => {
              expect(addEventListenerSpy)
                  .calledWithMatch('event-name', element._importLazyGroup, true);
});
```

While debugging through the code in chrome dev tools I located the following cause in calledWithMatch within sinon.js:

```js
calledWithMatch: function calledWithMatch() {
                var l = arguments.length;
                if (l > this.args.length) {
                    return false;
                }
                for (var i = 0; i < l; i += 1) {
                    var actual = this.args[i];
                    var expectation = arguments[i];
                    if (!sinon.match || **!sinon.match(expectation).test(actual))** {
                        return false;
                    }
                }
                return true;
},
```

It appears that the expectation and actual values match. However, the function used to test actual against expectation constructed by sinon.match provides the actual function as input into the expectation. For example, see the following pseudo-code.

```js
expectation = function(event) {
    // do something with event
}

actual = expectation
```

Sinon is current testing equivalence by running expectation(actual) to determine if the two are identical. Thank you for all of the awesome work you guys are doing and I hope this helps make sinon better. :-)

**Comment by fatso83** [comment]
Thank you for your bug report. Unfortunately I am not convinced this is an issue with sinon. I might be misreading the issue, but it seems as if you have an issue with the `calledWithMatch`, which is  part of your assertion library and/or extensions guessing sinon-chai?). Then that bug belongs there.

If this is a bug within Sinon, please reopen this issue with a reproducible code snippet that uses sinon's API's directly. Or of course if I totally misread the issue. It happens :-)

**Comment by fatso83** [comment]
Just realized you did specify the code was in Sinon ... Goes to show.

**Comment by mroderick** [comment]
I edited the OPs description to improve readability:

* removed instructions from the template
* added fenced code blocks to allow GFM syntax highlighting

**Comment by haydenmcp** [comment]
Hahaha, it happens @fatso83 . :-)
