### ISSUE TITLE
Unexpected behavior of stub.withArgs.

### ISSUE THREAD

**Issue by reklatsmasters** [sinonjs/sinon#1483]
* Sinon version : 2.3.6

**What did you expect to happen?**
`stub().withArgs()` should have strict arguments check.

**What actually happens**
`stub.withArgs` ignores part of the arguments in stub function.

**How to reproduce**
```js
const sinon = require('sinon')
const cb = sinon.stub()

// define behavior
cb.withArgs(42).returns(1)  // define cb(42)
cb.throws('cb')   // throws with any other cases

console.log(cb(42))  // works, ok
console.log(cb(42, 43))  // should throws, but works <<<
console.log(cb(43))  // throws, ok
```

**Comment by elad-nach** [comment]
why should it throw? it is legal to overload more parameters than in the function signature in javascript (due to the presence of the `arguments` keyword):
```js
$ node
> let f = (args)=>{return args;}
undefined
> f(1)
1
> f(1,1)
1
> f(1,'abcd')
1
```

cheers

**Comment by fatso83** [comment]
This is as intended. We allow partial matching. If you need an exact match I would create a custom matcher (see bottom of the [matcher docs](http://sinonjs.org/releases/v2.4.1/matchers/)).

If your custom matcher is nice and useful you can patch the project and supply us with a pull request :-) The same goes for the docs,btw, in case you feel they could be improved!
