### ISSUE TITLE
Documentation: useFakeTimers options

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#1485]
> the documentation for useFakeTimers says that you can list functions to fake but doesn't explain what that would mean if you do vs don't

Improvements should be made to https://github.com/sinonjs/sinon/blob/master/docs/release-source/release/fake-timers.md, and all the versions for 2.x.

**Comment by elad-nach** [comment]
@mroderick I can take this up. I'd also want to hook up the useFakeTimers implementation to the `shouldAdvanceTime` feature I submitted in lolex. I could take of the docs in the process.

**Comment by mroderick** [comment]
That would be lovely, thanks 🙏
