### ISSUE TITLE
Request for Upgrading documentation

### ISSUE THREAD

**Issue by jasonkarns** [sinonjs/sinon#1493]
Feature request: Changelog to document back-compat breaking changes. Presently the changelog makes no mention of breaking changes distinct from features or bug fixes. Ideally, there would be some sort of documentation in the 2.0 release for what's necessary to upgrade from 1.x line. I can't seem to find one in the repo or site. Short of an upgrading doc, I would expect breaking changes to be highlighted or called out in the release notes for each release and/or in the changelog. Neither appears to be true. This makes upgrading a large test suite rather painful (especially when considering the number of plugins involved like sinon-chai, sinon-as-promised, etc).

**Comment by mroderick** [comment]
In the documentation site there is a [migration guide to cover the upgrade from v1.17.x to 2.x](http://sinonjs.org/releases/v2.3.8/migrating-to-2.0/).

Hopefully this covers everything you need to upgrade Sinon in your project.

If you encounter things that the migration guide doesn't cover, then we would appreciate feedback in the GitHub issues or even better as pull requests.

**Comment by jasonkarns** [comment]
Thank you! Exactly what I was looking for. Frustrating that I couldn't find
it, though, in the Changelog, Releases on Github or main site. :/

**Comment by fatso83** [comment]
That is a good point, @jasonkarns! We could  certainly update the release docs with a pointer to the guide.
