### ISSUE TITLE
Skip rewrapping instead of exception

### ISSUE THREAD

**Issue by henit** [sinonjs/sinon#1505]
Example: 

    it('is test 1', () => {
        sinon.stub(Some, 'method');
        // testCode
        Some.method.restore();
    });

    it('is test 2', () => {
        sinon.stub(Some, 'method');
        // testCode
        Some.method.restore();
    });

If I skip the restore line, I get `TypeError: Attempted to wrap method which is already wrapped`. Just a suggestion.. Could these errors be skipped, just ignoring if the function is already stubbed, maybe just run reset so it is clean and ready for new tests.. If that where the case, I could skip the restore lines in all tests similar to the ones above.

**Comment by fatso83** [comment]
If you need auto-cleanup, there are several alternatives:
1. Use a `afterEach()` (guessing Mocha or Jasmine as the framework) to clean up after each of your stubs. Just reuse a variable, like `mySpy`, and do `mySpy.restore && mySpy.restore()` in the cleanup.
2. Use [sandboxes](http://sinonjs.org/releases/v2.4.1/sandbox/) to do auto-cleanup
3. Use [sinon-test](https://github.com/sinonjs/sinon-test) to wrap your functions _(my favorite)_
