### ISSUE TITLE
Property stubbing on process.env in Sinon 3

### ISSUE THREAD

**Issue by Siilwyn** [sinonjs/sinon#1513]
Regarding the discussion in [this issue for Sinon 2](https://github.com/sinonjs/sinon/issues/188#issuecomment-278656209) I found the documentation to be lacking on migrating from this:
```js
const sandbox = sinon.sandbox.create();

sandbox.stub(process, 'env', {SOME_KEY: 'some value'});

sandbox.restore();
```

However after some troubleshooting this seems to work for Sinon 3:

```js
const sandbox = sinon.sandbox.create();

sandbox.stub(process, 'env').value({'SOME': 'value'});

sandbox.restore();
```

Just wanted to leave this information for anybody having the same problem since the original thread is locked.

**Comment by fatso83** [comment]
@Siilweyn, if you think this is a shortcoming that should be addressed, feel free to push a small correction to the docs!

**Comment by lkashef** [comment]
This also works `sinon.stub(process.env, 'NODE_ENV').value('FAKE_ENV');`

**Comment by fatso83** [comment]
@lkashef The latter is probably the better/safer approach, as you are not overwriting all existing values in the `env` field.

**Comment by lkashef** [comment]
@fatso83 I am not sure which approach you are referring to.

**Comment by fatso83** [comment]
@lkashef Updated wording. Sorry for being unclear.

**Comment by lkashef** [comment]
No worries @fatso83, thanks for the confirmation.

**Comment by frosas** [comment]
I like the approach described by @lkashef but note it won't work for environment variables that are not previously set (`TypeError: Cannot stub non-existent own property MY_VAR`).

**Comment by sempasha** [comment]
What I need is
```js
const env = propess.env;
sinon.stub(propess.env, 'KEY').value('VALUE');
expect(env.KEY).toEqual('VALUE');
```
But it does not work, because it is unable to stub non-existing object property.

Suggested solution is
```js
const env = propess.env;
sinon.stub(propess, 'env').value({ ...propess.env, KEY: 'VALUE' });
expect(env.KEY).toEqual('VALUE');
```
But it is not applicable, because stub won't affect any property of `const env`;
