### ISSUE TITLE
.throws() in conjuction with .onFirstCall() doesn't work

### ISSUE THREAD

**Issue by RiddleMan** [sinonjs/sinon#1526]
Hi,

After upgrade to Sinon 3.2.0, I've spotted that some of my tests are failing.
As a result of a quick investigation, I've found that .throws() is not throwing when it's used together with .onFirstCall(), onCall() etc.

I've checked this issue for .withArgs() and it seems to work correctly.

* Sinon version : 3.2.0
* Environment   : nodejs
* Example URL   :
* Other libraries you are using:

**What did you expect to happen?**
It should throw an Error only on the first call or no of the call specified in the .onCall() method.
**What actually happens**
It doesn't throw any error.
**How to reproduce**

```javascript

  const stub = sinon.stub();
  stub
    .onFirstCall()
    .throws();

  try {
    stub();
    console.log('WRONG');
  } catch(e) {
    console.log('OK');
  }
```

**Comment by fatso83** [comment]
Not reproducible.

```
npm install sinon@3.2.0
foo@1.0.0 /tmp/foo
└─┬ sinon@3.2.0 
  ├── diff@3.3.0 
  ├── formatio@1.2.0 
  ├── lolex@2.1.2 
  ├── native-promise-only@0.8.1 
  ├─┬ nise@1.0.1 
  │ ├── just-extend@1.1.22 
  │ └── lolex@1.6.0 
  ├── path-to-regexp@1.7.0 
  ├── samsam@1.2.1 
  ├── text-encoding@0.6.4 
  └── type-detect@4.0.3 

npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

developer at developer-XPS-13-9360 in /tmp/foo 
$ node test.js
OK
```

test.js
```
var sinon = require('sinon')
const stub = sinon.stub();

stub.onFirstCall()
    .throws();

try {
    stub();
    throw "wrong"
} catch(e) {
    console.log('OK');
}
```

**Comment by RiddleMan** [comment]
I've made the same environment like yours, and I'm still getting the same problem.
If it will help I'm running on OS X, Node 8.3.0.

I'm also able to reproduce that inside of the browser (Chrome)
Here's the link to JSBin which causes that problem.

http://jsbin.com/vihebikone/edit?js,console

**Comment by fatso83** [comment]
I'm an idiot (examine my test above). Reopening.

**Comment by RiddleMan** [comment]
Yeah! It makes sense ;) But at the first look I didn't spot anything wrong 😁

**Comment by fatso83** [comment]
Created a [test case suitable for `git bisect`](https://github.com/fatso83/git-bisect-scripts/blob/master/sinon-1526.sh) and found the offending commit in #1511:
```
git bisect bad master                                                                                                                                                                                
git bisect good v2.0.0                                                                                                                                                                               
git bisect run ../git-bisect-scripts/sinon-1526.sh                                                                                                                                                   
# ... lots of output                                                                                                                                                                                               
ec74e944173e53fd71afa19e073f1262448534b9 is the first bad commit    
```
