### ISSUE TITLE
sinon.createFakeServer() throws `TypeError: server.configure is not a function`

### ISSUE THREAD

**Issue by EyalAr** [sinonjs/sinon#1531]
Sinon version: 3.2.0
Node version: 8.2.0

**To reproduce:**
```js
require("sinon").createFakeServer();
```

**Expected:**  
Fake server is created successfully.

**Actual:**
Error thrown `TypeError: server.configure is not a function`

**Analysis:**
When the function `createFakeServer` is [defined](https://github.com/sinonjs/sinon/blob/1b81ec67c30046f5117c9299faa24a66035d7fd5/lib/sinon.js#L32), the context of `nise.fakeServer` is not perserved.  
Instead, the context becomes the `sinon` object, which, as the error says, does not have a `configure` function.

**Suggested fix:**
`exports.createFakeServer = nise.fakeServer.create.bind(nise.fakeServer);`

**Temporary solution:**
Use `sinon.fakeServer.create()` instead.

**Comment by fatso83** [comment]
Good issue - thank you. 

P.S. fakeServer/nise is only meant to be used in a browser environment with a DOM, not node, but you might be doing something else

**Comment by fatso83** [comment]
The quickest way of seeing this is resolved is cloning the project and testing your intended fix. Mind trying it out and supplying us with a PR?

**Comment by EyalAr** [comment]
Will do, I'll work on a PR.
Thanks for the quick response!

**Comment by danifornells** [comment]
Sinon version: 3.2.1
Node version: 6.11.3

Similar error appeared on my CI tools, and seems to be related with the change recently made:

`not ok 25 PhantomJS 1.9 - Global error: TypeError: 'undefined' is not a function (evaluating 'nise.fakeServer.create.bind(nise.fakeServer)') at http://localhost:7357/node_modules/sinon/pkg/sinon.js, line 33`

**Comment by fatso83** [comment]
@danifornells Check [your other moving bits](https://github.com/ariya/phantomjs/issues/10522).
