### ISSUE TITLE
Assert lacks `calledWithNew`

### ISSUE THREAD

**Issue by tsclaus** [sinonjs/sinon#1535]
* Sinon version : 2.3.8 but newest documentation still lacks it
* Environment   : N/A
* Example URL   : N/A
* Other libraries you are using: N/A

For the most part, the Assert methods mirror the Spy methods. However, Spy supports `calledWithNew` while Assert does not. Not a huge inconvenience but it forces test files to use something besides the assert pattern. `assert.calledWithNew(spy)` makes the most sense for how it would be implemented.

**Comment by fatso83** [comment]
Thanks for the bug report. Would you mind having a go at implementing it? I think that would be the quickest win, if you want to have it within a reasonable timeframe.

**Comment by mroderick** [comment]
A pull request for this would be very welcome.

To update the documentation, you should add to the files in `docs/release-source`, which are the ones that will be used when we cut the new release.

**Comment by rgroothuijsen** [comment]
Just tested this with the latest version, and assert.calledWithNew appears to work as expected. Documentation still needs to be fixed, though.

**Comment by mroderick** [comment]
Fixed by #1544
