### ISSUE TITLE
Mock HTTP fetch in sinon

### ISSUE THREAD

**Issue by maryam-saeidi** [sinonjs/sinon#1546]
I am trying to mock HTTP fetch in jsfiddle. I am not sure what I do wrong that makes the result not to be equal to the mock one.

* Sinon version : 3.2.1
* Environment   : chrome (Version 62.0.3198.0 (Official Build) dev (64-bit))
* Example URL   :  http://jsfiddle.net/maryam_saeidi/yredb06m/7/
* Other libraries you are using:
polyfill.js
mocha.js
chai.js
mocha.css

**What did you expect to happen?**
I want to mock the HTTP fetch function.

**What actually happens**
It seems it doesn't mock the fetch function.

**How to reproduce**
Here is my sample code: (You can see the logs in the browser console.)
http://jsfiddle.net/maryam_saeidi/yredb06m/7/

**Comment by fatso83** [comment]
Fetch is a different API from XHR. The underlying library of the XHR stubbing, [nise](https://github.com/sinonjs/nise), only support XHR (and so does Sinon). You can check out sinonjs/nise#7 for some tips on how to accomplish this.
