### ISSUE TITLE
withArgs does not work properly with sinon.mock

### ISSUE THREAD

**Issue by byohay** [sinonjs/sinon#1547]
* Sinon version : 3.2.1
* Environment: OSX, Node 7 
* Other libraries you are using: Mocha, mjackson/expect

**What did you expect to happen?**
When I create a mock on a class and try to control the behavior of one of its functions using `withArgs`, an exception is thrown. Happens only when using multiple calls of `withArgs`.

**What actually happens**

**How to reproduce**
<details>
    <summary>Reproducible example</summary>

Assume I declared a class `C`:
```js
      class C {
        static foo(arg1, arg2) {return 'foo';}
      }
```
I try to control the behavior of `foo` using a mock on `C`:
```js
      it('test withArgs mock', () => {
        let CMock = sinon.mock(C);
        let fooStub = CMock.expects('foo');

        fooStub.withArgs('a', 'b').returns(1);
        fooStub.withArgs('c', 'd').returns(2);

        expect(fooStub('a', 'b')).toEqual(1);
        expect(fooStub('c', 'd')).toEqual(2);

        CMock.restore();
      });
```
Which throws the following exception:
> ExpectationError: foo received wrong arguments ["a", "b"], expected ["c", "d"]
    at Object.fail (node_modules/sinon/lib/sinon/mock-expectation.js:281:25)
    at Function.<anonymous> (node_modules/sinon/lib/sinon/mock-expectation.js:182:33)
    at Array.forEach (native)
    at Function.verifyCallAllowed (node_modules/sinon/lib/sinon/mock-expectation.js:175:27)
    at Function.invoke (node_modules/sinon/lib/sinon/mock-expectation.js:78:14)
    at proxy (node_modules/sinon/lib/sinon/spy.js:89:22)

While this code works:
```js
      it('test withArgs stub', () => {
        let fooStub = sinon.stub(C, 'foo');

        fooStub.withArgs('a', 'b').returns(1);
        fooStub.withArgs('c', 'd').returns(2);

        expect(fooStub('a', 'b')).toEqual(1);
        expect(fooStub('c', 'd')).toEqual(2);

        fooStub.restore();
      });
```
</details>

It is worth mentioning that the following scenarios work as expected:
```js
      it('test one withArgs mock', () => {
        let CMock = sinon.mock(C);
        let fooStub = CMock.expects('foo');

        fooStub.withArgs('a', 'b').returns(1);

        expect(fooStub('a', 'b')).toEqual(1); // ok

        CMock.restore();
      });
```
```js
      it('test one withArgs mock', () => {
        let CMock = sinon.mock(C);
        let fooStub = CMock.expects('foo');

        fooStub.withArgs('a', 'b').returns(1);

        expect(fooStub('c', 'd')).toEqual(1); // error: foo received wrong arguments ["c", "d"], expected ["a", "b"]

        CMock.restore();
      });
```

Meaning, the problem occurs only when using `withArgs` multiple times.
It might be related to #1381, but as you can see in the example, the solution suggested there does not work.

**Comment by fatso83** [comment]
Thanks for a *examplary* issue report. I don't use the mocks functionality, as it makes my brain hurt, so someone else will need to have a look at this, but your examples should make that a lot easier.

Feel free to have a look at the code yourself - often the quickest way of getting this fixed :-)

**Comment by byohay** [comment]
I got a look at the code.
First of all, this test works today:
```js
class C {
  static foo(arg1, arg2) {return 'foo';}
}

it('test withArgs mock', () => {
  let CMock = sinon.mock(C);

  CMock.expects('foo').withArgs('a', 'b').returns(1);
  CMock.expects('foo').withArgs('c', 'd').returns(2);

  expect(C.foo('a', 'b')).toEqual(1);
  expect(C.foo('c', 'd')).toEqual(2);

  CMock.restore();
});
```

There are two reasons why this works and the test in the original issue doesn't:
- I create two `expects`.
- I call the static method instead of the one returned by `expects`.

Meaning, this doesn't work either:

```js
it('test withArgs mock', () => {
  let CMock = sinon.mock(C);

  CMock.expects('foo').withArgs('a', 'b').returns(1);
  let fooStub = CMock.expects('foo').withArgs('c', 'd').returns(2);

  expect(fooStub('a', 'b')).toEqual(1); // Error: foo received wrong arguments ["a", "b"], expected ["c", "d"]
  expect(fooStub('c', 'd')).toEqual(2);

  CMock.restore();
});
```

Every time `expects` is called, the following happens:

- A new expectation (stub with `minCalls/maxCalls`) is created, only that it is a "scoped stub", it doesn't have connection to other `expects`. It is the object returned from `expects`.
- It is added to the list of expectations.

Which results in different behaviors for these scenarios:

- If you call the method returned by `expects`, it will be limited only to that `expects`.
- If you call the method and not the stub, it will search over all the `expects` and find one that fits. If there is more than one, it will call the first.

Is this the correct behavior? It seems to me more intuitive that once someone calls `expects` on a method, it will behave exactly like a `stub` (with the additional `minCalls/maxCalls`). This will result in:

- You will not be able to call `expects` more than once on the same method. 
- More code can be shared between `stub` and `mock-expectation`.
- The behavior of the scenarios above will be the same.

Now, what would happen to the `minCalls/maxCalls`? 

Since there is only one `expectation` now, I propose three alternative ways to do call count verification with mocks:

```js
  let fooStub = CMock.expects('foo').withArgs('a', 'b').returns(1).twice();
  fooStub.withArgs('c', 'd').returns(2).once(); // Does not affect the previous expectation.
```
```js
  let fooStub = CMock.expects('foo').withArgs('a', 'b').returns(1).twice();
  fooStub.withArgs('c', 'd').returns(2).once(); // Does not affect the previous expectation.
```

**Comment by byohay** [comment]
I got a look at the code.
First of all, this test works:
```js
class C {
  static foo(arg1, arg2) {return 'foo';}
}

it('test withArgs mock', () => {
  let CMock = sinon.mock(C);

  CMock.expects('foo').withArgs('a', 'b').returns(1);
  CMock.expects('foo').withArgs('c', 'd').returns(2);

  expect(C.foo('a', 'b')).toEqual(1);
  expect(C.foo('c', 'd')).toEqual(2);

  CMock.restore();
});
```

There are two reasons why this works and the test in the original issue doesn't:
- I create two `expects`.
- I call the static method instead of the one returned by `expects`.

Meaning, this doesn't work either:

```js
it('test withArgs mock', () => {
  let CMock = sinon.mock(C);

  CMock.expects('foo').withArgs('a', 'b').returns(1);
  let fooStub = CMock.expects('foo').withArgs('c', 'd').returns(2);

  expect(fooStub('a', 'b')).toEqual(1); // Error: foo received wrong arguments ["a", "b"], expected ["c", "d"]
  expect(fooStub('c', 'd')).toEqual(2);

  CMock.restore();
});
```

Every time `expects` is called, the following happens:

- A new expectation (stub with `minCalls/maxCalls`) is created, only that it is a "scoped stub", it doesn't have connection to other `expects`. It is the object returned from `expects`.
- It is added to the list of expectations.

Which results in different behaviors for these scenarios:

- If you call the method returned by `expects`, it will be limited only to that `expects`.
- If you call the method directly and not the stub, it will search over all the `expects` and find one that fits. If there is more than one, it will call the first.

Is this the correct behavior? It seems to me more intuitive that once someone calls `expects` on a method, it will behave exactly like a `stub` (with the additional `minCalls/maxCalls`). This will result in:

- More code can be shared between `stub` and `mock-expectation`.
- The behavior of the scenarios above will be the same.

**Now, what would happen to `minCalls/maxCalls`?**

Since there is only one `expectation` now, I propose three alternative ways to do call count verification with mocks:

- Allow to concat `once()`, `twice()` etc.
```js
  let fooStub = CMock.expects('foo').withArgs('a', 'b').returns(1).twice();
  fooStub.withArgs('c', 'd').returns(2).once(); // Does not affect the previous expectation.
```
Might be a bit confusing though.

- Don't allow to concat `once()`, `twice()` etc.
```js
  CMock.expects('foo').withArgs('a', 'b').returns(1).twice(); // `twice()` returns `null`, so that one has to call `expects()` again to set expectations for other arguments. 
  CMock.expects('foo').withArgs('c', 'd').returns(2).once();
```
More clear, but you cannot stub `foo` more than once so we will need a way to bypass that. Also, this is still possible: 
```js
  CMock.expects('foo').withArgs('a', 'b').returns(1).withArgs('c', 'd').returns(2).twice(); // I guess that this should only affect the last `withArgs`?
```

- Use Spy API which remembers the number of calls.
