### ISSUE TITLE
Mock/Stub a function (a npm module) with callback using Sinon

### ISSUE THREAD

**Issue by prashathsenthil** [sinonjs/sinon#1548]
I'm using json2csv npm module to convert the json response to csv format, the code looks like below..

`json2csv({ data: data, fields: ['id', 'firstName', 'lastName'] }, function (err, csv) {`
         ` if (err) {`
            `// Reject the promise with error - reject(err);`
          `} else {`
             `// Resolve the promise with csv data - resolve(csv);`
         `}`
        `});`

How to stub the above function using sinon so i can write unit tests for success and error scenarios. My unit testing stack is Jasmine and Istanbul.

I wasn't able to use sinon.stub or sinon.mock since they expect (object, "method") but in this case json2csv is a function.

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
