### ISSUE TITLE
Add sinon.restore(obj) to restore all stubbed methods on the object

### ISSUE THREAD

**Issue by tsclaus** [sinonjs/sinon#1553]
Without using sandboxes, there is no quick reversal to `sinon.stub(obj)`. `sinon.restore(obj)` and/or `sinon.stub.restore(obj)` could be added to serve as the inverse to `sinon.stub(obj)`. With the `walk` utility function, this should be pretty easy; with approval, I can add the feature.

An example of its usefulness (using Karma):

```
const sinon = require('sinon');

const testedLibrary = require('testedLibrary'),
      dependency    = require('dependency');

describe('testedLibrary', function() {
  beforeEach(function() {
    sinon.stub(dependency);
  });

  it('should test something', function() {
    // changing dependency.method behavior here automatically changes it in `testedLibrary.js` as well
    // since the same object is used in both files
  });

  afterEach(function() {
    // without this you either have to clear the cache or iterate over dependency yourself
    sinon.restore(dependency);
  });
});
```

**Comment by tsclaus** [comment]
Apologies, I missed this is in `util.js` as it's own function. This issue should definitely be closed.

**Comment by fatso83** [comment]
@tsclaus We always appreciate [contributions to the docs](https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md) :-)
