### ISSUE TITLE
Issue when spying on function that is not a member of global object

### ISSUE THREAD

**Issue by maxDrach** [sinonjs/sinon#1554]
Hi guys! I'm happy user of your library but I faced a problem in ES6 when I tried to test  function that is not a member of the global object (dummy2 - member of see-price-in-cart module) was invoked by another function (dummy1- member of see-price-in-cart module). This is not a case if we try a function that is a member of the global object - console.log() (console - global object). Please provide some solution for me. Here is a screenshot

![sinon](https://user-images.githubusercontent.com/11978118/30226616-46b3717a-949c-11e7-9797-9ab2ec312cab.PNG)

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions. Posting it on [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tagging it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon) is another good option.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
