### ISSUE TITLE
spy.getCall(n).args[n] returns the result of the arg, not what was passed in

### ISSUE THREAD

**Issue by TheHerm** [sinonjs/sinon#1555]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : Sinon v 3.2.1
* Environment   : node 6.11.2
* Example URL   : https://repl.it/Kvkb/1
* Other libraries you are using: AVA, lodash

**What did you expect to happen?**
I expect the sinon spy to return a snapshot of what was passed into it, not the actual reference

**What actually happens**
The sinon spy is returning a reference to the object that was passed into the 1st argument of the spied on function instead of a copy/snapshot and therefore the object has changed since it was passed into the spied on function.

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar

```javascript
test('passes the correct parameter into arg[0] of spy', t => {
  console.log('log num 2', spy.getCall(0).args[0]);
  console.log('log num 3', testOptions);
  t.deepEqual(spy.getCall(0).args[0], testOptions);
});

mergeDefaults = function (testOptions) {
    console.log('log num 1', testOptions);
    return _.defaultsDeep(testOptions, defaultOptions);
}

let returnedVal = mergeDefaults(_.cloneDeep(testOptions));
// I sent in a deep clone to the function to try to ensure that the original object was not modified
// before I was able to test it.
```
Here is the logs as output into the terminal
<details>
log num 1 --> { testKey: 'testValue',
  debug: true,
  fallbackLng: 'testFallbackLang' 
}

log num 2 --> { testKey: 'testValue',
  debug: true,
  fallbackLng: 'testFallbackLang',
  detection:
   { order: [ 'localStorage', 'navigator' ],
     lookupLocalStorage: 'overrideLanguage' },
  ns: [ 'common' ],
  defaultNS: 'common',
  interpolation: { escapeValue: false }
}

log num 3 --> { testKey: 'testValue',
  debug: true,
   fallbackLng: 'testFallbackLang' 
}
</details>

**Comment by fatso83** [comment]
Thanks for the issue report. The spy creation is not part of the code sample, hence this is not a reproducible test case we can run directly to ensure it has been fixed in a later release. Please make it runnable.

**Comment by mroderick** [comment]
> I expect the sinon spy to return a snapshot of what was passed into it, not the actual reference

I believe this expectation is the same that gave us these issues:

* #571 
* #583
* #665

Do you agree? Would you like to contribute to finishing the proposal in #665 and maybe even create a PR for it?

**Comment by TheHerm** [comment]
yes, #665 is basically what I was getting at.  I will close this issue in favor of 665 because it is a more fleshed out conversation covering the exact issue I was having
