### ISSUE TITLE
Uglify-js and js-yaml vulnerability 

### ISSUE THREAD

**Issue by facucompe** [sinonjs/sinon#1567]
![image](https://user-images.githubusercontent.com/12786130/30663067-c95e039c-9e1f-11e7-8b9e-2c287f97e4a5.png)

uglify-js and js-yaml are not updated

![image](https://user-images.githubusercontent.com/12786130/30663118-02b0efe2-9e20-11e7-8894-bcbadbdf23f6.png)

**Comment by mroderick** [comment]
Two screenshots have got to be the sparsest issue I've seen in awhile.

The `build` dependency was removed in #1564, two days ago.

I don't consider the other issue to be any kind of significant threat to Sinon.JS or it's users. If you do, then please submit a pull request and follow the guidelines.
