### ISSUE TITLE
Dependency Build Still exists.

### ISSUE THREAD

**Issue by frank-dspeed** [sinonjs/sinon#1571]
Please Review
```
─┬ sinon@3.3.0
  └─┬ build@0.1.4
    └── wrench@1.3.9
```

**Comment by mroderick** [comment]
@frank-dspeed there is no trace of the `build` dependency in current `master` (38376358c9f868c861c627294babfad100c6105c)

```text
rm -rf node_modules
npm install
npm ls build
sinon@3.3.0 /Users/morgan/code/sinonjs/sinon
└── (empty)
```

**Comment by frank-dspeed** [comment]
@mroderick but its there on travis for current 3.3.0 npm version of sinon so this is not fixed.

**Comment by mroderick** [comment]
> @mroderick but its there on travis for current 3.3.0 npm version of sinon so this is not fixed.

We are about to publish a new version, that will include the fix. Please be patient
