### ISSUE TITLE
Bad check for canColor in color.js

### ISSUE THREAD

**Issue by jgarver** [sinonjs/sinon#1574]
Recently, color.js was introduced to replace the chalk module.  It uses a simple check for "process" to determine if the environment can handle color.  chalk used the more robust check provided by the supports-color module.

In my browserify world, I have the process module, so I end up with weird ansi color codes in my browser.
[31mbad[0m [32mgood[0m 

Thanks!

**Comment by mroderick** [comment]
Thank you for the bug report. Fancy making it into a PR?
