### ISSUE TITLE
wrench deprecation warning on sinon install

### ISSUE THREAD

**Issue by benderTheCrime** [sinonjs/sinon#1581]
* Sinon version: ^4.0.1
* Environment: npm, nodejs
* Example URL: ?
* Other libraries you are using: any, this happens on an `npm i sinon`

**What did you expect to happen?**
Not have a deprecation warning thrown.

**What actually happens**
A deprecation warning was thrown.

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar
`npm i sinon`

Hey, I'm sorry if the details above don't satisfy the requirements of the template, but I think this will be an issue for consumers in any environment, with any version of NodeJS, and with any version of npm. I'm getting this deprecation warning when I install sinon:

```bash
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
+ sinon@4.0.1
```

Is there a way we can "check out fs-extra"? I think the API for wrench and fs-extra is similar and perhaps the upgrade would be horizontal. Is there any reason this switch hasn't been made? Would it be possible for me to open a PR for this?

**Comment by mroderick** [comment]
Sinon.JS doesn't install wrench.js as a dependency

```shell
ag -Q "wrench"
docs/_sass/bootstrap/_glyphicons.scss
175:.glyphicon-wrench                 { &:before { content: "\e136"; } }
```

```shell
mkdir issue-1581
cd issue-1581
npm init
npm i sinon
npm ls wrench.js
npm ls wrench.js
issue-1581@1.0.0 /Users/morgan/code/sinonjs/issue-1581
└── (empty)
```

It must be part of one of your other dependencies

**Comment by benderTheCrime** [comment]
I'll check again. Thanks.

**Comment by thom-nic** [comment]
It's a dependency of `build` however it looks like `build` was dropped from sinon as of v4.0.0:
```
$ npm ls wrench
myproj@1.0.0
└─┬ sinon@3.3.0
  └─┬ build@0.1.4
    └── wrench@1.3.9 
```

**Comment by fatso83** [comment]
Yeah, that was an unfortunate side effect of my doing `npm i build` instead of `npm run build` one dark and stormy night. Sorry about that. It was never supposed to be included.
