### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by tatsujb** [sinonjs/sinon#1595]
I'm using this scaffolding https://github.com/vuejs/vue-cli

and node js version : v6.11.2
and npm : 3.10.10

on a windows 10 pro (dev enabled) 64bit pc.

once in the project folder I tried : 

`npm install sass-loader node-sass style-loader --save-dev`

as instructed by this blog : https://medium.com/@mahesh.ks/using-sass-scss-in-vue-js-2-d472af0facf9

but got :

 ` -- UNMET PEER DEPENDENCY sinon@4.0.1`

then I tried : 

`npm install sinon@4.0.1` and `npm install sinon` 

and both returned the same error above.

Apparently sinon depends itself? what?

npm update now does the same thing : 

![image](https://user-images.githubusercontent.com/5132359/31938717-9f238c10-b8b8-11e7-8b0b-fbd08282cc78.png)

**Comment by fatso83** [comment]
Read the error. `karma-sinon-chai` requires `sinon@2.1.0`. Installing version 4.0.1 won't change this. Closing as this is not related to sinon at all.
