### ISSUE TITLE
.stub() doesn't work for overridden self.onerror

### ISSUE THREAD

**Issue by philipwalton** [sinonjs/sinon#1601]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : 4.0.2
* Environment : Browser (reproducible in Chrome/FF/Safari)
* Other libraries you are using: Mocha

**What did you expect to happen?**

`sinon.stub()` should stub `self.onerror` regardless of whether it's been set in user code or not.

**What actually happens**

In an environment like mocha.js (where `self.onerror` is assigned a function), `sinon.stub(self, 'onerror')` fails to wrap the method because its property descriptor doesn't return a function value.

The code causing the issue can be found here:
https://github.com/sinonjs/sinon/blob/v4.0.2/lib/sinon/stub.js#L30-L34

**How to reproduce**

http://jsbin.com/cefuzoguta/edit?html,console

**Comment by fatso83** [comment]
Verified. Not sure how to handle it. Thoughts?

**Comment by mroderick** [comment]
https://github.com/mroderick/wrapple Perhaps?

**Comment by fatso83** [comment]
This might be such a off-case, that I agree with @mroderick that we might not invest time/code complexity in solving this, but it raises the issue of documentation. We might add such an example to our how-to ("Handling non-stubbable native code"), where we show how to use a [Facade](https://en.wikipedia.org/wiki/Facade_pattern) to work around the problem.

**Comment by philipwalton** [comment]
Why is this case non-stubbable?

Is there an issue with using property assignment here? It looks like the wrap method logic already uses this in some cases: https://github.com/sinonjs/sinon/blob/v4.0.2/lib/sinon/util/core/wrap-method.js

**Comment by fatso83** [comment]
@mroderick it is unclear what our take on handling this issue is. Is it about missing documentation or a bug/missing feature?

**Comment by fatso83** [comment]
This issue was essentially about documentation in the end. If someone raises the need to see how to stub non-function prop descriptors we should make a new issue that is a lot clearer than this one!
