### ISSUE TITLE
Documentation for Getter/Setter spying and stubbing

### ISSUE THREAD

**Issue by loganhuskins** [sinonjs/sinon#1606]
Hey all,

Is there currently documentation anywhere on how to use the getter and setter spying features outlined in #1205? If not, I could read through the code and tests and add that in if it's needed. I searched pretty hard and did not see it anywhere do I figured I'd ask. Thanks.

**Comment by fatso83** [comment]
Is [this](http://sinonjs.org/releases/v4.0.2/stubs/#stubgetgetterfn) what you were looking for?

**Comment by loganhuskins** [comment]
For stubs that looks like it. I don't know of there is anything in the spy docs for them.

**Comment by fatso83** [comment]
Hmm ... I don't actually think spying has been implemented for getters/setters. I don't really know why either. The implementation would basically just be something like this:

```javascript
fn=Object.getOwnPropertyDescriptor(obj, prop).get
spy=sinon.spy(fn);
Object.defineProperty(obj, prop, { get: spy })
```

Care to take a stab at it?

**Comment by loganhuskins** [comment]
It has been implemented and I am using it. I found out how by looking through the tests in #1205. I found the tests [here](https://github.com/lucasfcosta/sinon/blob/8dace57ec83dbd59d7e574c15b6224c28cbcc092/test/spy-test.js#L2231)

It is done like this:

```
spy = sinon.spy(validApp, 'nameOfGetterFunction', ['get'])
```

Should this be in the docs? Or is that implementation not even a known thing at this point?

**Comment by mroderick** [comment]
It would be great to have it documented, thank you!

**Comment by loganhuskins** [comment]
For sure, I'll knock it out.

**Comment by mouse9** [comment]
Is there any way to spy it without class name?
I do have only object there in the spec and couldn't require the class of the getter setter is there any other way also?

**Comment by fatso83** [comment]
@mouse9 It is unclear what you are asking, and how that relates to stubbing/spying on getters. I don't understand what you mean by classes either. Classes has no real meaning in javascript and in most regards what you think of as classes are nothing more than objects. 

In any case, we are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by seanyang414** [comment]
For @loganhuskins 's code:
`spy = sinon.spy(className, 'nameOfGetterFunction', ['get'])`

Found that, in assertion, do need to assert on **spy.get** like:
`sinon.assert.calledOnce(spy.get);`

Previously was asserted on **spy** only, and didn't work.
