### ISSUE TITLE
Add propertyStub

### ISSUE THREAD

**Issue by shairez** [sinonjs/sinon#161]
Currently, we have a method stub, so we can stub an object's method, and if that object doesn't have this method or its name changes, sinon throws an exception.

Some of my tests are depended on object's property, which I want to also stub and to have the same failure mechanism as methods stub have.

Why property stubs you ask? I use it to test things like bindings and such.

Is there a reason not to add it? do you have a proposal on how to implement it? (I don't mind creating the PR myself, just wanted to get a second opinion).

Thanks,
Shai

**Comment by avand** [comment]
I think this behavior would be useful at least in one particular case: stubbing `window.location`. Currently, I have no idea how to write tests for my query string utility methods. Anytime you do `window.location = "?foo=bar"` the page reloads and my tests stop running. I guess I could put those particular tests on a different page.

**Comment by jonnyreeves** [comment]
Hi @avand, built in browser globals, like `window.location` can not be stubbed by sinon, instead we recommend you wrap such methods in your own api which you can then stub using sinon, eg:

```js
var urlUtils = {} 
urlUtils.setLocation = function (value) {
  window.location = value 
} 

// in your test code 
sinon.stub(urlUtils, 'setLocation') 
```

**Comment by avand** [comment]
Is it impossible for Sinon to stub an object's properties? Or is the issue
with stubbing globals? I'm just curious to know more about why Sinon
doesn't support stubbing properties. It's a feature I would expect in a
stubbing framework.

**Comment by mantoni** [comment]
@avand Sinon can stub properties (using the sandbox feature). It can also stub globals, if they are user defined. Sinon can not stub some special browser built-ins, for example the `location` object.

**Comment by rconnamacher** [comment]
A little late jumping in, but you can work around some use cases for stubbing location with history.replaceState(), which doesn't trigger any reloads. Just be sure to restore the correct URI after your tests are finished. So in your test, something like:

```
before: function() { _originalURI = location.href; },
after: function() { history.replaceState(null, "", _originalURI); }
testQuery: function() {
  history.replaceState(null, "", "?a=1&b=2");
  var parsed = myQueryParser();
  assert.deepEqual(parsed, {a: "1", b: "2");
}
```

There's no way to block code that directly sets properties on 'location', so if something does a `location.href = "http://redirect-to-some-site.com/"`, it'll still redirect the browser.
