### ISSUE TITLE
misleading Cannot clear time diagnostic

### ISSUE THREAD

**Issue by pabigot** [sinonjs/sinon#1611]
* Sinon version : 4.1.1
* Environment   : Node.js 4.5

I've occasionally encountered the problem in #872 and finally tracked it down: if `clearInterval` is called with an undefined interval sinon appears to record it as a timer rather than an interval.

Reproducible with mocha 4.0.1 and sinon 4.1.1 and this code under Node.js 4.5:

    'use strict';
    
    const sinon = require('sinon');
    
    describe('Test', function() {
      let clock;
      beforeEach(() => {
        clock = sinon.useFakeTimers(24 * 60 * 60 * 1000);
      });
      afterEach(() => clock.restore());
      it('should work', function() {
        const id = setInterval(() => null);
        clearInterval(id);
      });
    });

producing:

     lilith[49]$ node_modules/.bin/mocha sinon872.js 
    
    
      Test
        1) should work
    
    
      0 passing (9ms)
      1 failing
    
      1) Test
           should work:
         Error: Cannot clear timer: timer created with setTimeout() but cleared with clearInterval()
          at clearTimer (node_modules/sinon/node_modules/lolex/src/lolex-src.js:359:19)
          at Object.clearInterval (node_modules/sinon/node_modules/lolex/src/lolex-src.js:504:16)
          at target.(anonymous function) (node_modules/sinon/node_modules/lolex/src/lolex-src.js:406:34)
          at Context.<anonymous> (sinon872.js:13:5)

**Comment by fatso83** [comment]
Thanks, verified. Moved to sinonjs/lolex#138. Subscribe to updates there, or try to get a fix in, if you manage to find a fix :)
