### ISSUE TITLE
Async environement. assert.isCalled & assert.isNotCalled

### ISSUE THREAD

**Issue by cyrilchapon** [sinonjs/sinon#1612]
Hey,

I'm struggling to make sinon work in an async environment.
I'd like to stick with standards and avoid `sinon.test` and stuff.
I'm using mocha, chai, express. I'd like to test a controller

My Controller make a database call, and is async. It calls `res.json` on success, or `next` on error.

The following :
```
  it('should', function() {
    const req = {};
    const res = {
      json: sinon.spy()
    };
    const next = sinon.spy();

    myController.list(req, res, next);
    assert.notCalled(next);
    assert.called(res.json);
  });
```
...fails, shouting that `res.json` is not called.
But `res.json` IS actually called, I verified it with a simple callback.

How to test this ? I got inspired by [this](http://www.designsuperbuild.com/blog/unit_testing_controllers_in_express/), but later realized that their controller is a synchronous one...

NB: I don't want to bind a manual callback function to `res.json` or `next` : this is exactly why I'm using sinon.js

**Comment by fatso83** [comment]
This has nothing to do with sinon, and is a [detail of your test framework](https://mochajs.org/#asynchronous-code).
