### ISSUE TITLE
Sinon fake timers: global leaks requestAnimationFrame, cancelAnimationFrame

### ISSUE THREAD

**Issue by NoxWings** [sinonjs/sinon#1617]
* Sinon version : 3.0.0
* Environment   : node v6.12.0
* Other libraries you are using: mocha

**What did you expect to happen?**
Fake timers to not crash tests

**What actually happens**
Using fake timers with mocha `--check-leaks` option fails with
`Error: global leaks detected: requestAnimationFrame, cancelAnimationFrame`

**How to reproduce**
1. Create a tests file `test.spec.js`
```javascript
const sinon = require("sinon");

describe("#function name", () => {
    let clock;

    beforeEach(() => {
        clock = sinon.useFakeTimers();
    });

    afterEach(() => {
        clock.restore();
    });

    it("", () => {});
});
```
2. `npm install mocha sinon@3.0.0`
3. `npx mocha test.spec.js --check-leaks`

PS: 
Testing with 2.4.1 it is OK
Testing with 3.0.0 it shows the leak ERROR
Testing with "latest" (4.1.2) it shows the leak ERROR

**Comment by fatso83** [comment]
Thank you for this! The clock functionality is part of [lolex](https://github.com/sinonjs/lolex). Would you ind opening the bug there? We have some active contributors there that look into stuff like this.

**Comment by NoxWings** [comment]
Looks like it has already been fixed on Lolex.
Closing this issue too. Thx.

**Comment by fatso83** [comment]
Lolex is released in a new version, and as we employ slack caret versioning, a simple npm update should be sufficient.
