### ISSUE TITLE
Why did sinon block stubbing globals after version 1.7.x?

### ISSUE THREAD

**Issue by JemiloII** [sinonjs/sinon#1620]
I'm pretty frustrated about this, there are checks all over sinon disabling stubbing of function returned properties, unnamed properties, properties with getters and setters. Most frustrating is not being able to stub window. My team is using a dinosaur version of sinon, I want to move away from it, but we have many tests that rely on stubbing window methods. We have many stubs on window.confirm, window.location, window.onbeforeunload. We stub these so that we do not reload the page or block test execution, we alse check to make sure they are called with the right arguments. How do I disable this check? Why does someone feel that it's so important not to stub window in testing? It worked fine in previous versions on chrome, firefox, and phantomjs, so please don't say, it's not possible to stub window. It was working fine.

**Comment by mroderick** [comment]
In order to better assess this, could you provide a runnable test case that works in 1.17, but not in the newer major versions?

**Comment by fatso83** [comment]
Yeah, we have no way of asserting if this is true without some runnable code we can use to test against different `sinon` versions. We could do it ourselves, but we have a life too :)

**Comment by mroderick** [comment]
There's been no response from OP, despite it being two weeks. I am closing this
