### ISSUE TITLE
how do you create a stub/spy for an non-returned/parallel asynchronous function?

### ISSUE THREAD

**Issue by ztotta** [sinonjs/sinon#1625]
https://stackoverflow.com/questions/47563770/how-do-you-create-a-stub-spy-for-an-non-returned-parallel-asynchronous-function

In this example, barStub.called === false, presumably because the execution flow of fooStub does not wait for barStub to resolve.

I also put assert(barStub.called) in a 10 sec setTimeout, and it still was uncalled.

Is there a way to stub a method like bar?

```
const sinon = require('sinon')
const assert = require('assert')

const functionHolder2 = {
  bar: function() {
    return Promise.resolve('bar')
  }
}

const functionHolder = {
  foo: function() {
    functionHolder2.bar()

    return Promise.resolve('foo')
  }
}

const fooStub = sinon.stub(functionHolder, 'foo').returns(Promise.resolve({}))
const barStub = sinon.stub(functionHolder2, 'bar').returns(Promise.resolve({}))

functionHolder.foo()

assert(fooStub.called) // this passes
assert(barStub.called) // this fails
```

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions. Posting it on [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tagging it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon) is another good option.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by ztotta** [comment]
thanks!
