### ISSUE TITLE
Documentation CSS issue for text shadow

### ISSUE THREAD

**Issue by niftylettuce** [sinonjs/sinon#1631]
If you do a CMD or CTRL + F for search, and your result is in a code block then it looks horrible:

> e.g. `calledWith`

<img width="135" alt="screen shot 2017-12-11 at 2 26 39 am" src="https://user-images.githubusercontent.com/523141/33819912-cf38c3c0-de1a-11e7-90d1-f7602ac0271e.png">

**Comment by mantoni** [comment]
This seems to be caused by the text-shadow which seems unnecessary to me. I tried removing it with Chrome DevTools and it appears to look the same.

Pull request welcome :)

**Comment by niftylettuce** [comment]
Just remove text shadow completely?  why do I need to submit PR when you can do with 1 click through GitHub even..

**Comment by niftylettuce** [comment]
yay, thank you @mantoni 🎉 

<img width="325" alt="screen shot 2017-12-11 at 4 27 22 am" src="https://user-images.githubusercontent.com/523141/33824219-a53b98f2-de2b-11e7-898a-613ead97a002.png">
