### ISSUE TITLE
Synchronise releases, home site versus GitHub

### ISSUE THREAD

**Issue by bignose-debian** [sinonjs/sinon#1635]
The [releases for this GitHub repository](https://github.com/sinonjs/sinon/releases) currently show the latest release is “v3.2.0”, released 2017-08-11.

The [releases for the SinonJS project](http://sinonjs.org/releases/) currently show the latest release is “v4.1.3”. No release dates are shown.

Please ensure that every release at SinonJS appears as a release in this repository; and vice versa.

**Comment by fatso83** [comment]
It's not automated per now, which is source of the inconsistency. Care to patch the release script to push to Github?

**Comment by mroderick** [comment]
This could be automated as part of #1657

**Comment by bignose-debian** [comment]
On 25-Dec-2017, Carl-Erik Kopseng wrote:
> It's not automated per now, which is source of the inconsistency.
> Care to patch the release script to push to Github?

I don't maintain any code in GitHub and don't know the API; this is a
mystery to me :-)

-- 
 \     “Unix is an operating system, OS/2 is half an operating system, |
  `\    Windows is a shell, and DOS is a boot partition virus.” —Peter |
_o__)                                                        H. Coffin |
Ben Finney <ben@benfinney.id.au>
