### ISSUE TITLE
jQuery Deferred chain is not completely invoked if using fake server

### ISSUE THREAD

**Issue by eugenet8k** [sinonjs/sinon#1637]
I am migrating from Sinon v1.17.1 to the latest v4.1.3. Some of my existing unit tests fail in Mocha runner due to the problem when not all jQuery Deferred (Promise) chained handlers are executed, but only the first one. The same test code works well with older Sinon v1.x.

* Sinon version : 4.1.3
* Environment   : Chrome
* Example URL   : https://jsbin.com/xatebo/edit?js,console
* Other libraries you are using: jQuery 3.2.1

**What did you expect to happen?**
The jQuery Deferred promise chain should be completely invoked.

**What actually happens**
The second chained handler is not invoked if the fake server is used.

**How to reproduce**
Example of the problem:
https://jsbin.com/xatebo/edit?js,console

```js
sandbox = sinon.sandbox.create({useFakeServer: true});
promise = $.ajax({
  url: 'https://httpbin.org/get',
  success: () => console.log('handler success')
});
promise
  .then(() => console.log('promise then 1'))
  .then(() => console.log('promise then 2'));
sandbox.server.respondWith([200, '', '{}']);
sandbox.server.respond();
```
Output:
```
"handler success"
"promise then 1"
```

The same example that works (without Sinon fake  server):
https://jsbin.com/heyusuk/edit?js,console
```js
promise = $.ajax({
  url: 'https://httpbin.org/get',
  success: () => console.log('handler success')
});
promise
  .then(() => console.log('promise then 1'))
  .then(() => console.log('promise then 2'));
```
Output:
```
"handler success"
"promise then 1"
"promise then 2"
```

The same example that works (with Sinon v1.17.1):
https://jsbin.com/fixuzam/edit?html,js,console

I would appreciate any feedback or workaround that could help overcome the problem. Thanks!

**Comment by fatso83** [comment]
None of the jsbin using Sinon works:
```
ReferenceError: sinon is not defined
    at xatebo.js:3:1"
```

**Comment by eugenet8k** [comment]
@fatso83 I've updated the jsbin examples to load sinon.js from https compatible CDN. Now, it should work. Please check again in Chrome if you have a moment.

**Comment by eugenet8k** [comment]
For anyone who stuck with the similar problem here is the result of my research and possible workarounds. First of all, I need to admit that the root of the problem is the usage of the fake clock by default for the fake server starting from Sinon v2. This in conjunction of using jQuery v3 brings compatibility issues. jQuery Deferred object is based on using `window.setTimeout` to delay execution of the promise chain. But since fake server mocks `window.setTimeout`  the execution flow gets broken.

**Workaround (hack) 1:**
To manually update `longestTimeout` property of the fake server, which has `1` by default. Increasing it to any bigger number will force this [method](https://github.com/sinonjs/nise/blob/master/lib/fake-server/fake-server-with-clock.js#L42):

```
fakeServerWithClock.respond = function respond() {
    var returnVal = fakeServer.respond.apply(this, arguments);

    if (this.clock) {
        this.clock.tick(this.longestTimeout || 0);
        this.longestTimeout = 0;

        if (this.resetClock) {
            this.clock.uninstall();
            this.resetClock = false;
        }
    }

    return returnVal;
};
``` 

to execute scheduled Deferred chain handlers upon calling of `server.respond()`.

So the init code would look like:
```
sandbox = sinon.sandbox.create({useFakeServer: true});
sandbox.server.longestTimeout = 100;
```
_Full example:_ https://jsbin.com/nepotuh/edit?js,console

**Workaround (less hacky) 2:**
To forget about using `async` mode for testing jQuery AJAX related functionality.  This won't make SinonJS to stub native browser clock, hence all Deferred handlers will be executed without interruption.

But, there is still a hidden problem. By default SinonJS initializes `FakeXMLHttpRequest` with `async` set to `true` (https://github.com/sinonjs/nise/blob/master/lib/fake-xhr/index.js#L381). Too bad, because even if we initiate Ajax request with `async` flag set to `false`, SinonJS will stub the native clock before creating a new XHR request, due to this code in [fakeServerWithClock.addRequest](https://github.com/sinonjs/nise/blob/master/lib/fake-server/fake-server-with-clock.js#L12):

```
fakeServerWithClock.addRequest = function addRequest(xhr) {
    if (xhr.async) {
        if (typeof setTimeout.clock === "object") {
            this.clock = setTimeout.clock;
        } else {
            this.clock = lolex.install();
            this.resetClock = true;
        }
```

Luckily there is a workaround, we should update `FakeXMLHttpRequest` prototype `async` value to be `false` by default. So the final solution of SinonJS and jQuery initialization will look like:

```
$.ajaxSetup({async: false});
sinon.FakeXMLHttpRequest.prototype.async = false;
```
_Full example_: https://jsbin.com/jewahix/edit?js,console

**Comment by eugenet8k** [comment]
@fatso83 that was also one of my first ideas. But it doesn't solve the problem. I put the quote from the [fakeServerWithClock.addRequest](https://github.com/sinonjs/nise/blob/master/lib/fake-server/fake-server-with-clock.js#L12) in my comment, the clock is being mocked regardless of  `useFakeTimers` flag. Moreover, it would be probably wrong if that flag will affect the internal implementation of the fake server.

The essence of the problem in my understanding is the fact that `window.setTimeout` is a singleton. So mocking it will affect a lot of dependencies like jQuery Deferred. Maybe the implementation of the SinonJS fake server should be updated in the way that the `clock` won't replace native `window.setTimeout`.
