### ISSUE TITLE
sandbox.resetHistory() do not resets spied getters or setters

### ISSUE THREAD

**Issue by flakekun** [sinonjs/sinon#1638]
* Sinon version : 4.1.3
* Environment : Chrome 63.0.3239.84, Webpack 3.10.0, Karma 1.7.1, Mocha 4.0.1
* Example URL : https://codepen.io/flakekun/pen/jYroWB?editors=0012

**What did you expect to happen?**
Calls that was counted for spied getter through `sandbox` should have been zeroed after call to `sandbox.resetHistory()`

**What actually happens**
`called` property on getter spy is `true` after call to `sandbox.resetHistory()`. You have to manually reset getter calls by implicit call without sandbox.

**How to reproduce**
https://codepen.io/flakekun/pen/jYroWB?editors=0012

**Comment by flakekun** [comment]
Forgot to mention nodejs version, it is 8.9.1

**Comment by mroderick** [comment]
This has been fixed in `sinon@4.2.2`
