### ISSUE TITLE
Spying on objects with Symbol method names breaks assertion error messages

### ISSUE THREAD

**Issue by fongandrew** [sinonjs/sinon#1640]
* Sinon version : 4.1.3
* Environment : Ubuntu

Code for formatting assertion error messages does not properly account for non-string method names (i.e. symbols). This may be a regression of https://github.com/sinonjs/sinon/issues/1002.

**Reproduction Steps**

Running this bit of code:
```js
const sinon = require('sinon');
const sym = Symbol('my symbol');
const obj = { [sym]: (a, b) => a + b };
const spy = sinon.spy(obj, sym)
sinon.assert.calledWith(spy, 1, 2);
```

Results in this error:
```
TypeError: Cannot convert a Symbol value to a string
    at String.replace (<anonymous>)
    at Function.printf (/path/to/node_modules/sinon/lib/sinon/spy.js:375:31)
    at Object.assert.(anonymous function) [as calledWith] (/path/to/node_modules/sinon/lib/sinon/assert.js:80:68)
```

Instead of the expected `AssertError: expected Symbol(my symbol) to be called with arguments`.

Possible fix would be to explicitly type-cast symbol to string at https://github.com/sinonjs/sinon/blob/5e131b3e0a88eb703db551d4cbbb8b45f8c25d91/lib/sinon/spy.js#L379 (i.e. `return String(formatter.call(null, spyInstance, args))`)

**Comment by mroderick** [comment]
Thank you for this very thorough bug report!

Would you be up for creating a pull request to fix it?

**Comment by fongandrew** [comment]
Created!

**Comment by mroderick** [comment]
Thank you for your contribution 👍
