### ISSUE TITLE
Tests fail in Chromium when running locally

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#1643]
When running tests locally, I see this error for the last step.

```text
> node ./build.js

(node:29833) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:29833) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

> sinon@4.1.3 test-webworker /Users/mroderick/code/sinonjs/sinon
> mochify --https-server 8080 test/webworker/webworker-support-assessment.js

# chromium:
Error: net::ERR_SSL_PROTOCOL_ERROR

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

#### How to reproduce

1. `git checkout ca9e2facf9ada5137e3679a33d0d9994b580e592` (current `master`)
1. `npm test`
1. Observe error

I think that the first bad commit is `b6148f28ad692f61ec88269e1afddf508a35ace6`

**Comment by mroderick** [comment]
Weirdly, this only happens on my work machine. I've tried to update node & npm on my private machine, and everything is still great.

If anyone else experience this issue, please speak up

**Comment by mroderick** [comment]
Oh, it's probably because I was running other things on that port at the time...

**Comment by mantoni** [comment]
Can't reproduce on my machine. If you still see this, can you try if passing `--allow-chrome-as-root` to mochify makes it work? That is what we had to do for Travis and CircleCI.

**Comment by mroderick** [comment]
Stopping other things on port `8080` fixed the issue

**Comment by mantoni** [comment]
Hmmm. I think this could be changed so that a random free port is used.
