### ISSUE TITLE
sinon fake xhr server and polymer appLocalizeBehavior locales

### ISSUE THREAD

**Issue by tbockrath** [sinonjs/sinon#1645]
I am developing a web frontend using Polymer. I have a webcomponent which uses other webcomponents, for example a paper-input or some custom webcomponents. For demo purposes i am using the sinon fake xhr server to mock some elasticsearch requests, which is really nice for testing. In the webcomponents i use the polymer appLocalizeBehavior to load some locales from a json file. AppLocalizeBehavior uses iron-request to load the files via an url. I configured sinon to filter and exclude all urls including "locales.json", like this:

`this._server = sinon.fakeServer.create();
this._server.autoRespond = true;
this._server.xhr.useFilters = true;
this._server.xhr.addFilter(function(method, url) {
    return url.includes("locales.json");
});`

If i disable the xhr fake server the locales from all components are loading correctly. But if i enable sinon it seems like the locales are beeing loaded but sinon somehow returns them with a wrong encoding.

Someone out there facing similar problems?

**Comment by fatso83** [comment]
Try opening an issue on the [`nise` project](https://github.com/sinonjs/nise) that actually has all of this logic. 

And for this to be worked on we need a running example of what doesn't work, so submit a code sample that we can run in a browser to verify your claim. I suspect it having to do with the `text-encoding` library or something like that.
