### ISSUE TITLE
Proposal: adopt orphaned busterjs projects

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#1650]
I really enjoy using [referee][referee], but maintenance has declined in later years. I'd like to contribute to [referee][referee], but don't want my contributions to go stale quickly because of lack a mainainer attention.

Generally, the [projects in the  busterjs][busterjs] organisation have become orphaned,. They suffer from lack of maintainer attention, some are outright dead.

I think we should adopt some of these projects into the Sinon.js organisation in GitHub, where they can get the attention they deserve.

If we agree to do this, and the maintainers of [busterjs][busterjs] are happy with this, then we can discuss plans in detail.

---

- [x] `@sinonjs/formatio`
- [x] `@sinonjs/referee`
- [x] `@sinonjs/referee-sinon`
- [ ] `@sinonjs/samsam`

[referee]: https://github.com/busterjs/referee
[busterjs]: https://github.com/busterjs

**Comment by mantoni** [comment]
Very good suggestion. I found myself not adding referee to a project because of it's inactivity and uncertainty that comes with this situation. I think I'd use it again if we had it in the Sinon org. Also, we depend on libs like samsam anyway and therefore it makes sense to give them a new home here. 👍

**Comment by mroderick** [comment]
I have transferred `formatio`, `referee`, `referee-sinon` and `samsam` to the `sinonjs` organisation.

**Comment by mroderick** [comment]
I am using https://github.com/sinonjs/samsam/issues/17 to keep track of everything that needs doing as I go along.

**Comment by fatso83** [comment]
We could also move these pkgs into a `sinon` (or `sinonjs`) org/scope on NPM

**Comment by mroderick** [comment]
> We could also move these pkgs into a sinon (or sinonjs) org/scope on NPM

That's what I thought we could do, which is why I put `Publish module under @sinonjs scope with a new version` in the check list 👍
