### ISSUE TITLE
Pre-built v4.1.5 uses old version of nise

### ISSUE THREAD

**Issue by tzrh** [sinonjs/sinon#1656]
* Sinon version : 4.1.5
* Environment : N/A
* Example URL : http://sinonjs.org/releases/sinon-4.1.5.js
* Other libraries you are using: N/A

**What did you expect to happen?** / **What actually happens**

The build of sinon at http://sinonjs.org/releases/sinon-4.1.5.js should be built with nise v1.2.0, but is somehow being built with an earlier version of nise. The same applies to `sinon/pkg/sinon.js` when installing sinon v4.1.5 locally using npm.

**How to reproduce**

Note that http://sinonjs.org/releases/sinon-4.1.5.js doesn't include the changes from https://github.com/sinonjs/nise/commit/1990dd0bcf681de6a233a39280ce898c120d96fa#diff-8e958e497c1f86e91539a2fc732ef143 (search for `Fake server response body should be string`). Earlier versions of sinon (e.g. [v4.1.4](http://sinonjs.org/releases/sinon-4.1.4.js)) do include the change.

**Comment by mroderick** [comment]
Thank you for the very precise error report 👌 

I've published `sinon@4.1.6` to npm, and have deprecated `sinon@4.1.5`.

Could you verify the fix on your end and if confirmed, close this issue?

**Comment by mroderick** [comment]
##### Background

This issue was caused by an error on my part, as I forgot to run `npm install` after fetching `master` for the `sinon@4.1.5` release, which was released after #1534 was merged.

**Comment by mroderick** [comment]
I have published `sinon-5.0.0-next.3` with a fresh build including the changes from `sinon@4.1.6` as `sinon@next`

**Comment by tzrh** [comment]
Thanks, v4.1.6 looks fine!

**Comment by mroderick** [comment]
Thanks
