### ISSUE TITLE
sinon.spy(object, "method") and sinon.restore() does not work more than once on a method

### ISSUE THREAD

**Issue by oveddan** [sinonjs/sinon#166]
In setup and teardown methods, sinon.spy(object, "method") and sinon.restore() respectively does not seem to work more than once.

Take the below code:

```
beforeEach(function(){
      // spy out fs method that reads files
      sinon.spy(fs, 'readFile');
    });
    afterEach(function(){
      // restore readFile method
      fs.readFile.restore();
    });
```

When I call fs.readFile in one test, it is spied correctly, but in a second test the original method is called.

However, when I manually do the spying as so:

```
  beforeEach(function(){
      // spy out fs method that reads files
      this.oldReadFile = fs.readFile;
      fs.readFile = sinon.spy();
    });
    afterEach(function(){
      // restore readFile method
      fs.readFile = this.oldReadFile;
    });
```

I can run rs.readFile on each test and it is spied correctly.

To see the big bicture, check out two versions of the same test code:
[The one that works by manually spying out the method](https://github.com/oveddan/Node-TDD-Samples/blob/c03aa48bdbdacd9aa9a1fcc57a712ad50af5ca24/callbackTesting/logReader_tests.js)
[The one that does not work when it calls sinon.spy(fs, 'readFile'); and restore();](https://github.com/oveddan/Node-TDD-Samples/blob/c88f993438b4e6fe3e12a39e04656211a9481186/callbackTesting/logReader_tests.js)

For the record, what is failing is when it tests [a piece of code calling fs.readFile](https://github.com/oveddan/Node-TDD-Samples/blob/4d5c2a2d0840fd1cc892a24b37d5cb5b2eec066a/callbackTesting/logReader.js) and is attempting to spy that out.

And this is the error message:

```
 1) logReader getTodaysLogEntries(callback) should callback with error if reading log file causes error:
     AssertionError: expected { [Error: ENOENT, open 'Sat Jul 21 2012.log'] errno: 34, code: 'ENOENT', path: 'Sat Jul 21 2012.log' } to equal [Error: File does not exist]
      at Object.eql (/home/dan/Source/opensource/DanOvedNodeSamples/callbackTesting/node_modules/should/lib/should.js:286:10)
      at /home/dan/Source/opensource/DanOvedNodeSamples/callbackTesting/logReader_tests.js:43:20
      at /home/dan/Source/opensource/DanOvedNodeSamples/callbackTesting/logReader.js:12:9
      at [object Object].<anonymous> (fs.js:98:14)
      at [object Object].emit (events.js:64:17)
      at [object Object].<anonymous> (fs.js:92:18)
      at [object Object].emit (events.js:67:17)
      at Object.oncomplete (fs.js:1076:12)
```

**Comment by mitrey** [comment]
afterEach calls after each it() function. If you stub in it() but not in beforeEach() after call first it() your method is not stubbed. That's why object.method.restore do not added to object.method.

**Comment by sunfeng90** [comment]
How to solve this issue?

**Comment by mantoni** [comment]
@sunfeng90 Please stop adding comments to issues without saying what your actual problem is. If anything is not working for you, open a new issue with an example. If you have a usage question, send an email to the mailing list at https://groups.google.com/forum/#!forum/sinonjs. Thank you.

**Comment by sunfeng90** [comment]
OK
