### ISSUE TITLE
Docs and website are broken

### ISSUE THREAD

**Issue by dlo83** [sinonjs/sinon#1663]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : N/A
* Environment   : N/A
* Example URL   : N/A
* Other libraries you are using: N/A

**What did you expect to happen?**
Visited http://sinonjs.org/.  Expected site to load correctly.
**What actually happens**
Stylesheets not loading correctly, 404 errors in console.log for various assets. Clicking on documentation link takes you to invalid URL (http://sinonjs.org/sinon//releases/v4.1.6)
**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar

Visit the sinonjs.org website.

**Comment by dlo83** [comment]
Looks like this is getting addressed in #1662. Closing.

**Comment by mroderick** [comment]
Thank you for reporting it!
