### ISSUE TITLE
Possible to use dot notation

### ISSUE THREAD

**Issue by rightaway** [sinonjs/sinon#1681]
Instead of having to do `sinon.stub(object, 'key')`, could it be made possible to do `object.key = sinon.stub()`? It currently doesn't work with sanbox.restore and other things, would be nice to have this notation possible because of better completion and refactoring in IDEs.

**Comment by mantoni** [comment]
You’re requesting something impossible. When  assign a value, there is no way for sinon to record this to restore the previous value later.
