### ISSUE TITLE
Attempted to wrap ... which is already wrapped

### ISSUE THREAD

**Issue by rightaway** [sinonjs/sinon#1682]
I have a module like this

```js
const Redis = require('ioredis')
module.exports = new Redis({ settings })
```

I try to stub all its functions with

```js
const redis = require('redisModuleFromAbove')
sinon.stub(redis)
```

But I get `TypeError: Attempted to wrap getBuiltinCommands which is already wrapped`, where `getBuiltinCommands` appears in the `ioredis` code somewhere. I'm not wrapping this anywhere else in my code so I'm not sure why it thinks that function is already wrapped.

If I replace `sinon.stub(redis)`, with replacing all the individual functions like `sinon.stub(redis, 'set')`, then it works. But why can't I stub the entire object like I can with other objects? It works fine in other cases.

I tried various combinations with `sinon.stub`, such as `redis`, `redis.prototype`, `ioredis`, `ioredis.prototype`, but nothing works.

What I'm looking to do for example is `redis.set.getCalls()`. I'd like to stub the whole module, rather than all individual functions in the module. Why won't it work for this module in particular?

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
---
Do note that they might also need some code to reproduce this, which is hard as it is.
