### ISSUE TITLE
Broken matchers since Sinon v4.2.3

### ISSUE THREAD

**Issue by JoeTheFkingFrypan** [sinonjs/sinon#1691]
### Context ###

* Sinon version : Bug reproducible in `v4.2.3` and `v4.3.0`
* Environment   : Windows 10 / Linux using `node v8`
* Other libraries you are using: `Mocha v5.0.0`,

**What did you expect to happen?**

- This test use to pass using `sinon v4.2.2`
- Expected behaviour: matcher function should be run

**What actually happens**

- This test fails after upgrading to `sinon v4.2.3+` (introduction of `formatio` fork)

**How to reproduce**

##### Partial unit test #####

```javascript
// parseActivity.test.js

const sonicBusStub = {
  emit: sinon.stub().resolves()
};

const parseActivity = proxyquire('../parseActivity', {
  './sonic-bus': sonicBusStub,
});

afterEach(() => {
  sonicBusStub.emit.resetHistory();
})

// Matcher testing whether input value is instance of moment or not
const isMoment = sinon.match(value => {
  console.log(value);
  console.log(moment.isMoment(value));

  return moment.isMoment(value);
}, true);

it.only('Should emit an event when successfully parsed an activity', async () => {
  await parseActivity.run({
    appName: 'test',
    transactionId: '123transactionId',
  });

  sonicBusStub.emit.should.have.been.calledOnce();
  sonicBusStub.emit.should.have.been.calledWithMatch('activities.12345.parsed', {
    activity: {},
    createdAt: isMoment,
    transactionId: '123transactionId',
  });
});
```

##### Tested function #####

```javascript
// parseActivity.js
'use strict';

const moment = require('moment');
const sonicBus = require('./sonic-bus');

/**
 * @param {Object} payload Input payload
 * @returns {Object} Sport Heroes activity
 */
function parseActivity(payload) {
  const { transactionId } = payload;
  const eventName = 'activities.12345.parsed';
  const params = {
    transactionId,
    activity: {},
    createdAt: moment(),
  };

  return sonicBus.emit(eventName, params);
}

module.exports = ({
  run: parseActivity,
  errorCode: 'BROKEN_PARSE_ACTIVITY',
});
```

#### Using Sinon `v4.2.2` ####

![image](https://user-images.githubusercontent.com/2607260/36160371-4967b45a-10e1-11e8-940d-963355afa00d.png)

#### Using Sinon `v4.2.3` ####

![image](https://user-images.githubusercontent.com/2607260/36160435-72460da4-10e1-11e8-945f-664b56dd4999.png)

#### Using Sinon `v4.3.0` ####

![image](https://user-images.githubusercontent.com/2607260/36160475-89e84c92-10e1-11e8-9d9a-dc96277dce76.png)

**Comment by mroderick** [comment]
`parseActivity` is not defined, and it's unclear what that is expected to do.

Could you reduce the example further to something that we can run and study?

**Comment by JoeTheFkingFrypan** [comment]
Apologies for that. I have updated the snippet and added example code for `parseActivity`

What is expected to do is to run the matcher.
The test is failing without passing into the `isMoment` matcher (no console.log are shown)

**Comment by serhalp** [comment]
I just ran into this too, and after a lot of digging through the sinon source, I've narrowed it down a little further.

Previously, you could do this:
```js
spy.calledWithMatch({
  foo: sinon.match(function () { /* ... */ })
})
```

which [the docs](http://sinonjs.org/releases/v4.3.0/spies/) claim
> behaves the same as `spy.calledWith(sinon.match(arg1), sinon.match(arg2), ...)`

and given that [the docs](http://sinonjs.org/releases/v4.3.0/matchers/) also claim that `sinon.match(object)`
> supports nested matchers

I would expect the function at `foo` to be called to match recursively. However, I can clearly see that the function is never called. However, if I wrap the argument to `calledWithMatch` with `sinon.match()`, suddenly everything works as expected:
```js
spy.calledWithMatch(sinon.match({
  foo: sinon.match(function () { /* ... */ })
}))
```

I'm using 4.2.1, which doesn't align with what @JoeTheFkingFrypan reports here. It's possible this is somehow a different issue, I guess.

I'll try to bisect sinon versions later, and write a failing test if I have time.

**Comment by JoeTheFkingFrypan** [comment]
After further experimentation, it seems to have been caused by a version mismatch between 
- the local `sinon` of the project (`v4.2.3` and `v4.3.0`)
- And the one installed in devDependency(`v4.2.2`) --  internal testing tool, which is a revamp of `mocha-suite`

Bumping both solved the issue as the matcher function got called again.

**Comment by fatso83** [comment]
If your problem is gone in recent Sinon versions, @JoeTheFkingFrypan, I would assume we can close this. 

@serhalp It seems your problem differs from this. Would you mind opening a new issue so that we can seperate the two?

**Comment by JoeTheFkingFrypan** [comment]
Sounds good to me
