### ISSUE TITLE
sinon@next: fake.yield() and friends not implemented

### ISSUE THREAD

**Issue by mantoni** [sinonjs/sinon#1696]
This might be intentional, but I would like to see these helper functions implemented. `fake.firstCall.yield()` works and `fake.args[0][1]()` is also available.

Via #1586

**Comment by mroderick** [comment]
These were filtered out.

https://github.com/sinonjs/sinon/blob/0bd614f3e0cc4b5e024929db3828c120d3b2809a/lib/sinon/fake.js#L22-L25

Since we're designing a new API, we have the opportunity to improve things.

Do you think we should keep these as they are, or try to come up with a better API for them?

We could certainly do with some better documentation in this area.

**Comment by mantoni** [comment]
I personally only use `yield`, although I understand why the other functions were added. If we could find a way to reduce these use cases into a single API, that would be cool. I would be open to a new approach, but I fail to come up with any better ideas.

First, I thought we could try to add something to find the callback and leave the invocation to the user, but in my experiments, that is more verbose and less intuitive.

(e.g. `fake.findArg(sinon.match.func)(null, 123)` 👎 )

On the upside, the places where the two functions (`yield` and `yields`) are available are different:

- `sinon.fake.yields()` returns the programmed fake, while `sinon.fake.yield()` does not exist
- `fake.yield()` invokes a callback on a fake instance, while `fake.yields()` does not exist

So confusing the two causes an immediate error.

**Comment by mantoni** [comment]
One alternative that comes to mind would be this:

- `fake.yield(a, b)` as before
- `fake.yield.on(scope)(a, b)` instead of `fake.yieldOn(scope, a, b)`
- `fake.yield.to(property)(a, b)` instead of `fake.yieldTo(property, a, b)`

While is not much of a difference, it's at least making it more clear that `on` and `to` are special cases of `yield`.

This pattern could be applied to `yields` as well: `sinon.fake.yields.on(scope)(a, b)`.

**Comment by mroderick** [comment]
And `fake.yield.on(scope).to(property)(a, b)`?

**Comment by mantoni** [comment]
Yeah, that would be the logical consequence. Not 100% sure on all this really.

**Comment by mroderick** [comment]
That kind of api takes us back into the mutable space as well :(

**Comment by mantoni** [comment]
No, that it wouldn't. `fake.yield.on(scope)` returns a plain function. It's not a fake until you'd finally invoke it. So it could be immutable.

**Comment by mroderick** [comment]
Unless we do something like `fake.yield.onTo(scope, property)(a, b)` ... which looks a bit ... weird

**Comment by mantoni** [comment]
Or, `fake.yield({ args: [a, b] })`, which allows `fake.yields({ scope: that })` and any combination. The cost is more typing.

**Comment by mroderick** [comment]
How about `options` as an optional last argument?

```js
// without options
fake.yield("Morgan", "Roderick");

// with options
fake.yield("Morgan", "Roderick", {
    scope: that,
    property: "hello"
});
```

**Comment by mantoni** [comment]
How do you distiguish the options object from an argument I want to pass?

**Comment by mroderick** [comment]
> How do you distiguish the options object from an argument I want to pass?

Now you're just being difficult

**Comment by mantoni** [comment]
Haha. I'm not kidding or trying to be difficult. Here is an example where I'm invoking a callback with 3 arguments: https://github.com/javascript-studio/studio-json-request/blob/68b34a90606feece1f0cb00dfc11928c16f4580c/lib/request.js#L130

**Comment by mroderick** [comment]
> Haha. I'm not kidding or trying to be difficult

I know 😁

**Comment by mantoni** [comment]
`fake.yield('Max', 'Morgan', sinon.options({ scope: that }))`

**Comment by mroderick** [comment]
> `fake.yield('Max', 'Morgan', sinon.options({ scope: that }))`

This is my favourite so far, as it avoids drawbacks of the other ideas:

* passing arguments wrapped in an `Array` (`fake.yield({ args: [a, b] })`) seems awkward, and won't lend itself to idiomatic JS using `Function.prototype.apply`
* `I().am().not().a().fan().of().chainable().apis().as().they().make().return().values().meaningless().and().code().difficult().to().read().fin();`
* Having to invoke the return value seems awkward: `fake.yield.on(scope).to(property)(a, b)`

I suspect that most people will only use the form without the options argument (`fake.yield('Max', 'Morgan')`), I think we should optimise for that situation (the 80% case).

Creating `sinon.options` makes the code easy enough to read, and the added verbosity will only affect 20% or less.

**Comment by mantoni** [comment]
I agree in all points. The added verbosity might even lead to better readability. I never found `yieldOn` very telling.

**Comment by mroderick** [comment]
What shall we name the property? `scope`? `context`?

**Comment by mantoni** [comment]
I’d say `scope` for the `this` Object and `property` for the key to find the callback in the object (the `yieldsTo` equivalent).

Or would it be ok in all supported environments to use `this` as the property name?

**Comment by mroderick** [comment]
After giving this a bit more thought, I don't think we should expand the library to do things that our target version of JavaScript has first level support for: [`Function.prototype.bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind).

Instead, we should write better documentation and encourage people to do things in idiomatic JS ways.

Therefore `fake.yield('Max', 'Morgan');` should be the only way to use `fake.yield`.

I think we could even go so far as to deprecate the extra methods on `stub` for `@next`, and remove them in `@next+1`.

What do you think?

**Comment by mroderick** [comment]
Could you create an example to help me understand it?

**Comment by mantoni** [comment]
You are suggesting this, right?

```js
sinon.replace(obj, ‘thing’, sinon.fake.yields().bind(scope))
```

This would bind the scope the fake is invoked on, but not the scope the callback would be invoked on. I can create an example later today to illustrate.

**Comment by mantoni** [comment]
Here is a sandbox test case that reproduces the discussed scenario:

```js
        it.only("should invoke callback on specified thisValue", function () {
            var object = {
                property: function (callback) {}
            };
            var thisValue = {};

            var replacement = fake.yields();
            this.sandbox.replace(object, "property", replacement);

            var callback = fake();
            object.property(callback);

            assert.isTrue(callback.called);
            assert.equals(callback.firstCall.thisValue, thisValue); // Fails
        });
```

A possible solution without changing the API would be this:

```js
            var replacement = fake(function (callback) {
                callback.call(thisValue);
            });
```

The proposed feature would read like this:

```js
            var replacement = fake.yields(sinon.options({ thisValue: thisValue }));
```

Now that I've written out a complete example, I think that wrapping a custom function should be used in this scenario. This could be described in the docs and the migration guide. The same goes for `yieldsTo` and `yieldsToOn`.

**Comment by mantoni** [comment]
One more thought: The above example demonstrates how one can emulate `yieldsTo`, but I didn’t come up with a solution for `fake.yieldTo`.

How about exposing a `callback` on each fake and each call? Users can the invoke callbacks like this:

```js
fake.callback();
fake.secondCall.callback.call(thisValue);
```

What do you think? Other ideas?

**Comment by mroderick** [comment]
Looking at the documentation for `stub` and trying to map it to `fake` for both `yields` and `yield` as well as suggestions has me confused.

Let me try to untangle the mess of my understanding, perhaps we can fix some of the gaps in it.

##### `yields`

> Causes the stub to call the first callback it receives with the provided arguments (if any).

```js
const s = sinon.stub().yields('Max', 'Morgan', console.log);

// activate the stub, causes callback to be called
s();

// fake equivalent would be
const f = sinon.fake.yields('Max', 'Morgan', console.log);

// activate the fake, causes callback to be called
f();
```

If I want to change the `this` value, I can either use `yieldsOn` or `Function.prototype.bind`.

```js
// `yieldsOn`
const s = sinon.stub().yieldsOn(console, 'Max', 'Morgan', console.log);

// `Function.prototype.bind`
const t = sinon.stub().yields('Max', 'Morgan', console.log.bind(console));

// fake, using `Function.prototype.bind`
const f = sinon.fake.yields('Max', 'Morgan', console.log.bind(console));
```

If I've learned to use `bind`, why not go all the way?

```js
const s = sinon.stub().calls(console.log.bind(console, 'Max', 'Morgan'));

// or even simpler
const s = sinon.spy(console.log.bind(console, 'Max', 'Morgan')));

// and with fake
const f = sinon.fake(console.log.bind(console, 'Max', 'Morgan')));
```

At this point, I am wondering, do we even need `yields`?

**Comment by mroderick** [comment]
##### ~`yield`~ `callback`

> How about exposing a `callback` on each fake and each call? Users can the invoke callbacks like this:

```js
fake.callback();
fake.secondCall.callback.call(thisValue);
```

I like it!

Perhaps create another function to solve the `to` problem?

```js
fake.callback.to('property', 'Max', 'Morgan');
```

**Comment by mantoni** [comment]
You‘ve got the yields semantics wrong somehow. Your example should really be this:

```js
const s = sinon.stub().yields("Morgan");

s(console.log);
```

I‘ll see if I can find more real world examples. I’m surprised you get away without it. I use yields all the time 😄

**Comment by mroderick** [comment]
Perhaps we can update the documentation for `stub`while we're at it ... I am sure other people are getting it wrong too :)

**Comment by mantoni** [comment]
Okay, I'v implemented a real example demonstrating how `yields` works as a gist. The API is a function that reads a JSON file asynchronously, parses it and passes the parsed content to a callback.

https://gist.github.com/mantoni/00ff8e30e0404bf57a4164910c53bf58

I believe we agreed to leave the new fake `yields` behaviour as is with no additional features to yield to a property and without a way to configure a way. The solution for fakes are custom functions.

Regarding the `yield` (without "s") method, which this issue was originally opened for, I understand that we want a way that is more distinct from `yields` to avoid confusion. We also want a simplistic API, ideally without special APIs to configure the scope object or a property to yield to.

I think the `fake.callback()` idea is the best candidate we have so far. I'm therefore closing this issue and I'm going to open a new one to further discuss that option.
