### ISSUE TITLE
Documentation for useFakeTimers parameters

### ISSUE THREAD

**Issue by Freakachoo** [sinonjs/sinon#1713]
I've just found amazing feature in `sinon.useFakeTimers()`, that is not really documented properly.

If you want to fake not all timer functions (`setTimeout`, `setImmidiate`, `Date`, etc...) but only some of them you may use: 

`const clock = sinon.useFakeTimers({now: 0, toFake: ['Date']})`

Because faking all timer functions sometimes may cause problems. For example if you use `setTimeout` in an application code.

Feature not really documented and on official website wrong description of incoming parameters and no examples for the usage.

So, hope this will be useful for somebody.

**Comment by fatso83** [comment]
We'd love to have that feature documented, of course! All the features of the timer faking come from the [`lolex`](https://github.com/sinonjs/lolex) project, so it might make sense to simply delegate to its documentation for the timers.

The documentation for the options you mentioned are well documented for [`lolex.install()`](https://github.com/sinonjs/lolex#var-clock--lolexinstallconfig), so it might make sense to simply send people over there to avoid needing to duplicate all the options.

Would you like to help us out? That would be most appreciated. Introduction to fixing the docs [here](https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md).
