### ISSUE TITLE
sinon@next: Provide a way to invoke callbacks on fakes

### ISSUE THREAD

**Issue by mantoni** [sinonjs/sinon#1714]
This is a follow up issue from the discussion on #1696.

The Sinon spy and stub APIs have these functions:

- `yield` (aliased as `invokeCallback`)
- `yieldOn`
- `yieldTo`
- `yieldToOn`
- `callArg` (aliased as `callArgWith`)
- `callArgOn` (aliased as `callArgOnWith`)

They all intend to invoke callbacks that were passed to the spy or stub as an argument.

Instead of providing various ways to invoke arguments as functions, we could expose them in a more convenient way and let users invoke the functions. This allows to make use of `.call` and `.apply` to change the function scope.

Currently, arguments can be accessed through calls, e.g. the `fake.firstCall.args` array.

I would like to propose that we expose more references to arguments in order to avoid having to add all of the above methods to the new `fake` api:

- `fake.callback`: Referring to the last argument being passed to the fake in the last call, if it's a function. Otherwise this property does not exist.
- `fake.lastArg`: Referring to the last argument being passed to the fake in the last call.
- `fake.getCall(n).callback`: Referring to the last argument being passed to this specific call, if it's a function. Otherwise this property does not exist.
- `fake.getCall(n).lastArg`: Referring to the last argument being passed to this specific call.

The "legacy" API functions would map to the new fake API as follows:

| Legacy | Fake API |
|----|----|
| `yield(a, b, c)` | `fake.callback(a, b, c)` |
| `yieldOn(scope, a, b, c)` | `fake.callback.call(scope, a, b, c)` |
| `yieldTo(property, a, b, c)` | `fake.lastArg[property](a, b, c)` |
| `yieldToOn(property, scope, a, b, c)` | `fake.lastArg[property].call(scope, a, b, c)` |
| `callArg(index, a, b, c)` | `fake.lastCall.args[index](a, b, c)` |
| `callArgOn(index, scope, a, b, c)` | `fake.lastCall.args[index].call(scope, a, b, c)` |

The difference between `fake.lastArg` and `fake.callback` is purely semantical and implies a type check for `fake.callback`. I'm suggesting this, because it would be weird to have an object under `fake.callback`. On the other hand, `fake.lastArg()` doesn't read very nice.

**Comment by mroderick** [comment]
This was fixed with #1759
