### ISSUE TITLE
Inconsistent newlines in %D replacement using spy.printf

### ISSUE THREAD

**Issue by JayAndCatchFire** [sinonjs/sinon#1717]
* Sinon version: 4.4.2
* Environment: Ubuntu 16.04, Node v8.9.4, npm 5.7.1
* Other libraries you are using: [sinon-chai](https://github.com/domenic/sinon-chai) 2.14.0

**What did you expect to happen?**
I expected the `%D` replacement for `spy.printf` to have the same newline behavior regardless of the number of calls to the spy.

**What actually happens**
When there's only one call to a spy and I use the `%D` replacement with `spy.printf`, a newline is appended to the start of the replacement thanks to [this statement](https://github.com/sinonjs/sinon/blob/f89392c419dd3825d7af7fa0d58cc6ddeabfa3a6/lib/sinon/spy-formatters.js#L58) which is always executed.  However, when multiple calls have been made to the spy, a newline is _not_ placed at the beginning of the replacement because of [this conditional](https://github.com/sinonjs/sinon/blob/f89392c419dd3825d7af7fa0d58cc6ddeabfa3a6/lib/sinon/spy-formatters.js#L51) which only adds newlines before the "Call _n_:" label after the first iteration of the loop.

**How to reproduce**
```javascript
const Sinon = require('sinon');
const spy = Sinon.spy();
spy(1, 2, 3);
console.log(spy.printf('%D'));  // => "\n1\n2\n3"
spy(4, 5, 6);
console.log(spy.printf('%D'));  // => "Call 1:\n1\n2\n3\nCall 2:\n4\n5\n6"
```

I this an oversight in formatting or is this an intentional decision?  There don't seem to be any explicit unit tests for `%D` with the rest of the [`printf` tests](https://github.com/sinonjs/sinon/blob/f89392c419dd3825d7af7fa0d58cc6ddeabfa3a6/test/call-test.js#L1328), but altering how `%D` works causes tests like the [`assert.alwaysCalledWithMatch exception message` test](https://github.com/sinonjs/sinon/blob/f89392c419dd3825d7af7fa0d58cc6ddeabfa3a6/test/assert-test.js#L1664) to fail.

**Comment by mroderick** [comment]
Thank you for your accurate bug report.

I am sure it's an oversight that the formatting is inconsistent, and it's certainly an oversight that there are no unit tests for `%D`.

Would you like to contribute another pull request to amend that?

**Comment by JayAndCatchFire** [comment]
I'd love to make a PR to fix this.  But, which is the preferred version?  With a starting newline or without?

**Comment by mroderick** [comment]
I don't have strong opinions about this, and welcome discussion if anyone has arguments for either solution.

I'd prefer to always start with a newline, as that's the behaviour for the single call. I assume the single call is the more common usage, so people might have built integrations (like `sinon-chai`), that expect strings to start with a newline.

**Comment by JayAndCatchFire** [comment]
I concur with your preference. I'll make a PR that makes the multiple call format match the single call format.
