### ISSUE TITLE
Cannot stub non-existent own property [...]

### ISSUE THREAD

**Issue by ericmorand** [sinonjs/sinon#1720]
With sinon@4.4.2.

Consider the following code:

```javascript
const sinon = require('sinon');

class Foo {
    bar() {
        return 'bar';
    }
}

let foo = sinon.mock(Foo);

sinon.stub(foo, 'bar').returns('foo');
```

It throws the error `Cannot stub non-existent own property bar`.

**Comment by mroderick** [comment]
This is by design. There's plenty discussion of that in the issues, like #1537.

**Comment by mroderick** [comment]
I'll update the documentation to specifically say that it's not possible to stub non-existent properties

**Comment by ericmorand** [comment]
@mroderick, 

> I'll update the documentation to specifically say that it's not possible to stub non-existent properties

But `bar` exists.

**Comment by mroderick** [comment]
Oh, you've updated the example ... now I see what you mean :)

**Comment by ericmorand** [comment]
@mroderick, I'm sorry, yes, I updated it in less than a minute but you're too fat for me! :D

**Comment by mroderick** [comment]
Let's finish this issue first, before we tackle the other one.

In the documentation it states:

> If you need to stub getters/setters or non-function properties, then you should be using sandbox.stub

This is a limitation in current sinon, that we're working on addressing in `sinon@next`.

**Comment by ericmorand** [comment]
Thanks a lot for the clarification and pointing to the doc. I missed that part.

**Comment by jdmarshall** [comment]
@mroderick 

The documentation for stub.callsFake() still implies that you can stub nonexistant functions.

**Comment by mroderick** [comment]
@jdmarshall would you like to contribute an update to the documentation to correct this?

See https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md
