### ISSUE TITLE
Attempted to wrap [...] which is already wrapped

### ISSUE THREAD

**Issue by ericmorand** [sinonjs/sinon#1721]
With sinon@4.4.2, the following code throws a `Attempted to wrap bar which is already wrapped`:

```javascript
const sinon = require('sinon');

class Foo {
    bar() {
        return 'bar';
    }
}

let foo = sinon.createStubInstance(Foo);

sinon.stub(foo, 'bar').returns('foo');
```

**Comment by mroderick** [comment]
The issues you create are very terse. Please use the issue template and give a bit more information.

What did you expect to happen?

**Comment by ericmorand** [comment]
I expect to not throw an exception. I want to stub the `bar `function of my stub so that it returns 'foo' instead of 'bar'.

Isn't it what sinon is about? I'm testing it and I assumed it was the same thing that PHPUnit mock and stub library.

$foo = $this->getMockBuilder('Foo')->getMock();
$foo ->method('bar')->will($this->returnValue('foo));

**Comment by mroderick** [comment]
You were almost there.

```js
const sinon = require('sinon');

class Foo {
    bar() {
        return 'bar';
    }
}

let foo = sinon.createStubInstance(Foo);

foo.bar.returns('foo');
console.log(foo.bar());
```
