### ISSUE TITLE
Why can only functions defined by value property of descriptor be stubbed?

### ISSUE THREAD

**Issue by CoderK** [sinonjs/sinon#1731]
I am use [autobind-decorator](https://github.com/andreypopp/autobind-decorator) in my project. Usage autobind-decorator as shown below:

```javascript
class Component {
  constructor(value) {
    this.value = value
  }

  @autobind
  method() {
    return this.value
  }
}
```

Inside auto-bind decorator, it redefines context of function by using getter, setter.

```javascript
      Object.defineProperty(this, key, {
        configurable: true,
        get() {
          return boundFn;
        },
        set(value) {
          fn = value;
          delete this[key];
        }
      });
```

I tried to stub my component with sinon as show below, but the function with autobind was not become a stub.

```javascript
sinon.stub(Component)
```

I tracked why and figured out that in [stub-entire-objects.js](https://github.com/sinonjs/sinon/blob/4c6b875c96e8cd3efea18b1e28f2f55186c92065/lib/sinon/stub-entire-object.js), only function defined by value property of descriptor can be become stub.

```
        if (
            propOwner !== Object.prototype &&
            prop !== "constructor" &&
            typeof getPropertyDescriptor(propOwner, prop).value === "function"
        ) {
            stub(object, prop);
        }
```

I want to know if it was originally intended.

**Comment by mroderick** [comment]
Searching this project for "constructor" would give you #1265 as the second issue result, where this is discussed.

The background is well explained in the ["Motivation" for `sinon-helpers`](https://github.com/TNG/sinon-helpers#motivation), which offers a partial solution to your challenge.
