### ISSUE TITLE
What's with sinon v5 on Jan 11, 2018?

### ISSUE THREAD

**Issue by danactive** [sinonjs/sinon#1747]
Version v5.0.0 published to npm on Jan 11, 2018 but no update or migration guide since. What's with sinon v5 on Jan 11, 2018?

Greenkeeper.io tried to update my repo to sinon v5, see linked issue https://github.com/danactive/history/pull/260

**Comment by mroderick** [comment]
That version was a mistake on my part, and was unpublished. We're still working on the next MAJOR release.

I don't know Greenkeeper well enough to comment on why it has decided to pester you with this
