### ISSUE TITLE
spy doesn't work when i use dispatchEvent 

### ISSUE THREAD

**Issue by xunina** [sinonjs/sinon#1755]
````   
 *.js
 constructor (props: ICompatibleDivProps) {
      super(props)
      this.touchEndHandler = this.touchEndHandler.bind(this)
      this.touchMoveHandler = this.touchMoveHandler.bind(this)
      this.touchStartHandler = this.touchStartHandler.bind(this)
   }

  componentDidMount () {
    this.attachEvent('touchstart', this.touchStartHandler, { passive: true })
    this.attachEvent('touchmove', this.touchMoveHandler, { passive: false })
    this.attachEvent('touchend', this.touchEndHandler, { passive: true })
  }

  componentWillUnmount () {
    this.removeEvent('touchstart', this.touchStartHandler)
    this.removeEvent('touchmove', this.touchMoveHandler)
    this.removeEvent('touchend', this.touchEndHandler)
  }

  attachEvent (type: string, cb: (e: any) => any, option: any) {
    this.divElement.addEventListener(type, cb, option)
  }

  removeEvent (type: string, cb: (e: any) => any) {
    this.divElement.removeEventListener(type, cb)
  }

  render () {
    const { style, className } = this.props
    return (
      <div
        ref={div => this.divElement = div}
        style={style}
        className={className}
        onClick={this.props.onClick}
      >
        {this.props.children}
      </div>
    )
  }
````

````
 *.test.js
 test('event called is normal', () => {
  const wrapper = mount(
    <CompatibleDiv />
  )

  const instance = wrapper.instance() as CompatibleDiv
  const touchstartSpy = spy(CompatibleDiv.prototype, 'touchStartHandler')
  const div = wrapper.find('div').getDOMNode()
  div.dispatchEvent(new Event('touchstart')
  console.log('callCount: ', touchstartSpy.callCount)
  
})
````

* Sinon version :4.3.0
* Environment   :
* Example URL   :
* Other libraries you are using:  enzyme jest

**What did you expect to happen?**
touchstartSpy.callCount  value  is 1

**What actually happens**
touchstartSpy.callCount  value  is   0
why?

**Comment by fatso83** [comment]
There are some issues here, apart from this being a clear usage question.
1. It seems to be some kind of JS derived language with type annotations (Flow/Typescript?). I can't run this
2. I can't see any proof this is related to Sinon. There is no Sinon code here.
3. Jest includes much of Sinon's API, so this might very well be a Jest usage question. 

_Anyway:_
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon) (or perhaps `jest` in this case :smile_cat:), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
