### ISSUE TITLE
Original function called even when stubbing wiht sinon.stub().resolve()

### ISSUE THREAD

**Issue by armandAkop** [sinonjs/sinon#1767]
* Sinon version : 4.5.0
* Environment  : Macbook Pro running running Sierra version 10.12.6, node 6.11.4, npm 4.6.1.
* Other libraries you are using: mocha 5.1.1

Hi everyone, I'm playing around with sinon to get familiar with how stubbing works, and I came across this scenario (which I'm not sure is a bug or is intended functionality). I have 3 files in use: repository.js, dataManager.js, and the test file dataManager.test.js. Here is some code and output to demonstrate.

repository.js
```javascript
function getData() {
  return new Promise((resolve, reject) => {
      setTimeout(() => {
          resolve({ data: 123 });
      }, 1500);
  });
}

exports.getData = getData;
```

dataManager.js
```javascript
const getData = require('./repository').getData;

function retrieve() {
  return getData();
}

exports.retrieve = retrieve;
```

dataManager.test.js
```javascript
const sinon = require('sinon');
let repository = require('./repository');
const dataManager = require('./dataManager');

describe('get data', () => {
  before(() => {
    sinon.stub(repository, 'getData').resolves({data: 'mocked data'});
  })
  it('Should send back data', () => {
    dataManager
      .retrieve()
      .then(data => {
        console.log('test data:', data);
      });
  });
})
```

**What did you expect to happen?**
I expected the console.log to print out `"test data: { data: 'mocked data' }"`

**What actually happens**
What is printed is `"test data: { data: 123 }"`, indicating that the actual repository.getData() function was called.

HOWEVER, if I were to change dataManager.js to the following
```javascript
const repository = require('./repository');

function retrieve() {
  return repository.getData();
}

exports.retrieve = retrieve;
```

The console output `"test data: { data: 'mocked data' }"`, which is expected. Why is there a difference in how repository.getData() is required within dataManager when it comes to stubbing?

**Comment by fatso83** [comment]
The exported symbol from `repository` is essentially a property. Changing a property does not affect the original object that variable used to point to. Look at it like this:

```javascript
function f1(){}
var o1 = {a:f1}; //  // equivalent of the export from repository.js

var ref1 = o1.a;   // equivalent of dataManager.js's require() call and subsequent assignment

// equivalent of the tests require() call and subsequent overwrite
o1.a = function stub(){};
var ref2 = o1.a;

assert(ref1 !== ref2);
assert(ref1 === f1);
assert(ref2 === stub);
```

This is a simplified version of what you are experiencing. In order to actually effect the inner workings of a module you either need to inject the dependencies (which will change the module globally) into the module or work at the higher link level. See [this StackOverflow answer for an almost identical question](https://stackoverflow.com/questions/44783530/can-i-spy-with-sinon-a-function-call-in-an-external-module-function/44784054#44784054) for details.

**Comment by armandAkop** [comment]
Thanks @fatso83 that example really cleared it up
