### ISSUE TITLE
Default sandbox's restore method does not restore stubs/spies

### ISSUE THREAD

**Issue by ndhoule** [sinonjs/sinon#1775]
When using any sandbox method on the default sandbox, `restore()` does not restore mocks or spies properly. A minimal repro case on Sinon v5.0.2:

```js
const sinon = require('sinon');
const myApi = {
  someMethod() {
    console.log('test method!');
  }
};

sinon.stub(myApi, 'someMethod');
sinon.restore();
sinon.stub(myApi, 'someMethod');
// TypeError: Attempted to wrap someMethod which is already wrapped
```

It seems that in the [call to `extend` in `lib/sinon.js`](https://github.com/sinonjs/sinon/blob/master/lib/sinon.js#L63), the un-sandboxed `stub/spy/etc.` exports from `apiMethods` end up shadowing the sandbox methods, and so `restore()` doesn't do anything. The [Sandbox API docs](http://sinonjs.org/releases/v5.0.2/sandbox/) and source in `lib/sinon.js` seem to suggest that this is intended usage.

I only tested `stub` and `spy`, but I would expect any other shadowed methods also do not work as intended.

I ran these tests on Node v8.9.4 and Chrome 66.0.3359.117 via Karma/Chromedriver, though this issue seems unrelated to environment.

**Comment by mroderick** [comment]
Thank you for your detailed error report 👍

**Comment by ndhoule** [comment]
Thanks for addressing this so quickly! Much appreciated :)

**Comment by mroderick** [comment]
With good error reports, most bugs are easy to squash
