### ISSUE TITLE
spy.threw does not work as expected

### ISSUE THREAD

**Issue by Kignuf** [sinonjs/sinon#1778]
* Sinon version : 5.0.3
* Environment   : node 8.9.0
* Example URL   :
* Other libraries you are using:

**What did you expect to happen?**
According to the doc I can spy on a method and then check if it threw exceptions.
I expected that a method that I am spying would be safe to exceptions, so that I can make it throw and check that it did throw as I expected.

**What actually happens**
The test execution stops when I invoke my spied method because it throws the expected error.
I don't reach the assertion block of my test.

**How to reproduce**
Code to reproduce:
```
it.only('can assert if method throws', function () {
		function a() {
			throw new TypeError('toto')
		}

		const spy = sinon.spy(a)
		a()
		expect(spy.threw('TypeError')).to.be.true
	})
```
Output:
```
 Spy
    1) can assert if method throws

  0 passing (7ms)
  1 failing

  1) Spy
       can assert if method throws:
     TypeError: toto
      at a (test/example.js:130:10)
      at Context.<anonymous> (test/example.js:134:3)
```

**Comment by ashishkujoy** [comment]
I think its usage is like this

function a() {
        throw new TypeError('toto')
      }
      const spy = sinon.spy(a)
      try{
        spy();
      }catch(err){
        //keep quite
      }
      assert.isTrue(spy.threw());

**Comment by fatso83** [comment]
Basically, your assumption is false, and there is nothing in the docs saying that this should be true. You can also reference the test suite for examples on usage.

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
