### ISSUE TITLE
Stub a function which executes in a forEach causes args to return same arguments for all calls

### ISSUE THREAD

**Issue by pRatikSathaye** [sinonjs/sinon#1789]
Hello,

I have a function **makeCall** which gets executed 3 times in **forEach** loop.
> let arr = [];
> [1,2,3].forEach((number) => {
>   arr.push(makeCall(number, 'doSomething'));
> });

When I stub **makeCall** and tried to assert its **args** for each call using **stub.firstCall.withExactly(), stub.secondCall.withExactly(), stub.thirdCall.withExcatly()**
I always get `[3, 'doSomething']` for stub.firstCall.args, stub.secondCall.args, stub.thirdCall.args.

Shouldn't we get different arguments depend upon the call?

**Comment by fatso83** [comment]
This requires a runnable test case. I'll look briefly at it, referencing the tests first.

**Comment by fatso83** [comment]
I have used more than an hour trying to replicate the issue. Everything seems to work (see commit bef5776) referenced above. And the mystery function `withExactly` that I tried grepping for in all kinds of ways doesn't seem to exist. 

This is why the issue template asks for reproducible code and the version used. If you think there is a bug, please fill out the missing details from the [template](https://github.com/sinonjs/sinon/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by pRatikSathaye** [comment]
Hello @fatso83 ,
It was my fault. It is not `withExactly` but `calledWithExactly`.
I tried again but still facing the same issue.
I will update the issue with version number and other details as you said.
