### ISSUE TITLE
Error in documentation (Sandbox)

### ISSUE THREAD

**Issue by vokrik** [sinonjs/sinon#1795]
**Describe the bug**
![screen shot 2018-05-16 at 12 39 09](https://user-images.githubusercontent.com/1667866/40112530-848a4832-5906-11e8-973b-a83d56b3a996.png)

Since later on in the documentation it says that sinon itself is a default sandbox, I think the require should be following:
`var sandbox = require('sinon')`

**Context (please complete the following information):**

* Library version: 5.0.x
* Example URL: http://sinonjs.org/releases/v5.0.7/sandbox/

**Comment by vokrik** [comment]
Hmmm... looking back at it I am not sure...

I thought it was like that but apparently, the sinon itself is not a sandbox.

However if I do ` const sandbox = require('sinon').sandbox`
and then `console.log(sandbox)`
I get `{ create: [Function: wrapped] }` instead of an instance of sandbox. I think there might be a problem with how the sandbox is extended with the create function for compatibility with deprecated versions.

can somebody reproduce it?

**Comment by eveadele** [comment]
It seems like this error has been corrected -- the sandbox docs now look like this:

<img width="602" alt="Screenshot 2023-05-10 at 12 19 03 PM" src="https://github.com/sinonjs/sinon/assets/6191896/2d0753fb-29ca-44c0-a879-5e942d0b9d7f">

I tried out the code and I think it works as expected. Is it safe to call this issue solved?

**Comment by fatso83** [comment]
I have long forgotten about this, but I think the whole premise was wrong:
>  I think the require should be following:
var sandbox = require('sinon')

While, _yes, Sinon is a sandbox_, the docs are about sandboxes specifically and how to use them, so it makes sense to create one.

If you want proof that Sinon _is_ a sandbox, just take a look at `./lib/sinon.js` which has this code:
```javascript
var sandbox = new Sandbox();
var api = extend(sandbox, apiMethods);
module.exports = api;
```
