### ISSUE TITLE
Pass arguments through to throws(fn)

### ISSUE THREAD

**Issue by brian-mann** [sinonjs/sinon#1797]
**Is your feature request related to a problem? Please describe.**
When I use `sinon.stub(obj, 'method').throws(fn)` I would like `fn` to receive the arguments that I passed to `obj.method(...)`.

This is useful when I want to prevent a function from **ever** being called, but if it is, to throw a new error including the arguments in which it was called.

**Describe the solution you'd like**
```js
const sinon = require('sinon');

function verbose (...args) {
  return new Error(`obj.method(...) was called without being stubbed.\n\nIt was called with arguments: ${JSON.stringify(args, null, 2)}`);
}

const obj = {
  method () {}
}

sinon.stub(obj, 'method').throws(verbose)

obj.method('foo', 'bar', 'baz')
```

**Describe alternatives you've considered**
Using `sinon.addBehavior()` or `sinon.callsFake` to achieve this.

The **real reason** I am doing this is because the default behavior of a stub (to return `undefined`) is mostly useless IMO.

When this happens, code fails in incredibly unusual ways. It is much more useful to always throw an error (so errors bubble up) enabling you to get the stack trace and arguments in which it was called.

I would alternatively prefer the ability to configure sinon's default behavior of returning undefined, to instead enable me to do just as I described. Ideally that would be even better.

**Comment by mroderick** [comment]
Have you looked at [`fake`](http://sinonjs.org/releases/v5.1.0/fakes/)  and [`sandbox.replace`](http://sinonjs.org/releases/v5.1.0/sandbox/#sandboxreplaceobject-property-replacement)? Both were added in `sinon@5`.

```js
const obj = {
  method () {}
}

const dontCallUs = sinon.fake.throws('Unexpected call to method');

sinon.replace(obj, 'method', dontCallUs);

obj.method('foo', 'bar', 'baz')
```

It won't capture the arguments, but it will give you a stack trace. If you're running the tests locally, that should be sufficient to alert you that something is wrong, and you would reach for the debugger to get an accurate understanding of the issue.

> I would alternatively prefer the ability to configure sinon's default behavior of returning undefined, to instead enable me to do just as I described. Ideally that would be even better.

What would that look like?

**Comment by fatso83** [comment]
@brian-mann I actually don't see what you are proposing, because what you ask for exists already:
> When I use sinon.stub(obj, 'method').throws(fn) I would like fn to receive the arguments that I passed to obj.method(...).

I edited your code to be runnable, and if you just append `obj.method.getCall(0).args` you will get the arguments: `[ 'foo', 'bar', 'baz' ]` passed to verbose.

**Comment by brian-mann** [comment]
Instead of returning `undefined` I would like all stubs to throw if the calls did not match the `withArgs` and additionally be able to capture the args. @fatso83 I believe what you suggested regarding grabbing the args would work that way.

The whole point of this - is that the default behavior - returning `undefined` is utterly useless and mostly leads to runtime errors. Cannot call `foo` of `undefined`. When that happens - sure you can see a stack trace... you can bust out a debugger and track it down... but it's almost always... certainly... related to a `sinon.stub` not being called with the correct arguments when given a `withArgs`.

I would go as far as to say that if you **haven't** explicitly given a return value or `withArgs` to your stub that it should **always** throw by default. I would prefer being made aware of any situation where a stub was called and was either "forgotten about" or had incorrect args. Stubs are like punching a hole in reality - they can oftentimes be a huge source of confusion, indirection, and overstubbing leads to frequent bugs. I would prefer a smaller surface area with explicit controls over how and what functions return.

**Comment by fatso83** [comment]
I am sure it would be possible to pass a flag to the sinon sandbox that sets the default behaviour to throw. Someone needs to implement it, though ... (I am not volunteering :smile:)

I think the default behaviour is there for a reason, and I am not inclined to changing it, but a one-time setting of the flag should be a minor hindrance. While `sinon.createSandbox({throwByDefault:1})` is simple enough, I am not sure how to pass it to the default [sandbox](http://sinonjs.org/releases/v5.1.0/sandbox/). Would rather not introduce more attributes on the `sinon` object.

**Comment by sgronblo** [comment]
Ran into the same problem. Seems this is not possible right now, right?

**Comment by sgronblo** [comment]
Ah, never mind. Figured out how to do it based on fatso83's comment. I still think it would be a bit cleaner to pass the original arguments to the throws handler though. But happy, there was a workaround. Thanks.
