### ISSUE TITLE
Add a `throws` assertion?

### ISSUE THREAD

**Issue by briandipalma** [sinonjs/sinon#1808]
**Is your feature request related to a problem? Please describe.**

I want to assert a method call throws an exception.

**Describe the solution you'd like**

assert.throws(() => {class.method()}, "MyCustomErrorType")

**Describe alternatives you've considered**

try/catch but it's not as nice.

**Comment by fatso83** [comment]
Sinon is not an assertion library. You might want to check out [referee](https://sinonjs.github.io/referee/#exception).
