### ISSUE TITLE
Explain sinon.spy(myFunc)

### ISSUE THREAD

**Issue by santiago** [sinonjs/sinon#1810]
Can you explain what passing a _function_ to `spy` does? It does not make sense to me. Thanks
From docs:
```
var spy = sinon.spy(myFunc);
Spies on the provided function
```

**Comment by fatso83** [comment]
It wraps the function. If you now pass the resulting, wrapped function to something where it is used as a callback, you can then read how it was used.

It is pretty much functionally equivalent to [using `callThrough` on a conditionless stub](http://sinonjs.org/releases/v5.0.10/stubs/#stubcallthrough).

```javascript
const lolFunc = () => 42;
const spy = sinon.spy(lolFunc);

function consumer(numberProducer){
    numberProducer();
    numberProducer();
    numberProducer();
}

consumer(spy);

assert.equal(spy.callCount, 3)
```
