### ISSUE TITLE
Regression introduced in #1807

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#1814]
The simple PR #1807 to update the dependencies [broke the build for master](https://travis-ci.org/sinonjs/sinon/builds/383140838). 

Both IE11 and Safari has problems as of (IE11 Promise related, Safari faking time). Not sure why or what caused it, but lolex is a reasonable guess when it comes to Safari. 

We could simply revert the PR, but it should be possible to find the regression in the list of dependencies.

**Comment by fatso83** [comment]
Installing lolex 2.4.2 fixes the Safari issue.

**Comment by fatso83** [comment]
@sinonjs/core this is what is breaking the build. We could install lolex 2.4 or fix 2.7

**Comment by SimenB** [comment]
sinonjs/lolex#176 doesn't make sense... Which one did you mean?

**Comment by benjamingr** [comment]
Mind explaining why the JSDOM integration test was causing this issue? I'm not sure I understand.

**Comment by fatso83** [comment]
It's not the test. It's the property assignment in the same PR:
https://github.com/sinonjs/lolex/commit/8ec6170cc47a0fe3a351f7d2292041d60d832c1a
