### ISSUE TITLE
No obvious way to reset fakes

### ISSUE THREAD

**Issue by akdor1154** [sinonjs/sinon#1815]
**Describe the bug**
There's no obvious or documented way to reset the history of all `fake`s.

**To Reproduce**
```js
const sinon = require('sinon');
const fake = sinon.fake();
fake(1234);
sinon.resetHistory();
fake.getCalls() // returns [Call(1234)]

sinon.reset();
fake.getCalls() // returns [Call(1234)]
```
```js
const sandbox = sinon.createSandbox();
const fake = sandbox.fake() // error, can't make fakes from sandboxes (why??)
```

**Expected behavior**
All the above behaviours should return [] instead of [Call(1234), and sandboxes should be able to create fakes (in order to reset a set of fakes together).

* Library version: 5.0.10
* Environment: ubuntu 18.04

**Comment by mroderick** [comment]
I agree.

Sandboxes, including the default sandbox `sinon`, should be able to reset fakes.

**Comment by Horaddrim** [comment]
So this issue is resolved?

**Comment by mroderick** [comment]
Yes, with #1842

**Comment by akdor1154** [comment]
thanks guys.
