### ISSUE TITLE
Regression in v5.0.8+ fakeServer when $.ajax() XHR includes headers

### ISSUE THREAD

**Issue by scottohara** [sinonjs/sinon#1817]
**Describe the bug**
In `sinon@5.0.7`, using jQuery's `$.ajax()` to fetch a _non-existent_ URL from `fakeServer` returns a `404 Not Found` response, as expected.

In `sinon@5.0.8` and later, the same fetch now returns a `0` status.

**To Reproduce**
1. `npm install sinon@5.0.7`, and run the tests below
2. `npm install sinon@5.0.8`, and re-run the tests again

```javascript
describe.only("404 Not Found", () => {
  let fakeServer;

  beforeEach(() => (fakeServer = sinon.fakeServer.create({respondImmediately: true})));

  it("should work without headers", done => {
    $.ajax({
      url: "/bad",
      headers: {},
      error(response) {
        response.status.should.equal(404);
        response.statusText.should.equal("Not Found");
        done();
      }
    });
  });

  it("should work with headers", done => {
    $.ajax({
      url: "/bad",
      headers: {"X-FOO": 1},
      error(response) {
        response.status.should.equal(404);
        response.statusText.should.equal("Not Found");
        done();
      }
    });
  });

  afterEach(() => fakeServer.restore());
});
```

**Expected behavior**
The specs above create a `fakeServer` and then attempt to fetch a non-existant URL (`/bad`).
The only difference between the two specs is the second includes a request header, `X-FOO: 1`.
The specs assert the response returned from `fakeServer` is a `404 Not Found`

In `sinon@5.0.7`, both specs pass.
In `sinon@5.0.8` and later, the spec with the `X-FOO` request header fails

**Screenshots**
Results from `sinon@5.0.7`:
![5_0_7](https://user-images.githubusercontent.com/289327/40766890-4dbbd024-64f4-11e8-90f0-2722dc524931.png)

Results from `sinon@5.0.8`:
![5_0_8](https://user-images.githubusercontent.com/289327/40766957-78985a2e-64f4-11e8-8138-69b5b122b682.png)

**Context (please complete the following information):**

* Library version: 5.0.8+
* Environment: 
* Example URL:
* Other libraries you are using: jquery@3.3.1, webpack@4.10.2, chai@4.1.2, mocha@5.2.0

**Comment by fatso83** [comment]
Probably happened in 082f8e8ab3f8b5d6332550dd05c5b3c6fed82d91, going from `nise@1.2.0` to `nise@1.3.3`. Moving this issue over to the `nise` subproject.

**Comment by fatso83** [comment]
This issue was moved to sinonjs/nise#51

**Comment by fatso83** [comment]
This issue was moved to sinonjs/nise#52

**Comment by fatso83** [comment]
Thanks, @scottohara!
