### ISSUE TITLE
stub/spy a function

### ISSUE THREAD

**Issue by jim-king-2000** [sinonjs/sinon#1819]
I have a pure function.

```
  // func.mjs
  export function func() {
    return 1;
  }
```

How can I stub/spy it in a test file? The following code does not work. It seems sinon can only stub obj.method.

```
   // test.js
  import { func } from './func';
  const stub_func = sinon.stub(func).returns(2);
```

**Comment by mtliendo** [comment]
`import * as handyUtils from './func'`

`myStub = sinon.stub(handyUtils, 'func')`

That should work.

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by fatso83** [comment]
@mroderick This has been asked and answered multiple times, but I guess this ultimately points to us needing to have more how-tos/docs. This touches somewhat on the link seams, but people get confused when encountering ES6 and all the mess that entails (ES6 -> ES5 transpilation, "true" immutable ESM modules versus the ones loaded using ESM with and without [the `mutableNamespace` option](https://www.npmjs.com/package/esm), etc).

Not asking you, btw, merely noting it :-)

**Comment by mroderick** [comment]
@fatso83 you understand this issue much better than I do 😉

**Comment by jim-king-2000** [comment]
Since all of my source code files are mjs files, sinon reports the following error message. It seems that we have to wait for the support of ES module.


```
  TypeError {
    message: 'ES Modules cannot be stubbed',
  }
```

**Comment by fatso83** [comment]
@jim-king-2000 No, shipping Sinon as a ES6 module has nothing to do with that. You need to use the mutableNamespace option I mentioned above using the `esm` loader in Node if you want to have mutable namespaces.

**Comment by jim-king-2000** [comment]
I stub the pure function above with sinon successfully while I have to change the ut file name from "test.mjs" to "test.js". I suggest that sinon should support mjs test files.

**Comment by fatso83** [comment]
@jim-king-2000 You already got the docs ... it was the link to the NPM module. But anyway ... you might want to check out this thread: https://github.com/sinonjs/sinon/pull/1803#issuecomment-391525747

It is the author of `[esm](https://www.npmjs.com/package/esm)` which explains _to me_ how this option is used, and in his last comment he links to a repo with a example on how to set it up. If you look at that, you should have everything you need.

**Comment by fatso83** [comment]
P.S If you need any more help, @jim-king-2000, please post a questionto [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. You can link the question back here, but not that our issue tracker is not a help forum.

**Comment by jim-king-2000** [comment]
I read the thread and I still have no idea how to do. I use AVA + sinon with esm and I do not use babel. The following is my config. I'll post the question to StackOverflow ASAP. By the way, I insist that it is an issue, a doc issue is still an issue.


`"ava": {
    "require": [
      "esm"
    ],
    "babel": false,
    "extensions": [
      "mjs"
    ]
  }`

**Comment by fatso83** [comment]
Agreed. Added #1832. Did not find your question on SO, btw.

**Comment by jim-king-2000** [comment]
I'm writing it. Thanks for the help and the advise.

**Comment by jim-king-2000** [comment]
Here's the link: https://stackoverflow.com/questions/50763323/stub-a-function-from-a-es6-module-without-babel. Thank you again.

**Comment by jim-king-2000** [comment]
I follow the guide on SO, and stub ES6 function successfully. Thank you again. However, there are too many tricky things to be documented, or even better, be mitigated.
