### ISSUE TITLE
React propTypes validation is not invoked during component unit tests

### ISSUE THREAD

**Issue by lubomir-sokolovsky-sde** [sinonjs/sinon#1820]
Initially, I thought this bug is caused by Mocha. However, their team commented the error is not caused by Mocha. This was indeed confirmed by subsequent tests. They indicate the behavior is connected to Sinon libraries. Here is the [original bug description](https://github.com/mochajs/mocha/issues/3319): 

I have a React component (using TypeScript):

    import ...
    import PropTypes from "prop-types";

    export class PageSizeComponent extends React.PureComponent<PageSizeProps, PageSizeState> {

        public static defaultProps: Partial<PageSizeProps> = {
            pageSizes: [10, 20, 50, 100],
            initialPageSize: 10
        };
    
        static propTypes = {
            pageSizes: (props: PageSizeProps, propName: string, componentName: string) => {
                if (!props.pageSizes.length) {
                    return new Error("At least one option for page size must be supplied.");
                }
            }
        };
        ...
    }

    export default PageSizeComponent;

And a unit test testing the `propTypes` of the component:

    describe("PageSize", () => {
        let component: ShallowWrapper;
        let error: SinonStub;

        beforeEach(() => {
            error = stub(console, "error").callsFake((args) => console.log("console.error", ...Array.from(arguments)));
            component = shallow(<PageSize onChangePageSize={() => { }} pageSizes={[]} />);
        });

        afterEach(() => {
            error.restore();
            error = null;
            component = null;
        });

        it("should write a console error if pageSizes is empty", () => {
            expect(error.callCount).is.greaterThan(0);
        });
    });

When I try to run the tests, I get an assertion error saying, that the error count is 0 (although the expect count is 1). However, when I run the application and supply an empty array to the PageSize component, I can see the following message in the console:

    Warning: Failed prop type: At least one option for page size must be supplied.
        in PageSizeComponent (created by UsersComponent)
        ...

It seems that either the propTypes validation is not called or `Sinon.Stub` cannot work properly with `console` . I tried using `Sinon.Spy` instead, or calling `returns` instead of `callsFake`, but the results were the same.

I tried adding a simple `console.log` just before the `if` statement in the `propTypes` validation of the component. When running in browser, I could see the message in the console. However, when running `npm test`, the message did not get output. I tried adding console messages to other places (e.g. the `render` method) in the code and they did display in console when running `npm test.` Maybe the `propTypes` validation is not called at all for `ShallowWrapper`? However, using a real component instead of `ShallowWrapper` did not help either.

Used package versions are following:

    "karma-mocha": "^1.2.0",
    "karma-sinon": "^1.0.5",
    "react": "^16.3.1",
    "sinon": "^4.1.2",
    "sinon-chai": "^2.14.0",

**Comment by fatso83** [comment]
I don't see how this is a bug in Sinon. _Maybe_ it is, but we don't have any runnable code to check it against, and there is a whole forest of dependencies here that obscures what is going on, which is the main problem. I use Enzyme, Sinon and React every week, and I also override `console.error` in my tests to catch propType errors, but not in exactly the same way. Simply, there isn't enough here for us to investigate this issue with ... 

I would simply post this issue to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon).

Sorry :man_shrugging:
