### ISSUE TITLE
Document `callId` property of calls

### ISSUE THREAD

**Issue by DullReferenceException** [sinonjs/sinon#1827]
In trying to figure out how to do an advanced assertion with spies (asserting specific ordering based on calls with specific parameters), I looked at the documentation and found nothing available beyond `calledBefore` which only works on all calls globally. Luckily, in looking at the _code_ for `calledBefore`, I see that `callId` is a property of a call instance, and those can be compared to determine relative ordering.

It would have helped me and would help future users if `callId` is documented in [the spy call documentation](http://sinonjs.org/releases/v5.1.0/spy-call/#spycall), not only that it exists but that it also specifies a global calling order among all spies.

**Comment by fatso83** [comment]
That's a good suggestion, although I am not totally sure if it is a public API or one of our internal ones ... We could of course make it public. @mroderick might know. In any case, the quickest way of ensuring this happens is supplying a small PR with what you want. The docs are simple markdown files. See [this](https://github.com/sinonjs/sinon/tree/master/docs#documentation-release-process) for more information.

**Comment by DullReferenceException** [comment]
I don't think I need this after all. Apparently there are some undocumented methods for calls that work nicely. Closing in favor of https://github.com/sinonjs/sinon/pull/1831.
