### ISSUE TITLE
add named exports to esm bundle

### ISSUE THREAD

**Issue by chrisguttandin** [sinonjs/sinon#1833]
**Is your feature request related to a problem? Please describe.**
The commonjs bundle allows to import all provided functionality directly by its name like `const { spy } = require('sinon');`. Due to the different semantics of the `export` keyword of an ECMAScript module this doesn't work anymore when using esm modules.

```javascript
import { spy } from 'sinon';

// spy is undefined
```

**Describe the solution you'd like**
Currently the esm module only exports all of sinons API as the default export. Would it be possible to also add named exports for spy, stub, ... and so on?

**Describe alternatives you've considered**
It is of course possible to use the default import, although it is a bit more verbose.

```javascript
import sinon from 'sinon';

const mySpy = sinon.spy();
```

**Additional context**
I think this is related to #1828 and #1829.

**Comment by fatso83** [comment]
I did the work to export Sinon as an ESM because the way it was done did not require any code changes to the main sinon code (where one of its main goals is to be simple ES 5.1 code, avoiding transpilation). 

What you want is certainly possible, but unless one replaces all `module.exports` with ES2015 `export` (not an option), the only way I can think of is to have an extra compatibility file that re-exports the props as ES2015 exports. Certainly doable, but not something I am interested in maintaining - always making sure to duplicate whatever exports have been made ... Any takers? :)

**Comment by chrisguttandin** [comment]
Hi @fatso83, thanks for taking a look at this. I played a bit with the configuration of rollup and tried to find a way which automates the process.

Here is what seems to work: The rollup config could load the comonjs module and then use its keys to manually construct the named exports which get appended to the bundle produced by rollup.

```javascript
const sinon = require("./lib/sinon.js");

export default {
    input: "./lib/sinon.js",
    output: {
        file: "pkg/sinon-esm.js",
        format: "es",
        outro: Object.keys(sinon).map((key) => `const _${key} = sinon.${key}; export { _${key} as ${key} };`).join('')
    },
    // ...
```

If you think that this is a viable solution I'm happy to provide a pull request for this.

**Comment by fatso83** [comment]
Ooooh! That is _NICE_! I can't vouch for the solution covering every case, but I do understand it at least. I suggest creating a PR with that and letting people chime in on if they can come up with scenarios where it would not work.

**Comment by fatso83** [comment]
Closed by #1835

**Comment by DonaldBough** [comment]
Not sure why I'm having a hard time getting named exports to work. I even checked out @chrisguttandin 's example. When using `import {spy} from 'sinon';` in a node js test being ran by mocha, here's the error I get.

`import {spy} from 'sinon';
        ^^^
SyntaxError: The requested module 'sinon' does not provide an export named 'spy'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:176:24)
    at async Object.exports.loadFilesAsync (/Users/donaldbough/Documents/Source_Code/GradGrid_JHS/node_modules/mocha/lib/esm-utils.js:28:20)
    at async singleRun (/Users/donaldbough/Documents/Source_Code/GradGrid_JHS/node_modules/mocha/lib/cli/run-helpers.js:107:3)
    at async exports.runMocha (/Users/donaldbough/Documents/Source_Code/GradGrid_JHS/node_modules/mocha/lib/cli/run-helpers.js:144:5)
    at async Object.exports.handler (/Users/donaldbough/Documents/Source_Code/GradGrid_JHS/node_modules/mocha/lib/cli/run.js:306:5)
`

My environment:
- macOS Catalina
- Node JS v13.12.0
- Mocha 7.1.1 
- Sinon 9.0.2

**Comment by fatso83** [comment]
@DonaldBough We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions 😃 

Your issue deals explicitly with modules and importing of these. As Node does not support 'import' statements (without a '.mjs' extension or cli flags enabled) there is definitively something missing on your list of stuff in your environment. I am guessing Babel or the esm package. Babel and webpack are the usual culprits in these matters and I would look into that, especially as this is a common usecase that works for a lot of people. Try SO :)
