### ISSUE TITLE
Spy error message references old reset function

### ISSUE THREAD

**Issue by evonsdesigns** [sinonjs/sinon#1837]
**Describe the bug**
Very minor documentation error to report. The error message for sinon.spy's resetHistory function in sinon v5 is referencing the old `reset` function:
> "Move the call to .reset outside of the callback."

**To Reproduce**
1. See [this line](https://github.com/sinonjs/sinon/blob/master/lib/sinon/spy.js#L111) for the error that is thrown in the `resetHistory` function.

**Expected behavior**
Should reference the correct function name.

> "Move the call to .resetHistory outside of the callback."

**Context (please complete the following information):**

* Library version: 5.0.7

**Comment by mroderick** [comment]
Nice find! Would you be up for making a pull request to fix it?
