### ISSUE TITLE
Add call order to mocks

### ISSUE THREAD

**Issue by pronebird** [sinonjs/sinon#1839]
**Is your feature request related to a problem? Please describe.**

I have a simple call chain where the order is important, i.e:

```js
const mock = sinon.mock(myAPI);
mock.expects('method-1')
  .once()
  .withArgs('123');
mock.expects('method-2')
  .once()
  .withArgs('123');

// ...

mock.verify();
```

Currently I don't see any way to ensure the call order. One of the reasons as well because I have no idea what `expects` returns since documentation has no type information whatsoever.

**Describe the solution you'd like**
Have facilities to describe the call order in mocks. Maybe chain them somehow, have something like:

```js
mock
.expects('call1')
  .once()
  .withArgs('123')
.andThen() // !!!
.expects('call2')
  .once()
  .withArgs('123');
```

**Describe alternatives you've considered**

**Additional context**

**Comment by mroderick** [comment]
Would you like to take a crack at implementing this with a pull request?

**Comment by mroderick** [comment]
Related: [`sinon.assert.callOrder`](http://sinonjs.org/releases/v6.1.3/assertions/#sinonassertcallorderspy1-spy2-) ensures call order of spies

**Comment by pronebird** [comment]
I don't work on the codebase that used to require this kind of feature. Then I also switched to chai-spies and chai.
