### ISSUE TITLE
make pkg/sinon.js sourceMappingURL with path not data/uri

### ISSUE THREAD

**Issue by izelnakri** [sinonjs/sinon#1847]
current sinon builds add this massive data uri string at the end of the `pkg/sinon.js`, this should be a separate file(sinon.js.map) to significantly slim down the reading/parsing and file manipulation.

**Comment by fatso83** [comment]
We already ship a Sinon version without source mapping. You can use that if you don't like the embedded source map:
```
$ get-npm-file sinon pkg
package/pkg/sinon-esm.js
package/pkg/sinon-no-sourcemaps.js
package/pkg/sinon.js
```
