### ISSUE TITLE
Memory leak not well documented

### ISSUE THREAD

**Issue by nicojs** [sinonjs/sinon#1866]
**Describe the bug**

Using `sandbox.stub()` without using `sandbox.restore()` is actually a memory leak. It is pushed on a collection and never cleaned. We've noticed this after migrating to v5. With that release, Sinon itself has become a sandbox.  

**To Reproduce**

Use `sinon.stub()` often enough, without using `sinon.restore`. 

```js
const sinon = require('sinon');
while (true) {
    sinon.stub();
}
```

You'll get an error like this one (after just a couple of seconds):

```
<--- Last few GCs --->

[20732:000001C3946E8710] 14611510 ms: Mark-sweep 1352.6 (1425.8) -> 1330.9 (1424.8) MB, 430.4 / 0.0 ms  (average mu = 0.392, current mu = 0.509) allocation failure scavenge might not succeed [20732:000001C3946E8710] 14611524 ms: Scavenge 1331.7 (1424.8) -> 1331.3 (1425.3) MB, 4.8 / 0.0 ms  (average mu = 0.392, current mu = 0.509) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================
```

**Expected behavior**

I would expect the documentation to explicit mention `sinon.restore` in the `stubs` section. Preferably, right were stubs are introduced.

**Comment by mantoni** [comment]
I verified the issue. I agree this should be documented. @nicojs Would you be able to send a pull request for this?

**Comment by rodoabad** [comment]
@nicojs @mantoni this is an interesting conversation as I was always under the impression that whenever you create a `stub`, `mock`, or a `spy` that it's always a good idea to restore after using it.

Perhaps we can improve the documentation some more.

**Comment by nicojs** [comment]
@roboabad That is the idea, but that wasn't the case with `sinon.stub` before v5.

Yes I can do a pr for this. I will try to do that in the coming week
