### ISSUE TITLE
Type error: cannot read property 'withArgs' of undefined when using with `rewire`

### ISSUE THREAD

**Issue by Sufiane** [sinonjs/sinon#1870]
**Describe the bug**
I try to rewire some private function to be able to stub it (for unit testing)

**To Reproduce**
index.js:
```js
const myPromisifiedFunction = promisify(someFunct.ToPromisify)
```
index.test.js:
```js
const myModule = rewire('../myModule')
const myStub = sinon.stub()
const myStubbedFunction = myModule.__set__('myPromisifiedFunction', myStub)
```

then in my test:
```js
myStubbedFunction().withArgs(/* my args*/).rejects(/* some code */)
```

But then I get a `Type error: cannot read property 'withArgs' of undefined`

**Expected behavior**
I expect to be able to pass the stub to rewire to be able to stub some private variables/functions without the need to export them, and to be able to specify with which args the stub should be triggered

**Context (please complete the following information):**

* Library version: `6.1.4`
* Other libraries you are using: `rewire`: `4.0.1`

Thanks in advance for any help you may provide !

**Comment by mroderick** [comment]
Your `sinon` specific code looks fine to me, this looks more like an issue with how `rewire` is being used. 

I don't know much about rewire, but this looks promising:

https://joost.vunderink.net/blog/2016/03/27/sinon-vs-rewire-when-do-i-use-which/

**Comment by Sufiane** [comment]
Thanks @mroderick for your help ! 

Indeed the problem was my use of the combination of `sinon` & `rewire`.

I'll post my solution for anyone facing the same problem or that are interested:

`rewire` `__set__` function actually return a function that can overturn what you did with it, so I should have had:
```
const myModule = rewire('../myModule')
const myStub = sinon.stub()
const revertSet = myModule.__set__('myPromisifiedFunction', myStub)
```

Then I simply use `myStub` to attach args condition or whatever when needed.
