### ISSUE TITLE
Filtered synchronous FakeXMLHttpRequest throw Exception

### ISSUE THREAD

**Issue by sebcanonica** [sinonjs/sinon#1873]
**Symptom**
Using a fake server, if I try to filter a request (to let it go through normally) which is sent synchronously, then sinon throw an exception:

In Chrome
Uncaught DOMException: Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document.
    at y.u.send (https://cdnjs.cloudflare.com/ajax/libs/sinon.js/6.1.4/sinon.min.js:1:113357)
    at window.onload (https://fiddle.jshell.net/_display/:36:9)

In Firefox
InvalidAccessError: synchronous XMLHttpRequests do not support timeout and responseType. sinon.min.js:1
[61]</</y.defake/u.send
https://cdnjs.cloudflare.com/ajax/libs/sinon.js/6.1.4/sinon.min.js:1:113343
window.onload
https://fiddle.jshell.net/_display/:36:1

**To Reproduce**
1. Go to https://jsfiddle.net/sebcano/czmhLrqf/7/
2. Open the console
3. Click on Run

```javascript
const server = sinon.fakeServer.create();
server.xhr.useFilters = true;
server.xhr.addFilter(() => true);
const request = new XMLHttpRequest();
request.open('GET', 'anything.html', false);
request.send();
console.log('Not reached');
```

**Expected behavior**
The request should be served normally and no exception should be thrown

**Context**

* Library version: 6.1.4
* Environment: Chrome, Firefox, Edge
* Example URL: https://jsfiddle.net/sebcano/czmhLrqf/7/
* Other libraries you are using: None

**Additional context**
The defake method put in place a send method which modify the responseType of the real xhr, which is forbidden for synchronous xhr not in a worker context.
If I comment out this line, the behavior is Ok.

**Comment by lddubeau** [comment]
I confirm having the same problem if I run Sinon 6. The problem goes away if I revert to the latest in the 5.x series.

The change was introduced by this PR in [nise](https://github.com/sinonjs/nise/pull/45), which then made its way to Sinon.

**Comment by mroderick** [comment]
Issue migrated to sinonjs/nise#61
