### ISSUE TITLE
stub(obj, method).callFake() not work when method is defined as Function

### ISSUE THREAD

**Issue by ShanaMaid** [sinonjs/sinon#1877]
**Describe the bug**
I have a module

modules.js
```
export async function test () {
    return 1;
}
```

test.js
```
import * as Module from 'modules.js';
sinon.createSandbox().stub(Module, 'test').callFakce(() =>  2);

Module.test() // 1 .    it's incorrect!
```

but if do this

modules.js
```
export const test = async () => {
    return 1;
}
```

test.js
```
import * as Module from 'modules.js';
sinon.createSandbox().stub(Module, 'test').callFakce(() =>  2);

Module.test() // 2 .    it's correct!
```

**Comment by fatso83** [comment]
This has nothing to do with Sinon. This has to do with module loaders and the details of which are outside of Sinon's hands. If you are using ES Modules (which you are when using `import`) then they are not supposed to be modifieable! Hence Sinon cannot change them. If you transpile using Babel to ES5 they will be trivially stubbable, or if you use ESM with CJS compat settings that should also work.

This does work fine in my tests when using the `esm` loader and the CJS compatibility settings. Check that out.
See https://github.com/fatso83/sinon-issues/compare/sinon-1877-esm-cjs-compat?expand=1
See https://github.com/fatso83/sinon-issues/compare/sinon-1877-esm-no-cjs-compat?expand=1

**Comment by ShanaMaid** [comment]
@fatso83  thanks!
