### ISSUE TITLE
Property stubbing on process.env in node throws

### ISSUE THREAD

**Issue by mantoni** [sinonjs/sinon#188]
`process.env` does not implement `hasOwnProperty`.

Reproduce on the node repl:

``` js
sinon.andbox.create().stub(process.env, 'HELL', 'froze over')
TypeError: Property 'hasOwnProperty' of object #<error> is not a function
    at Object.stub (/Users/max/projects/hub.js/node_modules/sinon/lib/sinon/collection.js:96:33)
```

Interestingly, stubbing the entire environment works.

``` js
sinon.andbox.create().stub(process, 'env', { 'HELL', 'froze over' })
{ restore: [Function] }
```

**Comment by LukasBombach** [comment]
I use a sandbox and also run into issues. To explain this: I require my AWS key and secret to be in my ENV vars. I have a function that tells me when a any of them are missing. So I want to set the `AWS_SECRET_ACCESS_KEY` to test if my function tells me  the `AWS_ACCESS_KEY_ID` is still missing:

```javascript
  describe('when I need the missing keys in the ENV vars', () => {
    let sandbox;
    beforeEach(() => { sandbox = sinon.sandbox.create(); });
    afterEach(() => { sandbox.restore(); });
    it('should return the key/value pair if AWS_ACCESS_KEY_ID is missing', () => {
      sandbox.stub(process.env, 'AWS_SECRET_ACCESS_KEY', 'some access key');
      S3Client.getMissingKeysInEnv().length.should.equal(1);
      // other assertions
    });
  });
```

what I get is

>      TypeError: Cannot stub non-existent own property AWS_SECRET_ACCESS_KEY

**Comment by Siilwyn** [comment]
Workaround is stubbing the whole environment, like:
```js
describe('when I need the missing keys in the ENV vars', () => {
  let sandbox;

  beforeEach(() => sandbox = sinon.sandbox.create());

  afterEach(() => sandbox.restore());

  it('should have mocked environment', () => {
    sandbox.stub(process, 'env', {SOME_KEY: 'some value'});
  });
});
```

**Comment by Siilwyn** [comment]
Since version 3 I can't get it to work any more, could you shed some light on this @cjohansen?

**Comment by fatso83** [comment]
@Siilwyn Please reopen a new issue. You can link to this discussion in the description field, but it is highly probable this is related to something entirely else, like #1512. 

Remember to provide a minimal snippet showing what worked before 3.0, but not after.
