### ISSUE TITLE
Sinon Fake Timers: setInterval() does not work as expected

### ISSUE THREAD

**Issue by ggsbv** [sinonjs/sinon#1888]
Sinon's implementation of setInterval() does not work when a string is supplied as the interval.

1. Open Node REPL in the terminal.
2. Do the following and observe the output
```
const sinon = require('sinon')
const clock = sinon.useFakeTimers()
const blah = () => console.log(Date.now())

// passing a string
setInterval(blah, '100')

clock.tick(100)
clock.tick(100)
clock.tick(100)

// passing an int
setInterval(blah, 100)

clock.tick(100)
clock.tick(100)
clock.tick(100)
```

**Expected behavior**
You would expect setInterval to return the intervalID value at each invocation, incrementing by 100 each time. You would expect the same behaviour in both scenarios, regardless of whether the interval value is a string or an integer.

**Screenshots**
![screen shot 2018-08-28 at 17 22 04](https://user-images.githubusercontent.com/20184132/44736358-ed958800-aae6-11e8-9927-ef6f4d909c84.png)

**Comment by fatso83** [comment]
This issue was moved to sinonjs/lolex#201

**Comment by fatso83** [comment]
@ggsbv Left you a note in the lolex repo. Hoping for the best :)
