### ISSUE TITLE
Mock expects breaks function

### ISSUE THREAD

**Issue by zveljkovic** [sinonjs/sinon#1896]
**Describe the bug**
Calling mock on object with functions (tested both regular and arrow functions) in newest TypeScript breaks the function.

**To Reproduce**
```
const zzz = {
  findAll(){ return [] },
};
const mock = sinon.mock(zzz);
mock.expects('findAll').once();
console.log('zzz findAll ', zzz.findAll());
```
logs "zzz findAll  undefined"
**Expected behavior**
To return []

**Context (please complete the following information):**

* Library version: "sinon": "^6.2.0",
* Environment: node 8 and node 10
* Other libraries you are using: typescript 3

**Comment by fatso83** [comment]
Usage error. Not a bug. 

You are expecting the mock to return the original value, but that is a false assumption. Check the [docs](https://sinonjs.org/releases/v6.2.0/mocks/):
> Expectations implement both the spies and stubs APIs.

That means you can regard an expectation as a stub. A stub does nothing unless you tell it to. So check out the [stub API for all the possible variations](https://sinonjs.org/releases/v6.2.0/stubs/).

What you want to achieve looks like this (btw, I have never used a mock in my life before, so I find it ab it confusing):

```javascript
mock.expects('findAll').once().callThrough()
```

**Comment by zveljkovic** [comment]
Thank you so much!
