### ISSUE TITLE
Both calledOnce and called return false on standalone function even though the stub was called

### ISSUE THREAD

**Issue by almostprogrammer** [sinonjs/sinon#1907]
I was trying to test a standalone function using Sinon, and faced the following issue: when I stub a function which is called inside another function and mock return value `calledOnce` does not work on a created stub. Here's the code I'm using

```
// bar.js
const bar = () => 5;

export default bar;

```

```
// foo.js
import bar from './bar';

const foo = x =>  x + bar();

export default foo;
```

And example.test.js

```
import { assert } from 'chai';
import * as sinon from 'sinon';
import * as barModule from '../funcs/bar';

import foo from '../funcs/foo';

describe('API test', function() {
  it ('should pass the test', function() {
    const stub = sinon.stub(barModule, 'default').returns(10);
    const result = foo(2);
    console.log(stub);
    assert(result === 12, 'result is not 12');
    assert(stub.calledOnce, 'stub is not called');
    stub.restore(); 
  });
}

```

I've also noticed that neither `called` nor `calledOnce` are set to `true`, but `notCalled` is actually `true`

**Expected behavior**
stub.calledOnce should return true

**Context**

* Library version: 6.3.4
* Environment: Node 10.8.0, Meteor 1.7.0.5
* Other libraries you are using: chai

**Comment by fatso83** [comment]
Your issue isn't Sinon, but your module system. Sinon doesn't deal with loaders.

Morgan wrote a howto you should read:
https://sinonjs.org/how-to/link-seams-commonjs/

**Comment by fatso83** [comment]
Basically, all your modules have resolved their imports before you start modifying them. Hence, no effect. You need to intercept the loader to modify the import.
