### ISSUE TITLE
Add utility methods to stub properties on a SinonStubbedInstance

### ISSUE THREAD

**Issue by g-arjones** [sinonjs/sinon#1911]
AFAICT (didn't find anything in the docs), the only way to stub a property on a SinonStubbedInstance is:

```typescript
class User {
    public name = "Gabriel";
}

const stub = sinon.createStubInstance(User);
stub.name = "John";
```

Which works fine, but if`name` is a readonly property I get:

```
[ts] Cannot assign to 'name' because it is a constant or a read-only property.
```

Am I missing something?

**Comment by fatso83** [comment]
Looks like you are using TypeScript, obscuring what is really happening under the hood. I suggest you put the code in the [Playground](http://www.typescriptlang.org/play/) and see what code is generated and how you can attack that. All `createStubInstance` does is return a plain object with a stub in place for each property in the constructor's prototype.

--- 

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
