### ISSUE TITLE
Error installing latest version of SinonJS, @sinonjs/samsam@^2.1.2 is not available on the NPM registry

### ISSUE THREAD

**Issue by drochgenius** [sinonjs/sinon#1914]
**Describe the bug**
Error when installing latest version of `sinon@6.3.5` on Node 10.10.0, with NPM 6.4.1.

Dependency `@sinonjs/samsam@^2.1.2` version is not available from NPM registry.

Package

**To Reproduce**

Run `npm install`, an error is thrown:

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @sinonjs/samsam@^2.1.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'sinon'
npm ERR! notarget
```

**Expected behavior**
SinonJS installs from NPM without issue.

**Additional information**

Running `npm view @sinonjs/samsam`, I get that the latest published version is `2.1.1`.

```bash
@sinonjs/samsam@2.1.1 | BSD-3-Clause | deps: 1 | versions: 3
Value identification and comparison functions
http://sinonjs.github.io/samsam/

dist
.tarball: https://registry.npmjs.org/@sinonjs/samsam/-/samsam-2.1.1.tgz
.shasum: f352621c24c9e9ab2ed293a7655e8d46bfd64c16
.integrity: sha512-7oX6PXMulvdN37h88dvlvRyu61GYZau40fL4wEZvPEHvrjpJc3lDv6xDM5n4Z0StufUVB5nDvVZUM+jZHdMOOQ==
.unpackedSize: 57.6 kB

dependencies:
array-from: ^2.1.1

maintainers:
- cjohansen <christian@cjohansen.no>
- fatso83 <carlerik@gmail.com>
- mantoni <mail@maxantoni.de>
- mrgnrdrck <morgan@roderick.dk>
- peer5 <opensource@peer5.com>

dist-tags:
latest: 2.1.1

published 2 weeks ago by mrgnrdrck <morgan@roderick.dk>
```

**Comment by mroderick** [comment]
That’s odd. Are you using a proxy of sorts?

Both Travis CI and Circle CI were able to install latest samsam, so I think we can rule out the registry as the root cause.

**Comment by drochgenius** [comment]
Thanks for the quick answer.
Just tried again now, and it works fine.
Maybe some momentary glitch on the NPM registry.
I am not using a proxy.

Closing the ticket now.

Thanks
