### ISSUE TITLE
sinon.mock().expects().atLeast() ... expectation.verify() not working

### ISSUE THREAD

**Issue by gianisegatto** [sinonjs/sinon#1921]
**Describe the bug**
Sinon 6.3.5
expects.verify(); is not working as expected.

**To Reproduce**

**Component to be tested**
```javascript
module.exports = {

    handle: function(promise, res, next, okHttpStatus) {
        promise
            .then(payload => res.status(okHttpStatus ? okHttpStatus : 200).send(payload))
            .catch(exception => next(exception));
    }
};
```

**Unit test**
```javascript
const expect = require("chai").expect;
const sinon = require("sinon");
const routerPromiseHandler = require("../../../main/node/handler/PromiseHandler");

describe("Should handle promisse", () => {

    it("should handle success promise return", () => {

        const successMessage = {message: "Success"};

        const promiseTest = new Promise((resolve, reject) => {
            resolve(successMessage);
        });

        let res = {
            status: function() {},
            send: function() {}
        };

        const mockRes = sinon.mock(res);
        const expectStatus =  mockRes.expects("status").withExactArgs(200).atLeast(1)
        const expectSend =  mockRes.expects("send").withExactArgs(successMessage).atLeast(1)
        
        const spyNext = sinon.spy();

        routerPromiseHandler.handle(promiseTest, res, spyNext, 200);

        expectStatus.verify();
        expectSend.verify();

    });
});
```

**Describe the bug**
Is this way of checking if a method was called correct? I'm trying to see the best way to do that, but I couldn't find any example.

**Comment by gianisegatto** [comment]
Debugging the code I've found this error as well:
TypeError: Cannot read property 'send' of undefined.
Is there any way to do this in a better way?

**Comment by fatso83** [comment]
I don't see that you actually show anything wrong with Sinon, so this seems more like a usage scenario, for which this is the wrong forum.

---
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
