### ISSUE TITLE
spy.reset does not exist

### ISSUE THREAD

**Issue by schontz** [sinonjs/sinon#1922]
**Describe the bug**
The [documentation says](https://sinonjs.org/releases/v4.0.0/spies/#spyreset) that I can reset the state of a spy by calling `spy.reset()`, but `reset()` does not exist. I found `spy.resetHistory()` by inspecting the spy in Node and it appears to do what `reset()` does.

**To Reproduce**
```js
sinon = require('sinon');
sinon.spy().reset // == undefined
sinon.spy().resetHistory // == function
```

**Expected behavior**
I expect `spy.reset()` to exist and work because the docs say it does.

**Context (please complete the following information):**

* Library version: 6.3.5
* Environment: Node
* Other libraries you are using: none

**Comment by mgred** [comment]
@schontz The documentation you're using is for the version `4.0.0`. Please refer to this [docs](https://sinonjs.org/releases/v6.3.5/spies/) for version `6.3.5`.

**Comment by schontz** [comment]
Ah. I should rename this bug to:

A Google search for `sinon spy` brings you to 4.0 documentation, which says nothing at the top that it is out of date/old/etc. Please add something to the top of non-latest docs to indicate that I may be at the wrong place.
