### ISSUE TITLE
Put banner at the top of old documentation pages

### ISSUE THREAD

**Issue by schontz** [sinonjs/sinon#1923]
**Is your feature request related to a problem? Please describe.**
I was having issues writing sinon tests because Google search results link to old docs (e.g. `sinon spy` results point to `4.0.0` docs; see #1922).

**Describe the solution you'd like**
Old documentation should at the very least have a big banner at the top pointing me to the latest version of the docs. Better yet, if the referrer is a search engine it should redirect me straight to the latest version.

**Comment by fatso83** [comment]
This is something me and Morgan discussed in an exchange last year, but time constraints keep us from getting there. I absolutely feel your pain, though. It's good you brought it up again, as that shows it's not just a theoretical exercise, but a problem that actually needs addressing.

The time issue is still what's blocking progress, so if you can supply a PR to our docs site that is infinitely more valuable than a thousand :+1:'s.

The non-silly/non-sensitive parts of our Twitter exchange might serve as the food-for-thought to an actual solution:
![redirect-to-latest](https://user-images.githubusercontent.com/618076/46792098-cfa47f80-cd42-11e8-9992-f88682ec13f3.png)
![alert](https://user-images.githubusercontent.com/618076/46792097-cfa47f80-cd42-11e8-8a6b-664b9c5942dc.png)

The urls I refer to are these:
- https://webmasters.stackexchange.com/questions/99867/how-to-correctly-mark-up-different-versions-of-the-same-document-which-are-non-c/101534#101534
- https://webmasters.stackexchange.com/questions/109113/versioned-pages-making-sure-google-points-to-the-current

**Comment by schontz** [comment]
Wow, there's a lot to this. I think a simple banner on old doc pages is the low-hanging fruit on this one.

**Comment by fatso83** [comment]
Seemingly. I actually think the implementation effort for the non-banner stuff is easier than making a decent banner, so each to his own :grin: If you - or anyone really - can put together something half-decent in their lunch, we would love to have it :-)

**Comment by fatso83** [comment]
I am doing the `rel=canonical` stuff now to fix the search hits.

**Comment by schontz** [comment]
I don't have time for a PR, but this is something simple. Assuming there is a way to make a link to /latest/ you only need to update the next-to-latest version of the docs when you create a new one.

HTML:
```html
<!-- place right after opening body tag -->
<div class="bg-info" id="banner-message">
These docs are from an older version of sinon.
Do you want the <a href="/url/to/latest">latest</a> docs?
</div>
```

CSS:
```css
#banner-message {
  position: sticky;
  z-index: 400;
  left: 0;
  top: 0;
  right: 0;
  text-align: center;
  padding: 1em;
}
```

**Comment by fatso83** [comment]
Thanks for the suggestion! It's now live in the #1927 PR, along with all the SEO.

**Comment by schontz** [comment]
Wonderful!
