### ISSUE TITLE
Make spy properties non-enumerable

### ISSUE THREAD

**Issue by ehmicky** [sinonjs/sinon#1936]
**Is your feature request related to a problem? Please describe.**
When a Sinon spy assertions fails during unit testing, some assertion libraries like `power-assert` (used by Ava) will print all the spy properties (including the spy methods) which is very verbose and makes it harder to see why the test failed. 

**Describe the solution you'd like**
Make Sinon-specific spy properties non-enumerable.

**Describe alternatives you've considered**
  - customizing the assertion library `power-assert` but it's hard to do from Ava
  - customizing Ava but it's not possible because it directly relies on `power-assert` for this case
  - overriding `spy[Symbol.toStringTag]` or `spy.toJSON()` but this does not work since `power-assert` does not use either. Instead it iterates over enumerable properties.

**Additional context**
The feature request is about spies, but it most likely can be related to other Sinon objects, such as stubs and fakes.

Here's a screenshot of how verbose a single test Sinon assertion can become with Ava:

![enumerable_properties](https://user-images.githubusercontent.com/8136211/47487808-6bee7c00-d843-11e8-9f2a-ed7b1ef798ab.png)

**Comment by fatso83** [comment]
How would this affect REPL usage and API discoverability? One of my favorite ways of using new tech is through exploratory testing on  the REPL. Doing `var spy = sinon.spy(); spy.` and then <tab>ing my way through the various methods. Would this still work?

**Comment by ehmicky** [comment]
Yes, non-enumerable properties are still shown on tab autocomplete in Node.js REPL.

**Comment by mroderick** [comment]
This has been implemented with #1936 and released as `sinon@7.1.1`

**Comment by ehmicky** [comment]
Thanks for this.

However I do not think this worked:

```js
> sinon.spy()
{ [Function: proxy]
  isSinonProxy: true,
  called: false,
  notCalled: true,
  calledOnce: false,
  calledTwice: false,
  calledThrice: false,
  callCount: 0,
  firstCall: null,
  secondCall: null,
  thirdCall: null,
  lastCall: null,
  args: [],
  returnValues: [],
  thisValues: [],
  exceptions: [],
  callIds: [],
  errorsWithCallStack: [],
  displayName: 'spy',
  toString: [Function: toString],
  instantiateFake: [Function: create],
  id: 'spy#0' }

> Object.keys(sinon.spy())
[ 'isSinonProxy',
  'called',
  'notCalled',
  'calledOnce',
  'calledTwice',
  'calledThrice',
  'callCount',
  'firstCall',
  'secondCall',
  'thirdCall',
  'lastCall',
  'args',
  'returnValues',
  'thisValues',
  'exceptions',
  'callIds',
  'errorsWithCallStack',
  'displayName',
  'toString',
  'instantiateFake',
  'id' ]
```

As a consequence the original problem still arises.

**Comment by mroderick** [comment]
@ehmicky which version of `sinon` are you using to produce that output?

**Comment by ehmicky** [comment]
I am using Sinon `7.1.1`, Node `11.3.0`, Ubuntu `18.10`.

**Comment by ehmicky** [comment]
Bumping because this issue is still valid.

**Comment by fatso83** [comment]
Ah, @LouisBrunner explicitly just made the _functions_ non-enurable. The other non-function properties are still enumerable. Don't you still want to see those props?

**Comment by fatso83** [comment]
To make the props non-enurable, as well, you would have to use `Object.defineProperties` on the list of props that are created [here](https://github.com/LouisBrunner/sinon/blob/ae0b95c49ba1a1994d10d9f78313f40d3cabffea/lib/sinon/spy.js#L176).

Seems quite doable. Feel up to it, @ehmicky? A lot more likely it will be done if you are scratching your own itch :-)

**Comment by ehmicky** [comment]
Here you go: #1975
