### ISSUE TITLE
Feature Request: Make APIs extensible

### ISSUE THREAD

**Issue by mearns** [sinonjs/sinon#1937]
I'd like to be able to provide custom extensions to some of the APIs available in sinon, particularly the spy and spyCall APIs. This is somewhat analogous to the way [chaijs](https://www.chaijs.com/guide/plugins/) allows for plugins to define new assertions.

This would be useful, for instance, if you want to create convenience methods for asserting on calls with particular signatures. The example that inspired this is that I have a logging method that looks like `log(level, timestamp, message, metadata)`, and I want to spy on it and make assertions about how it is called, but there are many cases where I don't care about the specifics of the timestamp or metadata. Instead of having to pass in appropriate matchers to `spyCall.calledWith`, I could add a more convenient and more explicit method to the spyCall API such as:

```javascript
function loggedCritical (message, meta = sinon.match.any) {
    return this.calledWith('CRITICAL', sinon.match.date(), message, meta)
}
```
I would expect to be able to install this into the framework a la `chai.use`, something like:

```javascript
sinon.use(function (apis, extend) {
    extend(apis.spyCall, {
        loggedCritical: loggedCritical
    })
})
```

However, since these convenience functions will frequently be specific to a particular function (or family of functions), it would be useful to be able to install the extension on a specific spy, something like:

```javascript
var spy = sinon.spy()
spy.use(function (apis, extend) => {
    extend(apis.spyCall, {
        /* ... etc ... */
    })
})
```

Then any spyCalls created by that spy specifically, would use the extended API, but not other spies.

**Comment by fatso83** [comment]
If we had something like that we could trim away all of the non-essential (whatever they might be) method on the API and have that as a `sinon-extras` package or something. Then keeping the core in ship shape might prove easier. So this _sounds_ good, but I am unsure how easy this is.

**Comment by mroderick** [comment]
I've had [similar ideas for referee](https://github.com/sinonjs/referee/issues/19), although I envisioned a different way of plugging them in. Feedback welcome!

Referee already has an extension mechanism, which allows authors to plug in custom assertions. However, it is not very elegant and leads to having to import referee via a wrapper that installs the assertions. I'd like to make that much nicer.

If you're already using referee, then you could create custom assertions for that, which would do what you want. That might tide you over, while we discuss this suggestion.
