### ISSUE TITLE
deprecated text-encoding@0.6.4: no longer maintained

### ISSUE THREAD

**Issue by JustinBeckwith** [sinonjs/sinon#1940]
Greetings folks!  When running `npm install`, I'm getting an error letting me know that text-encoding is no longer maintained :)

```
nodejs-repo-tools (master) $ npm install
npm WARN deprecated text-encoding@0.6.4: no longer maintained
```

Details on my setup:
```
node: v10.10.0
npm: v6.4.1
sinon: v7.1.0
```

Looks like it's coming in from nise:

```
nodejs-repo-tools (master) $ npm ls text-encoding
@google-cloud/nodejs-repo-tools@2.3.5 /Users/beckwith/Code/nodejs-repo-tools
└─┬ sinon@7.1.0
  └─┬ nise@1.4.6
    └── text-encoding@0.6.4 
```

**Comment by fatso83** [comment]
Yup. We know :-) Already reported in its rightful place: sinonjs/nise#66

As the issue says, we need to either become the maintainer (or incorporating parts into Nise) or find a replacement.

Thanks for the report!
