### ISSUE TITLE
myStub.getCall(0).args[0] overrided by myStub.getCall(1).args[0]

### ISSUE THREAD

**Issue by tcarecolin** [sinonjs/sinon#1943]
* Sinon version : 6.1.4
* Environment   : node 10.0.0
* Other libraries you are using: chai, jest

**What did you expect to happen?**
I expect the firstCall arguments to be different than the secondCall if the same function is called with a slight difference in the call arguments (the function is called with only an object as parameters).
i.e: inside a loop we call the stubbed function then we add a property onto the object with used as parameters for the function call

```js
forEach(something....) {
     const myParam = {
        p1: 'property1',
     }
    const result = myStubbedFunction(myParam)
    const myParam2 = {
        p1: 'property1',
        p2: 'property2'
     }
   const result2 = myStubbedFunction(myParam2) 
}
```

**What actually happens**
I get exactly the same arguments for each of those 2 calls. 

**How to reproduce**
https://jsbin.com/xefuvof/edit?js,console

**Comment by mroderick** [comment]
Edited the description to use Markdown fenced blocks, which respects whitespace and supports syntax highlighting.

**Comment by mroderick** [comment]
The linked runnable example on jsbin is not runnable. Could you provide a runnable example? Perhaps as a git repository?

**Comment by fatso83** [comment]
Try [RunKit](https://npm.runkit.com), it's like JSBIN, just for Node. Managed to get your code running, after removing your dependency on local modules, but not while reproducing the issue ...
