### ISSUE TITLE
sinon.createStubInstance has no restore method?

### ISSUE THREAD

**Issue by epikhighs** [sinonjs/sinon#1945]
**Describe the bug**
I created a stub using sinon.createStubInstance(), but the returned stub has no restore method.  Is this by design?  I don't need to teardown a stub created with sinon.createStubInstance() ?

**To Reproduce**
let stub = sinon.createStubInstance(SomeConstructor);
stub.restore();

**Expected behavior**
stub.restore() is on the returned stub

* Library version: _please verify that the bug exists in the latest release_
* Environment: win 10 
sinon 7.1.1

**Comment by fatso83** [comment]
From the docs:
> If you want to create a stub object of MyConstructor, but don’t want the constructor to be invoked, use this utility function.

Since you are not modifying anything, there is nothing to restore.
