### ISSUE TITLE
Please add a CHANGELOG.md to the project root

### ISSUE THREAD

**Issue by adrianschmidt** [sinonjs/sinon#1946]
Finding the changelog for this project is a pain because you have no `CHANGELOG.md` in the project root. It would be very helpful if such a file was added, even if it just contained a link to `History.md`.

**Comment by mroderick** [comment]
It probably took you less time to find, than to create a new issue in this repository.

If you still feel this is important, how about creating a PR?

You'll want to:

* Rename `History.md` to `CHANGELOG.md`
* Update `scripts/preversion.sh` to instruct `git changelog` to use the desired filename

**Comment by adrianschmidt** [comment]
Sure, will do!

(Sorry for the late response.)

**Comment by mroderick** [comment]
This has been fixed with #1953 👍
