### ISSUE TITLE
Sinon stub typings error

### ISSUE THREAD

**Issue by saarkuriel** [sinonjs/sinon#1949]
**Describe the bug**
Since `@types/sinon: 5.0.6` stubs are getting typescript error: `Cannot invoke an expression whose type lacks a call signature`

**To Reproduce**
1. Install `@types/sinon` @ 5.0.6
2. Create a stub and return value, e.g: `sinonSession.stub(UUID, 'v4').returns('ID');`

**Expected behavior**
No typescript error

**Context (please complete the following information):**

* Library version: 6.3.5
* Environment:  node 8.11.2
* Other libraries you are using:
`@types/sinon: 5.0.6`
`typescript: 2.8.3`

If there's a new way of declaring stubs I'd like to know.
As a temporary solution for me I'm going back to 5.0.5

Thanks a lot

**Comment by mroderick** [comment]
Sinon.JS is a JavaScript project and does not maintain any TypeScript (or other non-JavaScript) artefacts.

Please report the issue where you get your type definitions, probably at https://github.com/DefinitelyTyped/DefinitelyTyped
