### ISSUE TITLE
createStubInstance override and null return values

### ISSUE THREAD

**Issue by spicalous** [sinonjs/sinon#1957]
**Describe the bug**
`sinon.createStubInstance` was extended recently to allow overrides such as:
```
sinon.createStubInstance(AClass, {
  aMethod: "a string",
  aChainableMethod: sinon.stub().returnsThis()
});
```
Theres a small issue which prevents a user from returning null values

**To Reproduce**
```
sinon.createStubInstance(AClass, {
  aMethod: null
});
```

**Expected behavior**
The library should correctly create a stub instance with a stub method returning null

**Reason**
Theres an initial check whether the override is a stub by checking if `createStubInstance` property exists on the return value https://github.com/sinonjs/sinon/blob/master/lib/sinon/stub.js#L85

This throws when we try to check a property of null

**Context (please complete the following information):**

* Library version: Current latest v7.x
* Environment: OSX

Thanks!
Let me know if it makes sense, I can help create a PR for it

**Comment by mroderick** [comment]
Thank you for your detailed analysis of the bug, it looks like an interesting one!
A pull request would be very welcome 👍
