### ISSUE TITLE
custom matchers value is undefined when using .withArgs(...)

### ISSUE THREAD

**Issue by dueyfx** [sinonjs/sinon#1960]
**Describe the bug**
It appears that using custom matchers in combination with .withArgs(...) has broken in release 7.2.0.  It works in release 7.1.1 

**To Reproduce**
Here's a simple example of the usage.  With release 7.2.0, the `value` in the sinon.matcher function is undefined. 
```
class MyClient {
  doTheStuff(myRequest: MyRequest) {
    console.log('you should not see this', myRequest);
  }
}

interface MyRequest {
  theString: string;
  theBool: boolean;
}

const client = new MyClient();

const methodToTest = (option1: boolean, option2: boolean) => {
  let myreq: MyRequest;
  if (option1 && option2) {
    myreq = {
      theString: 'success',
      theBool: true
    };
  } else {
    myreq = {
      theString: 'failure',
      theBool: false
    };
  }
  client.doTheStuff(myreq);
};

describe('methodToTest', () => {
  let mockClient;
  beforeEach(() => {
    mockClient = sinon.mock(client);
  });

  afterEach(() => {
    mockClient.restore();
  });

  it('when both options true, call client with success request', () => {
    mockClient.expects('doTheStuff').once().withArgs(
      sinon.match((value) => {
        console.log('matcherValue:', value);
        return value.theString === 'success' && value.theBool === true;
      })
    );
    methodToTest(true, true);
  });

  it('otherwise, call with failure request', () => {
    mockClient.expects('doTheStuff').once().withArgs(
      sinon.match((value) => {
        console.log('matcherValue:', value);
        return value.theString === 'failure' && value.theBool === false;
      })
    );
    methodToTest(false, true);
  });
});
```

**Expected behavior**
I expect that when the mock is called in the code, it will pass the arg to the sinon matcher to evaluate whether the arg is correct.

**Screenshots**
Test Run with Release 7.2.0 (FAILS)
<img width="655" alt="screen shot 2018-12-11 at 11 13 23 am" src="https://user-images.githubusercontent.com/45797651/49819476-2a565980-fd3b-11e8-8853-fdcc83638423.png">

Test Run with Release 7.1.1 (SUCCEEDS)
<img width="447" alt="screen shot 2018-12-11 at 11 13 11 am" src="https://user-images.githubusercontent.com/45797651/49819486-33dfc180-fd3b-11e8-9da5-4a634cf34a9a.png">

**Context (please complete the following information):**

* Library version: _7.2.0_ (loading using yarn/npm)
* Environment: nodejs8.10
* Example URL: none
* Other libraries you are using: Mocha, Typescript

**Comment by mantoni** [comment]
Patch released in `7.2.2`.
