### ISSUE TITLE
callThrough doesn't work on a withArgs sub-stub

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [sinonjs/sinon#1964]
**Describe the bug**

#1442 was not fully fixed by #1549.  The case of using stubs directly instead of with mocks and expectations, as shown in https://github.com/sinonjs/sinon/issues/1442#issuecomment-306330402, is still broken.

**To Reproduce**
This code will throw an exception `TypeError: Cannot read property 'apply' of undefined` due to the fake returned from `withArgs` not having a `wrappedMethod` member.
```javascript
let stub = sinon.stub(obj, 'method')
	.withArgs(123)
	.returns('bar')
	.callThrough();
obj.method('bar')
```

**Expected behavior**
The `callThrough` behavior should be available on `withArgs` fakes.

**Screenshots**

**Context (please complete the following information):**

* Library version: Verified with `6.3.4` and `master` at `97a12178`
* Environment: Linux Node 10.x
* Example URL: N/A
* Other libraries you are using: N/A

**Additional context**

I've prepared a test case demonstrating the issue:
https://github.com/sinonjs/sinon/compare/master...mgabeler-lee-6rs:issue-1964

**Comment by mroderick** [comment]
That's a nice test ✨ 

Would you like to contribute a PR to fix it?

**Comment by mgabeler-lee-6rs** [comment]
I had started looking into that at first, but didn't understand sinon's internals well enough to do so.  If I have time to figure that out, I'd happily do so, but TBH I don't see that happening in the next couple weeks, so if someone else wants to go for it in the meantime, that's fine with me.  If not, I'll try to revisit this when I have time :)

**Comment by mgabeler-lee-6rs** [comment]
Had some time to dig into this finally today, filed #2012 with a proposed fix

**Comment by fatso83** [comment]
Very nice work <3
