### ISSUE TITLE
Upgrading to Sinon v7.2.2: Possible JSON issue

### ISSUE THREAD

**Issue by daniel-onodje** [sinonjs/sinon#1966]
**Describe the bug**

When I emit a event using EventEmitter, the payload being a JSON stringified  class instance, on listening to that event and parsing the payload, the received and parsed payload and the original event are not seen as the same.

This code works as expected with `sinon` v7.1.1 but fails with `sinon` v7.2.2
The code is supplied as a gist https://gist.github.com/daniel-onodje/d1b1079cc038ca9511360669593e991b

Caveats:
I'm using `sinonChai`'s `calledWith` matcher to compare.

**To Reproduce**
Please look at the linked github gist

**Expected behavior**
Test passes

**Screenshots**

fails on 7.2.2

![image](https://user-images.githubusercontent.com/45559328/50902034-1b39f880-141a-11e9-9aab-d4774465cdf0.png)

passes on 7.1.1

![image](https://user-images.githubusercontent.com/45559328/50902088-43295c00-141a-11e9-85d1-3c818360d728.png)

**Context (please complete the following information):**

* Library version: 7.2.2
* Environment: `node v8.9.4` `npm v5.6.0`
* Example URL: https://gist.github.com/daniel-onodje/d1b1079cc038ca9511360669593e991b

* Other libraries I'm using:
     - chai
     - sinon-chai
     - mocha
     - eslint

**Additional context**

**Comment by mantoni** [comment]
This is working as designed and as it should be. You're comparing an `Event` instance with a plain object. These are neither the same nor equal.

You could change your assertion to `expect(evtCallback).to.be.calledWith({ field1: "FIELD_1" );`.
