### ISSUE TITLE
Argument of type is not assignable to parameter of type 'never'.

### ISSUE THREAD

**Issue by jose920405** [sinonjs/sinon#1972]
After upgrade the module to `"7.2.3"` and types to `"7.0.4"`, this error began to appear.

Code: 

```
const stubPermissions = sinon.stub(Permissions, 'request');
stubPermissions.resolves('denied'); => Error here.
```

> **Argument of type '"denied"' is not assignable to parameter of type 'never'.**

**Context**

* Library version: **"7.2.3"**
* Other libraries you are using: **"typescript": "3.2.4"**
____
**React Native Environment Info:**
```    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
      Memory: 32.61 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by mgred** [comment]
@jose920405, Sinon and its subprojects do not support Typesscript! 
These types are provided via [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). If there seem to be some differences between the current release and their types, please create an issue there.
