### ISSUE TITLE
calledWith ignores symbols used as property keys

### ISSUE THREAD

**Issue by BrandonE** [sinonjs/sinon#1974]
**Describe the bug**
Asserting `calledWith` ignores mismatched properties if they keys are [JavaScript symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol).

**To Reproduce**
```
var sinon = require('sinon');
var mock = sinon.mock();

mock({
    [Symbol("a")]: true
});

sinon.assert.calledWith(
    mock,
    {
        [Symbol("a")]: false
    }
);
```

**Expected behavior**
The above script should throw an `AssertError` because the mock was called with an object containing a `true` value when we were expecting a `false` value. It should behave similarly to this example that uses non-symbolic keys:

```
var sinon = require('sinon');
var mock = sinon.mock();

mock({
    a: true
});

sinon.assert.calledWith(
    mock,
    {
        a: false
    }
);
```

![image](https://user-images.githubusercontent.com/542245/52183117-4ff76080-27ca-11e9-802d-42f6246ca68e.png)

**Context (please complete the following information):**

* Library version: 7.2.3
* Environment: Node.js v10.8.0
* Other libraries you are using: None; I reproduced this issue in a newly initialized npm project.

**Additional context**
I started working on a solution, but I wanted to raise an issue before opening pull requests like the [contributing guide](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#contributing-to-the-code-base) suggests to make sure I'm going down the right path. Using [this change for samsam](https://github.com/sinonjs/samsam/compare/master...BrandonE:symbolic-keys) and [this change for formatio](https://github.com/sinonjs/formatio/compare/master...BrandonE:symbols), I get the behavior I expected for the script in the _To Reproduce_ section:

![image](https://user-images.githubusercontent.com/542245/52183166-b4b2bb00-27ca-11e9-831d-ba1304b6a1ca.png)

Because symbols are [unique](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Description), this:

```
var sinon = require('sinon');
var mock = sinon.mock();

mock({
    [Symbol("a")]: true
});

sinon.assert.calledWith(
    mock,
    {
        [Symbol("a")]: true
    }
);
```

will throw an `AssertError` (thanks @pettyalex for pointing this out):

![image](https://user-images.githubusercontent.com/542245/52216644-5a623a80-285c-11e9-93b9-bcae366283f2.png)

This, however, will not throw an `AssertError`:

```
var sinon = require('sinon');
var mock = sinon.mock();

const symbol = Symbol("a");

mock({
    [symbol]: true
});

sinon.assert.calledWith(
    mock,
    {
        [symbol]: true
    }
);
```

Unfortunately, the samsam change breaks [one unit test](https://github.com/sinonjs/samsam/blob/master/lib/deep-equal.test.js#L425):

![image](https://user-images.githubusercontent.com/542245/52183207-39053e00-27cb-11e9-9b15-9cd47c9dced4.png)

This is because `arguments` has a property symbol called `iterator`:

```
> function test() { return Object.getOwnPropertySymbols(arguments) } test();
[ Symbol(Symbol.iterator) ]
```

**Comment by mantoni** [comment]
Thank you for putting this detailed analysis and code changes together. We're definitely lacking proper Symbol support in Sinon and should do something about it.

Regarding your suggested solution, I think the fix should be slightly different: I'd say we should check the expectation for any symbol properties and only compare those to the actual. This means that additional symbol properties being added to the actual object do not break existing assertions. If we want to enforce strict matching of all symbols, then this would be a breaking change, because Sinon never looked at symbol properties before.

Any opinions or other ideas @sinonjs/sinon-core?

**Comment by BrandonE** [comment]
I like your suggestion. I'll put that solution together and open a PR for both samsam and formatio.

**Comment by mroderick** [comment]
That's some very detailed analysis, thank you ❤️ 

I like the proposed solution that doesn't break existing assertions 👍

**Comment by BrandonE** [comment]
@mantoni @mroderick [samsam](https://github.com/sinonjs/samsam/pull/64) and [formatio](https://github.com/sinonjs/formatio) pull requests for your consideration. Although I implemented the proposed solution and all existing unit tests pass, I still have concerns about the backwards compatibility of the samsam change, which I detail in the solution section.

**Comment by BrandonE** [comment]
Resolved by https://github.com/sinonjs/samsam/pull/64
