### ISSUE TITLE
[QUESTION] - console spy not catching log

### ISSUE THREAD

**Issue by jamessouth** [sinonjs/sinon#1977]
Hello, I posted this question [on SO](https://stackoverflow.com/questions/54639482/testing-js-esm-project-w-sinon-nyc-and-ava-test-w-spy-on-console-fails-desp) a couple of days ago but no answers yet, and it looks like you have ended the google group.  In my node/esm project testing with ava, nyc and sinon I'm not sure why my spy on console.log isn't noticing a log to the console.

* Sinon version : 7.2.3
* Environment   : `node` 10.15.1, `npm` 6.5.0, windows 10
* Other libraries you are using: `esm` 3.2.4, `nyc` 13.2.0, `ava` 1.2.1

**What did you expect to happen?**
In another part of my project I have successfully spied on console.log for call counts and args passed and here I expected the same - acknowledgement via callCount that a message was logged to the console.

**What actually happens**
callCount is 0 instead of 1, notCalled is true

**How to reproduce**

test [repo here](https://github.com/jamessouth/test-issue-repo)

**Comment by jamessouth** [comment]
Getting somewhere! The test passes when you comment out the import statement in main, so I guess this has something to do with `esm` so I will close this for now.

**Comment by fatso83** [comment]
@jamessouth You might find a lot of info on this issue [here](https://github.com/sinonjs/sinon/issues/1819#issuecomment-394772106) and on [this follow-up on Stackoverflow](https://stackoverflow.com/questions/50763323/stub-a-function-from-a-es6-module-without-babel). The setup is quite similar (ES6, Ava, ESM).

**Comment by jamessouth** [comment]
thank you @fatso83 this issue was actually caused by a bug in `esm` which has since been fixed with the 3.2.5 release
