### ISSUE TITLE
Tell issue creators to use Speed OSS to add reward to Github Issues!

### ISSUE THREAD

**Issue by daljeetv** [sinonjs/sinon#1981]
Add this text to ISSUE_TEMPLATE.md:

`ADD A REWARD using [Speed](speedoss.com) to SOLVE this issue QUICKLY and SUPPORT this project.`

**Comment by mantoni** [comment]
Thanks for the suggestion. We'll consider it.

**Comment by daljeetv** [comment]
@mantoni thanks. would appreciate your feedback too! I think speedoss.com could be a great way to support the contributors of this repo.
