### ISSUE TITLE
Sinon Spy calledOnce is not working

### ISSUE THREAD

**Issue by Mukesh23singh** [sinonjs/sinon#1982]
**Describe the bug**
I'm Using puppeteer module and trying mock page behavior which is a subclass of eventEmitter. 
The source code for this code is at https://github.com/Mukesh23singh/puppeteer-unit-testing 

**To Reproduce**
1. Clone the repo and do npm install 
2. Run npm t

**Expected behavior**
I am used spy feature of sinon to spy function to check if it is got called or not. the function is getting called, but the spec are getting failed 

* Environment: Node 8.11.3, 

  "dependencies": {
    "@types/mocha": "^5.2.6",
    "@types/node": "^11.9.4",
    "chai": "4.1.2",
    "mocha": "4.1.0",
    "puppeteer": "^1.12.2",
    "sinon": "4.2.2",
    "ts-node-register": "^1.0.0",
    "typescript": "^3.3.3"
  }

https://stackoverflow.com/questions/54784426/puppeteer-mock-page-request-object

**Comment by fatso83** [comment]
Not a bug in Sinon. Told you why in the SO answer. You need to check out Mocha's support for [async support](https://mochajs.org/#asynchronous-code).
