### ISSUE TITLE
ExperimentalWarning: queueMicrotask() is experimental.

### ISSUE THREAD

**Issue by brunorozendo** [sinonjs/sinon#1985]
**Describe the bug**
A warning is throwed by just import `sinon`
```
(node:15479) ExperimentalWarning: queueMicrotask() is experimental.
  <Root />
    ✓ calls componentDidMount

```

**To Reproduce**
Just import sinon
```
import sinon from 'sinon';
```
or
```
const sinon = require('sinon');
```

**Expected behavior**
No warning 

**Context (please complete the following information):**

* Library version: _7.2.4_ and _7.2.5_
* Environment:
```
$ node -v      
v11.10.0
$ npm -v 
6.8.0
$ uname -a
Linux fedora 4.20.11-200.fc29.x86_64 #1 SMP Wed Feb 20 15:56:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by fatso83** [comment]
This is sinonjs/lolex#232. Since this isn't really a functional bug impacting anything, I don't see why we should duplicate the issue here.  Follow the lolex issue for updates (it has seen work by @shdq).

**Comment by fatso83** [comment]
With lolex 4 out and included in the latest Sinon, this warning should not show itself, unless explicitly triggered by using queueMicrotask()
