### ISSUE TITLE
`lastArg` is set to undefined when last argument is `false`

### ISSUE THREAD

**Issue by davidpaulhunt** [sinonjs/sinon#1986]
**Describe the bug**
When using fakes, `lastArg` is set to `undefined` whenever the last argument passed is `false`.

The primary issue is in `fake.js#wrapFunc` where the assignment is using `&&` -
```js
var lastArg = (arguments.length > 0 && arguments[arguments.length - 1]) || undefined;
```
`lastArg` will always be `undefined` when the last passed argument is `false` not just _falsy_.

**To Reproduce**
Make an expectation of the last argument
_example uses `chai`_
```js
const foo = {
  greet() {
    this.speak("hello, world", false);
  },
  speak(msg, speakTwice) {
    console.log(msg);
    if (speakTwice) {
      console.log(msg);
    }
  }
};

const fake = sinon.fake();
sinon.replace(foo, "speak", fake);

foo.greet();

expect(fake.called).to.equal(true);
expect(fake.lastCall.lastArg).to.equal(false);
// => AssertionError: expected undefined to equal false
```

**Expected behavior**
`fake.lastCall.lastArg` should return `false` when the last argument of a function call is actually `false`.

**Context (please complete the following information):**

* Library version: `7.2.5`
* Environment: `nodejs@10.15` `npm@6.4.1` on `macOS 10.14`
* Other libraries you are using:
```json
"chai": "^4.2.0",
"mocha": "^5.2.0",
"sinon": "^7.2.5",
"ts-node": "^8.0.2",
```

**Comment by mroderick** [comment]
Thank you for the detailed bug report 🏆 

That is indeed a silly bug.

Would you like to contribute a PR to fix it?

That would involve adding a failing test to https://github.com/sinonjs/sinon/blob/master/test/issues/issues-test.js and a test to https://github.com/sinonjs/sinon/blob/master/test/fake-test.js, and of course fixing the actual problem.

You might want to cast a glance at [`CONTRIBUTING.md`](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md) before you decide.

We'd be happy to offer assistance where needed

**Comment by davidpaulhunt** [comment]
@mroderick agreed, it is a silly bug, but one that is immediately obvious.

I've read through CONTRIBUTING.md and I'd be happy to work on a PR to fix it.

I'll take a crack at it, cheers.
