### ISSUE TITLE
wrapping winston.js with stub doesn't work

### ISSUE THREAD

**Issue by adomas000** [sinonjs/sinon#1992]
#### Describe the bug

Stubbing winston or winston.createLogger method doesn't work( original function still gets called, because directories and files are created after a call)

#### How To Reproduce

```js
 it('should not call winston.createLogger', () => {
    sinon.stub(winston);
    winston.createLogger({
      transports: [
        new winston.transports.File({ 
          filename: 'fake/path/l.log'
        })
      ]
    })
  })
```

#### Expected behavior
Should not call winston.createLogger original methods or sub-methods

**Context (please complete the following information):**

* Library version: ^7.2.7
* Environment: Typescript
* Other libraries you are using:
"devDependencies": {
    "@types/chai": "^4.1.7",
    "@types/mocha": "^5.2.6",
    "@types/mock-fs": "^3.6.30",
    "@types/node": "^11.11.0",
    "@types/sinon": "^7.0.9",
    "@typescript-eslint/eslint-plugin": "^1.4.2",
    "@typescript-eslint/parser": "^1.4.2",
    "chai": "^4.2.0",
    "eslint": "^5.15.1",
    "mocha": "^6.0.2",
    "mock-fs": "^4.8.0",
    "sinon": "^7.2.7",
    "ts-node": "^8.0.3",
    "typescript": "^3.3.3333"
  },
  "dependencies": {
    "moment": "^2.24.0",
    "winston": "^3.2.1"
  }

**Comment by mroderick** [comment]
That's interesting. Are you using ESM or CommonJS?

**Comment by adomas000** [comment]
CommonJs

**Comment by fatso83** [comment]
verified

**Comment by MichaelBlockchain** [comment]
I am also experiencing this.

**Comment by AcehilmAbegrr** [comment]
Although it isn't stubbing the logger, if you want to not have the logger showing up when you srun your tests you can exclude them from your tests in your script text command in package.json with -x + path like this:
```
"scripts":{
"test": "npm run config && NODE_CONFIG_DIR=node/config/path nyc --check-coverage true -x 'node/path/to/winston-logger.js'"
}
```

**Comment by fatso83** [comment]
I don't know what I did when trying to reproce this, but I am not able to now. I am guessing I did something wrong, which is why it's important to document this using reproducible examples ...

This seems to work fine: https://runkit.com/fatso83/5d88e1f94606ec0013e12874
