### ISSUE TITLE
How to unit test SPFx promises with chained property and methods

### ISSUE THREAD

**Issue by asepdf** [sinonjs/sinon#1998]
How can i do unit test on sample TypeScript function below:

```
public getListItems(): Promise<CustomListObject[]> {
        return new Promise<CustomListObject[]>((resolve, reject) => {
            let listObjects: CustomListObject[] = [];
            this.sp.web.lists.getByTitle('TestList').items
                .select('Title')
                .filter('IsValidItem eq \'Yes\'')
                .get().then(
                    (allItems: any[]) => {
                        allItems.forEach(item => {
                            listObjects.push({ 'title': item.Title });
                        });
                        resolve(listObjects);
                    }).catch(
                        error => {
                            console.log(error);
                            reject(error);
                        }
                    );
        });
    }
```

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
