### ISSUE TITLE
sinon.deepEqual(new Date(0), new Date()) returns true.

### ISSUE THREAD

**Issue by faridnsh** [sinonjs/sinon#200]
sinon.deepEqual returns true for every two dates, even if they don't match.

I found out this problem, when my mock expectation didn't throw when it was called with the wrong date.

**Comment by troynguyen8** [comment]
Is there any way to correctly check deep equality of dates in a call to `spy.calledWithExactly`?

**Comment by mantoni** [comment]
It should just work™️. If you have an issue with dates and `calledWithExactly`, please open a new issue with a description stating what you expect to happen and what actually happens. If you have a usage question, it's probably best to post your question on StackOverflow using the Sinon tag. Thanks.
