### ISSUE TITLE
Example in Documentation for `fake` Doesn't work

### ISSUE THREAD

**Issue by 76784** [sinonjs/sinon#2000]
[See the last example for `fake` here](https://sinonjs.org/releases/v7.3.0/fakes/): 

Here is the code to test:
`testrunner.html`:
```
<!DOCTYPE html>
<html>
	<head>
                <meta charset="utf-8">
		<title>Sinon Test Using Mocha</title>
	</head>
	<body>
		<script src="node_modules/sinon/pkg/sinon.js"></script>
		<script src="test-sinon.js"></script>	
	</body>
</html>
```
`test-sinon.js`:
```
var fake = sinon.fake.returns('42');
sinon.replace(console, 'log', fake);
console.log('apple pie');
sinon.restore();
```
According to your documentation, the console should log `42`. But the console doesn't log anything.

Thanks.

**Comment by fatso83** [comment]
Actually, the docs doesn't say it should log 42. It just shows an interactive session that _evaluates_ to 42, meaning the _return value_ changes to 42, not the actual logging. This is verified to be working, both in Chrome and in the Node REPL. Try running this example: https://runkit.com/fatso83/sinon-2000
