### ISSUE TITLE
Fake XMLHttpRequest example contains `assert.equals` / `assert.match`, which error out

### ISSUE THREAD

**Issue by 76784** [sinonjs/sinon#2002]
See [https://sinonjs.org/#get-started](https://sinonjs.org/#get-started) (**Fake XMLHttpRequest** heading)

Example given:
```
var xhr, requests;

before(function () {
    xhr = sinon.useFakeXMLHttpRequest();
    requests = [];
    xhr.onCreate = function (req) { requests.push(req); };
});

after(function () {
    // Like before we must clean up when tampering with globals.
    xhr.restore();
});

it("makes a GET request for todo items", function () {
    getTodos(42, sinon.fake());

    assert.equals(requests.length, 1);
    assert.match(requests[0].url, "/todo/42/items");
});
```
What library are `assert.equals` and `assert.match` from? [Node.js](https://nodejs.org/docs/latest-v10.x/api/assert.html) uses `equal()` (singular), [as does Chaijs](https://www.chaijs.com/api/assert/#method_equal). [Chaijs does have](https://www.chaijs.com/api/assert/#method_match) `match()`, but it errors out here as well.

Thanks

**Comment by mantoni** [comment]
This example is using `@sinonjs/referee`. There could be a hint with a link in the docs. Would you like to contribute to improve the documentation?

**Comment by 76784** [comment]
Can you show me how referre is assigned to the assert variable?

**Comment by mantoni** [comment]
With node, browserify or webpack you would do `var assert = require('@sinonjs/referee').assert`. You can learn about the referee API on [the project documentation page](https://sinonjs.github.io/referee/).
