### ISSUE TITLE
SinonJS on ServiceNOW platform

### ISSUE THREAD

**Issue by jasbirsinghvig** [sinonjs/sinon#2005]
**Describe the bug**
Trying to load SinonJS fails with com.glide.script.RhinoEcmaError: Cannot set property "serverPrototype" of undefined to "[object Object]"

**To Reproduce**
1. Open <Scripts - Background> on a ServiceNOW instance (version Madrid)
2. copy paste SinonJS 7.3.1 and click "Run Script"
3. The Rhino engine complains about keywords being used as object properties; fix those by renaming and re-run the script.
4. Eventually you see the error "Evaluator: com.glide.script.RhinoEcmaError: Cannot set property "serverPrototype" of undefined to "[object Object]""

**Expected behavior**
The script should load without an Exception or Error message. The sinon object is available for use.

**Screenshots**
![Screen Shot 2019-04-03 at 3 56 18 PM](https://user-images.githubusercontent.com/32654417/55518485-0fc92880-5629-11e9-96b9-180585325d1c.png)

**Context (please complete the following information):**

* Library version: _please verify that the bug exists in the latest release_ Yes it does. We currently use 1.17.6 and it loads without any issue.

* Environment: ServiceNOW platform. I can arrange access for an instance.
* Example URL:
* Other libraries you are using:

**Additional context**
I had to modify the sinonjs script to rename the keywords used as property names.
In the function constructor `Sandbox()`, the keyword `this` is NULL

**Comment by fatso83** [comment]
We support evergreen browsers, IE11 and the two last Node versions. Rhino is not on the table. Feel free to push a PR to remedy the situation, but we won't officially support it.

**Comment by fatso83** [comment]
@mroderick I could find nowhere we actually list this or a mention of our strategy. Omission?

**Comment by mroderick** [comment]
> @mroderick I could find nowhere we actually list this or a mention of our strategy. Omission?

https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#compatibility

We could make that more prominent in the repository and on the website.

**Comment by fatso83** [comment]
Yeah, that's essential info, which I think should be in the README and the website, not in the contriubution guidelines.
