### ISSUE TITLE
Broken Assertions Docs Link

### ISSUE THREAD

**Issue by aaronmiller** [sinonjs/sinon#2013]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

Hello,

I hope all is well. I was looking through the sinon docs and ran into a broken link while sifting through the sandbox portion of the site. The link for `sandbox.assert` is broken.

* Sinon version : v7.3.2
* Environment   : Happens on sinonjs.org
* Example URL   : https://sinonjs.org/releases/v7.3.2/sandbox/assertions
* Other libraries you are using:

**What did you expect to happen?**

**What actually happens**

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar

<details>
    <summary>Really long code sample or stacktrace</summary>

    If you need to provide a dump of a stack trace or
    other lengthy material, such as 80 lines of example code,
    please stuff it in a `<details>` tag such as this
    to make the issue more readable. Thanks.
</details>

**Comment by fatso83** [comment]
Thank you. I verified this by going to https://sinonjs.org/releases/v7.3.2/sandbox/ and finding the sandbox.assert link.

Want to take a stab at fixing it? https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md

**Comment by brandonau24** [comment]
@fatso83 I can take a look at this, if that's okay with you.
