### ISSUE TITLE
Copyright Year in Footer (2010-2018)

### ISSUE THREAD

**Issue by vinitshahdeo** [sinonjs/sinon#2014]
The copyright year in footer is `2010-2018`. But now it should be `2010-2019`.

<img width="444" alt="Screenshot 2019-05-07 at 6 15 00 PM" src="https://user-images.githubusercontent.com/20594326/57300423-688e5400-70f4-11e9-8053-60cbd9ad1508.png">

**Comment by fatso83** [comment]
Closed in 62937cc
