### ISSUE TITLE
`sinon.resetHistory()` does not reset history

### ISSUE THREAD

**Issue by mcow** [sinonjs/sinon#2016]
Per the [docs](https://sinonjs.org/releases/v7.3.2/stubs/):

> _Since sinon@5.0.0_
> You can reset history of all stubs using sinon.resetHistory()

**To Reproduce**

```javascript
const assert = require('chai').assert;
const sinon = require('sinon');

describe('resetHistory', function() {
  var num = null;


  beforeEach(function() {
    num = sinon.createStubInstance(Number);
  });
  afterEach(() => {
    // Restore the default sandbox here
    sinon.restore();
  });

  describe('called on individual stub method', function() {
    it('should clear "called" status on stub', function() {
      num.toFixed();
      assert.isTrue(num.toFixed.called);
      num.toFixed.resetHistory();
      assert.isFalse(num.toFixed.called);
    });
  });

  describe('called on module', function() {
    it('should clear "called" status on all stubs', function() {
      num.toFixed();
      assert.isTrue(num.toFixed.called);
      sinon.resetHistory();
      assert.isFalse(num.toFixed.called);
    });
  });
});
```

[RunKit demo](https://runkit.com/fatso83/5cd3e47cdb83d1001a88c4c6)

**Actual results**

Second test fails:
""called on module: should clear \"called\" status on all stubs: ❌. [assert.isFalse] Expected true to be false""

**Expected results**

All tests pass

**Comment by fatso83** [comment]
I updated the issue with the content of the zip file and also added it as a runnable [RunKit demo](https://runkit.com/fatso83/5cd3e47cdb83d1001a88c4c6), asserting that it works.

**Comment by rpgeeganage** [comment]
I would like to help on bug fixing

**Comment by fatso83** [comment]
@rpgeeganage Please do! Here is our [getting starting guide](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#contributing-to-the-code-base)

**Comment by mcow** [comment]
I realize this comment is more of a feature request, but it would be nice if the "stub instance" object had its own `resetHistory()` (and `resetBehavior()` and `reset()`) methods, without needing to hit the entire sandbox.

**Comment by fatso83** [comment]
@mcow Stubs have [had those features since version 2 of Sinon](https://sinonjs.org/releases/v7.3.2/stubs/#stubreset). The sandbox additions are much more recent.

**Comment by rpgeeganage** [comment]
@fatso83 ,
Thanks a lot. I'll work on this.

**Comment by mcow** [comment]
@fatso83 Stub *methods* have that feature. *"Stub instance" objects*, the result of a `createStubInstance()` call (which lousy terminology is sinon's, don't blame me for the miscommunication) do not.

**Comment by rpgeeganage** [comment]
@fatso83,
I have looked into the implementation of `sinon.resetHistory` and `sinon.createStubInstance`.
What I notice is, `sinon.createStubInstance` does not use the implementation from `sandbox` but `sinon.resetHistory` uses the implementation from  `sandbox`. In `sinon.resetHistory` the `collection` is always empty. I'll dig deep.

**Comment by fatso83** [comment]
@mcow Aha, that explains things. I didn't notice the _instance_ bit :) Hopefully @rpgeeganage deep dive comes up with something fruitful.

**Comment by brandonau24** [comment]
@fatso83, should this issue be closed since the changes for it are merged into master?

**Comment by fatso83** [comment]
TG for astute observers 😄
