### ISSUE TITLE
withArgs returns in an unexpected way with matchers

### ISSUE THREAD

**Issue by TomVance** [sinonjs/sinon#2018]
**Describe the bug**
There appears to be an ordering / explicitly issue with withArgs when using sinon matchers.

When stubbing a function that takes a string argument, and choosing a return value based on it's arguments:

```javascript
stub.withArgs(sinon.match.string).resolves('a')
stub.withArgs('hello world').resolves('b')
```
The issue here is that both stubs resolve with 'b'.

**To Reproduce**
```javascript
const sinon = require('sinon')
const chai = require('chai')
const expect = chai.expect

const controller = {
  func: (string1, arr) => {
    return string1
  }
}

function runCode() {
  console.log('CALL 1:', controller.func('first'))
  console.log('CALL 2:', controller.func('second'))
}

describe('proof', () => {
  beforeEach(() => {
    sinon.stub(controller, 'func')

    controller.func.withArgs(sinon.match.string).returns('halp 1')
    controller.func.withArgs('second').returns('halp 2')
  })

  it('runs', () => {
    runCode()
  })
})

```

outputs:
```
halp 2
halp 2
```

**Expected behavior**
I would expect the calls to return 'halp1' and 'halp 2' respectively for each console log. As the second case is more specific than the first.

**Context (please complete the following information):**

* Library version:* sinon@7.3.0`
* Environment:
* Example URL:
* Other libraries you are using:

**Comment by fatso83** [comment]
This is actually [documented in the stubs docs](https://sinonjs.org/releases/latest/stubs/#defining-stub-behavior-on-consecutive-calls). Feel free to add a how-to section or similar to our docs, or come up with a suggestion on how the docs could be improved to communicate this, as this is a recurring theme. You can see an example on the [onCall api docs](https://sinonjs.org/releases/latest/stubs#stuboncalln-added-in-v18)
