### ISSUE TITLE
calledWith not working as expected

### ISSUE THREAD

**Issue by WaleedAshraf** [sinonjs/sinon#2019]
Sinon version: 7.3.2

spy.calledWith() not working as expected

```
code:
console.log('calledWith', sendToTopicSpy.calledWith('DeviceGroupCreated'))
console.log('calledWith args', sendToTopicSpy.getCall(0).args)

logs:
calledWith false
calledWith args [ '36db41d0-8d24-43c9-8a66-b4a368bb0c6b',
  'DeviceGroupCreated',
  { groupId: '36db41d0-8d24-43c9-8a66-b4a368bb0c6b',
```

screenshot:
![Screenshot 2019-05-10 at 4 51 31 PM](https://user-images.githubusercontent.com/8335457/57536156-e5633d00-7343-11e9-927c-471d9fdb47ea.png)

**Comment by fatso83** [comment]
Could you please use our issue template? I have no idea what the expected outcome vs actual outcome here is.
