### ISSUE TITLE
stubbing require & returned mod (possible solution included)

### ISSUE THREAD

**Issue by brewster1134** [sinonjs/sinon#2020]
so i am writing a webserver framework, that compiled various webpack configurations based on cli/config options, and was having an issue trying to test methods that call the webpack method. i was playing with the concept of a `stubRequire`, that seems to be working, but am not very confident in it. i was hoping for a sanity check on the approach, and to maybe iron it out a bit more to become a feature.

here is a working, but contrived example...

### test_helpers.js
```coffee
Module = require 'module'
_require = Module::.require
# i create a global object of modules to check for when calling require
global.requireStubs ||= {}

module.exports =
  stubRequire: (modToStub, returnVal) ->
    # create stub for when mod is required, and for if/when it is called as a method
    returnStub = sinon.stub().returns returnVal   # when required mod is called, return something
    requireStub = sinon.stub().returns returnStub # when mod is required, return a stub

    global.requireStubs[modToStub] =
      requireStub: requireStub
      returnStub: returnStub

    Module::.require = (modRequired) ->
      # get just mod file name
      modName = modRequired.match(/[^\/]+$/)[0]

      # check against file name and full path
      if modToStub == modRequired || modToStub == modName
        # delete cached required module
        filename = Module._resolveFilename modRequired, @
        delete Module._cache[filename]

        # restore require
        Module::.require = _require

        # call stub for the require call
        global.requireStubs[modName].requireStub 'require'

        # return object of stubs
        return global.requireStubs[modName].returnStub

      # passthrough require
      else
        Module._load modRequired, @

    return global.requireStubs[modToStub]
```

### foo_test.js
```coffee
{ stubRequire } = require 'test_helpers.js'

Foo = require 'foo.js'

# using webpack as the example, i also pass an object to return to stub when webpack.run() is called
stubRequire 'webpack',
  run: ->
    'webpack.run() called'

describe 'Foo', ->
  describe '_runWebpack', ->
    testReturn = null

    before ->
      foo = sandbox.createStubInstance Foo
      foo._runWebpack.restore()
      fooReturn = foo._runWebpack 'webpack config'

    it 'should require webpack', ->
      expect(global.requireStubs.webpack.requireStub).to.be.calledOnceWith 'require'
      expect(global.requireStubs.webpack.returnStub).to.be.calledOnceWith 'webpack config'
      expect(fooReturn).to.eq 'webpack.run() called'
```

### foo.js
```coffee
# this is what i want to stub...
webpack = require 'webpack'

module.exports =
  class Foo
    _runWebpack: (webpackConfig) ->
      compiler = webpack webpackConfig

      compiler.run =>
        console.log 'webpack success'
```

hopefully the example w/ comments explains the idea fairly well

**Comment by fatso83** [comment]
@brewster1134 Just some thoughts on why this ended up dead in the water:
- **it has an unclear description**. you have to read quite a bit to see if this concerns an issue, a suggestion or as it actually seems: an initial draft at a _feature_ that could be added to Sinon
- **the code is not javascript**. I know the file names end in `.js`, but guessing from the pythonesque look I'm guessing that I'm looking at Coffeescript? Which makes it a bit harder to follow.
- **it targets a version dependant way of stubbing a module loader in a specific product**. This in itself makes it a bit off-topic, as we specifically brand Sinon as a stubbing library for Javascript, where we don't concern ourselves with the details of the _many_ ways "modules" (basically functionality split out into files) are implemented in the actual system. For that, we have the ["how to's" that make use of other libraries](https://sinonjs.org/how-to/).

I'd basically made a simple NPM package called `@brewster1134/webpack-sinon-stubber` or something like that and just publish it to get some feedback. You'd target the core audience and see if it made sense.
