### ISSUE TITLE
Syntax error in documentation (stub)

### ISSUE THREAD

**Issue by FRTNX** [sinonjs/sinon#2024]
Greetings. This is more of a documentation typo than an issue. My reporting it is mostly for the sake of those new to Javascript who may get stuck on it. 

In the stubs documentation under `stub.throws()` there's a syntax error in `stub.throws("name"[, "optional message"]);`. Which should be `stub.throws("name", ["optional message"]);`.

**Comment by fatso83** [comment]
I guess this is where using inline javascript mixed with conventions on documenting optional parameters goes wrong. Using `[, arg1[, arg2]]` is a standard way of documenting optional parameters.  In any case, doing `, ["optional message"]` would not be the right solution. If this should be runnable at all, the brackets could be dropped, although I am not sure what the "right" solution would be here (probably using actual JSDoc to avoid inconsistency).
