### ISSUE TITLE
stub.withArgs does not limit return value as expected

### ISSUE THREAD

**Issue by jrnail23** [sinonjs/sinon#2025]
**Describe the bug**
When I use `withArgs` on a stub, it always returns the `returns` value, even if the args don't match those specified in `withArgs`.

**To Reproduce**
Here is a [failing test](https://runkit.com/jrnail23/sinon-withargs-bug). 
```js
const sinon = require("sinon");
const assert = require("assert");

const service = () => ({
    find: () => {}    
});

service.find = sinon.stub()
    .withArgs("A")
    .returns("HELLO");

const result = service.find("B");

assert.notEqual(result, "HELLO");
```

**Expected behavior**
According to the documentation, the `result` above should be `undefined`, but it is actually `"HELLO"`

**Context (please complete the following information):**

* Library version: v7.3.2
* Environment: node v10.15.3
* Example URL: https://runkit.com/jrnail23/sinon-withargs-bug
* Other libraries you are using: n/a

**Comment by fatso83** [comment]
Cloned the repo and changed two lines:
```javascript
const stub = service.find = sinon.stub();
stub
    .withArgs("A")
    .returns("HELLO");
```

You need to save assign the stub before instrumenting it ... This might be a doc issue, though, as it's been a problem since Sinon 1.x.

**Comment by fatso83** [comment]
Hmm ... Actually, [the examples are correct](https://sinonjs.org/releases/latest/stubs/#stubwithargsarg1-arg2-), so unless you have a suggestion for improving it (PR welcome!), I'm closing this.

**Comment by jrnail23** [comment]
@fatso83, It does indeed work the way you showed it, and I agree the docs might be be improved to better reflect the intended behavior. 
I assumed that the behavior would be the same whether first assigning the stub or not (though I'm still not quite clear why that's not the case). 
IMO, it would be a bit more friendly, ergonomically speaking, if they did work the same.
In any case, thanks for the quick response on this issue.

**Comment by fatso83** [comment]
> IMO, it would be a bit more friendly, ergonomically speaking, if they did work the same.

No issues with that. It's just hard to implement, as far as I can remember ... feel free to take a stab at it, though, but I'd advice you to take a good look at the historic issues for context. I think there are good reasons this hasn't been changed in the last decade.
