### ISSUE TITLE
Separate stubs for class and its instance

### ISSUE THREAD

**Issue by Amit-Modi** [sinonjs/sinon#2029]
**Is your feature request related to a problem? Please describe.**
I want to be able to create separate stubs for a class and one of its instance.
Currently, when i try this i get `TypeError: Attempted to wrap get which is already wrapped` when i try to do this.

_**my-code**_
```nodejs
const sinon = require('sinon');

class A {
	constructor(val) {
		this.val = val;
	}
	get() {
		return this.val;
	}
	set(val) {
		this.val = val;
	}
}
sinon.stub(A.prototype, 'get').returns('stub A');

const a = new A('a');
const b = new A('b');

sinon.stub(a, 'get').returns('stub a');

console.log('a = ', a.get());
console.log('b = ', b.get());

console.log('restoring a.get stub');
a.get.restore();
console.log('a = ', a.get());
console.log('b = ', b.get());

console.log('restoring A.prototype.get stub');
A.prototype.get.restore();
console.log('a = ', a.get());
console.log('b = ', b.get());
```
**_output I want_**
```
a = stub a
b = stub A
restoring a.get stub
a = stub A
b = stub A
restoring A.prototype.get stub
a = a
b = b
```
**_output I get**
```
TypeError: Attempted to wrap get which is already wrapped
```

**Describe the solution you'd like**
- Allow creating new stub for an instance.
- When the function is called check for stub in following order
    1. instance stub
    2. class stub
- When restoring, `instance.method.restore()` restore only instance stub if available, else restore class stub. where as `class.prototype.method.restore()` restores class stub only. (this is for backward compatibility, As in current versions, when i stub through class and restore through instance, the stub is restored);
**Describe alternatives you've considered**
- give configuration option for disabling  `TypeError: Attempted to wrap get which is already wrapped` check. (This will also help if some one wants to have nested stubs, although the design is very complicated and risky)

**Additional context**
I originally wanted the nested stubs Feature, as it will help me in other areas as well.
And I will be happy to help (on weekends) with the code if no one is available.

**Comment by fatso83** [comment]
Hi, even this is a usage question, I looked into it now and there is a very easy fix. You are trying to stub an instance which has no property of its own with the keyname you are trying to stub out. Therefore, you can simply _assign_ the stub to the instance. Afterwards you don't need to clean it up, if you are no longer interested in the instance, but if you do find you need to you can just delete the prop.

See https://runkit.com/fatso83/sinon-workbook/1.1.0
