### ISSUE TITLE
Improve CONTRIBUTING.md to include forking the project

### ISSUE THREAD

**Issue by brandonau24** [sinonjs/sinon#2030]
In the CONTRIBUTING.md file, I think it would be good to include a step to fork the project under the "Contributing to code base" section or to link [GitHub's Forking Project Guide](https://guides.github.com/activities/forking/) to explain forking. Although new users should have read GitHub's guides before beginning a project, I think reminding the contributor to fork the project instead of cloning the project directly would cause less confusion for a new contributor.

**Comment by fatso83** [comment]
That's a good idea. Want to submit a PR?

**Comment by brandonau24** [comment]
@fatso83 Sure thing!

**Comment by brandonau24** [comment]
@fatso83 This ticket can now be closed.
