### ISSUE TITLE
General test setup: spy show different behavior based on how many test I run

### ISSUE THREAD

**Issue by gremo** [sinonjs/sinon#2037]
**Describe the bug**
Test spy should be independent from each other test. It seems it's not. I'm following [the official guide](https://sinonjs.org/releases/v7.3.2/general-setup/).

**To Reproduce**

```typescript
/* tslint:disable:only-arrow-functions no-var-requires */

import * as chai from 'chai';
import { expect } from 'chai';
import * as sinon from 'sinon';
import sinonChai from 'sinon-chai';

const dotenv = require('dotenv');

chai.use(sinonChai);

describe('SimpleLoader', function() {
  beforeEach(function() {
   // This is the spy: test class (SimpleLoader) imports the dotenv module
    this.dotenvConfigCall = sinon.spy(dotenv, 'config');
    this.SimpleLoader = require('../../src/loaders/simple-loader').SimpleLoader;
  });

  afterEach(function() {
    sinon.restore();
  });

  // first test
  it('throws if configFile doesn\'t exist', function() {
    const loader = new this.SimpleLoader(`${__dirname}/fixtures/config-empty`);

    expect(loader.load.bind(loader)).to.throw('config.json');
  });

  // second test
  it('loads correctly using default options', function() {
    const loader = new this.SimpleLoader(`${__dirname}/fixtures/config-simple`);
    loader.load();

    // console.log(this.dotenvConfigCall.getCall(0));
    expect(this.dotenvConfigCall).to.be.calledOnceWith(sinon.match.has('path'));
  });
});
```
**Expected behavior**
Test should **be independent from each other**. In my example, both test pass if I run one and comment out the other, that is:

- if I skip the first one (`xit` vs `it`) **the second pass** (`console.log(this.dotenvConfigCall.getCall(0))` shows the call)
- if I run both tests, **the second fail**; `console.log(this.dotenvConfigCall.getCall(0))` returns empty array

**Screenshots**
Not relevant.

**Context:**

* Library version: 7.3.2
* Environment: Windows 10 x64 (1903)
* Example URL: -
* Other libraries you are using:

```txt
+-- @nestjs/common@5.7.4
+-- @nestjs/core@5.7.4
+-- @nestjs/testing@5.7.4
+-- @types/chai@4.1.7
+-- @types/convict@3.0.2
+-- @types/dot-object@1.7.0
+-- @types/dotenv@6.1.1
+-- @types/glob@7.1.1
+-- @types/mocha@5.2.6
+-- @types/proxyquire@1.3.28
+-- @types/rewire@2.5.28
+-- @types/sinon@7.0.12
+-- @types/sinon-chai@3.2.2
+-- chai@4.2.0
+-- convict@5.0.0
+-- dot-object@1.7.1
+-- dotenv@8.0.0
+-- glob@7.1.4
+-- mocha@6.1.4
+-- proxyquire@2.1.0
+-- reflect-metadata@0.1.13
+-- rewire@4.0.1
+-- rimraf@2.6.3
+-- rxjs@6.5.2
+-- sinon@7.3.2
+-- sinon-chai@3.3.0
+-- source-map-support@0.5.12
+-- testdouble@3.11.0
+-- ts-node@8.2.0
+-- tslint@5.16.0
`-- typescript@2.9.2
```

**Additional context**
None I suppose.

**Comment by mantoni** [comment]
I believe that `dotenv.config` is called when you first call `require('../../src/loaders/simple-loader')`. When you have both tests enabled, it's called on the first `beforeEach` call, but since `require` calls are cached, it will not evaluate again on the second call. This is how node require works and has nothing to do with Sinon.

There is a good explanation [on stackoverflow](https://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate), including a solution to clear the require cache.

Hope this help.

**Comment by gremo** [comment]
Thanks for the answer, however the call on dotenv is inside the load method of my test subject!

**Comment by fatso83** [comment]
This smells very much of a typical "dig into the code deeply to understand why some module loader thing is interfering with how stuff is supposed to work" and not so much an issue with Sinon in itself. We are quite time constrained, so I'd post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

Those guys regard questions like that as treats, so you'll probably have more success there.
