### ISSUE TITLE
Add a "PubSub" description to document

### ISSUE THREAD

**Issue by Simmyoungsub** [sinonjs/sinon#2040]
For example, "spies" does not describe "PubSub" in document.
Please add a description

**Comment by mroderick** [comment]
Why?

**Comment by fatso83** [comment]
Hmm ... Quite a bare issue report, but _I assume_ this is related [to the docs](https://sinonjs.org/releases/latest/spies/) for spies, where there is an example using a `PubSub` object.

@Simmyoungsub Please fill out the issue template the next time, so we don't have to guess.

@mroderick I can understand why he asks (assuming I'm right about the topic), as fresh programmrers don't necessarily know what a pub-sub system is, so they don't see it as a hypothetical implementation, but an actual global object. And this trips them up when trying out the examples. I'm sure this could be elaborated a _little bit_ for clarity.

**Comment by mroderick** [comment]
Perhaps we can improve the documentation by using other examples?

**Comment by fatso83** [comment]
I think we can keep it brief if we just embed the full picture as a runnable example for the user to play with: https://runkit.com/docs/embed

**Comment by adhyapranata** [comment]
Hi @fatso83 , is this good enough as a runnable example?

[https://runkit.com/adhyapranata/sinon-runkit-spy-demo](https://runkit.com/adhyapranata/sinon-runkit-spy-demo)

**Comment by fatso83** [comment]
@adhyapranata That's great! But we can do even better, by actually putting it in a test harness that people are used to, so I forked it: https://runkit.com/fatso83/sinon-runkit-spy-demo
It's using a minimal implementation of the Mocha API to make it look familiar. 

It would be cool if you could make a test on how this embeddding would look in our docs. To replace our current static examples, you can basically take the contents of my fork and use [the programmatic API](https://runkit.com/docs/embed) to make a script block that renders where the current example is.
That's good enough for a test!

If this works fine, we'll need to refine it a bit
- put the javascript file into some `examples` directory, so that we can run the examples as a test step to ensure it's always runnable
- Dynamically inject the file content into the generated README
- etc

But that's for later. If you could make a simple demo PR, that would be awesome!

**Comment by adhyapranata** [comment]
@fatso83 It would look like this (see image below). I use atom-dark for the theme and set the font-size to the same one as the static code example. What do you think?

![Spies - Sinon JS](https://user-images.githubusercontent.com/5564120/66205182-f340a280-e6d6-11e9-977c-a5c6825567ff.jpg)

**Comment by fatso83** [comment]
@adhyapranata Wow, that looks awesome! It actually looks better than I would expect, so a good thing to style it inline with what we have.

I think a mix of [Jekyll relative Includes](https://jekyllrb.com/docs/includes/) (like `{% include_relative examples/some.file %}`) and using page attributes that [one can loop through](https://dmitryrogozhny.com/blog/how-to-add-custom-script-to-single-post-in-jekyll) should get us exactly where we want to be.

Maybe you have a different/better suggestion on how to do this, but I would do it like this:

1. Extract the example script (done) into a separate file (like `example/spies-1-pubsub.js`).
1. Add a custom field to the `spies.md` header : 
```
examples:
- "spies-1-pubsub"
```
3. Add `<div data-example-id="spies-1-pubsub"></div>` to where you want the example embedded
4. `{% include embed-scripts.html %}` (this file must be created :-) )
5. Create the `_includes/embed-scripts.html` file with some content like
```html
{% for example in page.examples %}
{% assign filename = 'examples/' | example | append: '.js' %}
<template data-example-script="{{example}}">{% include_relative {{filename}} %}</template>
<script>
(function(){
    // get script example div
    var element = document.querySelector("[data-example-id={{ example }}]"),

    // get script example source from the template
    var scriptTemplate = document.querySelector("[data-example-script={{ example }}]"),

    var notebook = RunKit.createNotebook({
    // the parent element for the new notebook
        element: element,
        // specify the source of the notebook
        source: scriptTemplate.content
    })
})(); // IIFE - to avoid leaking variables
</script>
{% endfor %}
```

**Comment by adhyapranata** [comment]
@fatso83 That's just simply magnificent! Thank you for your detail guidance. I have updated the PR based on this. Please kindly have a look.

**Comment by srknzl** [comment]
A suggestion regarding code snippets via runkit:  

Since website theme is light, I think dark theme in code snippets does not look good. You can use a theme like in the express docs.

![image](https://user-images.githubusercontent.com/32355782/115108190-b914ba00-9f77-11eb-908b-74b797807958.png)

**Comment by mroderick** [comment]
@srknzl thank you for sharing your idea. Would you mind opening a new issue for this, so it can be discussed on its own merits?
