### ISSUE TITLE
Set stub default response

### ISSUE THREAD

**Issue by fgarcia** [sinonjs/sinon#2044]
**Is your feature request related to a problem? Please describe.**
I can stub a whole object but I want a friendly way to notify the developer that he/she must define missing stubs (which tends to happen if code within a future)

For example:

```
  let myClone = sinon.stub(myObj)
  myClone.foo.withArgs(1).returns('hello 1') 
  myClone.foo.withArgs(2).returns('something') 

```

Now weeks later the code is refactored, and myClone.foo(..) is called with new arguments. Currently it returns `undefined` by default.

**Describe the solution you'd like**
Enable a way to throw an error by default when a stub is called, preventing the user to reverse engineer the code until realizing that they are working with a stub, not the real thing:
 
`let myClone = sinon.stub(myObj).throwWhenNotDefined()`

**Comment by mantoni** [comment]
I just tried this and I think it does what you're asking for:

```js
const obj = { foo(a) {} };
const wrap = sinon.stub(obj);

wrap.foo.throws(new Error('Missing stub behavior'));
wrap.foo.withArgs(1).return('hi');
wrap.foo.withArgs(2).returns('there');

wrap.foo(1); // hi
wrap.foo(2); // there
wrap.foo(3); // Error: Missing stub behavior
```

**Comment by jlenon7** [comment]
Hey @mantoni, Is there any way to get the following behavior?:

```typescript
const obj = { 
  foo(a) { 
    return 'original implementation' 
  }
};

const stub = sinon.stub(obj, 'foo');

stub.withArgs(1).return('hi');
stub.withArgs(2).returns('there');

stub.foo(1); // hi
stub.foo(2); // there

stub.foo(); // original implementation
stub.foo(3); // original implementation
```

**Comment by mantoni** [comment]
You can try `sinon.stub(obj, 'foo').callsFake(obj.foo);`.

**Comment by jlenon7** [comment]
> You can try `sinon.stub(obj, 'foo').callsFake(obj.foo);`.

I've already tried it, this leads to recursive calls.

Thanks for the insight on `callsFake()`, this looks like to solve the problem:

```typescript
const stub = sinon.stub(obj, 'foo').callsFake((...args) => {
  return stub.wrappedMethod.bind(obj)(...args)
});

stub.withArgs(1).return('hi');
stub.withArgs(2).returns('there');

stub.foo(1); // hi
stub.foo(2); // there

stub.foo(); // original implementation
stub.foo(3); // original implementation
```

Do you know if it's possible that `wrappedMethod()` become `undefined`?

**Comment by mantoni** [comment]
If you keep a reference to `obj.foo` before installing the stub, `callsFake` should not lead to recursive calls:

```js
const foo = obj.foo;
const stub = sinon.stub(obj, 'foo').callsFake(foo);
```
