### ISSUE TITLE
How to mock method which returns different values depending on the received arguments?

### ISSUE THREAD

**Issue by YegorZaremba** [sinonjs/sinon#2050]
Hi, thanks a lot for amazing Sinon library :)

I have a question (or maybe its a docs issue)

https://stackoverflow.com/questions/56721007/how-to-mock-method-which-returns-different-values-depending-on-the-received-argu

**Comment by fatso83** [comment]
We don't do support on the issue tracker, but you usually get an answer. I don't know the mocks API, unfortunately.
