### ISSUE TITLE
How are we solving polyfill methods ?

### ISSUE THREAD

**Issue by bhalke** [sinonjs/sinon#2056]
I have method in file home.js

```
var dom= require("dom"); // dependency
  return function Home() {
    users = dom.createEventObject();
    return users;
  };
});
```

my sinon test case as below

```
var home = require("home");
describe("test users", function() {
  it("show users", function() {
    new home();
    // my expect cases
  });
});
```
```
tried adding stub, but stub still calling this method.
getting error as TypeError: dom.createEventObject is not a function

how can we overcome this issue ?

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
