### ISSUE TITLE
Lodash security warning

### ISSUE THREAD

**Issue by geekyrajshri** [sinonjs/sinon#2067]
sinon is having vulneribility issue because of lodash vulnerability in its transitive dependencies.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/8193580/61715532-f506f500-ad7a-11e9-884f-b1c415a0c1e2.png">

**Comment by mantoni** [comment]
Fixed in 67b8c0c085901b28e01bf9e007f95902cad3b614.
