### ISSUE TITLE
Unable to mock React useState

### ISSUE THREAD

**Issue by JamesIves** [sinonjs/sinon#2069]
**Describe the bug**
I'm unable to use Sinon to mock the React hook `useState`. I've tried multiple different ways but always end up with it not being mocked.

My code looks like this:

```javascript
import React, { useState } from 'react';

function Expand() {
  const [expanded, setExpanded] = useState(null);

  return (
    <div>
      <button onClick={() => setExpanded(true)}>
        Expand
      </button>
    </div>
  );
}
```

And using Sinon in my test I've tried to stub it like so:

```javascript
import * as React from 'react'; 
import {stub} from 'sinon';

const component = mount(<Expand />);
const setExpandedStub = stub();
const setStateStub = stub(React, 'useState').returns([
  null,
  setExpandedStub,
]);

component
  .find('button')
  .prop('onClick')();

t.equals(
  setExpandedStub.args[0],
  true,
  'Should set the state to true.'
);
```

Logging out `useState` in my function when my test runs seems to reveal that it never actually gets mocked by Sinon: `[Function: useState]` and I'm unable to call `setExpandedStub.args` etc.

**To Reproduce**
1. Attempt to mock `React.useState`.
2. It never mocks.

**Expected behavior**
I expect the function to be stubbed so I can tell when it has been called.

**Context (please complete the following information):**

* Library version: `7.3.2`
* Environment: `Mac OSX`
* Other libraries you are using: `React, Enzyme, Tape`

**Additional context**
https://reactjs.org/docs/hooks-state.html

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by JamesIves** [comment]
I did - but I don't understand how this doesn't fall under the guidelines for reporting issue?  From my understanding Sinon isn't working as intended in this use case based on the [stubbing documentation](https://sinonjs.org/releases/v7.3.2/stubs/) and previous cases where this same code works fine. If it's working as intended it's unclear as to why.

**Comment by fatso83** [comment]
There is nothing that says Sinon is doing anything wrong here. And there are multiple ways the example could go wrong and they all relate to binding. Meaning that you probably bind the reference to useState in your client code before you stub out the export in the test. 

This relates to module binding, probably using Babel and/or Webpack, which is not what this library is about. 

We do have multiple guides though, and I would try out the link levels replacement strategy first ("link seams"):
https://sinonjs.org/how-to/.

This should work fine when running through Babel-Node, but if you also employ Webpack you'll encounter complications, which is out of scope (as the various Webpack versions have different ways of exporting modules).

**Comment by fatso83** [comment]
P.S. Post a link to the stackoverflow question and I'll try to find time in making a runnable example project.

**Comment by fatso83** [comment]
Here's a runnable demo how I stub out `useState` using only Sinon: 
https://repl.it/@fatso83/React-library-stubbing-demo-sinon-only

I don't have access to a development environment on holiday, so I just coded it up in the browser using repl.it, and as I don't know how to configure it using Babel and all that jazz it is purely standard Ecmascript.

**Comment by JamesIves** [comment]
Really appreciate the example and the explanation!

**Comment by fatso83** [comment]
No worries - at least now we can refer people to an example :)

BUT should it for some reason NOT work in your case, I assume it's due to some bundler/packer configuration issue, most probably Webpack. In that case, you might be interested in reading https://github.com/sinonjs/sinon/issues/1762 or the associated webpack thread https://github.com/webpack/webpack/issues/6979#issuecomment-479161284 to understand why Sinon is not responsible for this and what options you have to achieve your target. 

Izhaki has some good input.

**Comment by littleh322** [comment]
How would you handle multiple `useState` instances using different types in your functional component?
**For example:**
`const [open, setOpen] = useState<boolean>(false);`
`const [name, setName] = useState<string>('Enter name here...');`

**Comment by fatso83** [comment]
@littleh322 That's a usage question and we are not equipped (i.e. payed) to handle general support.; please post it to StackOverflow and tag it with sinon, so the bigger community can help answer your questions. They are usually _very_ quick (and I am often one of them, just not in my parental leave).
