### ISSUE TITLE
No release notes for 7.4.0

### ISSUE THREAD

**Issue by ffflorian** [sinonjs/sinon#2071]
Hi,
I don't know how this usually works with sinon releases but I was wondering why the latest release 7.4.0 doesn't have a release tag and no release notes. Is there a reason for this or am I just being too impatient? :smiley:

**Comment by fatso83** [comment]
I might have forgot to push the tags after doing `npm publish` ...

**Comment by hieuunguyeen** [comment]
+1
Does 7.4.x have changes regarding `createStubInstance`? It's breaking our tests that were passing with 7.3.2

**Comment by fatso83** [comment]
I'll try to revert @latest to 7.3.2, seeing that the release commits weren't pushed.

**Comment by fatso83** [comment]
So 7.4.0 has been unpublished and 7.3.2 set as `latest`. But I might need to ping you again, @hieuunguyeen, as there were no intended breaking changes. The only reason for a version change, AFAIK, was that I bumped the Lolex and Nise version numbers, which added some API's.

Could you try to install the latest Sinon version from master by doing `npm install sinonjs/sinon` and try to run your tests using that? If they break, could you open a new issue with a reproducible test case?

**Comment by simoneb** [comment]
Not a good move to unpublish a version. You may know that there are lots of automated tools out there updating dependencies automatically. By unpublishing 7.4.0 you have broken our CI pipeline and probably quite a few others.

**Comment by gajus** [comment]
@fatso83 Can you please release version 7.4.0? Even if it is just re-releasing the current version. This broke our CI/CD pipeline for hundreds of packages.

**Comment by fatso83** [comment]
Sorry about this noise. A bit rusty on the NPM intricasies. 7.4.1 has been released to remedy the situation.

@gajus It's not possible to reuse a version that has been unpublished, so 7.4.0 will stay gone.
