### ISSUE TITLE
Stub S3 method doesn't work

### ISSUE THREAD

**Issue by WonJaesub** [sinonjs/sinon#2083]
I try to write unit test with S3, but it was failed with error.
I typed typescript.

my test method
```
export const getUrlFromS3 = async (fileName: string): Promise<string> => {
  const s3: S3 = new S3({
    accessKeyId: process.env.AWS_ACCESS_KEY,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
  });
  const params = {
    Bucket: process.env.AWS_BUCKET_NAME,
    Key: `${fileName}.pdf`,
    Expires: 60 * 5
  };
  return new Promise((resolve, reject) => {
    s3.getSignedUrl("getObject", params, (err: Error, url: string) => {
      if (err) {
        reject(err);
      }
      resolve(url);
    });
  });
};
```

and my test file
```
import * as manageS3 from "./manageS3";
import * as Aws from "aws-sdk";
import * as Sinon from "sinon";
import { expect } from "chai";

describe("manageS3", () => {
  let sandbox: Sinon.SinonSandbox;
  beforeEach(() => (sandbox = Sinon.createSandbox()));
  afterEach(() => sandbox.reset());

  it("getUrlFromS3 test", async () => {
    sandbox
      .stub(Aws.S3.prototype, "getSignedUrl")
      .callsFake((operation, params, callback) => {
        return callback(undefined, "");
      });
    const url = await manageS3.getUrlFromS3("");
    console.log(url);
  });
});
```

and it is error message
`Argument of type '(operation: any, params: any, callback: any) => any' is not assignable to parameter of type '(operation: string, params: any) => string'.ts(2345)`

S3 has two of methods that are
```
    getSignedUrl(operation: string, params: any, callback: (err: Error, url: string) => void): void;
    getSignedUrl(operation: string, params: any): string;
```

Why can't the first method stub?

**Comment by fatso83** [comment]
This is not a Sinon issue. The error you get is from the TypeScript system you are employing, and is not something we are involved in.

---
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon) and `typescript`, so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by jiayiming001** [comment]
good
