### ISSUE TITLE
UX: Easy way to restore after spying on all methods of an object

### ISSUE THREAD

**Issue by fearphage** [sinonjs/sinon#2087]
In #2027 we gained the ability to spy on all methods of an object. However the only way to restore the object is to use a sandbox or visit every method of the object. It would be a convenient and a better user experience if `spyOnEntireObj` returned a way to revert everything back to normal.

**Comment by fatso83** [comment]
Are not these concerns also equally valid for `stubEntireObj`?

**Comment by mroderick** [comment]
Something like this?

```js
var o = {
  hello: function hello(){ console.log('hello') }
};
sinon.spy(o);

sinon.restoreObject(o)
```

or perhaps even

```js
var o = {
  hello: function hello(){ console.log('hello') }
};
sinon.spy(o);

sinon.restore(o)
```

**Comment by fearphage** [comment]
I like `.restoreObject()`. It's more explicit about its intent and it won't be confused with normal `spy/stub.restore()`.
