### ISSUE TITLE
Document sinon.restoreObject()

### ISSUE THREAD

**Issue by fearphage** [sinonjs/sinon#2089]
This was added recently (#2088). It needs to be documented. We could use your help.

**Comment by franck-romano** [comment]
Hi,

It will be a pleasure to contribute but I need a little help to know where to add the doc part.
Should it be located in `utils.md` ? :)

Thanks

**Comment by fatso83** [comment]
That seems like the right place, yes. I would also link to it from the spies and stubs sections. 

If you haven't seen it, here's where to start: https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md
