### ISSUE TITLE
Issue with "mock.verify()" when called from within a Promise callback.

### ISSUE THREAD

**Issue by kchanna** [sinonjs/sinon#2138]
**Describe the bug**

**To Reproduce**

`it("test case 100", () => {
        return getPromiseA()
            .then((A1) => {
                const mock1 = sinon.mock(MyObject);
                mock1.expects("someMethod").twice();
                A1.getPromiseB("1234").then((response) => {
                    mock1.restore();
                    mock1.verify();
                }).catch((error) => {
                    console.log("+++--- (Error) END of testCase +++++");
                }}, (rejectedP) => {
            }).catch((err) => {
                console.log("-------- (REJ-C) END of testCase ++++");
            });
    });`
Execute the above test case

**Expected behavior**
This test case should fail. Because "someMethod" should actually be called only once. 
But I've expected it to be called twice.
Hence this test case should fail.

Actual result: Test passes.

When the line mock1.verify();
executes, it actually throws an error in the browser console:
Expected someMethod([...]) twice (called once)
    at Object.fail (http://localhost:5858/build/js/testSuites.js:18184:21)

But because of the multiple promises, it never surfaces up.

**Context (please complete the following information):**

* Library version: 7.5.0
* Environment: MAC OS Mojave
* Example URL:
* Other libraries you are using:

**Additional context**

**Comment by kchanna** [comment]
This has been answered here: https://stackoverflow.com/questions/58325428/mock-verify-doesnt-fail-the-test-if-called-from-promise-callback/58369779#58369779


`it("test case 100", () => {
    let mock1 = null;
    return getPromiseA().then((A1) => {
        mock1 = sinon.mock(MyObject);
        mock1.expects("someMethod").twice();
        return A1.getPromiseB("1234");
    }).then(() => {
        // response from "A1.getPromiseB"
        mock1.restore();
        mock1.verify();
    });
// No need for catch, since the error will be caught and reported as failure by Sinon.
});`

This worked for me as well.

**Comment by mroderick** [comment]
Edited https://github.com/sinonjs/sinon/issues/2138#issuecomment-541493990 to add syntax highlighting
