### ISSUE TITLE
More inclusive language in the docs

### ISSUE THREAD

**Issue by carolstran** [sinonjs/sinon#2139]
:wave: Sorry I know I'm ignoring all of your well-thought out templates, but I wasn't sure where this would land! Here me out...

I noticed that there are many instances of the word "simply" in your documentation. Unfortunately, words like this can make people feel frustrated and isolated while reading (myself included, hence the issue) - especially if they are facing issues.

If it's alright with your team, I'd like to take a shot at updating the content to make it more inclusive by removing instances of "simply", "easy", "just", etc. I'm part of the team behind [Unmock](https://github.com/unmock/) and we're using Sinon quite a bit, so I'm happy to help 😊  

Also if you're interested or want more information on this topic, I'd highly recommend watching Jim Fisher's [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) talk from Write the Docs Prague 2018 ✍️ 🤓 

Thank you for the work you do and please let me know if you need more details!

**Comment by mroderick** [comment]
Improving the language of the documentation would be most welcome! 👏

**Comment by carolstran** [comment]
Yay! I'm on it 🚀

And @mroderick, SAME 🙈 I've always been pretty careful about simply, but "just" has recently come to my attention especially because I tend to use it when explaining things out loud 😬

**Comment by mroderick** [comment]
"Can't we just ...?" 😱

**Comment by fatso83** [comment]
I have a branch lying somewhere where I trimmed the docs to a single release for each major (basically the latest version for each major). I guess I should finish that ... :)

**Comment by carolstran** [comment]
Thanks stale bot! This totally fell off my plate, but I have some time this week where I can work on it 😊
