### ISSUE TITLE
Issue with stubbing a method of an ES6 class

### ISSUE THREAD

**Issue by kchanna** [sinonjs/sinon#2142]
**Describe the bug**
I'm having trouble mocking an ES6 class at a prototype/class level.

I searched quite a bit and couldn't get a proper answer. Hence asking again.
I can stub an object easily, but not able to stub a prototype/class.

Is it even possible to stub a class method in Sinon?

**To Reproduce**
```javascript
/*
 * TestJSClass class
 */
export default class TestJSClass {
    methodA = (a) => {
        console.log("Called methodA with parameter:" + a);
    }

    methodB = () => {
        console.log("Called methodB  (true)");
        return true;
    }

    methodC = () => {
        console.log("Called methodC  (false)");
        return false;
    }

    methodD = () => {
        console.log("Called methodD  (100)");
        return 100;
    }
};
```
Tests
```javascript
describe("helpers: TestJSClass", () => {
    beforeEach(() => {

    });

    afterEach(() => {
    });

    it("Test TestJSClass object", () => {
        const obj = new TestJSClass();

        obj.methodA();
        assert((obj.methodB() === true), "Should return true");
        assert((obj.methodC() === false), "Should return false");
        assert((obj.methodD() === 100), "Should return 100");
    });

    it("Test TestJSClass object, by overriding (mocking) methods", () => {
        const obj = new TestJSClass();

        obj.methodA();
        const stub1 = sinon.stub(obj, "methodB").returns(false);
        const stub2 = sinon.stub(obj, "methodC").returns(true);
        const stub3 = sinon.stub(obj, "methodD").returns(200);

        assert((obj.methodB() === false), "Should return false");
        assert((obj.methodC() === true), "Should return true");
        assert((obj.methodD() === 200), "Should return 200");

        stub1.restore();
        stub2.restore();
        stub3.restore();
    });

    it("Test TestJSClass prototype object, by overriding (mocking) methods", () => {
        const stub1 = sinon.stub(TestJSClass, "methodB").returns(false);
// This also doesn't work:   const stub1 = sinon.stub(TestJSClass.prototype, "methodB").returns(false);

        const obj = new TestJSClass();

        obj.methodA();

        assert((obj.methodB() === false), "Should return false");
        assert((obj.methodC() === false), "Should return false");
        assert((obj.methodD() === 100), "Should return 100");

        stub1.restore();
    });

});
```

**Expected behavior**
I should be able to stub a class at a prototype/class level. If I run the above test, the third test fails.
Test TestJSClass object		PASS
Test TestJSClass object, by overriding (mocking) methods		PASS
Test TestJSClass prototype object, by overriding (mocking) methods	FAIL  Cannot stub non-existent own property methodB

The third test fails with the error: Cannot stub non-existent own property methodB

**Screenshots**
![sinon_issue](https://user-images.githubusercontent.com/7152633/66730550-18b87380-ee70-11e9-9178-0b238cf59697.png)

**Context (please complete the following information):**

* Library version: 7.5.0
* Environment: MAC
* Example URL:
* Other libraries you are using:

**Additional context**
How do I mock/stub the method of a class at a prototype/class level.

**Comment by fatso83** [comment]
See meta-issue #1121  and the headline "Cannot stub arrow function in a class #1136". 

> I should be able to stub a class at a prototype/class level. 

You are able to do that. But your methods are not there. They are _instance_ properties of the object, not its prototype, so this has nothing to do with the prototype at all, which is why your tests fail. You need to revisit _what an arrow function does_ and _where_ your functions are actually created. Try using a Babel sandbox to see what the resulting ES5 code would look like. 

I wrote an explanation in #1136. Feel free to reopen this if it's not sufficient :-)

**Comment by kchanna** [comment]
Aaarrgghhh.. Arrow functions... I keep forgetting that I've used "Arrow functions".
It has caused much heartache, before also.
Arrow functions can seriously lead you to look in another directions, if there's an issue.


It worked for me now. Thank you so much. The new code:

`/*
 * TestJSClass class
 */
export default class TestJSClass {
    methodE(a) {
        console.log("Called methodA with parameter:" + a);
    }

    methodF() {
        console.log("Called methodB  (true)");
        return true;
    }

    methodG() {
        console.log("Called methodC  (false)");
        return false;
    }

    methodH() {
        console.log("Called methodD  (100)");
        return 100;
    }
};
`

Test class:
`describe("helpers: TestJSClass", () => {
    beforeEach(() => {

    });

    afterEach(() => {
    });

    it("Test TestJSClass prototype object, by overriding (mocking) methods 1", () => {
        const stub1 = sinon.stub(TestJSClass.prototype, "methodF").returns(false);
        const stub2 = sinon.stub(TestJSClass.prototype, "methodG").returns(true);
        const stub3 = sinon.stub(TestJSClass.prototype, "methodH").returns(300);

        const obj = new TestJSClass();

        obj.methodA();

        assert((obj.methodF() === false), "Should return false");
        assert((obj.methodG() === true), "Should return true");
        assert((obj.methodH() === 300), "Should return 300");

        stub1.restore();
        stub2.restore();
        stub3.restore();
    });
});
`
