### ISSUE TITLE
Stubs donesn't work on specifics tests when existis multiple test cases

### ISSUE THREAD

**Issue by lukaswilkeer** [sinonjs/sinon#2157]
**Describe the bug**
Same as #1119 

**To Reproduce**
Wrote a pseudocode to reproduce the beheavior.
```js
import { expect } from 'chai'
import sinon from 'sinon'

afterEach(() => sinon.restore())

describe('test scenario 1', () => {
    it('shold do some stuf', (done) => {
        const modelStub = sinon.stub(Model.prototype, 'save')
        .resolves(itensMock)

        expect(itens).to.have.lengthOf(3)
        done()
    })
})

describe('test scenario 2', () => {
    it('shold do some stuf', (done) => {
        const modelStub = sinon.stub(Model.prototype, 'save')
        .resolves(itensMock)

        expect(itens).to.have.lengthOf(1)
        done()
    })
})
```

**Expected behavior**
Sinon to restore each stub after done was called when this doens't occur. In some test cases the stub doens't apply and the db ins invoked.

**Screenshots**
![error](https://user-images.githubusercontent.com/1809628/68529063-3cd56c00-02d9-11ea-8051-2094a7a3b723.png)

**Context (please complete the following information):**

* Library version: Sinon 7.5.0
* Environment: Debian/RHEL
* Other libraries you are using:

- babel

**Comment by fatso83** [comment]
Hi, thank you for the issue. Are you able to to make a reproducible example? We cannot use this to debug the issue (which we have yet to see). And it's not really a duplicate, seeing the issue you linked to is fixed in v2+.

**Comment by lukaswilkeer** [comment]
The error was a mistake on tests. A model call that doens't haven't stubed.

**Comment by fatso83** [comment]
Ok, I interpret that as a close as no issue order :)
