### ISSUE TITLE
current state of setter/getter spies

### ISSUE THREAD

**Issue by 43081j** [sinonjs/sinon#2160]
7.2.3:
https://sinonjs.org/releases/v7.2.3/spies/#using-a-spy-to-wrap-property-getter-and-setter

7.2.4 and onwards don't have this section of the docs.

For a patch release to remove a piece of functionality would be very questionable in terms of versioning so i assume the logic is still there in the source.

However, can someone please clear up what the situation is?

* Can we still spy on setters/getters this way?
* Where did the docs go?
* What is returned, if it works? a property descriptor? so it has a special signature different to all other spy calls?

Maybe the docs just went walkies by accident?

**Comment by fatso83** [comment]
Well spotted. If you have any chance to do a forensic of this by using `git blame` and `git log -p` on the affected files, you might spot the actual reason in the log descriptions (and/or PR text).

I don't know/remember, but you might be right that it's accidental.

**Comment by 43081j** [comment]
https://github.com/sinonjs/sinon/commit/714911ee19f237f7b5ef10d04ba3afb4b1c705a5#diff-2969afd226e75d3e2d257a1ab427d503

but no obvious reason why

**Comment by fatso83** [comment]
Something mysterious has been going on. I have hunch to what it is. The link you posted to the commit shows the diff for the _generated_ docs for the latest version. That is always generated from `release-source/release/spied.md`. Looking at that, I see no mention of getters and spies: 
https://github.com/sinonjs/sinon/commits/master/docs/release-source/release/spies.md

**Comment by fatso83** [comment]
And here it is: https://github.com/sinonjs/sinon/commits/714911ee19f237f7b5ef10d04ba3afb4b1c705a5/docs/_releases/latest/spies.md.

It shows the PR #1976 by @salomvary added this section to the _generated_ docs, not the source, and we were unable to catch it.

Would you like to reintroduce them, @43081j?

**Comment by fatso83** [comment]
And with regards to return types you seem to be right. In the case of using `types` (get/set), the descriptor will be passed as the third argument (`method`) to wrapMethod, which returns this argument after mutating it. Ref https://github.com/sinonjs/sinon/blob/master/lib/sinon/spy.js#L188

**Comment by 43081j** [comment]
great, thanks for looking into it.

i was fixing up the typescript types, turns out they've been wrong for some time 🙈 PR is open anywho
