### ISSUE TITLE
Spy not working on function

### ISSUE THREAD

**Issue by ericmorand** [sinonjs/sinon#2162]
**Describe the bug**

Using sinon 7.5.0, spying a function that is _not_ part of an object doesn't work as expected.

https://sinonjs.org/releases/v7.5.0/spies/#creating-spies-sinonspy-method-signatures

**To Reproduce**

```js
const {spy} = require('sinon');

let f = () => {

};

let s = spy(f);

f();

console.warn(s.called); // false

let obj = {
    f: () => {

    }
};

s = spy(obj, 'f');

obj.f();

console.warn(s.called); // true

```

`s.called` should return `true` in both cases.

**Comment by fatso83** [comment]
Hi, @ericmorand. This is just a misunderstanding of how spies and stubs work. The created spy needs to "live" somewhere. If you spy on a method of an object, Sinon will replace the original function in that "namespace". If a function doesn't exist as a property on _something_, which reference should Sinon really replace? Sinon doesn't do anything "magical", it's just Javascript, so think about how you would solve this. You might find out it might not be solvable :)

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by ericmorand** [comment]
@fatso83, it's not a misunderstanding. It's in the doc:

https://sinonjs.org/releases/v7.5.0/spies/#creating-spies-sinonspy-method-signatures

> var spy = sinon.spy(myFunc);
> Spies on the provided function

That it may not be possible is not the issue there. I'm not supposed to know the internals of Sinon and if the doc says that you found a way to spy on a local function, I have no reason to believe otherwise.

**Comment by fatso83** [comment]
Aha, that's a different matter!. Then that's poor wording which needs to be fixed. It should say something like "Wraps the function in a spy. You can pass this spy instead of the original function when you need to verify how a function is being used."

Would you care to update the issue to reflect the new content?

**Comment by ericmorand** [comment]
> Wraps the function in a spy. You can pass this spy where original function would be passed when you need to verify how the function is being used.

Much better wording, definitely.
