### ISSUE TITLE
Http response mocking doesnt work for $.ajax() with cache: false

### ISSUE THREAD

**Issue by smitalm** [sinonjs/sinon#2172]
**Describe the bug**
I am using sinon to mock response to ajax requests made with jquery. 
If i set `cache: false` on request, fake server mocking doesnt work. If i set `cache: true`, it works.

**To Reproduce**
```javascript
it('Test', function() {
    const server = sinon.createFakeServer();
    server.autoRespond = true;

    server.respondWith('/test', [
        200, { 'Content-Type': 'application/json' }, '{"test": "test"}'
    ]);

    return $.ajax({
        'Content-Type': 'application/json',
        method: 'GET',
        cache: false, // true works (response mocked correctly), false doesnt
        url: '/test'
    }).promise()
        .then((data) => {
            console.log(data);
            return data;
        }, (e) => {
            console.error(e);
            return Promise.reject(e);
        });
});
```

**Expected behavior**
Response should be mocked regardless of cache setting. 

* Library version: 7.5.0
* Environment: Jest unit test
* Example URL:
* Other libraries you are using: Jest, jQuery

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
