### ISSUE TITLE
Sinon indirectly depends on two major versions of samsam

### ISSUE THREAD

**Issue by mantoni** [sinonjs/sinon#2177]
**Describe the bug**

```bash
❯ npm ls @sinonjs/samsam
sinon@7.5.0 /Users/max/projects/sinon
├─┬ @sinonjs/formatio@3.2.2
│ └── @sinonjs/samsam@3.3.3
├─┬ @sinonjs/referee@3.2.0
│ └── @sinonjs/samsam@3.3.3
└── @sinonjs/samsam@4.2.0
```

While nothing breaks, this has the negative side effect that `@sinonjs/samsam` v3 depended on `lodash` which is therefore bundled with sinon, which accounts for half the bundle size.

**To Reproduce**

Install `disc` globally and run

```bash
❯ node_modules/.bin/browserify ./lib/sinon.js --no-detect-globals --full-paths --standalone sinon | discify --open
```

This opens an interactive sunburst chart in the browser showing file sizes. You can see that lodash is > 500 KB large.

**Expected behavior**

Lodash shouldn't ship with sinon as we only need a tiny fraction of the functionality. This has been addressed with `@sinonjs/samsam` v4 already.

<img width="712" alt="Bildschirmfoto 2019-12-20 um 12 39 06" src="https://user-images.githubusercontent.com/332271/71252606-c25f2980-2325-11ea-933a-dcdeb10a8b90.png">

**Comment by fearphage** [comment]
FYI `npx` is available in modern node versions so this simplifies the repro steps:

```shell
npx browserify ./lib/sinon.js --no-detect-globals --full-paths --standalone sinon | npx disc --open
```

Also to simplify things like this, I add `./node_modules/.bin` to my `PATH` to save some typing:

```shell
export PATH=$PATH:./node_modules/.bin
```
