### ISSUE TITLE
@sinonjs/commons version in Sinon v8 is out of date

### ISSUE THREAD

**Issue by forehalo** [sinonjs/sinon#2180]
**Describe the bug**

After bump up sinon version to v8, the dependency @sinonjs/commons version is still kept at v1.4.0 which has incompatible api required by sinon

[https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/next-tick.js#L3](https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/next-tick.js#L3)

**Screenshots**
![image](https://user-images.githubusercontent.com/8281226/71335923-f897e580-257f-11ea-9689-139222262897.png)

**Context (please complete the following information):**

* Library version: v8.0.0

**Comment by mantoni** [comment]
This has been fixed with Sinon 8.0.1. Thank you for reporting ❤️

**Comment by forehalo** [comment]
@mantoni @mroderick Thank you all for the quick fixing
