### ISSUE TITLE
Since upgrading to Sinon v8 my tests involving Sinon.match.func now fail.

### ISSUE THREAD

**Issue by davesag** [sinonjs/sinon#2183]
**Describe the bug**
I have a test as follows

```js
it('called validateFields with the complete set of params and the validation rules', () => {
  expect(validateFields).to.have.been.calledOnceWith(
    match(fullParams),
    match(validations)
  )
})
```

where `fullParams` are simple `{ name: 'some string or numeric value' }` and
`validations` are either `{ name: 'a string', or_name: match.func }`

If the `validations` object only contains string values it all works fine, but if it contains `match.func` then it fails.

This worked fine in Sinon 7 but fails in Sinon 8.  I've traced the failure down to the use of `sinon.match` and `sinon.match.func`.

### Details.

* Library version: 8.0.1
* Environment: Running with Mocha and sinon-chai
* Example URL: https://github.com/davesag/ir-api/blob/2e170f2d91d5715427862fda8078272e50c76442/test/helpers/privateHandlerTest.js#L92-L97
* Other libraries you are using: mocha, sinon-chai, chai, chai-as-promised (and others, see https://github.com/davesag/ir-api/blob/2e170f2d91d5715427862fda8078272e50c76442/package.json#L46-L72)

**Comment by mroderick** [comment]
This is an interesting one!

As far as I've been able to determine using `git bisect`, the first failing commit is 5bb2273ac2fabfc112269fa6d304a73147a2777a, where `@sinonjs/samsam` is upgraded.

I've not yet been able to determine which change in `@sinonjs/samsam` was the first that causes  the tests to fail.

**Comment by 43081j** [comment]
I figured it out FYI. I'll push a pr if nobody else does some time soon (though it is Christmas after all so may be tomorrow 😂)

It's just a match function not being passed down in the recursion inside samsam

**Comment by mroderick** [comment]
`@sinonjs/samsam@4.2.1` is out. If you re-install / update your lock files, this issue should be gone.
