### ISSUE TITLE
Proposal: Support negative indices for getCall

### ISSUE THREAD

**Issue by RealZogger** [sinonjs/sinon#2196]
The API currently provides:
`getCall(n)`
`getFirstCall`
`getSecondCall`
`getThirdCall`
`getLastCall`

Some functions in js support negative indices to get elements from the end of the array (e.g. `arr.slice(-2)` returns the last 2 elements of an array).

Currently, `getCall(-n)` returns null

The proposal is to support negative indices to get previous calls, for example
`getCall(-1)` would be equivalent to `getLastCall`
`getCall(-2)` would be the second last call.
`getCall(-n)` where n > the number of calls would return `null`

**Comment by fatso83** [comment]
Have a look at the implementation and see to what degree it would complicate the implementation. You would essentially need to create a circular buffer so that a pointer could be shifted to keep things in sync for each call. That's quite a different beast from simple arrays, and I am not all that sure it's worth it given that this is the first time I heard someone have a need for it in the ten years Sinon existed :-)

**Comment by RealZogger** [comment]
well, from what I've seen I think it's a one line change - At the start of the getCall function, if a negative index is supplied, add the length of the array to the passed in index and get that index instead.

I'm wrapping around getCall in my tests to do effectively this and it works fine.

My use case is that I am running async tests on a vscode extension using the vscode-test package. I'm stubbing a particular function in the vscode API, and I know that the function should be called twice just before resolving.

However the vscode test package runs up the ide so it's technically possible for someone running the text to interfere with the test by accident, perhaps clicking something.

Obviously the IDE should be left alone but for the sake of being a bit more robust against this kind of thing I'm getting the last two calls to the function as these must be the calls I'm interested in.

It's not a majorly important feature for me and quite a niche case, but I thought I would raise it to see if anyone thought it was worthwile

**Comment by fatso83** [comment]
If it seems relatively simple to implement, just have a go at it :smiley_cat:
