### ISSUE TITLE
Allow to stub named functions without default exports or *

### ISSUE THREAD

**Issue by gilian1993** [sinonjs/sinon#2220]
**Is your feature request related to a problem? Please describe.**
When I have to stub a named function I currently do something like:
```
import * as i18n from "@/i18n";
sinon.stub(i18n, "useTranslation").value(() => ({
	t: sinon.stub().returnsArg(0)
}));
```
In this case my `@/i18n` module has no default exports and only named exports.

**Describe the solution you'd like**
It would be nice if I could stub that module/function like so:
```
import { useTranslation } from "@/i18n";
sinon.stub(useTranslation).value(() => ({
	t: sinon.stub().returnsArg(0)
}));
```
This will make the "wildcard" import obsolete and makes for (in my opinion) much cleaner code.

**Comment by fatso83** [comment]
What you are asking is not possible - at least in javascript. When you _stub_ something, it means you replace _something_ on the _object_ with a different implementation. If all Sinon sees is `someFunction`, how can it know which object it is supposed that function is "owned" by? Javascript's object model further complicates the issue, with prototypes, the ability to "loan" functions from other objects, etc. A function is really not owned by anything but itself.
