### ISSUE TITLE
spy arguments list reflects current state of objects and does not reflect the state of objects from when the spy was called

### ISSUE THREAD

**Issue by dannymarsland** [sinonjs/sinon#2222]
**Describe the bug**
The spy arguments list reflects current state of objects and does not reflect the state of objects from when the spy was called. Is this intentional and an occupational hazard or is there a way around this behaviour?

**To Reproduce**
```javascript
const obj = {
  fn:  (input) => {}
};
const stub = sinon.stub(obj, 'fn');
const arg = {
  value: 1
  }
obj.fn(arg);
arg.value = 2
obj.fn(arg);
console.log(stub.firstCall.args); // output: [ { value: 2 } ] . expected: [ {value: 1 }]
```

**Expected behavior**
Spy argument lists to contain the state of the object from when the spy was actually called

* Library version: 8.1.1

**Comment by fatso83** [comment]
Giving you the argument by reference and not by value _is by design_.

The spy gives you _the argument_ with which the function was called. It does not do time travel. It _is_ the object, not the object as it was at any given time, as representing a snapshot of that object varies from use-case to use-case. Deep cloning all objects would both be wasteful, usually not what people want and also entails surprises of their own. What value would a snapshot of an object with a  circular reference look like, for instance? Or a snapshot of an object that was created using the module pattern? Some of these things have no correct answer.

If you want some kind of snapshotting functionality you need to implement this yourself by using the `stub` or `fake` interface with a custom stub. Something like this:

```javascript
function createFakeWithArgumentSnapshots(){
  const clone = (argument) JSON.parse(JSON.stringify(argument));
  const fake = sinon.fake((arg) {
    fake.callSnapshots.push(clone(arg));
  });
  fake.callSnapshots= [];
  return fake;
}

const myFake = createFakeWithArgumentSnapshots();
sinon.replace(obj, 'fn', myFake);

....
console.log(myFake.callSnapshots[0])
```
