### ISSUE TITLE
HTTP Server should document how you simulate offline behaviour 

### ISSUE THREAD

**Issue by tarjei** [sinonjs/sinon#2236]
**Is your feature request related to a problem? Please describe.**
I tried to find documentation on how to setup the fakeServer to respond like the server is offline, i.e. not answering any requests.

**Describe the solution you'd like**

# Offline handling

To test how your client works when there is no connectivity with the server you can use a respond method like this:

```js
server.respondWith("GET", "/some/article/comments.json", (res) => {
   throw new Error("offline") // or something else
})
);

```

**Comment by mroderick** [comment]
Thank you for taking the time to create an issue for the missing documentation 💯 

Would you like to contribute a PR to fix the documentation?

**Comment by tarjei** [comment]
@mroderick I would if I knew the answer to the part "or something else" in the part above :)

If someone can give me the correct way to simulate offline handling in sinon, I'll contribute the docs.

**Comment by fatso83** [comment]
@mroderick For a long time I was browsing docs to find examples on how to use the server functionality for Tarjei, and only now did I realize this is almost a feature request. Or a question if we have a certain feature. 

With that in mind, TBH I do not know how to do this or if we explicitly have a way to handle it. I _do see_ we have explicit [support for simulating errors in XHR](https://github.com/sinonjs/nise/blob/master/lib/fake-xhr/index.test.js#L1383), with well-defined (w3c) behavior.

There is nothing indicating support for this in our test suite, AFAIK: https://github.com/sinonjs/nise/blob/master/lib/fake-server/index.test.js

My guess is that we do not have a way of setting error state on the XHR using the server interface. Which might make sense, given that you are simulating a server, not the client side of a network connection (which is what the XHR is supposed to cover). Maybe you can just use the Fake XHR for this?

**Comment by mroderick** [comment]
> @mroderick For a long time I was browsing docs to find examples on how to use the server functionality for Tarjei, and only now did I realize this is almost a feature request. Or a question if we have a certain feature.

Thanks!

**Comment by tarjei** [comment]
The closest thing I found was the `response.error()` method. It seems to end up simulating the same behaviour as a network error when used with my framework (superagent). I found it after filing this request. If `response.error()` is the correct way I can file a PR.

**Comment by fatso83** [comment]
@tarjei This does seem to indicate a lack in our docs, so if this seems to achieve your intended goal, then please do supply a PR :-)

**Comment by tarjei** [comment]
Sorry, smorry, corona. I'll try to put together a PR soon!
