### ISSUE TITLE
`sinon.restore()` not working

### ISSUE THREAD

**Issue by Rauno56** [sinonjs/sinon#2242]
**Describe the bug**

`sinon.restore()` doesn't seem to be working. I must be doing something wrong.

**To Reproduce**

```js
// install sinon first: `npm install sinon@9.0.1`

const assert = require('assert');
const sinon = require('sinon');

const spy = sinon.spy(() => 'called');
console.log('spy', spy(), spy.callCount);

sinon.restore();

assert.equal(spy.callCount, 0);
```

**Expected behavior**

Expect `sinon.restore()` to set `callCount` back to 0 and the script :point_up: not to error.

**Context:**

* Library version: 9.0.1
* Environment: linux,  tested on node@12.16.1 and node@13.12.0

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
