### ISSUE TITLE
Stub replaces function in test file where i have imported it, but not in the actual code

### ISSUE THREAD

**Issue by IlyaGaluza** [sinonjs/sinon#2248]
Hi. I have this issue for a pretty long time. 
[In one file, lets call it base.js i have the following:
```
export const async getUsersData() //some code here
export const getProfileData()
```
in second.js:
```
import * as controller from '../base.js'
...
await controller.getUsersData()
```
So i want to stub  getUsersData in order to return specific data for testing from it

In test.js:
```
`mport sinon from 'sinon'
import * as controller from '../base.js'
const userStub = sinon.stub(controller, 'getUsersData');
```
So the issue is that it dont replace this getUsersData method. 
I'm doing
```
console.log(controller)
```
in both `second.js` and `test.js`. And in test original method is replaced by stub, but not in the `second.js`. Controller in `second.js` has its original methods. Looks like stub is only replacing method in `test.js` and don't take effect in any other files

**Comment by mustafaKamal-fe** [comment]
did you get this to work?

**Comment by fatso83** [comment]
@mustafaKamal-fe We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. Your question looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

The answer to the question is entirely dependant on the environment you are running and/or building the code in (pure ESM, transpilation, ...), so it needs much supporting code and information.
