### ISSUE TITLE
9.0.2 is missing from everywhere except NPM

### ISSUE THREAD

**Issue by epmatsw** [sinonjs/sinon#2250]
**Describe the bug**
https://www.npmjs.com/package/sinon shows that 9.0.2 is the latest release. However, all other sources seem to agree that 9.0.1 is the most recent release:
* https://github.com/sinonjs/sinon/releases
* https://github.com/sinonjs/sinon/blob/f29baf7dd74c42934f8e1a067b08f9f75933b574/CHANGELOG.md
* https://github.com/sinonjs/sinon/blob/f29baf7dd74c42934f8e1a067b08f9f75933b574/package.json#L4
* https://sinonjs.org/releases/

I'm sure that it's just a CI issue or missed push, but it'd be good to get confirmation of that.

**To Reproduce**
1. Go to https://www.npmjs.com/package/sinon. See that 9.0.2 exists.
2. Go to https://github.com/sinonjs/sinon/releases. See that 9.0.2 doesn't exist.
3. Worry that 9.0.2 is a compromised release.

**Expected behavior**
9.0.2 should exist at all places.

**Comment by austince** [comment]
It seems the `9.0.2` NPM tag is being frequently republished as well, leading my paranoia to hover around step #3...

**Comment by epmatsw** [comment]
From what I can tell, the diff between the current 9.0.2 and 9.0.1 is harmless, so I don't think there's too much to worry about here.

**Comment by mroderick** [comment]
This was a mistake by me.
I published `v9.0.2` to npm, but failed to push the tag to this repository.

This has happened before, and until we implement [`@studio/changes`](https://github.com/javascript-studio/studio-changes) in this repository, as we have in several other sinon projects.

If anyone would like to contribute a PR to do that, then the implementation in `@sinonjs/samsam` is working well, and can be used for inspiration:

https://github.com/sinonjs/samsam/blob/master/package.json#L29-L31

**Comment by austince** [comment]
Thanks for the update @mroderick, I've also had success with [semantic-lease](https://github.com/semantic-release/semantic-release) and found it very easy to set up as well.

**Comment by mroderick** [comment]
> I've also had success with [semantic-release](https://github.com/semantic-release/semantic-release) and found it very easy to set up as well. Unless you're tied to `@studio` for other reasons, would you consider that as an alternative?

We're not particularly tied to using the `@studio/changes` package, other than it does the job for the other projects and is familiar, because it is made by one of the Sinon maintainers.

I think it would be worth exploring `semantic-release` as well. Would you mind creating a new issue and describe what adopting `semantic-release` would entail?

**Comment by epmatsw** [comment]
@mroderick thanks for the clarification on this. If you want to keep conversation going in here we can leave this open, otherwise I'm fine closing if you are!
