### ISSUE TITLE
Integrity Check failed

### ISSUE THREAD

**Issue by kishanravindra** [sinonjs/sinon#2252]
**Describe the bug**
On yarn add sinon. We are facing below Issue.
error https://registry.yarnpkg.com/jest-haste-map/-/jest-haste-map-24.9.0.tgz: Integrity check failed for "jest-haste-map" (computed integrity doesn't matc
h our records, got "sha512-kfVFmsuWui2Sj1Rp1AJ4D9HqJwE4uwTlS/vO+eRUaMmd54BFpli2XhMQnPC2k4cHFVbB2Q2C+jtI1AGLgEnCjQ== sha1-s4pdZCdJNOIfpBeump++t3zqrH0=")

**Comment by mroderick** [comment]
That doesn't look like a problem with Sinon.

In a clean project

```shell
$ yarn add sinon
yarn add v1.17.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 15 new dependencies.
info Direct dependencies
└─ sinon@9.0.2
info All dependencies
├─ @sinonjs/commons@1.7.2
├─ @sinonjs/fake-timers@6.0.1
├─ @sinonjs/formatio@5.0.1
├─ @sinonjs/samsam@5.0.3
├─ @sinonjs/text-encoding@0.7.1
├─ diff@4.0.2
├─ has-flag@4.0.0
├─ isarray@0.0.1
├─ just-extend@4.1.0
├─ lodash.get@4.4.2
├─ nise@4.0.3
├─ path-to-regexp@1.8.0
├─ sinon@9.0.2
├─ supports-color@7.1.0
└─ type-detect@4.0.8
✨  Done in 1.52s.
```

As you can see, the dependency is not installed by Sinon.

```shell
npm ls jest-haste-map
/Users/morgan/code/sinon-2252
└── (empty)
```

By now you have probably solved your problem and moved on. Next time, please be a good sport and update the issues you open with what you learn, and close them when possible. That will save maintainers of open source projects valuable time. Thanks.
