### ISSUE TITLE
Stub doesn't replace imported from node_modules

### ISSUE THREAD

**Issue by drinkingChai** [sinonjs/sinon#2253]
**Describe the bug**
When importing from a local file in the repo, i.e. from `./test_module'`, and stubbing it via the `stub` function, it works. However, if `test_module` is installed via npm/yarn, it doesn't work.

**To Reproduce**
1. Install some module via npm/yarn. For this example, say some 'test_module'.
2. Create some function to test:
```
// myFn.js
import {fooFn} from 'test_module';

export const myFn = () => {
  // call fooFn
  fooFn();
};
```
3. Create a test file in an adjacent directory __tests__, and do the following:
```
import module from 'test_module';
import {myFn} from '../myFn';

describe('...', () => {
  it('...', () => {
    const fooFnStub = stub(module, 'fooFn').returns('foo');
    
    // call your function
   myFn();

   console.log(fooFn.callCount); // <-- this will be 0, it should be 1
  });
});

```

**Expected behavior**
Stub should replace functions in node_modules.

**Context (please complete the following information):**

* Library version: '6.1.5' (tried with latest 9.0.2, same issue)
* Environment: node 10.16.3

**Comment by rgroothuijsen** [comment]
See also #1711 for a similar case, where it's noted that stubbing dependencies like this is out of Sinon's scope. [The documentation](https://sinonjs.org/how-to/stub-dependency/) provides some possible alternatives.
