### ISSUE TITLE
Return function from addFilter to remove the filter just added.

### ISSUE THREAD

**Issue by luc-tielen** [sinonjs/sinon#2254]
**Is your feature request related to a problem? Please describe.**
In a test suite at work we have to enable a filter for only a small set of tests, but we have to disable it afterwards again for the other tests. 

**Describe the solution you'd like**
Right now, addFilter just pushes the filter function onto the existing XHR filters.
It would be cool if we can do something like this:
```
describe("some description", () => {
  let removeFilter;
  beforeEach(() => {
    removeFilter = sandbox.server.xhr.addFilter(filter);
  });

  afterEach(() => {
    removeFilter();
  })
});
```

Implementation can be as simple as:
```
FakeXMLHttpRequest.addFilter = function addFilter(fn) {
  this.filters.push(fn);
  var removeFilter = function() {
    this.filters = this.filters.filter(
      function(filter) { return filter !== fn; }
    );
  };
  return removeFilter;
};
```

**Describe alternatives you've considered**
None, this is what I ended up using at work (with a helper function wrapping sinon). :sweat_smile:

**Additional context**
/

**Comment by mantoni** [comment]
Thank you submitting this proposal. There should centrainly be a way to remove and I like your proposal.

However, there are two more questions coming to my mind:

- Why are the `filters` shared between fake server instances? Shouldn't it be re-created with every call to `useFakeServer()`?
- Shouldn't `sinon.reset()` also clear the request filters?
