### ISSUE TITLE
Recursive setTimeout call with promise and useFakeTimers

### ISSUE THREAD

**Issue by cainrus** [sinonjs/sinon#2256]
When I use useFakeTimers then setTimeout will not be called recursively after promise is resolved.

**To Reproduce**
https://gist.github.com/cainrus/a3023be217add3bc8e162ec95a3ec843

**Current output**
```
 MOCHA  Testing...



  StoreManager
    synchronization
1
2
3
1
      1) 111222


  0 passing (2s)
  1 failing

  1) StoreManager
       synchronization
         111222:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/serg/projects/work/leon-front3/packages/web/dist/js/main.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

**Expected behavior**
Expected console output:
```
1
2
3
1
2
3
1
2
3
```

**Screenshots**

**Context (please complete the following information):**

* Library version: _please verify that the bug exists in the latest release_
* Environment:
node v12.15.0
mocha "6.2.3"
sinon "7.5.0"

**Comment by rgroothuijsen** [comment]
`tick()` works for synchronous functions, and `tickAsync()` produces a result closer to what would be expected. You can then evaluate your assertion in the promise returned by `tickAsync()`.

**Comment by cainrus** [comment]
@rgroothuijsen, thank you. Used `sinon@7` within project, there were no `tickAsync` api
