### ISSUE TITLE
(BUG) SINON <> DELAY - Bug when using Sinon 'useFakeTimers' and Delay

### ISSUE THREAD

**Issue by ViniciusFXavier** [sinonjs/sinon#2264]
**Describe the bug**
When using Sinon in my project to test my application, I realized that the test never stopped running and after some time I ended up discovering this "incompatibility".

**To Reproduce**
Here is an example code to reproduce the problem:
```js
const sinon = require('sinon'); // 9.0.2
const delay = require('delay'); // 4.3.0

async function run() {
  sinon.useFakeTimers(1590721200000);
  await delay(1000);
  console.log('This message will never be executed !!!');
}
run();
```

**Additional context**
Issue in [DELAY](https://github.com/sindresorhus/delay/issues/49): https://github.com/sindresorhus/delay/issues/49

**I don't think it's a problem in either repository, I just need help trying to solve it, maybe a work around.**

**Comment by rgroothuijsen** [comment]
If you add a `tickAsync()` before the `await`, it will continue:

```
   async function run() {
      var timer = sinon.useFakeTimers(1590721200000);
      timer.tickAsync(1000);
      await delay(1000);
      console.log('This message will never be executed !!!');
   }
```
