### ISSUE TITLE
stub readonly property throw "Cannot stub non-existent property"

### ISSUE THREAD

**Issue by ljian3377** [sinonjs/sinon#2266]
**Describe the bug**
* Library version: 9.0.2

**To Reproduce**
```
import * as sinon from "sinon";
class B {
    public readonly a: string;
    public get(): void {}
}

const bStub = sinon.createStubInstance(B);
sinon.stub(bStub , "a").value("test");

// let b = new B();
// sinon.stub(b, "a").value("test");
```
**Expected behavior**
stub properly.

There is an old issue mentioning the same issue but is closed with a comment that is not quite helpful for me. https://github.com/sinonjs/sinon/issues/829

**Comment by ljian3377** [comment]
However, assigning value beforehand to the property, then the stub will work. But I really don't want to invoke the constructor as it's prettty complicated.

```
import * as sinon from "sinon";

class B {
    public readonly a: string;
    public get(): void {}
    constructor(aa: string) {
        this.a = aa;
    }
}

// const bStub = sinon.createStubInstance(B);
let b = new B("t");
sinon.stub(b, "a").value("test");
console.log(b.a);
```
output: test

**Comment by ljian3377** [comment]
Currently working around with directly assigning to the stub object.
```
import * as sinon from "sinon";

class B {
    public readonly a: string;
    public get(): void {}
    constructor(aa: string) {
        this.a = aa;
    }
}

const bStub = sinon.createStubInstance(B);
(bStub as any).a = "test";
console.log(b.a);
```
output: test

**Comment by mroderick** [comment]
We have made conscious decision to not allow stubbing non-existent properties, as that would make for some very confusing scenarios.

The submitted code doesn't look like JavaScript to me, I don't know how to run it.

Please create a new issue and fill in the template to save everyone some time.

**Comment by gukoff** [comment]
> We have made conscious decision to not allow stubbing non-existent properties, as that would make for some very confusing scenarios.

What are the confusing scenarios?
Would it help to add this functionality behind a flag `stub(obj, 'propertyName', forceIfNonExistent=true)` to make sure the user knows what they are doing?

**Comment by gukoff** [comment]
I see, thanks. Could you take a look if this is someting you're looking for? 
https://github.com/sinonjs/sinon/pull/2539

If yes, I could finish this PR next week.

**Comment by gukoff** [comment]
@fatso83 is this how you imagine this feature? If yes, I can finish this PR next week.

https://github.com/sinonjs/sinon/pull/2539#issue-1847072337
