### ISSUE TITLE
Undefined variable `descriptor`

### ISSUE THREAD

**Issue by adamcohenrose** [sinonjs/sinon#2271]
The `descriptor` variable is undefined at this point in the code: 
https://github.com/sinonjs/sinon/blob/e684c1ef863abb000b9775c6fcf5b2a79bd02752/lib/sinon/stub.js#L84

Since typeof an undefined variable will be undefined, this part of the logic will always be true and have no effect.

**Comment by mroderick** [comment]
Well spotted 🚀 

The line above it doesn't make much sense either ... 

The changes were introduced in https://github.com/sinonjs/sinon/commit/278c2ce66cb88e81e3752c672ed630369f15fc34

@lucasfcosta @fatso83 would you mind taking a look at this?

**Comment by fatso83** [comment]
> The line above it doesn't make much sense either ...
@mroderick not sure what you mean

As can be seen from the commit, there was a third argument at some point. This is no longer the case. We should be able to remove this with impunity 🙏

**Comment by mroderick** [comment]
> @mroderick not sure what you mean

I'm not sure anymore either. Just ignore me :)

**Comment by mantoni** [comment]
Addressed in #2289. Thanks everyone 👍
