### ISSUE TITLE
Request: expectation.withArgs() supports multiple args

### ISSUE THREAD

**Issue by neverendingqs** [sinonjs/sinon#2272]
**Is your feature request related to a problem? Please describe.**

#992 and #1193 were closed with documentation changes in #1432 that describes the current behaviour:

> An `expectation` instance only holds onto a single set of arguments specified with withArgs. Subsequent calls will overwrite the previously-specified set of arguments (even if they are different), so it is generally not intended that this method be invoked more than once per test case.

A single test may call the same mock multiple times with different arguments, but can not be written at this time due to this limitation. 

**Describe the solution you'd like**

`expectation`s can track multiple `withArgs()` call, each with their own expectations.

**Describe alternatives you've considered**

Workarounds with stubs or spies may be possible, but roughly doubles the amount of test code required (once to stub behaviour, and once to verify expectations).

**Additional context**

None

**Comment by mroderick** [comment]
None of the maintainers of Sinon are paid to work on Sinon, and none of us are using the mocking features ourselves.

That means that it is unlikely that the maintainers are going to expand or improve those features. The changes will have to come from contributors.

Having said that, we're a friendly bunch and are happy to help contributors get started.

Would you be interested in making a pull request to make the improvements yourself?

**Comment by neverendingqs** [comment]
Thansk @mroderick - makes sense to me.

I will post back if I have time to take a look.
