### ISSUE TITLE
blm

### ISSUE THREAD

**Issue by rgeerts** [sinonjs/sinon#2274]
Saw there are places where the terms blacklist/white list are used.  Consider replacing these.  

Didn't do an exhaustive search of other terms that could be offensive, but see https://twitter.com/TwitterEng/status/1278733305190342656

**Comment by mroderick** [comment]
I agree, words matter.

How about contributing a pull request to make the changes?

**Comment by Uzlopak** [comment]
There is not one place where the term blacklist was used in this project code! Only once in a comment (how to change the comment???). Also a quick search for the term "sanity", "dummy" and so on did not result in any code line affected. 

Yeah sure... rename your "master" branch to "primary" or so... 

The lazyness from OP stinks as it is easier to . Close this thread, as this is not stopping supposed racism but some person feeling better by yakshaving instead of actually solving issues.

**Comment by rgeerts** [comment]
https://github.com/sinonjs/nise/pull/167/commits/bbfc55a9a5e6061cb8234cd65b7983a7713813c1  

The yak is mostly shaved now.  But your vitriol is misplaced; much like my original suggestion may have been ignorantly misplaced not knowing how the code was divided in sub-projects. There may be other subprojects that could be improved.

**Comment by Uzlopak** [comment]
Nice, so you can close this Issue as there was no issue.

**Comment by mantoni** [comment]
@Uzlopak Your comments are not constructive and the tone is not very respectful. Please read our [Contributor Covenant Code of Conduct](https://github.com/sinonjs/sinon/blob/master/CODE_OF_CONDUCT.md).

**Comment by Uzlopak** [comment]
@mantoni 
Consider my post as freedom of speech under Article 10 of the European Convention on Human Rights, which overrides your CoC (Stichwort: mittelbare Drittwirkung von Grundrechten). 

If you disagree:
When will you rename the master-branch to primary-branch?

**Comment by Uzlopak** [comment]
This is how you can rename master to anything you want, which "improves language to respect less privileged populations"

https://stackoverflow.com/questions/8762601/how-do-i-rename-my-git-master-branch-to-release

**Comment by Uzlopak** [comment]
@rgeerts Maybe renaming the master branch is something you should also tell everyone in their projects?

**Comment by mroderick** [comment]
@rgeerts thank you for your contribution 💯

**Comment by Uzlopak** [comment]
I also thank rgeerts for his extensive work on this project.
