### ISSUE TITLE
Rename master branch to primary branch

### ISSUE THREAD

**Issue by Uzlopak** [sinonjs/sinon#2278]
Saw there are places where the term master is used. Consider replacing these.

Didn't do an exhaustive search of other terms that could be offensive, but see https://twitter.com/TwitterEng/status/1278733305190342656

also see:
https://stackoverflow.com/questions/8762601/how-do-i-rename-my-git-master-branch-to-release

**Comment by mroderick** [comment]
Thank you for raising this issue.

In our opinion, in the context of software repositories, "master" takes on the meaning of ["an original version of something from which copies can be made"](https://dictionary.cambridge.org/dictionary/english/master).

We are choosing to follow git conventions. When those conventions change, we will make appropriate changes to the Sinon repositories.
