### ISSUE TITLE
Rename master branch to primary branch

### ISSUE THREAD

**Issue by Uzlopak** [sinonjs/sinon#2279]
Unfortunately my original issue was closed without a further discussion.

Currently the primary branch is named master, which is highly racist terminology and non-welcoming to less fortunate minorities.

@mroderick argues, that the use of a master branch is a convention in git. But does this mean, that we should accept all conventions? Should we have accepted slavery in the confederate states, because it was a convention? Despite the fact that sinonjs can easily change the name of the "master"-branch to primary so the so called convention is just the initial value and not a strict rule. Maybe this is the argument of a white male, like @mroderick who can not understand why the term master is highly racist to the proud african american population and hides himself behind a dictionary, made from whites.

Please reconsider the renaming so that less fortunate minorities will be welcomed, according to the CoC.

**Comment by mshaaban0** [comment]
@Uzlopak Thank you for your sympathy, I understand your point however this change is really dependent on git convention, I don't think we can just rename all branches to primary, it will confuse a lot of people, especially junior devs.

I think the proper place to discuss this change is https://github.com/git/git

Also I kinda like this definition from Cambridge Dictionary :)

![image](https://user-images.githubusercontent.com/6163988/88234808-e5660900-cc79-11ea-8155-93b8382ab7b7.jpeg)
