### ISSUE TITLE
Renaming master branches to main

### ISSUE THREAD

**Issue by mshaaban0** [sinonjs/sinon#2282]
### Description 

Sinon is aware that the word `master` maybe offensive to some people, and in the light of [Git](url), [Github](https://github.com/github/renaming), and [IETF](https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.1) initiatives to have a clean non-offensive language, we shall follow the suggested convention.

This issue is to collect feedback, document potential downfalls, and keep track of any helpful migration tools/resources.

### Migration

[Github](https://github.com/github/renaming#what-were-changing-pencil2) is investing to provide a seamless renaming experience by the end of the year.

[Git 2.28](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch) is introducing `init.defaultBranch` to enable users to choose the default branch name for newly initialised repo. 
Accordingly, all new repos under sinonjs organisation shall have the default branch name as `main`

All repos under Sinon organisation, we will make pull requests to fix-up scripts, documentation, etc. to make the transition as seamless as possible

**Comment by mroderick** [comment]
Once GitHub have tools in place to make the transition seamless, we can make the changes without any disruption for contributors.

**Comment by fatso83** [comment]
Could we close this if we are not doing it? It's been two years and not really a big push from anyone. Not sure "main" is that much less offensive when you start digging anyway, seeing that its Germanic roots mean "force, violent effort" :smiley_cat:

**Comment by mantoni** [comment]
It's actually quite easy to do. Simply rename the branch in the settings and GitHub will show a notification on the project front page with command line instruction on how to switch to the new main branch. I've done this several times now in private repositories and it's really straight forward.

**Comment by fatso83** [comment]
Whatever floats our boat 🤷‍♀️ 

<details>The tidal wave of people pretending to care about this passed by the time Covid hit, so not sure you will find anyone that cares anymore (unless you ask Twitter).</details>

**Comment by mroderick** [comment]
I've renamed the `master` branches to `main` in all non-archived repositories. Come what may 🚀
