### ISSUE TITLE
not compatible with deno

### ISSUE THREAD

**Issue by zimtsui** [sinonjs/sinon#2288]
**Describe the bug**

when testing with deno, it says `Make sure to await all promises returned from Deno APIs before finishing test case.`

duplicated to: https://github.com/denoland/deno/issues/6138

**To Reproduce**

```ts
// a.ts
import 'https://jspm.dev/npm:sinon@9';
Deno.test('1', async () => {});
```

```sh
$deno test ./a.ts
```

**Context (please complete the following information):**

* Library version: 9.0.3
* Environment: ubuntu20.04 / x64 / deno1.3.0

**Comment by fatso83** [comment]
Closing as this issue is not an issue and no feedback was received.

**Comment by zimtsui** [comment]
i don't have the ability. but thanks very much for you group making such a useful tool of sinon 👍
