### ISSUE TITLE
Fakes - no way to override promise library in fakes

### ISSUE THREAD

**Issue by fearphage** [sinonjs/sinon#2293]
Fakes are hard coded to use the global `Promise` library: 

https://github.com/sinonjs/sinon/blob/9d4a01bcc4de1f881bb1743535a5273f42a4c457/lib/sinon/fake.js#L64-L78

There is no way to override this behavior and use an alternative library (like `bluebird`).

Similar interfaces that support this functionality:

* `sandbox.usingPromise()`
* `stub.usingPromise()`

**Comment by mroderick** [comment]
This has been fixed with #2301
