### ISSUE TITLE
Documentation: Link from "spies" to "matchers" broken

### ISSUE THREAD

**Issue by PierreFritsch** [sinonjs/sinon#2305]
**Describe the bug**
On the documentation page for spies, the link to the documentation page for matchers is broken.

**To Reproduce**
1. Go to the documentation for Spies: https://sinonjs.org/releases/latest/spies/
2. Click on the link: (see <a href="matchers">matchers</a>)

The target URL https://sinonjs.org/releases/latest/spies/matchers results in a 404 error.

**Expected behavior**
I assume the link should direct to: https://sinonjs.org/releases/latest/matchers/

**Context**

* Browser: Tested with Safari and Chrome on macOS. The issue occurs on both browsers.

**Note**: The link to the matchers page appears 3 times on the "spies" page

**Comment by fatso83** [comment]
Thanks for the find. If you could supply a PR with `../` fix that would be 🏅 .
