### ISSUE TITLE
can't stub uuid@8 anymore

### ISSUE THREAD

**Issue by htorjmen** [sinonjs/sinon#2310]
Hello,

Lately i did an update for all my dependecies but i have a problem when stubbing a uuid.
Before this was my code: 

`public static createStub(): void {
        this.uuidv1Stub = sinon.stub(uuid, 'v1').callsFake(() => {
            const v1Id = this.onV1ReturnIds.shift();
            if (!v1Id) {
                throw Error('No more id in onV1ReturnIds');
            }
            return v1Id;
        });
        this.uuidv4Stub = sinon.stub(uuid, 'v4').callsFake(() => {
            const v4Id = this.onV4ReturnIds.shift();
            if (!v4Id) {
                throw Error('No more id in onV1ReturnIds');
            }
            return v4Id;
        });
    }`

so when i updated my uuid to version 8 i changed my code to look like the old interface of uuid library:

`public static createStub(uuid: UuidSpecHelper.Uuid): void {
        this.uuidv1Stub = sinon.stub(uuid, 'v1').callsFake(() => {
            const v1Id = this.onV1ReturnIds.shift();
            if (!v1Id) {
                throw Error('No more id in onV1ReturnIds');
            }
            return v1Id;
        });
        this.uuidv4Stub = sinon.stub(uuid, 'v4').callsFake(() => {
            const v4Id = this.onV4ReturnIds.shift();
            if (!v4Id) {
                throw Error('No more id in onV1ReturnIds');
            }
            return v4Id;
        });
    }`
`type v1 = typeof uuidv1;
type v4 = typeof uuidv4;

export namespace UuidSpecHelper {
    export interface Uuid {
        v1: v1;
        v4: v4;
    }

}`

this is the new import : `import { v1 as uuidv1, v4 as uuidv4 } from 'uuid';
`
but doesn't work either, does anyone know how to stub the new version of uuid ?

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
