### ISSUE TITLE
v9.2.1 release missing from GitHub and changelog

### ISSUE THREAD

**Issue by robertknight** [sinonjs/sinon#2311]
The current npm release is v9.2.1. There is no corresponding entry in CHANGELOG.md or GitHub release however. The last entry in those places is for v9.2.0.

I'm guessing this is probably just an oversight. Having this information is important for consumers of the package to check for any compatibility issues and is also one of several indicators of the trustworthiness of the release.

**Comment by mroderick** [comment]
Thank you for reporting this @robertknight 💯

Over the years we've made improvements to the release process of the Sinon  libraries, but some of those have yet to make it into the main library.

The missing release was an oversight on my part, as I missed one step in the (regrettably still) manual release process.

The release process is something I'm hoping to work on soon, to make it much less error prone and easier to do.

**Comment by robertknight** [comment]
Thanks for the quick response @mroderick and for your ongoing work on Sinon!
