### ISSUE TITLE
Two small typos in matcher docs

### ISSUE THREAD

**Issue by danielrentz** [sinonjs/sinon#2313]
**Describe the bug**
The page for matchers contains two typos:

This allows to logically combine **mutliple** matchers. The result is a new **matchers** that requires both (and) or one of the matchers (or) to return true.

**To Reproduce**
1. Go to https://sinonjs.org/releases/v9.2.1/matchers/
2. Scroll down to 'Custom matchers'
3. See error

**Expected behavior**
mutliple => multiple
matchers => matcher

**Comment by mantoni** [comment]
Thank you. Would you care to make these changes yourself?

You can find instructions on how to make documentation changes here: https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md

**Comment by danielrentz** [comment]
Sure. Where should I do the changes? In `_releases/v9.2.1/` or in `release-source/`?

**Comment by fatso83** [comment]
Release-source.

**Comment by danielrentz** [comment]
#2315 2315
