### ISSUE TITLE
[Feature Request] fakeServer.respondWith(customMatcherFunction, response);

### ISSUE THREAD

**Issue by johnmiroki** [sinonjs/sinon#2318]
Currently, to make a mock data server:

```
var server = sinon.createFakeServer([config]);
server.respondWith(urlRegExp, response);
```

It works but regular expression can be tricky. I hope FakeServer supports:

```
fakeServer.respondWith(customMatcherFunction, response);

function customMatcherFunction(url) {

    return url.endsWith("xxx");
}
```

Could you please consider this? Really appreciate it!

**Comment by fatso83** [comment]
A feature requests in the form of a pull request is the only way this will happen, I'm afraid :)

**Comment by fatso83** [comment]
Thanks for the PR!
