### ISSUE TITLE
Can the npm build include the browser build?

### ISSUE THREAD

**Issue by domenic** [sinonjs/sinon#232]
We're using npm to manage our client side dependencies. It would be very useful to be able to pull down Sinon by using `"sinon": "~1.5.2"` in our `package.json`, and then include it via

``` html
<script src="node_modules/sinon/sinon-browser.js"></script>
```

Would you be open to this?

**Comment by Aldaviva** [comment]
FYI for anyone looking to include Sinon in their web pages using the official NPM artifact, you actually want to use
```html
<script src="node_modules/sinon/pkg/sinon.js"></script>
```
