### ISSUE TITLE
calledWith fails if the object has been modified during execution

### ISSUE THREAD

**Issue by russoedu** [sinonjs/sinon#2322]
**Describe the bug**
I'm testing a function that tries to create a ticket on Jira that has a "try catch" and it alters the object before performing the "catch"

As I set a custom field that might not have the entry I'm sending, I update it and then try again.

I made a clone of the logic so the test can be reproduced

This is the class I'm testing

```js
module.exports = class SinonFailure {
  constructor () {
    this.importantStuff = {
      id: 1234,
      value: 'asbc',
      something: {
        value: 'original value'
      }
    }
  }

  static async theRequest (something) {
    return something
  }

  async someTestCode () {
    try {
      const r = await SinonFailure.theRequest(this.importantStuff)
      this.r = r
    } catch (error) {
      this.error = error
      this.importantStuff.something = { value: 'updated data' }
      this.r = await SinonFailure.theRequest(this.importantStuff)
    }
  }
}

```

This is the test

```js
const fs = require('fs')
const chai = require('chai')
const expect = chai.expect
const { stub } = require('sinon')
const sinonChai = require('sinon-chai')
chai.should()
chai.use(sinonChai)
const { describe } = require('mocha')

const SinonFailure = require('../src/sinon-failure')
describe('SinonFailure', () => {
  describe('someTestCode(value)', () => {
    let theRequest = null

    beforeEach(() => {
      theRequest = stub(SinonFailure, 'theRequest')
    })

    afterEach(() => {
      theRequest.restore()
    })

    it('should call with altered params', async () => {
      theRequest.onCall(0).throws('some error')
      theRequest.onCall(1).resolves('success')

      const failure = new SinonFailure()
      await failure.someTestCode()

      expect(theRequest).to.have.been.calledTwice
      expect(theRequest).to.have.been.calledWith({
        id: 1234,
        value: 'asbc',
        something: {
          value: 'original value'
        }
      })

      expect(theRequest).to.have.been.calledWith({
        id: 1234,
        value: 'asbc',
        something: {
          value: 'updated data'
        }
      })

      expect(failure.r).to.be.equal('success')
      expect(failure.error).to.be.equal('some error')
    })
  })
})
```

During my tests, I'm trying to check both calls, but Sinon is storing the object reference, not the "value" itself, so when during the execution I update the object, both calls are stored on Sinon as the same call, as the object was updated.

I was able to debug and see the arg "changing" on the first call when the object was updated:

![image](https://user-images.githubusercontent.com/472146/103087984-3a1efe80-45e1-11eb-8844-ce697f326c70.png)
![image](https://user-images.githubusercontent.com/472146/103088004-4c00a180-45e1-11eb-8527-06e8fc4617c1.png)

* Library version: 9.2.1
* Environment: Windows, Node 14
* Other libraries you are using:

**Comment by mroderick** [comment]
I updated the original post to add syntax highlighting

**Comment by mroderick** [comment]
Is your issue the same core challenge as discussed in these issues?

* https://github.com/sinonjs/sinon/issues/571
* https://github.com/sinonjs/sinon/issues/583
* https://github.com/sinonjs/sinon/issues/665

Perhaps what you need is to use [`calledWithMatch`](spycalledwithmatcharg1-arg2-) instead of `calledWith`? That method uses a matcher, to see if your object *matches* the expectations.

See  https://sinonjs.org/releases/v9.2.2/matchers/

**Comment by russoedu** [comment]
I completely understand that only having a “copy” of the object would completely destroy lots of things on Sinon, so it really doesn’t make sense to do.

Maybe a secondary “called” (calledState?) array with copies could solve it. We don’t change the existing api (and don’t break every single “calledWith” written, but we have the ability to check object states for each call.

Só, it’s up to you guys close this one amd if interested, create an “improvement” ticket with this idea. 

Thanks a lot for all the great answers.

**Comment by russoedu** [comment]
> Is your issue the same core challenge as discussed in these issues?
> 
> * #571
> * #583
> * #665
> 
> Perhaps what you need is to use [`calledWithMatch`](spycalledwithmatcharg1-arg2-) instead of `calledWith`? That method uses a matcher, to see if your object _matches_ the expectations.
> 
> See https://sinonjs.org/releases/v9.2.2/matchers/

I’m using “match” for other cases, but in this case I’m checking exactly on f the method mutated the object from “a” to “b”... but I can only see “b”, as the reference stored on the “called” array points (as expected) to the same object.

**Comment by fatso83** [comment]
This is _essentially_ the linked issue #665, and to quote @mantoni https://github.com/sinonjs/sinon/issues/665#issuecomment-387489909:

> There have been attempts to implement this, but it’s very hard to make copies of objects in a reliable way. Especially when you think of class instances and circular dependencies. It’s a can of worms. If you want to try as well, feel free :)

I don't mind this, but brave souls have already tried and failed. So, closing this for now, but if you want to have a go, feel free!

I _do_ think this should be possible case-by-case, so if I was whoever wanted to do this, I would do this:

```javascript
const snapshot = (args){
   return JSON.parse(JSON.stringify(args));
}
const snapshots = [];

// add additional logic for checking the snapshots afterwards

const fake = sinon.fake((...args) {
    snapshots.push(snapshot(args));
    return 42;
}

```

Then I could just check the snapshots afterwards. The `snapshot()` function would need to be customized for your use case, of course, as it does not handle circular dependencies, DOM specifics and such nastyness.
