### ISSUE TITLE
Examples missing on Spies Documentation

### ISSUE THREAD

**Issue by govindrai** [sinonjs/sinon#2338]
**Describe the bug**
The documentation is supposed to provide examples after explanations, but the examples are simply missing:

**To Reproduce**

1. Go to https://sinonjs.org/releases/v9.2.4/spies/
2. See missing examples in first and second section

**Expected behavior**
I expect to see examples.

**Screenshots**
![Screen Shot 2021-01-29 at 7 52 22 AM](https://user-images.githubusercontent.com/13859249/106296901-14e86600-6207-11eb-98bb-1ebc4f5701b3.png)

**Comment by fatso83** [comment]
@govindrai This seems to work when I have tested it, but you are probably affected by one of two things happening:
1. Javascript is turned off (probably not that likely)
2. The RunKit service that dynamically injects a runnable script in the docs is down (more likely).

It works now, and I assume the latter point holds, but feel free to retest and report back should it not work, and if you do: open up DevTools and attach the console log. I expect it to contain errors.

**Comment by fatso83** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/618076/106386024-4ada4580-63d3-11eb-883e-bf0c0af8032e.PNG)
for reference (from your url)

**Comment by govindrai** [comment]
Thanks for pointing me to the network logs. It was actually a chrome extension "Dark Reader" that causes 404s when runkit is trying to load the examples. Weird. Upon reloading with the extension off, I can see the examples.

**Comment by fatso83** [comment]
@govindrai This does point to a small issue with JS only solutions: no one knows that something went wrong. This could of course have been remedied in a very simple manner if we changed this:

```diff
- <div data-example-id="spies-3-wrap-existing-method"></div>
+ <div data-example-id="spies-3-wrap-existing-method">
+ A runnable example will be injected here with javascript. 
+ Should it not load, check your browser console for errors.
+ </div>
```

Relevant files:

- https://github.com/sinonjs/sinon/blob/master/docs/_includes/embed-scripts.html
- https://raw.githubusercontent.com/sinonjs/sinon/master/docs/release-source/release/spies.md
