### ISSUE TITLE
callsFake() always runs when mixed with yields()

### ISSUE THREAD

**Issue by ziluvatar** [sinonjs/sinon#2339]
**Describe the bug**

When you define a stub with `callsFake()`, if you later modify the stub behavior with `yields()`, both of them will run when the stub is called, first `yields()` then `callsFake()`.

**To Reproduce**
```js
const sinon = require('sinon');

console.log('Using sync callsFake and returns\n');

const works = sinon.stub().callsFake(() => 'fake');
works.returns('return');

console.log(works());

console.log('\nUsing callback-ish callsFake and yields\n');

const doesNotWork = sinon.stub().callsFake((cb) => cb('fake'));
doesNotWork.yields('return');

doesNotWork(console.log);
```

**Expected behavior**
```
Using sync callsFake and returns

return

Using callback-ish callsFake and yields

return
```

**Actual behavior**
```
Using sync callsFake and returns

return

Using callback-ish callsFake and yields

return
fake
```

**Context:**

- Library version: 9.2.4
- Environment: NodeJS 12.19.0

**Additional context**
N/A

**Comment by fatso83** [comment]
PR merged :) Thanks!

**Comment by ziluvatar** [comment]
Great! I'll close this issue then 👏
