### ISSUE TITLE
Possible to stub a method twice for different arguments?

### ISSUE THREAD

**Issue by ryanhuff** [sinonjs/sinon#2344]
Hi. I'm using `axios` to hit different APIs. I'd like to create stubs for each API, but they're all POST requests.

So I can't seem to do this:
```
const axios = require("axios");
let sandbox = sinon.createSandbox();
let api1 = sandbox.stub(axios, "post").withArgs(url1, data, config).returns(Promise.resolve(expected_response1);
let api2 = sandbox.stub(axios, "post").withArgs(url2, data, config).returns(Promise.resolve(expected_response2);
```

it complains that I've already stubbed `axios.post`...

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

---
P.S. That being said, your entire issue is quite easy to fix. Just reuse the original stub. It would probably be something like 

```javascript
const api = sandbox.stub(axios, "post")
api.withArgs(url1, data, config).returns(Promise.resolve(expected_response1);
api.withArgs(url2, data, config).returns(Promise.resolve(expected_response2);
```

Create a SO question if you need more help.
