### ISSUE TITLE
Will sinon.stub() support for overloading method in future?

### ISSUE THREAD

**Issue by wing324** [sinonjs/sinon#2350]
**Is your feature request related to a problem? Please describe.**
I knew we can avoid overloading method in our own source code. However, we have to use other APIs which we can't modify it. The API could be an overloading method. Currently, I have tested sinon.stub() to stub an overloading method. But it seems the sinon.stub() will pick one of overloading methods randomly. Even I include specific type of parameters and specific return type.

The basic example:
`
import * as sinon from 'sinon';

class A {
    method(str: string): string;
    method(num: number): number;
    method(arg: string | number) {
        return arg;
    }
}

describe('sinon stub testing', () => {
    it('overloading method testing', () => {
        let a: A = new A();
        // Will have an error: Argument of type 'string' is not assignable to parameter of type 'number'
        sinon.stub(a, 'method').returns('a');
    });
});
`

**Describe the solution you'd like**
I was wondering if we can make the sinon.stub() corresponds with the args or return types?

**Describe alternatives you've considered**
I can use sinon.mock() to make it works, but I think if we also make sinon.stub() works for it, that would be better.

**Comment by mantoni** [comment]
You're using a TypeScript feature that is not supported by native JavaScript. I don't know how these functions are compiled, but you'd need to figure out what actually happens in JavaScript and then use Sinon against the actual code.

Since we're not planning to support TypeScript directly, I'll close this issue. Feel free to share your insights here for others who might have the same question. Thanks.

**Comment by fatso83** [comment]
This is purely a typescript typing issue. You either use the DefinitelyTyped bindings or the ones we supply - I do not know which as you do not state it. You can then either fix the typings (preferably in ours 😄) or you can redeclare the typings in your own testing code.
