### ISSUE TITLE
Sinon 10 uses fake-timers 7 and nise 5, nise 5 uses fake-timers 6. So with one package we get two defferent majors of subpackage.

### ISSUE THREAD

**Issue by blazkovicz** [sinonjs/sinon#2353]
Sinon 10 uses fake-timers 7 and nise 5, nise 5 uses fake-timers 6. So with one package we get two defferent majors of subpackage.
Fix please!

**Comment by bcoe** [comment]
For clarification, @mroderick. The issue reported by myself and @nicoleczhu is actually related to this (not #2352, as first thought). _Although both issues are related to timers changes._

@43081j is working on a change here to get types corrected https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52297

**Comment by mroderick** [comment]
`nise@5.0.2` uses `@sionjs/fake-timers@7`

If you re-install `sinon@10`, you should only get one version of `@sinonjs/fake-timers`: `v7.0.4`

**Comment by fatso83** [comment]
I guess this can be closed. Can @blazkovicz confirm that this indeed fixes the issue?

**Comment by blazkovicz** [comment]
I can not install sinon 10.0.2, is it published? 10.0.1 still has the issue.

**Comment by mroderick** [comment]
@blazkovicz thank you for the error report 🥇 and the followup 👍
