### ISSUE TITLE
Proposition of using a light runkit theme 

### ISSUE THREAD

**Issue by srknzl** [sinonjs/sinon#2355]
This is a suggestion regarding code snippets via runkit.

Since sinon website theme is light, I think dark theme in code snippets does not look good. You can use a theme like in the express docs.

Runkit on express:

![image](https://user-images.githubusercontent.com/32355782/115108447-2d9c2880-9f79-11eb-95db-17cc5c614889.png)

link to the page: http://expressjs.com/en/starter/hello-world.html

I think same thing applies to non-runkit code snippets:

![image](https://user-images.githubusercontent.com/32355782/115110923-64c50680-9f86-11eb-981d-92e7d3b7089a.png)

**Comment by fatso83** [comment]
I have no strong feeling pro/con (there are much bigger fish in the pond to fry), so feel free to whip up something or do some testing with a screenshot.

**Comment by srknzl** [comment]
This is only a css magic:

you can compare the two:

![image](https://user-images.githubusercontent.com/32355782/115190557-e173f400-a0f0-11eb-9007-359901a1587e.png)
![image](https://user-images.githubusercontent.com/32355782/115190569-e6d13e80-a0f0-11eb-8cc2-48a22d19c9d6.png)

**Comment by fatso83** [comment]
>  so we can use runkit everywhere(could make page loads slower though)

@srknzl The thought is to use Runkit for all snippets, but in my initial PR I just did it for one of the pages. I hoped someone would follow my example and do the same for the rest 😄 You do point to a specific issue though: runkit snippets are not showing until the runkit embeds are loaded. that is very easily fixed: by default we just include the snippets as static text when building the site. then they are dynamically replaced afterwards. that prevents javascript related issues and slow network from causing weird rendering issues.

That means it sill makes sense to syntax highlight or color static snippets for this reason. There are also snippets that do not make sense to have as runnable examples, like the exports example above.

**Comment by srknzl** [comment]
> by default we just include the snippets as static text when building the site. then they are dynamically replaced afterwards.

yeah, in the [spies page](https://sinonjs.org/releases/v10.0.1/spies/), before embedded runkit components are loaded, the snippets are not shown.

> That means it sill makes sense to syntax highlight or color static snippets for this reason.
 
I agree that runkit is not required for all snippets. I do not know how non-runkit snippets are highlighted, but having same highlight theme with runkit snippets would be good. That can be a light one or a dark one

**Comment by fatso83** [comment]
Hi, @srknzl . What do you need to move this forward? I do not remember what you need specifically at this point.

**Comment by srknzl** [comment]
Nothing actually. This was just an idea, it is up to you to implement it.

**Comment by srknzl** [comment]
no unfortunately. It was just changing background color to white and text color to black using dev tools
