### ISSUE TITLE
notCalledWith() method not implemented

### ISSUE THREAD

**Issue by thanpolas** [sinonjs/sinon#236]
Although documented, there is no `notCalledWith()` method exposed on spies or stubs

**Comment by DudaGod** [comment]
@mantoni @cjohansen hello guys.

I still see [in the spies documentation](http://sinonjs.org/releases/v4.0.0/spies/) information about methods `notCalledWith` and `notCalledWithMatch`. Which can not be used and this is really confusing. 

Can you fix it please?

**Comment by mroderick** [comment]
This has [already been explained above](https://github.com/sinonjs/sinon/issues/236#issuecomment-12833513), `notCalledWith` is only available on `spyCall`.
