### ISSUE TITLE
npm test failed

### ISSUE THREAD

**Issue by zhanghba** [sinonjs/sinon#2362]
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Invalid character: '`'

**Comment by mroderick** [comment]
With [`sinon@10`](https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md#1000--2021-03-22), we allowed more modern JavaScript syntax and dropped support for legacy runtimes.

If you want to keep using Sinon with PhantomJS, you can pin your Sinon to version 9 or use a transpiler to make it into ES5.

[Development on PhantomJS has been suspended for 2 years now](https://github.com/ariya/phantomjs/issues/15344), so you'll probably experience problems with most libraries.

**Comment by zhanghba** [comment]
@mroderick 
show others issue
![image](https://user-images.githubusercontent.com/35982572/117933632-558e6a00-b334-11eb-8ac0-66c7f05d4390.png)

**Comment by zhanghba** [comment]
use sinon  7.5.0  npm test successful
