### ISSUE TITLE
Stub created via 'createStubInstance' is missing class methods

### ISSUE THREAD

**Issue by eyalroth** [sinonjs/sinon#2374]
**Describe the bug**

Sinon does not create stub methods on a stub created via `createStubInstance`.

**To Reproduce**

Run the following mocha test:
```js
const sinon = require('sinon');
const AWS = require('aws-sdk');

describe('Foo', () => {
  const stubAwsClient = sinon.createStubInstance(AWS.Lambda);
  console.log(stubAwsClient.invoke); // undefined
});
```

**Expected behavior**

I expected Sinon to stub the `invoke` method of `AWS.Lambda`; instead, the stub has no such property (`undefined`).

I somehow managed to come up with this workaround:
```js
const stubAwsClient = sinon.createStubInstance(Object.getPrototypeOf(new AWS.Lambda()).constructor);
console.log(stubAwsClient.invoke); // [Function (anonymous)]
```

But I'm not really sure if this solution is appropriate, and it also requires the instantiation of an actual instance of the class.

**Context**
- Library version: 9.2.4
- Environment:
  - MacOS
  - node: 14.16.1
- Other libraries you are using:
  - aws-sdk: 2.825.0
  - mocha: 8.2.1

**Additional context**

I'm pretty new to JS, coming from statically typed OOP background (Java) where classes and inheritance are better defined, so I'm not sure whether this is a bug or something I'm missing with the language.

**Comment by fatso83** [comment]
Hi, I had a quick look at the source code for [AWS Lambda](https://github.com/aws/aws-sdk-js/blob/master/clients/lambda.js) and my quick impression is that this is a specific problem for this library, as it does some _pretty funky stuff_. 

Usually, having to stub all the methods of an object to test a single method is a smell that your SUT is doing too much, so it might be you could have a look at your SUT if it could be simplified in some manner and then just pass in a simpler stub. Then combining that with a [link seam](https://sinonjs.org/how-to/link-seams-commonjs/) could result in pretty simple and readable tests.

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by eyalroth** [comment]
@fatso83 Thanks for the (extremely fast) response.

I indeed suspected that this has something to do with how the AWS sdk adds methods to its clients; looks like it uses "reflection" to add methods according to JSONs which describe the REST API.

> This ticket looks like a usage question

I wasn't sure whether this is a usage question or a bug, but your reply clarified that. Thanks!
