### ISSUE TITLE
sinon.assert.match strictness when passing array of objects

### ISSUE THREAD

**Issue by alesmenzel** [sinonjs/sinon#2375]
**Describe the bug**

`sinon.assert.match` does not seem to work as described by the docs nor by the observed behavior. It states the match should ignore additional properties, which is does, when passing an object. The same does not work when passing array of objects.

**To Reproduce**

```
var sinon = require("sinon")

var expected = [{ x: 1 }],
  actual = [{ x: 1, y: 2 }];

sinon.assert.match(actual, expected); // throws
```

```
var sinon = require("sinon")

var expected = { x: 1 },
  actual = { x: 1, y: 2 };

sinon.assert.match(actual, expected); // success
```

**Expected behavior**

Expecting the same optional behavior.

**Workaround**
```
var sinon = require("sinon")

var expected = [sinon.match({ x: 1 })],
  actual = [{ x: 1, y: 2 }];

sinon.assert.match(actual, expected); // success
```

**Comment by fatso83** [comment]
Hi, I checked [the docs](https://sinonjs.org/releases/v10.0.1/matchers/) which indeed _does not say_ that this should work. The default matcher covers `number`, `string`, `object`, `regexp` - not array. It takes a `function` to cover other cases; either one of the built-ins (like `sinon.match.array` or `sinon.match.array.deepEquals`) or a custom one.

I created a reproducible runnable at RunKit that shows how you can create a custom matcher.

https://runkit.com/fatso83/sinon-2375-loose-array-element-matching/2.1.0

**Comment by fatso83** [comment]
P.S. Our default matchers come from our [samsam](http://sinonjs.github.io/samsam/) project. Feel free to file a PR if you feel that we should add some matcher!
