### ISSUE TITLE
Reset all anonymous spies?

### ISSUE THREAD

**Issue by aryo** [sinonjs/sinon#2386]
**Describe the bug**
Is there a way to restore all anonymous spies without having to manually restore each of them individually?

**To Reproduce**

```
const spyA = sinon.spy();
const spyB = sinon.spy();

spyA();
spyB();

sinon.restore();

spyA.called; // true
spyB.called; // true
```

Even calling sandbox.restore() doesn't reset anonymous spies created via the sandbox.

**Comment by fatso83** [comment]
Usage questions are best done on StackOverflow, but it's worth noting that `restore != reset`. When doing `sandbox.restore()` you restore the objects that have been mutated into their previous state. It does not really do anything with the stubs and spies that were created in that sandbox. 

If you want to continue working with those spies and stubs, you need to reset them explicitly. You can either reset behaviour or history or both. For your case, what you are looking for is `sinon.resetHistory()`, which you can use in place of `sinon.restore()`. If you use both, note that ordering matters. If you restore first, then it will have no idea of previously created stubs.

**Comment by aryo** [comment]
Ah, I see... Thanks for the info @fatso83. Apologies for asking this in the wrong channel!
