### ISSUE TITLE
spy doesnt detect function call

### ISSUE THREAD

**Issue by Xusr404** [sinonjs/sinon#2388]
**Describe the bug**
For website tests I use Cypress. I have some custom events and i use cy.spy. 
For the first time it works fine, but if i run the function a second time directly after the first time, it always says "expected "test" to have been called with arguments "test", but it was never called". I also tried waits, but that changed nothing.

```js
Cypress.Commands.add('waitForEvent', (event, absoluteSelector, expectedURL) => {
      cy.window().then((win) => {
          const spyFuncName = expectedURL,
              spyObj = {},
              eventCallback = function(e) {
                  win.removeEvent(event, win.document, eventCallback);
                  console.log("WANTED", e.data.url);
                  spyObj[spyFuncName](e.data.url);
              }
  
              spyObj[spyFuncName] = function(eventUrl) {
                  console.log("WANTED", "Spy: " + eventUrl);
              }
          
          cy.spy(spyObj, spyFuncName);
          win.addEvent(event, win.document, eventCallback);
    
          cy.get(absoluteSelector)
            .click()
            .then(() => {
                expect(spyObj[spyFuncName]).to.be.calledWith(expectedURL);
          });
      });
  })
```

Cypress Version: 7.6.0

**Comment by mroderick** [comment]
I edited the original post to add syntax highlighting

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

---

I know [Cypress is wrapping Sinon](https://docs.cypress.io/api/utilities/sinon), but I do not know it and so I cannot really start to tell what is wrong as the error messages are all outside of Sinon. I cannot see anything immediately wrong either. Good luck!
