### ISSUE TITLE
withArgs(sinonMatchers) fails to work if the sandbox was created by a helper module

### ISSUE THREAD

**Issue by kemokid** [sinonjs/sinon#2392]
A matcher created by sinon imported into your namespace will not work with a sandbox created by an imported module that imports its own copy of sinon.

**To Reproduce**

Create an NPM module that wraps sandbox creation. Call it for example `test-setup-helpers`.

```js
import * as sinon from 'sinon';

export function setupSinonSandbox() {
  const data = {
    sandbox: null as sinon.SinonSandbox
  };
  beforeEach(function() {
    data.sandbox = sinon.createSandbox();
  });

  afterEach(function() {
    data.sandbox.restore();
  });

  return data;
}

export { sinon };
```

Now npm install that module into your repo, and add the following test:

```js
import { expect } from 'chai';
import * as sinon from 'sinon';

import * as testSetupHelpers from 'test-setup-helpers';

const obj = {
  aSimpleFunction: function (arg1: string): string {
    return 'arg1 is ' + arg1;
  }
};

describe('sinon matching test', () => {
  const testSinon = testSetupHelpers.setupSinonSandbox();

  it('exact string works', () => {
    const sandbox = sinon.createSandbox();
    sandbox.stub(obj, 'aSimpleFunction').withArgs('whatever').returns('poof!');

    expect(obj.aSimpleFunction('whatever')).to.equal('poof!');
    sandbox.restore();
  });

  it('sinon.match.string works', () => {
    const sandbox = sinon.createSandbox();
    sandbox.stub(obj, 'aSimpleFunction').withArgs(sinon.match.string).returns('poof!');

    expect(obj.aSimpleFunction('whatever')).to.equal('poof!');
    sandbox.restore();
  });

  it('module-created sandbox exact string works', () => {
    testSinon.sandbox.stub(obj, 'aSimpleFunction').withArgs('whatever').returns('poof!');

    expect(obj.aSimpleFunction('whatever')).to.equal('poof!');
  });

  it('module-created sandbox works with matcher from re-exported sinon', () => {
    testSinon.sandbox.stub(obj, 'aSimpleFunction').withArgs(testSetupHelpers.sinon.match.string).returns('poof!');

    expect(obj.aSimpleFunction('whatever')).to.equal('poof!');
  });

  it('module-created sandbox should work with our own sinon.match but does not', () => {
    testSinon.sandbox.stub(obj, 'aSimpleFunction').withArgs(sinon.match.string).returns('poof!');

    expect(obj.aSimpleFunction('whatever')).to.equal('poof!');
  });
});
```

**Expected behavior**
All tests should pass.

**Actual behavior**
The last test, `'module-created sandbox should work with our own sinon.match but does not'`, fails.

**Context (please complete the following information):**

- Library version: 11.1.1
- Environment: MacOS
- Other libraries you are using: chai

**Comment by mantoni** [comment]
Can you check if you have two versions of `@sinonjs/samsam` installed?

```
npm ls @sinonjs/samsam
```

This should be a single version. If it shows up twice, it should be marked as deduped.

Marchers are only recognized correctly when they are created with the same module instance as they're checked (a prototype instance check).

**Comment by kemokid** [comment]
By setting the version directly in both modules, I get:

```
$ npm ls @sinonjs/samsam
test_repo@1.43.0 /Users/martin/git/test_repo
├── @sinonjs/samsam@2.0.0 
└─┬ sinon@6.1.3
  └── @sinonjs/samsam@2.0.0  deduped
```
but the matchers fail to work.

But also I notice:
```
$ npm ls samsam
test_repo@1.43.0 /Users/martin/git/test_repo
└─┬ sinon@6.1.3
  └─┬ @sinonjs/formatio@2.0.0
    └── samsam@1.3.0 
```

In any case, I would argue this is still a bug. If the matchers are the right version, they should be used. If the matchers are the wrong version, they should throw some kind of error. Silently proceeding but failing to act as specified is the worst behavior.

**Comment by fatso83** [comment]
I am going to close this issue if @kemokid does not have anything to add to Max' question. The bug report was great, btw, but it would be nice not to spend stuff that is outside of our control.

**Comment by fatso83** [comment]
Feel free to reopen if you find the time and verify this is actually an issue.
