### ISSUE TITLE
Missing release v11.1.2 tag and changelog updates

### ISSUE THREAD

**Issue by robertknight** [sinonjs/sinon#2393]
The current npm release of sinon is [v11.1.2](https://www.npmjs.com/package/sinon). This tag is [missing in GitHub](https://github.com/sinonjs/sinon/releases) and the changes for this release are not present in CHANGELOG.md on master.

The [package diff comparison](https://diff.intrinsic.com/sinon/11.1.1/11.1.2#file-CHANGELOG.md) of the two releases shows that this does appear to be a legitimate release with some non-trivial changes. The package diff comparison includes an updated CHANGELOG, so perhaps the changes were made locally on a developer's machine but not pushed back to the repository?

**Comment by fatso83** [comment]
Well spotted. We have talked about years about automated releases based on semantic versioning to avoid this repeated nuisance, but there is only a handful of aggregated developer hours available per month, so we never get around to it 😄

**Comment by mroderick** [comment]
Thank you for reporting this @robertknight.

That was my mistake. I've pushed the missing tag, and it shows up in GitHub now.

If you don't mind, I'll leave this issue open, and see if we can't work on this in near future.

**Comment by robertknight** [comment]
Thanks for the update. Regarding release automation, a process that worked well for our projects was to run the `npm publish` step as part of a CI workflow triggered by the creation of a GH release ([example for GitHub Actions](https://github.com/hypothesis/frontend-shared/blob/main/.github/workflows/npm-publish.yml)), with the rest of the process (bumping package version, updating changelog etc.) still done manually.

**Comment by mroderick** [comment]
This has been addressed in https://github.com/sinonjs/sinon/pull/2394, using the same solution that we're using in `@sinonjs/referee`, etc.
