### ISSUE TITLE
Stub failed when upgrade ts-node to 10.x 

### ISSUE THREAD

**Issue by RifeWang** [sinonjs/sinon#2401]
**Describe the bug**
Everything is ok when my ts-node version is 8.x ~ 9.x , but stub failed when ts-node is 10.x 

**To Reproduce**
The code likes below:

```
// file: ./lambda.ts
export const getAWSLambda = () => new AWS.Lambda({ region: AWS_DEFAULT_REGION });
export class AWSLambda {
  private readonly lambda: AWS.Lambda;
  constructor() {
    this.lambda = getAWSLambda();
  }
  async invoke(params: ServerlessParams): Promise<ServerlessResponse> {
      const response = await this.lambda.invoke({
        // ...
      }).promise();
      return {};
  }
}


// file: unit.test.ts
import sinon from 'sinon';
import * as lambda from './lambda';

describe('Lambda Unit Test', () => {
  let lambdaService: lambda.AWSLambda;
  let sandbox: sinon.SinonSandbox;
  let getAWSLambdaStub: sinon.SinonStub;
  let invokeStub: sinon.SinonStub;

  before(() => {
    sandbox = sinon.createSandbox();
  });

  beforeEach(() => {
    invokeStub = sandbox.stub();
    getAWSLambdaStub = sandbox.stub(lambda, 'getAWSLambda');
    getAWSLambdaStub.returns({
      invoke: () => ({
        promise: invokeStub,
      }),
    });
    lambdaService = new lambda.AWSLambda();
  });

  afterEach(() => {
    sandbox.restore();
  });

  it('shound succeed to invoke', async () => {
    invokeStub.resolves({
      StatusCode: 200,
    });

    // called real function, stub failed.
    const res = await lambdaService.invoke();  

    expect(getAWSLambdaStub).to.be.calledOnce;
    expect(invokeStub).to.be.calledOnce;
  });
});

```

**Context (please complete the following information):**

- Library version:  
- sinon: 11.1.2 
- ts-node: 10.2.1
- typescript: 3.9.7
- node: 14.17.3

tsconfig.json:
```
{
  "compilerOptions": {
    "preserveConstEnums": true,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strict": true,
    "moduleResolution": "node",
    "sourceMap": false,
    "outDir": "dist/src",
    "allowJs": true,
    "checkJs": true,
    "noUnusedLocals": true,
    "skipLibCheck": true
  },
  "exclude": [
    "src/exp",
    "src/public"
  ],
  "include": [
    "src/**/*"
  ],
  "ts-node": {
    "transpileOnly": true,
    "transpiler": "ts-node/transpilers/swc-experimental"
  }
}
```

**Comment by fatso83** [comment]
Hi, @RifeWang! Welcome to our tracker and thanks for reporting. Unfortunately, we do not explicitly support TypeScript in any form. Of course it should _run_, but if something fails that relates to typescript it is not on our table. You have also not provided any error, so it is impossible to help you. That being said, this seems like an issue with configuration and not Sinon in itself, so you should try out StackOverflow or some typescript forum to get better help.

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, just reply here, but make sure you follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
