### ISSUE TITLE
await next N timers: `clock.nextNAsync(n: number)`

### ISSUE THREAD

**Issue by bennypowers** [sinonjs/sinon#2404]
**Is your feature request related to a problem? Please describe.**
When I already know how many timers I want to await, I may do something like:
```js
beforeEach(async () => {
  await clock.nextAsync();
  await clock.nextAsync();
  await clock.nextAsync();
});
```

**Describe the solution you'd like**
It would be easier on the eyes to simply:
```js
beforeEach(() => clock.nextNAsync(3));
```

**Describe alternatives you've considered**
```js
export async function nextNAsync(clock, n) {
  for (const _ of Array.from({ length: n }))
    await clock.nextAsync();
}
```

**Comment by fatso83** [comment]
I think this is a rather slim use case, and given the already large API, I think we should pass. Thanks for raising this, anyhow!
