### ISSUE TITLE
Asserting on callCount with a numeric string results in very confusing failure message

### ISSUE THREAD

**Issue by cincodenada** [sinonjs/sinon#2408]
**Describe the bug**
This bug was originally reported in `sinon-chai` by @BebeSparkelSparkel as https://github.com/domenic/sinon-chai/issues/136 but turned out to be an issue with Sinon itself. The bug is that we can get the error message `AssertError: expected spy to be called 10 times but was called 10 times` - this happens when specifying `callCount` as a string.

**To Reproduce**
I made a slightly modified version of the original test case so that it just uses Sinon:
```
const sinon = require('sinon');
const n = '10',
      s = sinon.spy();
for(let i=0; i < n; ++i) s();

sinon.assert.callCount(s, n);
```

Run the above, you will get `AssertError: expected spy to be called 10 times but was called 10 times` which is a very confusing error message.

**Expected behavior**

One of two options:
 1. Sinon could coerce numeric strings into numbers, and pass the assertion
 2. Sinon could surface the actual problem, which is that callCount was not a number.

Both of these seem sensible, the first is a little more user-friendly, the second is a little more correct.

Internally it looks like Sinon raises a `TypeError`, which is I think what is actually triggering this failure, so it could just surface that, or it could attempt to convert to a number.

This actually happens with any string: `sinon.assert.callCount(s, 'banana')` will get you `expected spy to be called banana times but was called 10 times`, which is less confusing, but also it would probably be better to instead fail with an error about `banana` not being a number.

**Context (please complete the following information):**

- Library version: All versions (tested with most recent releases for v1-11, including 11.1.2)
- Environment: OS X
- Other libraries you are using: None

**Comment by fatso83** [comment]
Great bug report. We always lean on the side of being correct and throwing early rather than try and coerce types, so any fix should take that into account.
