### ISSUE TITLE
Objects that have interacted with sinon mock are skipped by Garbage Collector

### ISSUE THREAD

**Issue by d-borisov** [sinonjs/sinon#2415]
**Describe the bug**

Looks like sinon affects GC mechanism. Objects that have called methods that were configured in sinon's mock are not swept by V8 GC.

**To Reproduce**

Consider this source code:

```
const createStubInstance = require('sinon').createStubInstance;

class SomeClass {
    constructor(id, dependency) {
        this.id = id;
        this.subDependency = dependency.getString();
    }
}

class Dependency {
    getString() {
        return 'real string';
    }
}

async function showcase() {
    const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

    const dependencyMock = createStubInstance(Dependency);
    dependencyMock.getString.returns('string mock');

    let arr = [];
    arr.push(new SomeClass('withReal', new Dependency()));
    arr.push(new SomeClass('withMock', dependencyMock));
    console.log('array with objects');

    global.gc();
    console.log('gc() A');
    await sleep(10_000);

    arr = [];
    console.log('array cleared');

    global.gc();
    console.log('gc() B');
    await sleep(10_000);
}

showcase();
```

Please run the source code above (use `--expose-gc` flag) and make two heapdumps
* one after the first call of `global.gc();`. stdout will get `'gc() A'`
* another after the second call of `global.gc();`. stdout will get `'gc() B'`

Search for objects of `SomeClass` in dumps. Object with `id='withReal'` was swept out by GC, object with `id='withMock'` still exists in heapdump.

**Expected behavior**
Both objects `id='withReal'` and `id='withMock'` are swept out by GC.

**Screenshots**

First heapdump.
![heapdump1](https://github.com/d-borisov/sinon-gc/blob/main/heapsdumps/heapdump-1.png?raw=true)

Second heapdump.
![heapdump2](https://github.com/d-borisov/sinon-gc/blob/main/heapsdumps/heapdump-2.png?raw=true)

**Context (please complete the following information):**

- Library version: 12.0.1
- Environment: Node v16.13.0, npm 8.1.0
- Example URL: https://github.com/d-borisov/sinon-gc
- Other libraries you are using: N/A

**Additional context**
N/A

**Comment by fatso83** [comment]
Hi, @d-borisov . Thanks for reporting this! I do think this is not as mysterious as you might think 😃 In Sinon, we are not really doing any kind of magic; it's all plain Javascript with very simple object references, nothing fancy. So the explanation is likely to be quite basic as well.

I am not sure you are aware that we are using [a default sandbox](https://sinonjs.org/releases/latest/sandbox/#:~:text=Default%20sandbox) for all created fakes?
> Since sinon@5.0.0, the sinon object is a default sandbox. Unless you have a very advanced setup or need a special configuration, you probably want to only use that one.

That means, that even if you have removed all references in _your_ code, there will still be references in Sinon's default sandbox. If you want to remove them, you need to empty the sandbox by calling `sandbox.restore()`.

Does this fix the issue?

**Comment by d-borisov** [comment]
@fatso83 hello.

Thanks a lot!

Yes, this helps.

```
const sinon = require('sinon');
const createStubInstance = sinon.createStubInstance;
const restore = sinon.restore;

class SomeClass {
    constructor(id, dependency) {
        this.id = id;
        this.subDependency = dependency.getString();
    }
}

class Dependency {
    getString() {
        return 'real string';
    }
}

async function showcase() {
    const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

    const dependencyMock = createStubInstance(Dependency);
    dependencyMock.getString.returns('string mock');

    let arr = [];
    arr.push(new SomeClass('withReal', new Dependency()));
    arr.push(new SomeClass('withMock', dependencyMock));
    console.log('array with objects');

    global.gc();
    console.log('gc() A');
    await sleep(10_000);

    arr = [];
    restore();                                  //    <<--   sandbox cleaning
    console.log('array cleared');

    global.gc();
    console.log('gc() B');
    await sleep(10_000);
}

showcase();
```

After adding `restore()` I got the second heapdump without `SomeClass` object with `id='withMock'`.

I see you mentioned above that this `id='withMock'` object was not swept by GC because there is a reference to it hold by mock-object. But I cannot understand how this reference appeared. 

I suppose that the reason is a call to `this.subDependency = dependency.getString();` in `SomeClass` constructor. But how it leads to a reference? :) 

I will close this issue and investigate further.

Thanks!

**Comment by d-borisov** [comment]
@fatso83 hmm... interesting. 

So what is the reason for object with `id='withMock'` not being GC-ed? The single reference to this object was in array `arr` and it was removed. 

Do fakes hold a reference to a context they were called from? 

I cannot get why GC decided not to delete object with `id='withMock'` :) Actually there no need in this object anymore - no one will interact with it because no one has any reference to it.

I think I should learn more details on how GC works :)

**Comment by fatso83** [comment]
> So what is the reason for object with id='withMock' not being GC-ed? The single reference to this object was in array arr and it was removed.

Unless I am mistaken, I already told you twice: it is the only reference in _your_ code, but in Sinon's code it keeps a reference to every created stub. And it keeps these references even if _your_ code is not referencing it. As long as any code is referencing it, it cannot be GC-ed. Hence the need to call `restore()` on the sandbox, to enable GC.

> Do fakes hold a reference to a context they were called from?
No, but Sinon holds a reference to the fakes internally. Did you check out the link to the relevant code supplied above? It should be quite clear from looking at that code.
