### ISSUE TITLE
SinonStub typings after withArgs is incorrect

### ISSUE THREAD

**Issue by jmclean-starburst** [sinonjs/sinon#2442]
**Describe the bug**
When calling `sinon.stub(someClass, "someProperty").withArgs("someArg")`, the return type has attributes `parent` and `matchingArguments`. Intellisense is yelling when you try to access the `.parent` attribute bc it is not within type `SinonStub`

this means I am unable to call `myStub.parent.callCount` unless i decorate the line with `// @ts-ignore`

In fact, `myStub.called` will yield false, however `myStub.withArgs("someArg").called` will yield true. 

**Expected behavior**
Intellisense will correctly handle a SinonStub after it is initialized w/ `withArgs`

**Context (please complete the following information):**

- Library version: 11.1.2

**Additional context**

**Comment by fatso83** [comment]
There is a reason we ask for some way of reproducing the issue:
```
~/code/sinon (master)
$ grep SinonStub | wc -l
0
```
As you can see, we do not provide anything called [`SinonStub`](http://definitelytyped.org/docs/sinon--sinon/interfaces/sinonstub.html). Given the `@ts-ignore`, it seems this is Typescript related, and we do not provide TypeScript definitions (that was only a short-lived experiment in v7 that did not turn out well), only JSDoc which, although works, is inferior in what it could provide compared to TypeScript. You probably want to file a bug (or better, a Pull Request :angel: ) to the [Definitely Typed project](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58484), as we do not provide any support for these externally maintained types.
