### ISSUE TITLE
[](dbartholomae:patch-1)Zaram22

### ISSUE THREAD

**Issue by Zaram22** [sinonjs/sinon#2445]
[](
#75:patch-1)

__Originally posted by @Zaram22 in https://github.com/smeijer/unimported/pull/75#issuecomment-1043871652__

**Comment by Zaram22** [comment]
#2445

**Comment by fatso83** [comment]
What? Seems like a bot.

**Comment by fatso83** [comment]
@mroderick I blocked this account after the bottish behavior in #2441 #2444 and #2445.
