### ISSUE TITLE
"The Fetch API is an experimental feature" is logged on node 18

### ISSUE THREAD

**Issue by nicojs** [sinonjs/sinon#2453]
**Describe the bug**
Importing from `'sinon'` results in this warning being logged on node 18:

> The Fetch API is an experimental feature

**To Reproduce**

1. `nvm install 18.0.0`
2. `nvm use 18.0.0`
3. `mkdir tmp && cd tmp`
4. `npm i sinon`
5. `echo 'import("sinon")' > index.mjs`
6. `node index.mjs`

**Expected behavior**
This seems like simply importing `sinon` is doing some HTTP call. Why would it need to do a `fetch` call?

**Context (please complete the following information):**

- Library version: `sinon@13.0.2`
- Environment: linux
- Other libraries you are using: none

Running with `--trace-warnings` reveals a stack trace:

```
(node:9486) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at lazyUndici (node:internal/bootstrap/pre_execution:188:5)
    at get (node:internal/bootstrap/pre_execution:204:16)
    at 106.../configure-logger (file:///home/nicojs/tmp/node_modules/sinon/pkg/sinon-esm.js:15736:24)
    at o (file:///home/nicojs/tmp/node_modules/sinon/pkg/sinon-esm.js:1:324)
    at file:///home/nicojs/tmp/node_modules/sinon/pkg/sinon-esm.js:1:375
    at 103.../configure-logger (file:///home/nicojs/tmp/node_modules/sinon/pkg/sinon-esm.js:15361:15)
    at o (file:///home/nicojs/tmp/node_modules/sinon/pkg/sinon-esm.js:1:324)
    at file:///home/nicojs/tmp/node_modules/sinon/pkg/sinon-esm.js:1:375
    at 107../fake-server (file:///home/nicojs/tmp/node_modules/sinon/pkg/sinon-esm.js:16648:17)
```

**Comment by nicojs** [comment]
Hmm intersting. Thanks for the response. I'll close this issue, as the warning isn't logged anymore in node@>18.1. Let's not waste too much time on this 🤷‍♀️

**Comment by mantoni** [comment]
I think this was the culprit: https://github.com/nodejs/node/issues/42792

**Comment by nicojs** [comment]
Ow, nice find!

**Comment by kishanbhensadadiya** [comment]
> Hmm intersting. Thanks for the response. I'll close this issue, as the warning isn't logged anymore in node@>18.1. Let's not waste too much time on this woman_shrugging

I just tried. IT is not working in node@18.1

**Comment by fatso83** [comment]
>  IT is not working in node@18.1

@kishanbhensadadiya What does that even mean? Please elaborate - you are way too cryptic with "not working". Do you mean you still get the warning with Node 18.2? Or are you thinking about something else? Details, Node version, Sinon version, etc.
