### ISSUE TITLE
Mock function inside frozen Object

### ISSUE THREAD

**Issue by jamauro** [sinonjs/sinon#2492]
Is it possible to mock a function that's contained within a frozen Object?

If not, are there any recommended workarounds?

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

---

Feel free to post a link to your question here and we will likely have a look. That being said, having some example code to more easily reproduce the situation and be totally certain that we understand the situation, will improve the likelyhood of success :)
