### ISSUE TITLE
 Attempting to change configurable attribute of unconfigurable property.

### ISSUE THREAD

**Issue by ishikapanchal-sdn** [sinonjs/sinon#2500]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**

- Library version: _please verify that the bug exists in the latest release_
- Environment:
- Example URL:
- Other libraries you are using:

**Additional context**

**Comment by fatso83** [comment]
We cannot help anyone that does not put in the effort needed to help them. Please fill out the template and re-open after completing.
