### ISSUE TITLE
Sinon stub MomentJS cant stub main function

### ISSUE THREAD

**Issue by t1a2l** [sinonjs/sinon#2518]
**Describe the bug**
momentjs:
/**
 * @param strict Strict parsing disables the deprecated fallback to the native Date constructor when
 * parsing a string.
 */
declare function moment(inp?: moment.MomentInput, strict?: boolean): moment.Moment;
export = moment;
export as namespace moment;

it isa function and also a namespace, cant seem to be able to stub the function.

**To Reproduce**
const moment = require('moment');
const sandbox = sinon.createSandbox();
sandbox.stub(moment, "moment").callsFake(function(item) { 
        return item;
  });

**Expected behavior**
function idetified and result should appear inside item

**Context (please complete the following information):**

- Library version: 15.1.0
- Environment: VS code windows 10
- Other libraries you are using: momentjs

**Additional context**
getting error : TypeError: Cannot stub non-existent property moment

**Comment by fatso83** [comment]
You are trying to stub a property `'moment'` of the `moment` namespace. AFAIK, you are rightly told that doesn't work, given that the typings are correct, so this does not seem like an issue with Sinon, but rather how to use it 😄 

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by t1a2l** [comment]
@fatso83 moment is a function within the moment library, it is like the main function, I wonder if it is somehow connected to another issue with utility functions here "https://github.com/sinonjs/sinon/issues/562" it seems like a bug rather then a usage issue.

**Comment by fatso83** [comment]
No, `moment` is not a function within the moment library. The `moment` module _is_ both a function and a namespace. As a function is an object, you can attach any number of props to it.

When you do `sinon.stub(moment, 'moment')` you are trying to wrap `moment.moment`, and as you can see there are no fields on the namespace called `moment`. The exports are all constants or utility functions:

<img width="312" alt="image" src="https://github.com/sinonjs/sinon/assets/618076/8c08c004-82d8-4d2e-8e36-676940159a42">

Now, for your issue, what you _want_ to do is basically replace the entire `moment` library during module loading. That is not something Sinon does. We can modify _exports_ on the libraries, but we do not try to affect linking level operations. 

See this small article for tips on how to do this: https://sinonjs.org/how-to/link-seams-commonjs/
