### ISSUE TITLE
SyntaxError: Unexpected token 'export' on the latest version of sinon 15.2.0 with jest

### ISSUE THREAD

**Issue by hrai** [sinonjs/sinon#2522]
**Describe the bug**
I'm getting error while importing sinon that's setup with jest. 

This error does not exist in `v14.0.2`

**Expected behavior**
When running `yarn jest` it should not produce the error below.

**Screenshots**
![image](https://github.com/sinonjs/sinon/assets/52148253/fed9a2e3-6427-4bb1-8bca-0f0493fe3633)

**Context (please complete the following information):**

- Library version: sinon@15.2.0
- Environment: WSL Ubuntu

**Additional context**

Even adding below doesn't solve the problem.

```
  "transformIgnorePatterns": [
    "/node_modules/(?!(sinon)/)"
  ],
```

**Comment by McFoggy** [comment]
we faced exactly the same using `jest` and had to revert to version `sinon@15.1.2`

`transformIgnorePatterns` did not solved our issue neither.

**Comment by tjunghans** [comment]
Adding the following to your jest config fixes the issue:

```
moduleNameMapper: {
  sinon: "<rootDir>/node_modules/sinon/pkg/sinon.js",
},
```

**Comment by fatso83** [comment]
The relevant change is mentioned in the [changelog](https://github.com/sinonjs/sinon/blob/main/CHANGES.md#1520), specifically [this commit](https://github.com/sinonjs/sinon/commit/d220c99516ddb644d3702b4736bdfd311a2b05ec) for Webpack 5 compatibility. Not a bug. 

I am not sure why Jest picks up the module from `browser` field (the only change), though, which is a bit strange. 

---

I read up a bit on this through https://github.com/jestjs/jest/issues/9771 and [Jest's Configuration pages](https://jestjs.io/docs/next/configuration). The bit mentioning `customExportConditions` seems to apply:
> Both jest-environment-jsdom and jest-environment-node allow specifying `customExportConditions`, which allow you to control which versions of a library are loaded from `exports` in `package.json`. `jest-environment-jsdom` defaults to `['browser']`. jest-environment-node defaults to `['node', 'node-addons']`.

That probably explains it, if you are using jsdom or something else setting `customExportConditions` in the test environment to `"browser"`.

**Comment by hrai** [comment]
According to the comments, I added the config but the issue persists.

![image](https://github.com/sinonjs/sinon/assets/4055444/e306547f-70e6-4855-b9e0-32c69e93ac9d)

**Comment by tjunghans** [comment]
@hrai Try "node" instead of "browser".

**Comment by fatso83** [comment]
@hrai Sorry for being unclear. I can see that this sentence can be seen as ambiguous:
> That probably explains it, if you are using jsdom or something else setting `customExportConditions` in the test environment to `"browser"`.

What I meant to say was that if jsdom (or something else) is setting `customExportConditions` to `"browser"`, that would explain your problem. The fix is then to set it to something else than that, like @tjunghans proposed .

**Comment by fatso83** [comment]
If someone would like this to appear in our official sinonjs.org docs, we ❤️  PR's! [Here is how](https://github.com/sinonjs/sinon/blob/main/docs/CONTRIBUTING.md).
