### ISSUE TITLE
I can't find the CHANGELOG

### ISSUE THREAD

**Issue by Offirmo** [sinonjs/sinon#2549]
First thanks for this amazing and reliable lib!

**Is your feature request related to a problem? Please describe.**
`yarn outdated` is telling me there is a new major versionof sinon. I'd like to check the changes. I couldn't find any changelog.

**Describe the solution you'd like**
There should be a changelog to evaluate the trade-offs of an upgrade.
It should be either:
* in Github releases
* in a standard CHANGELOG file
* on the website
Ideally there should be a CHANGELOG file and the website releases should point to it.

**Describe alternatives you've considered**
I checked:
* the release page: https://sinonjs.org/releases/v15/
  *  it doesn't contain any change log nor any link to a change log
* Github release notes https://github.com/sinonjs/sinon/releases
  * they're outdated (from 2018)
* any standard CHANGELOG file at the root of the repo?
  * there is none

**Comment by fatso83** [comment]
@mroderick [The changelog is online](https://sinonjs.org/releases/changelog), but I don't think we have ever had a reference to it 🙈

**Comment by fatso83** [comment]
Added the link in a linked pr.

**Comment by Offirmo** [comment]
Amazing! Thanks a lot!

I missed the `CHANGES.md` Any chance we could rename it to `CHANGELOG.md` for discoverability? It seems to be some sort of standard https://common-changelog.org/#21-file-format

Thanks again!

**Comment by fatso83** [comment]
I was thinking the same. It was actually called `History.md` at one point, so it should not be a matter of religious importance 😄

**Comment by fatso83** [comment]
We are inconsistent anyway. In the [fake-timers repo](https://github.com/sinonjs/fake-timers) it is called CHANGELOG, in `referee` CHANGES, in `nise` it's called [History.md](https://github.com/sinonjs/nise/blob/main/History.md), etc

**Comment by fatso83** [comment]
Even core contributor @mantoni's tool to generate such files, [@studio/changes](https://www.npmjs.com/package/@studio/changes), generates `CHANGES.md`, so we're somewhat consistent at least 🙃

**Comment by mantoni** [comment]
Studio Changes has a `--file` option if a different name is preferred.

**Comment by Offirmo** [comment]
Thanks again @fatso83 !

`yarn outdated` showed me the 17.0 update today and by following the link I could find the CHANGELOG ✅
