### ISSUE TITLE
SyntaxError: Unexpected token . ->  assert(opts?.sinonXhrLib, "No XHR lib passed in");

### ISSUE THREAD

**Issue by chuphalashit19** [sinonjs/sinon#2583]
**Describe the bug**
SyntaxError: Unexpected token .
 assert(opts?.sinonXhrLib, "No XHR lib passed in");

**To Reproduce**

1. Go to file sinon/lib/create-sinon-api.js:19

**Screenshots**
![image](https://github.com/sinonjs/sinon/assets/55797173/dd20f381-66dc-4d71-9958-71f80ef01f8b)

By when can we expect this problem to be resolved as it is failing our builds

**Comment by fatso83** [comment]
[Please fill in the entire bug template](https://github.com/sinonjs/sinon/blob/main/.github/ISSUE_TEMPLATE/Bug_report.md?plain=1). It's there for a reason.You are missing a lot of very essential information. I'll close this and you can reopen it when done.
