### ISSUE TITLE
Cannot stub private methods in native JavaScript classes

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [sinonjs/sinon#2588]
**Describe the bug**
I'm trying to test a native JavaScript class that contains a mix of public and [private methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#private_methods). While I can easily stub the public methods to test them, I'm unable to do so with the private methods.

I've tested against Sinon.JS 9.2.4 in our codebase, as well as against what I believe to be Sinon.JS 17.0.1 (in the console while visiting https://sinonjs.org/), and the behaviour is the same: an error stating "TypeError: Cannot stub non-existent property [name]".

**To Reproduce**
- Visit https://sinonjs.org/
- Open the console and set up a class. I used the following code:
```javascript
const MyClass = class {
  aPublicMethod() {
    console.log('public');
  }

   #aPrivateMethod() {
     console.log('private');
   }
}
const myInstance = new MyClass();
```
- Try and stub the public method: `sinon.stub(myInstance, 'aPublicMethod')` - this works fine
- Try and stub the private method - either with or without the hash prefix: `sinon.stub(myInstance, 'aPrivateMethod')` or `sinon.stub(myInstance, '#aPrivateMethod')` - neither work

**Expected behaviour**
Stubbing private methods would work.

**Actual behaviour**
I get an error: "TypeError: Cannot stub non-existent property #aPrivateMethod".

**Context (please complete the following information):**
- Sinon version : 9.2.4 and 17,.0.1 (see note at top of issue)
- Runtime: Chrome 121.0.6167.184 (Official Build) (x86_64)

**Comment by fatso83** [comment]
This is not a bug. [To quote MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties):

> Private properties get created by using a hash # prefix and cannot be legally referenced outside of the class. The privacy encapsulation of these class properties is enforced by JavaScript itself.

Sinon cannot do magic. If the JS engine itself prevents any other object from reaching the property, neither can we. As you can see from the below screenshot, there is no trace of the private field in the `MyClass` prototype. If it does not have a property for us to manipulate, we cannot reference it.
```
<img width="607" alt="image" src="https://github.com/sinonjs/sinon/assets/618076/89c49cb4-6b52-4052-a72c-c4b96a0a37bd">
```

And frankly, that is exactly how it should be. If your unit tests are tampering with privates you should rightly be prevented from accessing them 😄 If you don't want JS to enforce privacy, don't use the feature. You could then use a convention as in the old days of having `__privateProperty` or something, if you really wish to.
