### ISSUE TITLE
docs: overview of compatible nodejs versions

### ISSUE THREAD

**Issue by Rotzbua** [sinonjs/sinon#2601]
**Is your feature request related to a problem? Please describe.**

The support docs states that the current LTS nodejs is supported.

For projects that are slower to upgrade the node version, it is difficult to find the correct sinon version, as the current LTS version is newer than the old one required by the projects. Currently it is difficult to find out which sinon version supports an old node version.

**Describe the solution you'd like**

Simple table which states which is the minimum supported node version for every mayor sinon version.

| Sinon | min Node |
|-------|----------|
| 18    | 18       |
| 17    | 18       |

**Describe alternatives you've considered**

As alternative re-add and maintain engines attribute in package.json for upcoming releases. Was removed in #1608.

**Additional context**
nope

**Comment by fatso83** [comment]
Finding historic versions for Node is indeed a good case. I guess we could try to reflect this somehow. Maybe we should have a little unit test that checks the versions running on CI are the same ones listed. Not sure how to keep it in sync otherwise.

**Comment by fatso83** [comment]
Thanks for the PR. I supplied feedback on https://github.com/sinonjs/sinon/pull/2602 last week.

**Comment by fatso83** [comment]
It's possible to automate like this in our pipeline. This is how to extract the major versions:
```
❯  echo "node 20.10.0" | awk '{split($2, a, "."); print a[1]} '
20
```

So this would be sufficient to get the Node versions supported during a build:
```
"npx" browserslist 'maintained node versions'  | awk '{split($2, a, "."); print a[1]} '
20
18
```

Do you want to have a stab at how this could be used to automate updating some table or similarly?
