### ISSUE TITLE
Mysterious undocumented v18

### ISSUE THREAD

**Issue by Offirmo** [sinonjs/sinon#2604]
Hi team, thank you for this amazing lib!

yarn is prompting me to upgrade to sinon v18

![Screenshot 2024-06-01 at 16 30 12](https://github.com/sinonjs/sinon/assets/603503/28caea6b-38b3-4846-a9bc-e1f203ee6466)

However this v18 is undocumented:

- https://sinonjs.org/releases/
- https://sinonjs.org/releases/changelog

In those day and ages of supply chain attacks, I was wondering if something was wrong?

Thanks!

**Comment by fatso83** [comment]
Thanks for bringing this to our attention. Something must have gone wrong when doing the release that I did not notice. I'll re-run the release bits.

**Comment by fatso83** [comment]
v18 is now out on sinonjs.org. Thanks!

**"fix":**
```
DRY_RUN=1 scripts/postversion.sh 
git push origin releases 
```
