### ISSUE TITLE
sinonjs/text-encoding is not tagged

### ISSUE THREAD

**Issue by bastien-roucaries** [sinonjs/sinon#2607]
Hi,

Debian project and ubuntu like to have github version tagged

Could you tag the last version https://github.com/sinonjs/text-encoding

Thanks

**Comment by fatso83** [comment]
It's unclear what you are asking. Do you mean a Git tag, a NPM tag, what? Please be specific. What is the Definition of Done here? Give some references to policies and possibly other repos that enforce this.

**Comment by bastien-roucaries** [comment]
Le lundi 19 août 2024, 14:04:17 UTC Carl-Erik Kopseng a écrit :
> It's unclear what you are asking. Do you mean a Git tag, a NPM tag, what? Please be specific. What is the Definition of Done here? Give some references to policies and possibly other repos that enforce this.
> 
> 
Pleae add a git tag

Thanks

Bastien

**Comment by fatso83** [comment]
✅ 

- https://github.com/sinonjs/text-encoding/compare/v0.7.2...22e9676

````
❯ git tag
0.7.1   v0.1.0  v0.5.1  v0.5.3  v0.5.5  v0.6.1  v0.6.3  v0.7.0  v0.7.2
0.7.2   v0.5.0  v0.5.2  v0.5.4  v0.6.0  v0.6.2  v0.6.4  v0.7.1  v0.7.3
```
