### ISSUE TITLE
Sinon.assert does not work with new dates form Sinon timers

### ISSUE THREAD

**Issue by krystianolech** [sinonjs/sinon#2630]
Hello, I noticed that on Sinon 19 some of my test stoped working.
Case where it happen is related to situations where fakeTimers are used with something that is passed to function and later asserted by Sinon.match.

Here is minimal code to reproduce it:

```typescript
import * as Sinon from "sinon";

const now = new Date("2024-01-01");
const clock = Sinon.useFakeTimers({
  now,
  toFake: ["Date"],
});

const stub = Sinon.stub();

stub(new Date());

Sinon.assert.calledWith(stub, now);
```

This code works fine on v18 but it fails on v19.

**Comment by fatso83** [comment]
This is interesting. The code fails when running with the latest Sinon from NPM, but it does not fail with the latest source code in the repo 🤔 

```
✦ ❯ cat my-test.mjs
import * as Sinon from "sinon";
import { test } from "mocha";

test("test date", function () {
  const now = new Date("2024-01-01");
  const clock = Sinon.useFakeTimers({
    now,
    toFake: ["Date"],
  });

  const stub = Sinon.stub();

  stub(new Date());

  Sinon.assert.calledWith(stub, now);
});
```

```
✦ ❯ npx mocha my-test.mjs


  1) test date

  0 passing (7ms)
  1 failing

  1) test date:
     AssertError: expected stub to be called with arguments
Mon Jan 01 2024 01:00:00 GMT+0100 (GMT+01:00)
      at Object.fail (file:///private/tmp/node_modules/sinon/pkg/sinon-esm.js:131:27)
      at failAssertion (file:///private/tmp/node_modules/sinon/pkg/sinon-esm.js:274:20)
      at assert.<computed> [as calledWith] (file:///private/tmp/node_modules/sinon/pkg/sinon-esm.js:303:17)
      at Context.<anonymous> (file:///private/tmp/my-test.mjs:15:16)
      at process.processImmediate (node:internal/timers:478:21)
```

**Now using a reference to the build in locally**
```
# First did this
cd ~/dev/sinon
npm run build
```

Changed the top line to read
```
import * as Sinon from "./pkg/sinon-esm.js";
```

then ran it:
```
npx mocha my-test.mjs


  ✔ test date

  1 passing (5ms)
```

Not expected.

**Comment by fatso83** [comment]
For some reason, I am unable to make it pass locally. Which is good, I guess, but I have no idea how I made it pass.

There seems to be a reference issue somehow. The time is the same in the object, but not the reference.
<img width="1203" alt="Skjermbilde 2024-12-04 kl  12 20 47" src="https://github.com/user-attachments/assets/ff28f0c3-ccd5-4fea-ac10-5386cee0e8bb">

**EDIT:**
... 
Ah. I got it now. This is not an error. After naming the objects that are involved, I just realised you are creating a Date object before installing timers, creating a _new_ object, calling the stub with the second object, and then asserting that you have called the stub with the first. That is a logical error in itself. So this is not a bug, even if it should have worked by chance earlier.

<img width="903" alt="Skjermbilde 2024-12-05 kl  15 16 36" src="https://github.com/user-attachments/assets/36ac7387-00a3-4ff7-80a7-adf023070370">

The test should have assert that you called the stub with the passed-in object, not the one that initialised time. At best, you could compare that the time was equal.

**Comment by krystianolech** [comment]
@fatso83 thank you for verifying!
I want to follow up on this - both dates will be different instances of date object but storing same date.
My understanding was that Sinon.match is competing dates not references.
Do I get it right that it's not a case? Is there any build in way to compare dates inside sinon.match?

**Comment by fatso83** [comment]
[From the docs](https://sinonjs.org/releases/v19/assertions/) it says
> 
```
sinon.assert.calledWith(spyOrSpyCall, arg1, arg2, ...);
```
> Passes if spy was called with the provided arguments.

It does not say much about "soft" comparisons, so given nothing else, this will be a reference check.

I am not aware of anything else that will do that - out of the box, but you could of course pull out the args and compare those (doing `.getTime()`, etc). Not as elegant, of course :(
