### ISSUE TITLE
stub.resetBehavior() missing in documentation

### ISSUE THREAD

**Issue by ikokostya** [sinonjs/sinon#267]
`sinon 1.6.0`

Method `stub.resetBehavior()` looks like public but it missing in documentation.
What difference between `stub.yields()` and `stub.thenYields()`?

**Comment by dotchev** [comment]
I still find `resetBehavior` useful and worth documenting.

Consider this code
```js
Generally it makes a lot of sense to be able to reset all behavior-related changes on a stub.

**Comment by mroderick** [comment]
Please don't revive issues that have been closed for years.

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. If you have usage questions, please post them to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you believe that you've found a bug in Sinon.JS, please open a brand new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
