### ISSUE TITLE
stub doc omission about how to restore whole-object methods was confusing

### ISSUE THREAD

**Issue by dmose** [sinonjs/sinon#270]
From the current website docs:

var stub = sinon.stub(obj);
    Stubs all the object's methods.

I tried to use stub.restore, and was confused to not find it there.  Adding a sentence to the docs that explicitly stated that the way forward here is to use sandboxes or sinon.test() would have been very helpful.

That said, Sinon is great; thanks for all the hard work!

**Comment by Pyrolistical** [comment]
This is not part of the documentation http://sinonjs.org/docs/#stubs

Without reading the docs I tried `stub.restore()`.  Should we add the method `restore` if doesn't already exist?  It would avoid clobbering and existing `restore` method.

**Comment by mroderick** [comment]
> This is not part of the documentation http://sinonjs.org/docs/#stubs

You're right, it isn't. I've created #810 to keep it on the radar. It should be a fairly easy contribution to make.

If you find other gaps in the documentation, please don't hesitate to create an issue for them.

> Should we add the method restore if doesn't already exist? It would avoid clobbering an existing restore method.

Nobody likes surprises (in code). Where possible, the behaviour should be consistent, not conditional.
