### ISSUE TITLE
(Simple) Higher-level abstraction for `fakeServer`

### ISSUE THREAD

**Issue by kjbekkelund** [sinonjs/sinon#284]
I've been using Sinon.JS to write quite a few tests for various applications, and I always end up creating a couple of small helpers to help keep my tests clean when working with fake XMLHttpRequests.

First of all, I'm not a big fan of creating a `fakeServer` in `beforeEach`. I don't like putting things in `beforeEach` that is not used in _all_ the tests, and I almost always only perform Ajax requests in a subset of the tests. 

Also, in most of my tests there is only one Ajax request I want to respond to.

Simple example with today's api:

``` javascript
var server = sinon.fakeServer.create();
server.respondWith([200, { "Content-Type": "application/json" },
        '[{ "id": 12, "comment": "Hey there" }]']);

// perform ajax request

server.respond();

// request has responed

server.restore();
```

My proposal:

``` javascript
sinon.fakeResponse([{ "id": 12, "comment": "Hey there" }], function() {
    // perform ajax request
});
// request has responed
```

I.e. it defaults to `200` and `application/json`. It also `JSON.stringify`s the input if is not already a string. It can also accept an options object, e.g.

``` javascript
sinon.fakeResponse({ "msg": "fail" }, { statusCode: 400 }, function() {
    // perform ajax request
});
// request has responed
```

It's not a big thing, but I think my test code looks far cleaner when using this abstraction.

Any thoughts? If there's an interest I'll create a pull request.

**Comment by fatso83** [comment]
I have made an [attempt at implementing this](https://github.com/fatso83/sinon/commit/3d5a11a0b829ba0aac27a15e1a3a99b1b8cbecf1), but although the tests run by `buster-test --config test/buster.js` pass, the tests fail miserably when I run `./scripts/ci-test.sh`:
  UncaughtError: ./buster/bundle-0.7.js:14997 TypeError: test:setUp listener threw error: 'undefined' is not a function (evaluating 'sandbox.inject(test.testCase)')

The errors seem to be in the Buster test runner. I think this has something to do with me removing these methods from the sinon.sandbox property, although they are present on any actual created sandbox. Any tips on progressing with fixing these errors?

**Comment by mantoni** [comment]
I still like the idea of `sinon.sandbox`, especially because it would work with the new arrow functions which I tend to use in Mocha these days. Unfortunately, this will not make it into Sinon 2 since we just have to make a cut at some point to the the release (finally) out the door. We should consider the addition of `sinon.sandbox` as a feature and the deprecation of `sinon.test`, and reworking / merging `sinon.sandbox.create` for a later major.
