### ISSUE TITLE
Exception when restoring methods under phantomjs

### ISSUE THREAD

**Issue by giulianob** [sinonjs/sinon#306]
When running our tests in phantomjs, we're seeing an exception that gets thrown when sinonjs is restoring sessionStorage.getItem method. It happens at the following "delete" call:

```
            method.restore = function () {
                // For prototype properties try to reset by delete first.
                // If this fails (ex: localStorage on mobile safari) then force a reset
                // via direct assignment.
                if (!owned) {
                    delete object[property];
                }
                if (object[property] === method) {
                    object[property] = wrappedMethod;
                }
            };
```

After some research, it appears that delete will throw exceptions when javascript is running in strict mode if it's unable to delete a property. From Mozilla's page: "Third, strict mode makes attempts to delete undeletable properties throw (where before the attempt would simply have no effect):" In Chrome, when we delete sessionStorage.getItem after it's wrapped it simply sets it back to the native implementation. In Phantom, it throws an exception if it's unable to delete. It looks like the comment above already expects cases where the delete fails and the method needs to be restored manually but it doesnt expect cases where the delete throws an exception.

Would it be possible to add a try/catch around the delete for strict browsers?

**Comment by nmabhinandan** [comment]
Cannot restore sinon spies in phantom js. But it's working fine in chrome

**Comment by dynaum** [comment]
+1

**Comment by GCheung55** [comment]
Could you describe your setup or share code to reproduce the issue?
