### ISSUE TITLE
Sinon.fakeServer does not work under Node.js because its file isn't wrapped properly

### ISSUE THREAD

**Issue by moll** [sinonjs/sinon#319]
The `fake_xml_http_request.js` file has an iffy wrapping it for proper `global` access. The `fake_server.js` file does not and with the following "check" in its header it never has a chance to get a reference to the global `sinon` because the `var sinon` declaration is hoisted to the top of the scope:

``` javascript
if (typeof sinon == "undefined") {
    var sinon = {};
}
```

**Comment by hayesmaker** [comment]
that's cool, because it doesn't work in the browser either
