### ISSUE TITLE
Sinon.js not working when minified

### ISSUE THREAD

**Issue by Timothee** [sinonjs/sinon#332]
Hello,

I came across an issue that puzzled me for a bit: my tests were running fine in the browser, but didn't when running in PhantomJS.
The reason was that we have PhantomJS set to run on a minified version of our code. The culprit is this part of the code: (https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/spy.js#L75-L88)

``` javascript
    function createProxy(func) {
        // Retain the function length:
        var p;
        if (func.length) {
            eval("p = (function proxy(" + vars.substring(0, func.length * 2 - 1) +
                ") { return p.invoke(func, this, slice.call(arguments)); });");
        }
        else {
            p = function proxy() {
                return p.invoke(func, this, slice.call(arguments));
            };
        }
        return p;
    }
```

When minified `p` and `func` can be renamed to anything (in my case `b` and `c`), so the call to `eval()` doesn't do anything useful. Then the spy is actually set to `undefined` and it of course fails at some point.

The `eval()` call looks like it's there to make sure the spy has the right `length` property. I dug through the commit history and it came back to this one: https://github.com/cjohansen/Sinon.JS/commit/facc8280baa4713a95321f4a31cb50f811064570 where a big `switch/case` block was replaced with `eval`.

Right now, it seems that options are:
- to bring back a huge `switch/case` block, but nobody wants that :)
- drop the requirement to have `spy.length` return the same value as the function that is being spied on
- leave it as it is, why would one want to minify Sinon anyway?

As far as I'm concerned, I'll just put sinon out of our minified version and be done with it, but I figured I should bring it up since it wasn't easy to identify.

I'll be happy to write a patch as needed, based on where the discussion goes.

**Comment by nicolasv** [comment]
I'm running into this problem with `sinon.fakeServer` being undefined in the minified version of sinon 1.15.4: http://jsbin.com/yipina/1/edit?html,console

Working around it by using the non-minified version.
