### ISSUE TITLE
respondWith doesn't work with certain parameters

### ISSUE THREAD

**Issue by xenyou** [sinonjs/sinon#336]
If respondWith called with a URL including query parameter and a function , it doesn't work.

http://jsbin.com/iyebiWI/8/edit?html,js,output

This error reported in console.

```
TypeError: requestUrl.match(...) is null
```

**Comment by mroderick** [comment]
This has been fixed in `sinon@2.0.0`.

http://jsbin.com/iyebiWI/8/edit?html,js,output
