### ISSUE TITLE
Consider making stubs' async callbacks play well with fake timers

### ISSUE THREAD

**Issue by julienw** [sinonjs/sinon#339]
When using fake timers in a browser environment that doesn't have setImmediate, async stubs need that we manually call `sinon.clock.tick()` to trigger the call.

It would be very nice that somehow the fake timers expose a "nextTick" function that the stub's async callback could use.

I think this wouldn't break existing code, as users calling explictly tick() would then do nothing.

Or the async callback could call `sinon.clock.tick()` if the fake timers run, but I fear this could have side effects if other timeouts are already scheduled.

What do you think ?

**Comment by mroderick** [comment]
Could you provide a couple of examples on how this would be used, to make it clearer what you're suggesting?

**Comment by julienw** [comment]
```javascript
setup(function() {
  this.sinon.useFakeTimers();
  this.sinon.stub(myObject, 'method').yieldsAsync();
});

...

test('times out', function(done) {
  myObject.method(function() { done(); });
  // times out because yieldsAsync uses setTimeout internally.
});
```

This works instead:
```javascript
setup(function() {
  this.sinon.useFakeTimers();
 this.sinon.stub(myObject, 'method');
});

test('works', function(done) {
  myObject.method(function() { done(); });
  myObject.method.yield();
});
```

But I wonder if *async methods should not play better with fake timers. "play better" could be as simple as throwing because we use fake timers. Or using another mechanism than setTimeout. Or use the real setTimeout instead of the fake setTimeout. It's actually your choice.

I think my preference would go to throwing: if we use fake timers, it's usually because we don't want asynchronous stuff. But a micro/macrotask-based solution would also prevent timeouts, so it would be nice as well.

**Comment by mantoni** [comment]
Hm, I see your point, but throwing would be a breaking change. The problem is that people might already use it in this context and simply do call `clock.tick()` to trigger the async callback.

I agree that it's not particularly nice the way it is and the current behavior is also not completely obvious. How about adding something like this:

```js
var clock = sinon.useFakeTimers();
clock.autoYieldAsync(); // not the best name maybe
```

This would perform real async yields, as if there was no fake timer. Would that make it better?

**Comment by julienw** [comment]
This could work, yep.

Another possibility could be `clock.throwOnAsyncOperations()` :)

and please make it return "clock" we could just do `clock = sinon.useFakeTimers().throwOnAsyncOperations()`)


Is it possible to still output a console.warn if using an async stub operation with fake timers ? Likely only when it's called because a user could set the fake timer _after_ setting an async stub.

**Comment by mantoni** [comment]
@mroderick @cjohansen Do you guys also think this features makes sense? If yes, the hardest question in software development: how do we name the function(s)?

**Comment by cjohansen** [comment]
Seems to me that it is a bug that async stubs time out when the timers are faked. Shouldn't the async callbacks just use the real `setTimeout`? You use fake timers to control the execution of your app code, not the testing system.

**Comment by mantoni** [comment]
@cjohansen Now that is way too obvious :cake:

**Comment by fearphage** [comment]
This [looks fixed](http://jsbin.com/jutiso/edit?html,js,console). Please reopen if I'm wrong.

**Comment by julienw** [comment]
So I debugged quickly and I think this works by chance:

* this works in the browser because browserify injects a polyfill for process.nextTick.  See https://github.com/defunctzombie/node-process/commit/e481e478c838f7f09a68f28facdbf6345b4dd99d where they started caching setTimeout especially for this case :)
  And yieldsAsync uses `process.nextTick` if it finds it: see https://github.com/sinonjs/sinon/blob/4f3a3acd70041aff54ea2f50704f17115badb295/lib/sinon/behavior.js#L12
* this works in node because process.nextTick exists

Should sinon rely on browserify injection and simplify the code from the previous link?

**Comment by mroderick** [comment]
> Should sinon rely on browserify injection and simplify the code from the previous link?

I would prefer if we didn't rely on side effects from using a particular bundler

**Comment by julienw** [comment]
I think other bundlers do it too -- at least I know webpack injects `https://github.com/defunctzombie/node-process/blob/master/browser.js` by default.
