### ISSUE TITLE
Clock not working with jQuery animations

### ISSUE THREAD

**Issue by mikeobrien** [sinonjs/sinon#355]
So I'm trying to use the clock to test the visibility of an element after a fade in. I cannot seem to get this to work at all, it's as if the element is not completing the animation. If I use the clock against a `setTimeout` it works. Also if I use mocha's async `done()` I can see that the animation completes (So I know for sure that it's happening). I tried using the [example in the docs for animations and the clock](http://sinonjs.org/docs/#clock) and it doesn't work either. Here is a fiddle of my tests:

http://jsfiddle.net/hcoverlambda/R9Pa5/8/

Any ideas?

**Comment by mroderick** [comment]
@mikeobrien the runnable example is broken. Would you mind fixing it up? It'll help people understand the issue, making it more likely that someone will work on it. Thanks

**Comment by Munksey** [comment]
I am using jQuery 2.1.3 and found that the jQuery.now method needs to be stubbed. I imagine that when jQuery gets loaded, it keeps a reference to Date.now before it gets stubbed.

Running something like this will resolve the problem:

`  
  before(function() {
    this.clock = sinon.useFakeTimers();
    sinon.stub(jQuery, 'now', () => Date.now());
  });

  after(function() {
    this.clock.restore();
    jQuery.now.restore();
  });
`

**Comment by mroderick** [comment]
It is well established by now that (older) jQuery was not written very defensively. This is a bug on their side, and should be fixed there
