### ISSUE TITLE
Mocking objects - remove default functionality?

### ISSUE THREAD

**Issue by nzakas** [sinonjs/sinon#382]
We've been using mocks for a bit and ran into an issue. Let me first start with a simple example:

``` js
var mock = sinon.mock(myAPI);
mock.expects("myMethod").once();
```

This works pretty simply, I know that if I don't call `myAPI.myMethod()`, then the test will fail (or if it gets called more than once). I also know that the actual functionality for the method will not execute. That part works great.

The problem we've run into is if I call, for instance, `myAPI.anotherMethod()` in a test but it was unexpected that this would happen. Without hardcoding an expectation for each remaining method, I will never be informed that an unexpected method call occurred and, because I've already mocked out at least one method, there's a chance that the interaction between a fully-functional method and a mocked method will cause side effects.

There are mocking libraries in other languages that automatically create expectations for all methods on a mocked object (expects that the methods are not called unless otherwise specified) and remove the default functionality from those methods. Is there any chance this is being planned or discussed for Sinon?

**Comment by wryun** [comment]
Coming from a Python background, this is something I miss. What's the recommended way to stop incorrect calls passing through? If I'm mocking something that hits an external resource (db, http, etc.), I never want my call to actually hit the underlying library...

I could, as you suggest, stub(obj) and assert on that, but I still don't see the incorrect calls.

Agree with what @nzakas says about expectations; I feel like if stub can stub out everything in an object, mock should at least have option of doing so. How would you feel about a strictmock or similar?

**Comment by nzakas** [comment]
@wryun I created Leche to handle this case: https://github.com/box/leche

**Comment by wryun** [comment]
Great - thanks!
