### ISSUE TITLE
Can't stub the console.* functions in IE 7-9

### ISSUE THREAD

**Issue by fabiosantoscode** [sinonjs/sinon#386]
The following code (wrapped in an if-statement to check if console exists), fails in IE 9 (and earlier. Tested down to IE7).

```
var stub = sinon.stub(window.console, 'error', function () { /* ... */ })
```

This happens because in IE7-9 `typeof window.console.error === 'object'`, which makes sinonjs throw an error because it the stubbed object is not identified as a function. Is there any chance this can be fixed inside sinon-js?

My current workaround is:

```
if (typeof window.console.error === 'object') {
    var _consoleError = window.console.error;
    window.console.error = function (s) { _consoleError(s) }
}
```

And then I can stub console.error properly.

**Comment by peterkr** [comment]
+1

**Comment by peterkr** [comment]
@fabiosantoscode. this issue still exist, is there any work around get to use console.object in stub method. I have tried your workaround, but issue still persit by throwing the error "Object doesn't support this action".

**Comment by mroderick** [comment]
@fabiosantoscode I ended up writing [wrapple](https://github.com/mroderick/wrapple), perhaps that can solve the problem for you
