### ISSUE TITLE
clean up XHR event listeners on fake server

### ISSUE THREAD

**Issue by kumar303** [sinonjs/sinon#430]
If you need to test how your application responds to errors you could set up a test like this with a fake server:

```
var server = sinon.fakeServer.create();
server.respondWith(function(xhr, id) {
  xhr.dispatchEvent(new sinon.Event('error', null, null, xhr));
});
```

This works fine. However, the event listener persists across tests. You have to do some cleanup yourself, like this:

```
server.respondWith(function(xhr, id) {
  xhr.dispatchEvent(new sinon.Event('error', null, null, xhr));
  xhr.eventListeners = {};  // stop listening to events
});
```

It would be nicer if sinon did this itself when you call `server.restore()`, i.e. loop through all fake xhr objects and clear their event listeners.

**Comment by mroderick** [comment]
It's been more than three years, is this still relevant?

**Comment by kumar303** [comment]
I'm not sure. Feel free to close it; the bug hasn't been bothering me :)
