### ISSUE TITLE
XMLHttpRequest.abort() fires load event

### ISSUE THREAD

**Issue by kumar303** [sinonjs/sinon#432]
I'm working with code like this:

```
var server = sinon.fakeServer.create();
server.respondWith(function(xhr, id) {
  xhr.abort();
});
// make the request...
server.respond();
```

It seems that abort() triggers the `load` event first, with data. Eventually it triggers the abort event but the timing doesn't seem right. In reading the code I see that a ready state change before triggering abort is probably the culprit here. I think abort() should not trigger any load events at all.

Maybe I'm setting up an abort call wrong?

I'm using Sinon from node @1.9.0

**Comment by Standard8** [comment]
I believe this has been fixed in the latest code by #861. It isn't released yet, but the fix is there and seems to work.

**Comment by lddubeau** [comment]
I've tried with 1.17.4 which contains PR #861. To get jQuery to recognize an xhr as aborted in 1.17.3, I had to do this:

    xhr.readyState = sinon.FakeXMLHttpRequest.UNSENT;
    xhr.statusText = "abort";
    xhr.abort();

with 1.17.4, I have to do this:

    xhr.statusText = "abort";
    xhr.abort();

**Comment by fatso83** [comment]
There is currently a big discussion related to the changes introduced by 1.17.4 in https://github.com/sinonjs/sinon/issues/1040#issuecomment-216996170. Regarding what fires when, loaded events and errors, you might want to wait until the dust settles for a final solution. Seems like we have a bigger bug in here.

**Comment by fearphage** [comment]
I believe this issue has been resolved. If you disagree, feel free to reopen the issue with any additional details that you can provide.
