### ISSUE TITLE
Stubbing fs.readFileSync fails since 1.8.1

### ISSUE THREAD

**Issue by rprieto** [sinonjs/sinon#458]
In Sinon `1.7.0`, the following works as expected:

``` js
sinon.stub(fs, 'readFileSync');
```

Later versions seem to throw:

```
TypeError: Cannot call method 'charCodeAt' of undefined
```

Unfortunately I can't seem to get a real stack trace for the error. Stubbing `fs.readFile` (not sync) works fine, and I'm running Node `v0.10.25`.

**Comment by roc** [comment]
I also get this issue, in javascript... what should I add to usefully prove this?

**Comment by fearphage** [comment]
Is the code open source? Have you tried upgrading to a later version of sinon?

**Comment by roc** [comment]
@fearphage didn't have any free time to reproduce this until now. Here's an example with `proxyquire`, which I feel maybe muddies the waters of what's happening here, but I'd hoped it might be useful nonetheless:

https://github.com/roc/sinon-filesync

**Comment by fearphage** [comment]
@roc Your test case is a no go. It's broken. No passing tests at all.

```shell
➜  sinon-filesync git:(master) mocha         


  loading a file and printing it
    1) should say hello m8

  replace file contents
    2) "before all" hook


  0 passing (13ms)
  2 failing

  1) loading a file and printing it should say hello m8:
     TypeError: Cannot read property 'charCodeAt' of undefined
      at Object.stripBOM (internal/module.js:48:14)
      at require (internal/module.js:20:19)
      at Context.it (test/index.js:11:17)

  2) replace file contents "before all" hook:
     TypeError: Cannot read property 'charCodeAt' of undefined
      at Object.stripBOM (internal/module.js:48:14)
      at Object.require.extensions.(anonymous function) (node_modules/proxyquire/lib/proxyquire.js:259:43)
      at Proxyquire._withoutCache (node_modules/proxyquire/lib/proxyquire.js:179:12)
      at Proxyquire.load (node_modules/proxyquire/lib/proxyquire.js:136:15)
      at Context.before (test/index.js:22:11)
```

**Comment by fearphage** [comment]
```js
'use strict'

const file = require('fs').readFileSync(
  __dirname + '/file.txt', 'utf8'
);

module.exports = `hello ${file}`;
```

The way your code is written you'll never be able to mock it out without something like `proxyquire`. You're calling functions at import-time which is generally a bad idea. To rephrase, as soon as someone require's your file, you start executing code. That's suboptimal. If you altered your code a bit, it would make it much easier to test and much more friendly for other people to use.

```js
const fs = require('fs');

module.exports = function() {
  return `hello ${fs.readFileSync(...)}`;
};
```

Here's an example of it working for someone else:

http://stackoverflow.com/questions/18044737/mock-fs-readdir-for-testing
