### ISSUE TITLE
Calling both callbacks passed to function

### ISSUE THREAD

**Issue by horaklukas** [sinonjs/sinon#460]
When I have stubed function that takes two or more callback arguments, eg. `drag(moveCallback, startCallback, stopCallback)` then I need to invoke more than one callback at test. For example I want to invoke `startCallback(x, y)` for saving drag start position and then `moveCallback(dx, dy)` for setting image position (move it) with function `img.position(x, y)`. But when I write test like this

```
img.drag.callsArgOn(1, img)
img.drag.callsArgOnWith(0, img, 20, 30)

setImageDragging(img)

Img.stream.position.should.been.calledWithExactly(20, 30)
```

only the second callback (at position 1) is called. Is there possibility to invoke both callbacks (with stub's method that changes context of callback)?

**Comment by mantoni** [comment]
The docs are still missing. This will be tracked by #1411. Closing.
