### ISSUE TITLE
Implement withExactArgs for stubs

### ISSUE THREAD

**Issue by julienw** [sinonjs/sinon#461]
There is currently no way to do something like:

``` javascript
var stub = sinon.stub().returns(false);
stub.withExactArgs('foo').returns(true);
stub.withArgs('foo', 1).returns(true);
```

So that:

``` javascript
stub('foo') // returns true
stub('foo', 1) // returns true
stub('foo', 2) // returns false
```

If I use `stub.withArgs('foo')` instead, then `stub('foo', 2)` returns true.

**Comment by mroderick** [comment]
@julienw are you still working on this?

**Comment by julienw** [comment]
I never worked on this ;)

**Comment by mroderick** [comment]
Since this hasn't seen any traction for three years, I am going to close it. If anyone wants to work on this, they're welcome to re-open this issue
