### ISSUE TITLE
Progress Event - must have lengthComputable parameter

### ISSUE THREAD

**Issue by AidasK** [sinonjs/sinon#467]
https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/event.js#L45
http://www.w3.org/TR/2014/REC-progress-events-20140211/#dom-progressevent-lengthcomputable

**Comment by khaliy** [comment]
As a consumer this is a must have for me, I assume no one else has a PR for this so my aim is to fix it.

**Comment by cjohansen** [comment]
:+1:

**Comment by khaliy** [comment]
I have some problem running unit tests, seems the tests are not executed unless some common package. How can I run all of the tests?

**Comment by mroderick** [comment]
@khaliy what output are you seeing? How do you determine that not all tests are run?

**Comment by khaliy** [comment]
When I run npm tests: 
19 test cases, 1120 tests, 1866 assertions, 0 failures, 0 errors, 0 timeouts, 2 deferred

with phantomjs: 
3 test cases
77 tests
201 assertions
0 failures
0 errors
0 timeouts

And in browser:
2 test cases 73 tests 97 assertions 0 failures 0 errors 0 timeouts

**Comment by khaliy** [comment]
By TDD I added a test which fails by default but all of these were still passed.

**Comment by khaliy** [comment]
Without being able to run my tests, please check the PR.
Thanks

**Comment by fearphage** [comment]
Fixed a while ago
