### ISSUE TITLE
Enhancement: Save Multiple withArgs for multiple calls

### ISSUE THREAD

**Issue by marcosrmendez** [sinonjs/sinon#483]
For example if I want to test that a function is called 5 times, passing parameter 1, 2,3,4,5

sinon.mock(object).expects('method').exactly(5).withArgs(0).withArgs(1).withArgs(2).withArgs(3).withArgs(4);

**Comment by joshma** [comment]
I think I have a similar issue - I'd like to assert that a method gets called once with arg X, and once with arg Y. Maybe there's some other way I'm missing?

```
> x = {foo: function(y) { return y + 1; }}
> sinon.mock(x).expects('foo').once().withArgs(100).once().withArgs(200)
> x.foo(100)
< sinon.js:3712 Uncaught Error: Unexpected call: foo(100)
    Expected foo(200[, ...]) once (never called)
    Expected foo(200[, ...]) once (never called)
    at Object.fail (http://sinonjs.org/releases/sinon.js:3712:33)
    at Object.invokeMethod (http://sinonjs.org/releases/sinon.js:3442:35)
    at Object.foo (http://sinonjs.org/releases/sinon.js:3364:43)
```
