### ISSUE TITLE
Feature request: Optionally have fakeServer remove each response from the stack as used.

### ISSUE THREAD

**Issue by muffinresearch** [sinonjs/sinon#498]
I'd like to be able to use the fakeServer but instead of it respond with the most recently added match, I'd like it to operate on a stack of responses such that with each response the response is removed.

This is nice for testing because it makes responses more explicit and makes sure things aren't just happening because you are receiving the same response more than once if called a second time.

Here's an example: If I want to test some code to ensure that if a poll response changes it's handled correctly it would be much easier if I could make multiple `respondWith` calls knowing that they will be used in the same order they were added.

To make this work there's really only a couple of minor changes required. I'd suggest this could be an optional feature. E.g. you'd pass some kind of consumeStack=true into create or something like that. This way it won't break backwards compatibility.

I see a similar ticket was raised #368 but the solution given assumes a more manual approach to set up. I don't want to have to set up responses around the code I'm testing as I'm testing at a higher flow level.

I'm currently overriding `processRequest` but that requires adding a lot of the other util functions which aren't otherwise exposed.

Another possibility might be to change the API so that `respondWith` can optionally remove the response on first use. Or have something like `respondWithOnce()`

I'd be happy to work on a PR for this but before doing so I wanted to sanity check the idea and check I'm not missing some obvious other way to do the same thing.

**Comment by blimmer** [comment]
I would really like something like this, as well. `stub` has a [really nice API](http://sinonjs.org/docs/#stub-onCall) to do this with `stub.onCall`, and it would be great to be able to do something like this.
