### ISSUE TITLE
$.ajax or fakeServer async:false issue with jQuery 2.1.*

### ISSUE THREAD

**Issue by UYEONG** [sinonjs/sinon#510]
http://jsfiddle.net/uyeong21c/tz7wj/

Passes in jQuery 1.11.0
Fails in jQuery 2.1.0

**Comment by mroderick** [comment]
This was fixed in https://github.com/sinonjs/sinon/commit/4e630b167ed661823a9b2b4d9ff2ac2d1af1db7c
