### ISSUE TITLE
sandbox.restore cannot restore fakeTimers in it

### ISSUE THREAD

**Issue by mocheng** [sinonjs/sinon#550]
Below test case fails on timeout.

``` javascript
    suite('#sandbox#', function() {
        test('should restore all fake', function(done) {
            var foo = {
                bar: function() {
                    return 3;
                }
            };

            var sandbox = sinon.sandbox.create();
            sandbox.stub(foo);

            foo.bar.returns(1);
            assert.equal(1, foo.bar());

            sandbox.useFakeTimers();

            var ok = false;
            setTimeout(function() {
                ok = true;
            }, 5000);

            sandbox.clock.tick(5000 + 1);
            assert.equal(true, ok);

            sandbox.restore();
            assert.equal(3, foo.bar());

            setTimeout(function() {
                // This never get called.
                done();
            }, 1);
        });
    });
```

After `sandbox.restore()`, the stub is restored, but fakeTimers are not.

Sandbox should restore all fakes hooked on it, right?
or something wrong in my code?

Thanks.

**Comment by Munksey** [comment]
I think this issue has been open for a while, but I have a situation in which setTimeout is not restored.

```
describe('setTimeout restore', function () {
  const original = window.setTimeout;

  it('restores setTimeout', function () {
    const sandbox = sinon.sandbox.create();

    sandbox.useFakeTimers();
    sandbox.spy(window, 'setTimeout');
    sandbox.restore();

    expect(original).to.equal(setTimeout);
  });
});
```

I'm wondering what the correct behavior here is. Normally, sinon doesn't let you wrap something that is already wrapped. Should this produce an error or should it restore the timer?

**Comment by LadnovSasha** [comment]
I had the same issue. Please make sure you are not calling `sinon.useFakeTimers()` twice in a row, without restoring behavior to default

**Comment by electrotype** [comment]
> I had the same issue. Please make sure you are not calling `sinon.useFakeTimers()` twice in a row, without restoring behavior to default

Thank you so much for taking the time to write the solution.
