### ISSUE TITLE
Object has no method 'useFakeXMLHttpRequest'

### ISSUE THREAD

**Issue by vevo-kurt-snyder** [sinonjs/sinon#551]
I can't set up a an XHR fake -- here's my code:

console.dir sinon
xhr = sinon.useFakeXMLHttpRequest()

The first line indicates I've got the module -- output is:
{ wrapMethod: [Function: wrapMethod],
  extend: [Function: extend],
  create: [Function: create],
  deepEqual: [Function: deepEqual],
  functionName: [Function: functionName],
  functionToString: [Function: toString],
  getConfig: [Function],  ...

But I can't actually call the function:

TypeError: Object #<Object> has no method 'useFakeXMLHttpRequest'

**Comment by mantoni** [comment]
This should have been addressed in Sinon 2 with the CommonJS refactoring. If this is still an issue, please shout and we'll reopen.
