### ISSUE TITLE
AMD: Built version from master is broken

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#555]
I've tried to create a [pull request to verify that the API is working in AMD contexts](https://github.com/cjohansen/Sinon.JS/pull/554), and it seems to be working fine in the source version. 

The current master does not build Sinon in a way that works with RequireJS.

Steps to reproduce
https://gist.github.com/mroderick/82fcb7caa43aced684c8

Some of this was discussed in #553

@neonstalwart @cjohansen @mantoni I think this is all that is blocking us from doing a new release and drawing a line in the sand. I am too tired to wrap my head around this, if any of you could have a look that would be great.

**Comment by kentcdodds** [comment]
@jhnns, thanks for the tip of using the 2.0 branch. Are you aware of whether this is still necessary?

**Comment by leftcoastgeek** [comment]
does anyone have the 1.x branch working with webpack? I'd like to use that branch since its actively being developed. I've not been able to get the npm or prebuilt version of sinon to work with webpack.
