### ISSUE TITLE
sandbox.useFakeServer() does not actually setup sandbox.requests

### ISSUE THREAD

**Issue by bitinn** [sinonjs/sinon#568]
I would like to be proved wrong, but it would seem `sandbox.useFakeServer()` will only create the fake server object on `sandbox.server`, but not fake XHR on `sandbox.requests` (return `undefined` in my simple test).

```
sandbox = sinon.sandbox.create();
sandbox.useFakeServer();
console.log(sandbox.requests);
```
PS: I am not sure the best practice on this, but it would seem that one would either fake XHR or fake server response, but probably not both?

**Comment by fearphage** [comment]
Very old issue. Came up in searching.

```js
var server = sandbox.useFakeServer();
console.log(server.requests.length);

// logs "0"
```
