### ISSUE TITLE
Feature Request: make XHR2 testing easier

### ISSUE THREAD

**Issue by bitinn** [sinonjs/sinon#569]
A notable issue being that fakeServer and fakeXHR do not populate `xhr.response`, this is quite critical to  [XHR2](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) as users can define `xhr.responseType` and expect `xhr.response` to contain formatted data:

eg. `xhr.responseType = 'json'` will result in a Javascript object of parsed json response at `xhr.response`, without needing to do extra `JSON.parse`; the gain is more significant for `Blob` type binary data, where dev no longer need to [hack mime type](http://www.html5rocks.com/en/tutorials/file/xhr2/) then read data as plain/text.

XHR2 support is [fairly wide nowadays](http://caniuse.com/#feat=xhr2), it would seem like a good time to add such support.

**Comment by mroderick** [comment]
@nicolai86 all help is greatly appreciated :+1:

**Comment by bitinn** [comment]
I think people mostly use Fetch instead of XHR2 (much easier to mock, I hope), closing it for good.
