### ISSUE TITLE
Arrays in arguments are logged as references

### ISSUE THREAD

**Issue by dskaram** [sinonjs/sinon#571]
When the arguments to a method are an array, a copy of the array should be logged by sinon and not the array itself as that could be modified by later code, leading to wrong assertions.

Attaching a failing test case.   

```
  it("should not hold array references in args", function () {
        var testObject= { test: sinon.spy() },
            refs= [];


        testObject.test(refs);
        refs.push("anything");
        testObject.test(refs);

        expect(testObject.test.getCalls()[0].args).to.deep.equal([]);
        expect(testObject.test.getCalls()[1].args).to.deep.equal(["anything"]);
  });
```

**Comment by nicholaswmin** [comment]
Is there still no solution to this?

**Comment by zmknox** [comment]
Should this behavior be documented in some way? As is, this can lead to some initially confusing results, and it may take someone a while to figure out why their assertions may be failing when, at time of the spy call, they would have been correct. Adding a note to the spy docs could help folks get a better understanding of why the actual behavior happens.

(I realize I'm replying to a 9 year old issue, but this issue just popped up for me and I hope to make things clearer for others in the future)

**Comment by fatso83** [comment]
@zmknox Absolutely, but where 😄 If you can find what you think is the appropriate place for these docs on sinonjs.org, feel free to push a PR. [Very easy to get started](https://github.com/sinonjs/sinon/blob/main/docs/CONTRIBUTING.md)!
