### ISSUE TITLE
console.table Spy is not restored with sandbox.restore()

### ISSUE THREAD

**Issue by oncletom** [sinonjs/sinon#577]
Hello,

I use a spy to check what has been passed to console.table:

``` js
describe('test suite', function(){
  var sandbox, consoleTableSpy;

  beforeEach(function(){
    sandbox = sinon.sandbox.create();

    consoleTableSpy = sandbox.spy(console, 'table');
  });

  afterEach(function(){
    sandbox.restore();
  });

  it('dummy', function(){});
  it('dummy (but sinon should throw an exception)', function(){});
});
```

I use `karma-sinon-chai` and get this exception:

```
PhantomJS 1.9.7 (Mac OS X) NativeApp "before each" hook FAILED
    TypeError: Attempted to wrap table which is already spied on
```

**Comment by mroderick** [comment]
@oncletom thank you for reporting this! :+1: 

This is an interesting one. Can you still reproduce this with the latest Sinon.JS release (1.12.2)? Can you reproduce it in other browsers than PhantomJS 1.9.7?

**Comment by oncletom** [comment]
Hello @mroderick, I will give another go and see if I still encounter the issue. I cannot even remember which project it was related to :-D
