### ISSUE TITLE
Fake timers should trigger on restore

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#578]
I was experiencing the weirdest error ([reproducable test case](https://github.com/fatso83/bug_demos/tree/master/sinon.ie9.promise.bug)) yesterday, where wrapping one test in `sinon.test` and exchanging `sinon.stub` for `this.stub` would cause all subsequent tests using Promises to fail in IE9.

I finally tracked it down to having to do with the es6 promise implementation using `setTimeout` to shim the Promise implementation in older browsers missing a native Promise implementation. The point of a sandbox is that changes in the sandbox should not propagate outside of the sandbox, and therefore I was curious to what might cause this.

Turns out that the [ES6 Promises shim](https://github.com/fatso83/bug_demos/blob/master/sinon.ie9.promise.bug/es6-promises.js) uses a queue of functions of `setTimeout(fn, 1)` to simulate async execution, and that any Promises created in the `sinon.test` function will cause subsequent Promise creations to hang, unless the timers are triggered somehow.

Real timers trigger at some point, so would it not be right if Sinon also triggered its timers when restoring the global state created by the sandbox to its previous state?
## 

Of course one can hack around this when one is aware of what is going on (either ticking the clock a few millis, or simply setting `sinon.config = {     useFakeTimers : false }`, but that assumes everyone knows the setTimeout abstraction is leaking.

I could try and look into how to do this and propose a PR, but I won't bother starting until I know the idea is sound :-)

**Comment by mroderick** [comment]
@fatso83 thank you for reporting this :+1: 

This issue looks a lot like https://github.com/cjohansen/Sinon.JS/issues/246, where the library authors haven't cached `setTimeout`.

I imagine that adding `var setTimeout = setTimeout` somewhere in the beginning of that file would make the issue go away.

Does that solve the issue for you?

**Comment by fatso83** [comment]
That should fix this specific issue, but that wasn't why I raised the issue. I think the callbacks that are still queued at restore time should then be triggered by default, as that would avoid having to make changes to third-party libraries that expect them to fire at some point.  

Since you already have access to the queue of callbacks this would not be a big change in terms of LOC, but I am unsure if this could somehow break existing behaviour.
