### ISSUE TITLE
spyCall arguments are stored by reference and can be overwritten between calls

### ISSUE THREAD

**Issue by vitalets** [sinonjs/sinon#583]
It seems spyCall stores arguments by reference so it can lead to unexpected behavior:

``` js
var sinon = require('sinon');
var spy = sinon.spy();
var obj = {a: 1};
spy(obj);
// change property of object spy called with
obj.a = 2;
spy(obj);

console.log('first call:', spy.firstCall.args);
console.log('second call:', spy.secondCall.args);

// output:
// first call: [ { a: 2 } ] - expecting here {a: 1} !!
// second call: [ { a: 2 } ]
```

I think spyCall should make deep copy of arguments to save their values.
Is it expected behavior or any plans to change it?

thanks!

**Comment by castarco** [comment]
@vitalets **6 years later**, they didn't bother on documenting this issue, I was almost about to open a bug report, but it seems they don't care at all, not even to provide a different mechanism to support that specific use case.

**Comment by mroderick** [comment]
@castarco please refrain from trolling, and go read https://github.com/sinonjs/sinon/issues/571#issuecomment-58650589
