### ISSUE TITLE
When running with grunt jasmine plugin Error: mismatch: Mismatched anonymous define() module: function loadDependencies(require, exports, module)

### ISSUE THREAD

**Issue by gunalmel** [sinonjs/sinon#591]
When running my tests with sinon and grunt jasmine plugin (sinon is added to test page directly using a script tag, not with require), if I use versions [1.11.1](http://sinonjs.org/releases/sinon-server-1.11.1.js) & [1.11.0](http://sinonjs.org/releases/sinon-1.11.0.js) my tests throw the error below, however when using [1.10.3](http://sinonjs.org/releases/sinon-1.10.3.js), everything works just fine. I worked around the issue by setting all declarations of isAMD variable to false.

> > Error: mismatch: Mismatched anonymous define() module: function loadDependencies(require, exports, module) {
> >         sinon = module.exports = require("./sinon/util/core");
> >         require("./sinon/extend");
> >         require("./sinon/typeOf");
> >         require("./sinon/times_in_words");
> >         require("./sinon/spy");
> >         require("./sinon/call");
> >         require("./sinon/behavior");
> >         require("./sinon/stub");
> >         require("./sinon/mock");
> >         require("./sinon/collection");
> >         require("./sinon/assert");
> >         require("./sinon/sandbox");
> >         require("./sinon/test");
> >         require("./sinon/test_case");
> >         require("./sinon/match");
> >         require("./sinon/format");
> >         require("./sinon/log_error");
> >     }
> > http://requirejs.org/docs/errors.html#mismatch at
> > _SpecRunner.html:21

**Comment by mroderick** [comment]
> Hi, on the same topic, it seems like Sinon.JS' define call being anonymous will trigger the error (mismatched…) when using an inlined script, such as one generated by rjs. Simply adding a name, define('sinon', [], … solves the issue, but I am not sure whether it would have any unpleasant side-effect.

I'll take a closer look at this as a solution, thank you for posting!
