### ISSUE TITLE
Nested setImmediate will freeze the browser on next tick call

### ISSUE THREAD

**Issue by soutaro** [sinonjs/sinon#593]
If `setImmediate` is used in a function invoked via `setImmediate`, the `tick` call does not return.

The following is an example and a patch for this issue.
- Branch https://github.com/soutaro/Sinon.JS/tree/nested-setImmediate
- Example https://github.com/soutaro/Sinon.JS/commit/9b22add07f769903fcc72fed75bdca724eb7d1d5
- Fix https://github.com/soutaro/Sinon.JS/commit/1731851a00300d64a60e56308c31c124c74c85c1

The fact that time does not pass at all during timer execution causes this issue. My patch is trying to fix this by incrementing `now` on timer execution.

I am not sure if this fix is ok. It breaks some test cases of the library which depends on exact current time, and there may be such tests written by users.

**Comment by soutaro** [comment]
I forgot to close the issue.

**Comment by mroderick** [comment]
Thank you 👍
