### ISSUE TITLE
Sinon + PhantomJS "elementconstructor" issue?

### ISSUE THREAD

**Issue by lakenen** [sinonjs/sinon#594]
I'm trying to test whether an HTML Element was passed to a function, so I did this:

``` js
this.mock(thing)
    .expects('someFn')
    .withArgs(sinon.match.instanceOf(Element));
```

It works fine in the browser, but when run in PhantomJS (via [grunt-contrib-qunit](https://github.com/gruntjs/grunt-contrib-qunit)), I am getting this error:

`TypeError: Expected type of type to be function, but was elementconstructor`.

Not sure if this is actually a bug in PhantomJS or not, but I figured Sinon issues would be a good place to start...

**Comment by philipwalton** [comment]
I'm seeing this same issue for `sinon.match.instanceOf(Event)`. It's happening in both PhantomJS and Safari.

Seems like the `sinon.typeOf` check could be refactored to wrap the `instanceof` check in a try/catch and report that it wasn't a function in the catch block.
