### ISSUE TITLE
"undefined:undefined: when attempting to stub a method declared on a function prototype

### ISSUE THREAD

**Issue by lsiden** [sinonjs/sinon#599]
The following code

```
var MyClass = (function() {
  function MyClass() {}

  MyClass.prototype.$save = function() {
    return {};
  };
  return MyClass;
})();

  # This will send the message 'undefined: undefined' to the console.
    sinon.stub(MyClass.prototype, '$save').yields([]);
```

generates the console message

   PhantomJS 1.9.8 (Linux) Controller: ... FAILED

Is this a known problem?

**Comment by mroderick** [comment]
@lsiden thank you for reporting this :tropical_drink: 

This is not a known issue to me. Did you find a resolution to it? Which version of Sinon.JS did you use to produce the error with?

**Comment by lsiden** [comment]
Sorry, this is too old.  If you can't recreate it, go ahead and close.

**Comment by lsiden** [comment]
Haven't encountered this again.

**Comment by mroderick** [comment]
Thank you 👍
