### ISSUE TITLE
Exempt native functions from the typeof check

### ISSUE THREAD

**Issue by cjohansen** [sinonjs/sinon#604]
Suggested by @fabiosantoscode in https://github.com/cjohansen/Sinon.JS/issues/386#issuecomment-63384848:

Don't enforce `typeof` to be `"function"` if the function "looks like" a native function.

**Comment by mroderick** [comment]
This looks stalled to me. Is anyone working on this?

**Comment by fabiosantoscode** [comment]
I don't really maintain that codebase anymore and nobody supports those IE
versions anyway
