### ISSUE TITLE
Typo in code examples on http://sinonjs.org/qunit page

### ISSUE THREAD

**Issue by GitMje** [sinonjs/sinon#605]
I believe that there may be a typo in the code examples on the http://sinonjs.org/qunit page.  It calls "equals" (e.g., "equals(jQuery.ajax.getCall(0).args[0].url, "/some/resource");"). I believe this is intended to be QUnit's assert.equal (I fall into this typo all the time with QUnit because I'm used to JUnit's assertEquals).  

Please see http://api.qunitjs.com/category/assert/.  Let me know if there's a way that I can help with updating this.

I appreciate the work that you're doing on this project. Sinon.JS is really sweet.

Best regards,

Michael

**Comment by mroderick** [comment]
That page page does not exist on the new documentation site.

I've tried searching the codebase for "equal(j", for which there are no hits. I am closing this.
