### ISSUE TITLE
XHR: Content-Type clobbered

### ISSUE THREAD

**Issue by terinjokes** [sinonjs/sinon#607]
FakeXMLHttpRequest's [`send` method](https://github.com/cjohansen/Sinon.JS/blob/239d013e61383ae9c6c393bec38b776f5baee939/lib/sinon/util/fake_xml_http_request.js#L414-L438) currently clobbers the "Content-Type" header if set, by removing anything after the first ";" and forcibly appending ";charset=utf-8".

A real XHR object allows sending binary data via `TypedArray`s, `ArrayBuffer`s, and `Blob`s. They also correctly form encode when sent with `FormData` values. As "Content-Type" might have application-specific behavior, blindingly clobbering them makes it difficult for developers to properly test the functionality.

**Comment by mroderick** [comment]
@terinjokes Thank you for reporting this.

> FakeXMLHttpRequest's send method currently clobbers the "Content-Type" header if set, by removing anything after the first ";" and forcibly appending ";charset=utf-8".

Does this behaviour differ from what out-in-the-wild implementations of XMLHttpRequest? Do they all behave the same way?

> A real XHR object allows sending binary data via TypedArrays, ArrayBuffers, and Blobs. They also correctly form encode when sent with FormData values. As "Content-Type" might have application-specific behavior, blindingly clobbering them makes it difficult for developers to properly test the functionality.

By real, do you mean IE10 and onwards? ;) [IE9 and below doesn't have the `FormData` global](http://caniuse.com/#search=formdata)

Do you have a proposal on how to improve FakeXMLHttpRequest to match developers' expectations, without getting to close to one specific real-world implementation?

**Comment by terinjokes** [comment]
> Does this behaviour differ from what out-in-the-wild implementations of XMLHttpRequest? Do they all behave the same way?

Just now I've tested the behavior of the following browsers, which were at my easy disposal: IE9, IE10, Chrome 39, Firefox 34, and Safari 8. I created a new XHR object, and set the "Content-Type" header:

```javascript
var xhr = new XMLHttpRequest();
xhr.open('GET', 'http://httpbin.org/headers', true);
xhr.setRequestHeader('Content-Type', 'application/json');
xhr.onreadystatechange = function() {
  if (this.readyState==4 || this.readyState=="complete") {
    console.log(this.responseText);
  }
}
xhr.send()
```

In every case, the response body shows that the browser sent the request with "Content-Type" set to "application/json".

> IE9 and below doesn't have the FormData global

That's fine. IE8 doesn't support `Date.now`, but that doesn't stop FakeTimers from detecting if it exists and faking it if it does.

**Comment by moll** [comment]
Just experienced this, too, when using Sinon and its XHR mock on Node. It also lacks the `FormData` global.

**Comment by dstillman** [comment]
Not sure why this was marked as a feature request. This is clearly a bug, as @terinjokes's example shows. This requires ";charset=utf-8" to be appended to all tests that check the sent Content-Type header. (Even "text/plain" shouldn't have a charset appended if it wasn't set explicitly in the XHR.)

**Comment by moll** [comment]
This is still the case as of Sinon v1.17.2.

**Comment by moll** [comment]
I suspect that is still the case 2 years later unless someone can confirm it's definitely not.

**Comment by mroderick** [comment]
Let's investigate this further

**Comment by mnahkies** [comment]
@mroderick should this move to the nise tracker?

**Comment by fatso83** [comment]
@mnahkies, preferably, yes. If you would do the honours it saves us the trouble :-) Please refer to this bug to keep a history.

**Comment by mroderick** [comment]
@mnahkies that would be great, thank you!

I've used this with success in the past: https://github.com/buildo/gh-issue-mover

**Comment by mnahkies** [comment]
Issue migrated to sinonjs/nise#33

**Comment by fatso83** [comment]
Closed in favor of the `nise` bug tracker. AFAIK that's our general workflow, but feel free to reopen, @mroderick
