### ISSUE TITLE
Sinon mock exploding in node 0.11

### ISSUE THREAD

**Issue by dcousens** [sinonjs/sinon#613]
The error ([ref](https://travis-ci.org/bitcoinjs/bitcoinjs-lib/jobs/42356908#L1478))
``` javascript
TypeError: Cannot assign to read only property 'length' of function Object() { [native code] }
at Object.expects (/home/travis/build/bitcoinjs/bitcoinjs-lib/node_modules/sinon/lib/sinon/mock.js:76:22)
```

The impl. code ([ref](https://github.com/bitcoinjs/bitcoinjs-lib/blob/2.0.0/test/ecpair.js#L145-L146))
``` javascript
      it('passes the options param', sinon.test(function() {
        var options = { compressed: true }

        this.mock(ECPair).expects('constructor')
          .once().calledWith(options)

        ECPair.makeRandom(options)
      }))
```

Relevant lines of sinon.js code: https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/mock.js#L76

Not sure why this is blowing up, but I suspect its probably something related to `[].push` being used the way it is.  Perhaps `Array.prototype.push` would avoid this?

**Comment by dcousens** [comment]
Any solutions to this?

**Comment by dcousens** [comment]
Replacing `[].push` with `Array.prototype.push` fixes this. @mroderick thoughts?

**Comment by dcousens** [comment]
Still unsure of the root cause for this, as promised in #698, I'll eventually get around to an isolated test case for you @mroderick.

**Comment by dcousens** [comment]
@mroderick can you assign this to me? Keep losing track of it

**Comment by mroderick** [comment]
> @mroderick can you assign this to me? Keep losing track of it

Apparently, only collaborators can be assigned issues

**Comment by dcousens** [comment]
Well, that sucks.

**Comment by dcousens** [comment]
Still occurs.

**Comment by dcousens** [comment]
Assuming this is a wont-fix,  shall I close?

**Comment by mroderick** [comment]
> Assuming this is a wont-fix, shall I close?

I'd love to fix it, if we can get a boiled down test case to reproduce it

**Comment by dcousens** [comment]
I'm probably never going to have time to fix this,  @mroderick up to you to keep open

**Comment by fatso83** [comment]
I'll run this through a [custom git bisect script](https://github.com/fatso83/git-bisect-scripts/blob/master/sinon-passes-custom-test) to try and find the regression. Has worked in the past.

**Comment by dcousens** [comment]
I don't know if this even happens any more.

**Comment by fatso83** [comment]
[sinon-test is nowadays a separate project](https://github.com/sinonjs/sinon-test), so the test cannot be run on normal sinon anymore. Closing until I can get a reproducible test case.
