### ISSUE TITLE
Document all sandbox APIs

### ISSUE THREAD

**Issue by ash2k** [sinonjs/sinon#614]
Please mention sandbox API methods like `verify()`, `verifyAndRestore()`, etc in the docs. I wanted to request that functionality but decided to take a look at the sources. And there it was! Please, document the API so users can find it.

**Comment by hellboy81** [comment]
Is there some tests for it?

**Comment by mroderick** [comment]
If someone feels like contributing some documentation, that would be great.

It's all right here in this repository: https://github.com/sinonjs/sinon/tree/master/docs
