### ISSUE TITLE
sandbox.failOnUnverified

### ISSUE THREAD

**Issue by ash2k** [sinonjs/sinon#619]
Please consider adding a method to sandbox to fail if it contains unverified mocks. Can be useful to catch mocks, that were not verified in test(s).

Or it can be an option to `restore()` method, or even it's default behaviour.

**Comment by mroderick** [comment]
I am having a hard time imagining how we would create meaningful error messages for this one.
Since this hasn't seen any activity in more than two years, I am closing it.
