### ISSUE TITLE
How can I mock a class in JavaScript

### ISSUE THREAD

**Issue by tobias-neubert** [sinonjs/sinon#629]
Hi,

Yes, I know that JavaScript knows nothing about classes. But coming from the Java world I wonder how I can mock away an AMQP server for example, without the need to provide a fake object that implements the same "Interface" as the original object? Here is an example where I try to mock rabbit.js.
The interesting question is, how do I get a mock for **contextMock** near the end of the example without 1) call the original `createContext`method or 2) provide a dummy object that implements the original interface? I mean, the whole purpose of mocking libraries (in Java) is to not have to implement the to be mocked classes yourself.
So, please, can anybody tell me how to achieve that? Or can anybody assure me that this simply is not possible with JavaScript? At least I could then stop thinking about this and concentrate on the important things again :-)

I am really, really thankful for any help,
Tobias

``` javascript
var rewire = require('rewire');
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
chai.should();

var sinon = require('sinon');
var rabbitjs = require('rabbit.js');

var testling;
describe('Foo', function() {
  it('should eventually get ready', function (done) {
    testling.ready().should.eventually.become(true).and.notify(done);
  });
}

beforeEach(function () {
  sandbox = sinon.sandbox.create();
  rabbitjsMock = sandbox.mock(rabbitjs);
  rabbitjsMock.expects('createContext').once().returns(contextMock);
  Foo.__set__('rabbitjs', rabbitjs);
  testling = new Foo('localhost', '5672');
});
afterEach(function() {
  sandbox.restore();
});
```

**Comment by jcollum** [comment]
Could you put up your final code if you have it?
