### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by GCheung55** [sinonjs/sinon#630]
The devDependencies are out of date and prevent Sinon.JS tests from running in IE6 and IE8. I'm only guessing, but I think it won't work in IE7 too.

**Reproduce:**
- clone repo
- run `npm install`
- run `./node_modules/.bin/http-server` to spin up the server
- Go to localhost:8080/test/sinon.html

The issue seems to be because `buster-test/lib/buster-test/test-context.js` has `var when = require("when");` which effectively replaces the `when` object with undefined.

**Comment by mantoni** [comment]
Browsers are tested on SauceLabs with each build now.
