### ISSUE TITLE
Sinon.JS errors when inlined with rjs

### ISSUE THREAD

**Issue by chikamichi** [sinonjs/sinon#631]
Hi,

I'm experiencing a few problems with Sinon.JS when using requirejs' optimizer to generate a build where sinon is inlined with all the other scripts in my codebase. Everything's fine when running the codebase as separated files.
At first, I got a [mismatch](http://requirejs.org/docs/errors.html#mismatch) error, which I fixed locally by adding an explicit name to [the `define` call](https://github.com/cjohansen/Sinon.JS/blob/766106fc782b8621182211cc52e498a8791f1ab5/build#L51) for sinon : `define('sinon', [], …`.

But then, I got this strange error: `Uncaught TypeError: undefined is not a function`, at [this spot](https://github.com/cjohansen/Sinon.JS/blob/3c6afcc6844f88978383bdb4d2accde64a10b78b/lib/sinon/format.js#L21). For some reason, `configure` is not available on the `formatio`… because `formatio` is not what it should be :)

My requirejs setup is as follow (using [asciidisco/grunt-requirejs](https://github.com/asciidisco/grunt-requirejs)):

``` coffeescript
# Inside my Gruntfile…
    requirejs:
      compile:
        options:
          modules: [
            name: 'main'
            insertRequire: ['main']
          ]
          appDir: 'app'
          baseUrl: './js'
          dir: 'build'
          removeCombined: true
          #optimize: 'uglify2'
          optimize: 'none'
          uglify2:
            compress:
              sequences: false
            mangle: false
          optimizeCss: 'none'
          paths:
            sinon: "lib/sinon"
            jquery: "lib/jquery"
            # …many libs, then project's files
```

By inspecting the callstack, I realized that once I pass a name in `define()`, this "sinon" module is taken into account in the loop and thus, [this spot hits twice](https://github.com/cjohansen/Sinon.JS/blob/766106fc782b8621182211cc52e498a8791f1ab5/build#L69) ("formatio" then "sinon").

Sinon.JS' AMD setup is a bit involved, I did not find a workaround to the primary issue (mismatch error) that wouldn't have that kind of side effect. Any help appreciated! :thought_balloon: 

---

_Btw, why including Sinon.JS in a build? That's for a project where FakeServer is used to mock some external APIs. Maybe it's possible to only include that part?_

**Comment by chikamichi** [comment]
@mroderick you may close this issue I guess :)

**Comment by mroderick** [comment]
Thank you
