### ISSUE TITLE
IE8 sinon.spy.call.printf thisValues test is failing

### ISSUE THREAD

**Issue by GCheung55** [sinonjs/sinon#635]
`sinon.spy.call.printf thisValues` fails in IE8 because the actual is a windows object.

The expected value is "undefined".

I've narrowed it down to https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/spy.js#L74 where the `this` is the `window` object in IE8.

**Comment by mroderick** [comment]
@GCheung55 thank you for reporting this :ice_cream: : 

Would you mind providing a bit more detail on how to produce the error? 
It could be:
*  a pull request with a failing test
* [a git repo with an example](https://github.com/mroderick/sinon-555)
* a gist
* jsfiddle
* even some code pasted into a comment on this ticket

Having a runable example that shows the code failing goes a long way towards understanding it, and towards fixing it.

**Comment by GCheung55** [comment]
https://github.com/cjohansen/Sinon.JS/blob/master/test/sinon/call_test.js#L1260 is the test that's failing. It's on master so it's definitely runable. It's just a matter of getting an environment running IE8 to run the tests.

**Comment by mroderick** [comment]
Hmm. I think I'll have to revive my plans to use vanilla Buster.JS, so we can run the tests in everything.

**Comment by mroderick** [comment]
https://github.com/cjohansen/Sinon.JS/pull/684 got merged to master this weekend

Now Sinon.JS uses vanilla Buster.JS, you should be able to run tests in IE :)

**Comment by mroderick** [comment]
All the tests pass in the browsers we're currently supporting, IE8 was dropped awhile ago. I am closing this.

If anyone can produce a reproducible, runnable test case that we can run in IE8, then please re-open this issue.
