### ISSUE TITLE
asynchronous server responses 404.

### ISSUE THREAD

**Issue by AWinterman** [sinonjs/sinon#637]
sinon: 1.12.1: environments: jsdom@0.0.7 or chrome Version 39.0.2171.95 (64-bit): https://gist.github.com/AWinterman/23cb8f24f62e83d195fb

It isn't possible to make the sinon fake server respond on a future turn of the event loop. Requests to a URL for which the server will respond asynchronously 404, whether autorespond is on or off. See the https://gist.github.com/AWinterman/23cb8f24f62e83d195fb for full details. I can copy information here if you'd like.

**Comment by mroderick** [comment]
It would be helpful if the examples were in the ticket, unless ofc. you'd provided at git repository that one could clone and run the code :)

> Note that this feature is intended to help during mockup development, and is not suitable for use in tests. --http://sinonjs.org/docs/#auto-respond

I am not entirely sure I understand why your example doesn't work (it's late here). However, perhaps you could share what you're trying to accomplish, there might be other ways of getting there.

**Comment by AWinterman** [comment]
@mroderick you can `git clone https://gist.github.com/23cb8f24f62e83d195fb.git` and then follow the instructions in the README. I can copy more details here if you'd like.

Basically I don't think the fakeServer should HAVE to be synchronous. I think you should be able to schedule the response for a future turn of the event loop.

autorespond isn't the issue, the issue is that you can't setTimeout(function() { req.respond() }) inside the server mock endpoint.

**Comment by mroderick** [comment]
> @mroderick you can git clone https://gist.github.com/23cb8f24f62e83d195fb.git and then follow the instructions in the README. I can copy more details here if you'd like.

I was not aware of that, thanks!

**Comment by freethejazz** [comment]
I think this is partly a bug in the documentation and partly a feature request/enhancement. @mroderick The docs you link to say that the `request` object can be configured with a `autoRespond` and an `autoRespondAfter` property, but I can't find a reference to that anywhere in the code base (source or tests). The only references to those two properties are on the fake server object. I think that's a bug.

@AWinterman You mentioned that:
> It isn't possible to make the sinon fake server respond on a future turn of the event loop.

That's not true, actually. `server.autoRespond=true` triggers a response 10ms later by default and can be configured with the `server.autoRespondAfter` property. Additionally, if you'd rather not use `server.autoRespond`, you can wrap the `server.respond` in a `setTimeout` yourself. The problem you're experiencing is that when you call `server.respond`, all of the current requests get processed. I think the real feature you're trying to describe is that you want to be able to configure response times on an end-point by end-point, or maybe even a request by request, basis. That is what I'd qualify as a feature request/enhancement (assuming the issue with the docs is a bug).

I think that would be a pretty cool feature that would make mockup development much more dynamic and realistic. It would allow the developer to simulate the variability of network activity, which would allow them to show off things like loading displays for some requests without having to slow down all requests. Is that something that fits with your vision of the project, @cjohansen?

**Comment by rplantiko** [comment]
The problem is not about the `server.respond` function but about `server.processRequest` (one level downwards). This function `server.processRequest` calls the configured handler for the request and, _immediately after that call_, it expects the corresponding response arrary to be filled. 

If the (mocked) request processing is asynchronous, that response array is not yet filled, and therefore the server responds with the fallback: 404 = Not found: 

```
        processRequest: function processRequest(request) {
            try {
                if (request.aborted) {
                    return;
                }

                var response = this.response || [404, {}, ""];

                if (this.responses) {
                    for (var i = 0, l = this.responses.length; i < l; i++) {
                        if (match.call(this, this.responses[i], request)) {  // match() already executes the response function (if the request fits)!
                            response = this.responses[i].response;
                            break;
                        }
                    }
                }

                if (request.readyState != 4) {
                    request.respond(response[0], response[1], response[2]);  // response HAS to be present here
                }
            } catch (e) {
                sinon.logError("Fake server request processing", e);
            }
        },
```
My solution was very easy and doesn't need to redefine anything in sinon.js: In my mock handler, I simply set the request readyState to 4. This way, the `request.respond()` call will be surpressed 

```
			response: function(xhr, urlParams) {
				var payload = JSON.parse(xhr.requestBody)
				var respond = function(statusCode) { return xhr.respond.bind(xhr,statusCode,{}); };
				controller.handle_request(payload).then(respond(200),respond(404));
				xhr.readyState = 4; // Surpress sinon's synchronous processing (which would result in HTTP 404)
				return true; // Indicate the match to sinon's match() function
			}
```
