### ISSUE TITLE
AMD support does not work as expected for `pkg/sinon.js`

### ISSUE THREAD

**Issue by MiguelCastillo** [sinonjs/sinon#639]
When loading `pkg/sinon.js` via requirejs, AMD detection does not work correctly [here](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon.js#L14).

The problem happens when loading `pkg/sinon.js` due to a `var define;` right before the IEFF for sinon runs.  The `var define;` causes `define` to be undefined when detecting AMD.

Take a look here [sinon](http://sinonjs.org/releases/sinon-1.12.2.js) and search exactly for `var define;` to see where the problem occurs.  I got things working by simply removing `var define;`, but I am not sure how that's getting inserted during the build process, so I will defer to someone with more knowledge here.

I am happy to test any proposed changes.

**Comment by MaikuMori** [comment]
Run into this issue when using `sinon@1.12.2` inside karma test runner:
```
PhantomJS 1.9.8 (Linux) ERROR
  Error: Mismatched anonymous define() module: function () {
        return (root.sinon = factory());
      }
  http://requirejs.org/docs/errors.html#mismatch
  at /home/maiku/Projects/xxx/node_modules/requirejs/require.js:141
PhantomJS 1.9.8 (Linux): Executed 0 of 0 ERROR (0.088 secs / 0 secs)
```

Last version that works for me is `1.10.3`.

Version `1.11.1` has a different error:

```

INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket ATQ3s07m5Yok_HQoJog7 with id 72830728
PhantomJS 1.9.8 (Linux) ERROR
  Error: Mismatched anonymous define() module: function loadDependencies(require, exports, module) {
          sinon = module.exports = require("./sinon/util/core");
          require("./sinon/extend");
          require("./sinon/typeOf");
          require("./sinon/times_in_words");
          require("./sinon/spy");
          require("./sinon/call");
          require("./sinon/behavior");
          require("./sinon/stub");
          require("./sinon/mock");
          require("./sinon/collection");
          require("./sinon/assert");
          require("./sinon/sandbox");
          require("./sinon/test");
          require("./sinon/test_case");
          require("./sinon/match");
          require("./sinon/format");
          require("./sinon/log_error");
      }
  http://requirejs.org/docs/errors.html#mismatch
  at /home/maiku/Projects/xxx/node_modules/requirejs/require.js:141
PhantomJS 1.9.8 (Linux): Executed 0 of 0 ERROR (0.077 secs / 0 secs)
```

**Comment by mroderick** [comment]
@MaikuMori how do you conclude that this is related to the original bug report?

**Comment by mroderick** [comment]
@MiguelCastillo thank you for reporting this :fireworks: 

Would you mind providing a bit more detail on how to produce the error? 
It could be:
*  a pull request with a failing test
* [a git repo with an example](https://github.com/mroderick/sinon-555)
* a gist
* jsfiddle
* even some code pasted into a comment on this ticket

Having a runable example that shows the code failing goes a long way towards understanding it, and towards fixing it.

**Comment by MaikuMori** [comment]
@mroderick You're right, the bug I encountered seems to be more related to #591.

I can open a seperate issue if that helps.

**Comment by MiguelCastillo** [comment]
@mroderick For sure, let me put something together for ya in the next day or two.
