### ISSUE TITLE
Fake events on XHRs - progress, load, etc.

### ISSUE THREAD

**Issue by MarkTraceur** [sinonjs/sinon#642]
I want to test how an object responds to XHR events like progress, load, abort, error, but I don't really want to test how the data is transported (i.e. I don't want to have to stub a server for every kind of event), could we have fake event methods like xhr.fireEvent( 'progress' ) et al.?

Thanks!

(for now I will stub servers, I guess - looking at other issues it doesn't seem so hard, but this would be some delicious sugar)

**Comment by mroderick** [comment]
Pull requests welcome :)
