### ISSUE TITLE
sinon.test swallows exceptions which occur in an asyc test case

### ISSUE THREAD

**Issue by xwk** [sinonjs/sinon#650]
I noticed if I'm wrapping an async test spec with sinon.test and if the test spec runs to some exception, the test will hang, without either printing the stack trace nor the timeout error.

Here is an example to illustrate the problem
````
sinon = require("sinon");

describe("test", function() {
  return it("should raise exception", sinon.test(function(done) {
    throw Error("an error");
    return done();
  }));
});
````
When you run this spec with mocha, the mocha will just sit there without any progression.

According to https://github.com/cjohansen/Sinon.JS/issues/610, I added a line sinon.defaultConfig.useFakeTimers = false in the example code. With this change,the test will timeout eventually, but still does not give any indication of the original exception occurred.

**Comment by jwalton** [comment]
Here's another example:

```
sinon = require("sinon");

describe("test", function() {
  return it("should raise exception", sinon.test(function(done) {
    done(new Error("an error"));
  }));
});
```

If you remove `sinon.test`, this fails immediately.  If you leave it in, then this has to time out.

**Comment by fatso83** [comment]
Living on as sinonjs/sinon-test#3
