### ISSUE TITLE
Losing stack trace on error

### ISSUE THREAD

**Issue by jj09** [sinonjs/sinon#677]
Hi,

When I encounter an exception, Sinon is rethrowing it, but loosing stack:
![](http://snag.gy/hP1bi.jpg)
 

I found a workaround (rethrow ```exception.stack```): http://stackoverflow.com/questions/9006490/is-there-any-workaround-to-rethrow-an-exception-and-preserve-the-stacktrace-in-j

It works:
![](http://snag.gy/0w0vX.jpg)
 
Maybe we can change it in the library?

**Comment by mroderick** [comment]
@jj09 thank you for reporting this.

Could you provide a code sample to help better understand the issue?

**Comment by jj09** [comment]
@mroderick

Here is the sample: https://github.com/jj09/sinonjs-demo 
Clone, set revision to second commit and open index.html

Third commit fixes the issue.

I also created a pull request with the fix: https://github.com/cjohansen/Sinon.JS/pull/678

**Comment by fatso83** [comment]
Re-reported as sinonjs/sinon-test#18
