### ISSUE TITLE
Allow to replace previously-defined responses with server.respondWith()

### ISSUE THREAD

**Issue by huguesdk** [sinonjs/sinon#685]
When multiple different fake server responses are needed in tests, it would be useful to be able to replace a previously-defined response by simply calling server.respondWith() with the same arguments (method, URL,…) except for the response itself. This way, some individual tests could redefine individual responses, while the responses for the general case are defined globally for a group of tests. This kind of behavior works fine for stubs, for example.

Would this make sense or am I missing something?

**Comment by symmetriq** [comment]
I'm trying to do this too, and can't figure out any way to do it. Even calling `server.restore()` doesn't stop it from sending the response I originally registered for a particular URL.
