### ISSUE TITLE
restore doesn't restore properties properly

### ISSUE THREAD

**Issue by simonzack** [sinonjs/sinon#690]
`object[property] =` occurs in numerous places in the code base to restore properties, but this does not restore properties properly in modern javascript. 

`Object.getOwnPropertyDescriptor` & `Object.defineProperty` should be used instead.

**Comment by mantoni** [comment]
Can you provide an example where the current implementation fails?

**Comment by simonzack** [comment]
var obj = {};
    Object.defineProperty(obj, 'nonWritable', {value: function(){
      return 1;
    }});
    var stub = sinon.stub(obj, 'nonWritable').returns(2);
    console.log(obj.nonWritable());
    stub.restore();

1 is printed instead of 2.

**Comment by simonzack** [comment]
Sure, in the following code:

    var obj = {};
    Object.defineProperty(obj, 'nonWritable', {value: function(){
      return 1;
    }});
    var stub = sinon.stub(obj, 'nonWritable', function(){return 2;});
    console.log(obj.nonWritable());
    stub.restore();

1 is printed instead of 2.

**Comment by mantoni** [comment]
This is an example of `sinon.stub` not working with `Object.defineProperty`, but I see your point ;-)
