### ISSUE TITLE
Question: is it possible to avoid "EvalError unsafe-eval"?

### ISSUE THREAD

**Issue by beck** [sinonjs/sinon#710]
Sinon version: 1.13.0 (master)
Environment: OSX / Atom Package Manager (apm 0.142.0) / node 0.10.35

Context - working an Atom.io package, specifically [a code linter](https://github.com/AtomLinter/Linter) and the tests make liberal use of Sinon.

When using a stub it throws:
```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
at createProxy (/Users/doug/Projects/Sinon.JS/lib/sinon/spy.js:86:86)
at Function.create (/Users/doug/Projects/Sinon.JS/lib/sinon/spy.js:145:29)
at Function.create (/Users/doug/Projects/Sinon.JS/lib/sinon/stub.js:86:42)
at Object.stub (/Users/doug/Projects/Sinon.JS/lib/sinon/stub.js:43:32)
at [object Object].<anonymous> (/Users/doug/Projects/linter/spec/linter-spec.coffee:14:31)
```

Found one attempt at a solution called [loophole](https://github.com/atom/loophole) but it [has issues](https://github.com/atom/loophole/issues/1).

Looking for any advice / suggestions?

**Comment by gandm** [comment]
I am also developing specs for my package in Atom that are trying to stub the fs. I too get the original unsafe-eval message and when using the loophole package I get reset undefined! I'd like to be able to stub this!

```stubWriteFileSync = sinon.stub(fs, 'writeFileSync').return(undefined)```
gets
![image](https://cloud.githubusercontent.com/assets/2313237/7978024/af0dd968-0a88-11e5-8b60-6fa5e3ec0340.png)

whereas
```allowUnsafeEval -> stubWriteFileSync = sinon.stub(fs, 'writeFileSync').return(undefined)```
gets
![image](https://cloud.githubusercontent.com/assets/2313237/7978015/8cf8c3b0-0a88-11e5-9de7-604018cd77a7.png)
