### ISSUE TITLE
Sinon fake servers do not work with IE9

### ISSUE THREAD

**Issue by huangginny** [sinonjs/sinon#715]
Sinon version: 1.13.0
Environment: Karma-SauceLabs
Browser: IE9 under Windows7

I was loading Sinon with Karma and SauceLabs. However, one of the API calls (which should return fake objects) are always returning 404. Removing the test that contains the API call is not helping -- other API calls start to fail. On newer browsers of IE it works. It does seem like that the face servers are not working with IE 9.

**Comment by LaurentGoderre** [comment]
I am experi3encing this also both on Saucelabs and on a VM for testing IE9

**Comment by LaurentGoderre** [comment]
It seems that the problem was introduce in 0.13 and seems to be caused by the fact that FakeXMLHttpRequest or FakeXDomainRequest are not getting called.

**Comment by LaurentGoderre** [comment]
I found out that this commit is the one causing this to fail

https://github.com/cjohansen/Sinon.JS/commit/e8de34b5ec92b622ef76267a6dce12674fee6a73

**Comment by sloria** [comment]
@LaurentGoderre Interesting, as I believe that commit was supposed to *fix* IE9 support.

**Comment by LaurentGoderre** [comment]
Yeah...maybe it fixed on use case and broke the others. When I revert this fix manually though I get another error. The last version that works for me is 1.12.

I suspect that this commit may also be causing issues.

9ac683412f10aa3cf4cc85fae90165500f64cf15

**Comment by leoselig** [comment]
What's the state of this issue? There seems to be no progress and we are experiencing the same error

**Comment by fatso83** [comment]
This bug report lacks far too much information for it to be worked on. If you create a reproducible test case that will increase its chances of it being picked up. If any of you are able to create a test case that fails in `HEAD`, but not in an earlier release, it would be most welcome ...

**Comment by matz3** [comment]
@fatso83 did you have a look into #732? For me this seems to be the exact same issue. I can open a PR with a failing test case if you want to.

**Comment by fatso83** [comment]
@matz3 Having some code that shows the problem always helps, but I see you already posted an example on jsbin, so that is plenty good for me. This case is what is missing triggering code. Maybe the two issues are related, but without example code I cannot verify it.

I'll have a look at #732 now this weekend.
