### ISSUE TITLE
Stubbing window (of jsdom) failing in sinon > 1.13.0

### ISSUE THREAD

**Issue by ihodes** [sinonjs/sinon#719]
I've pinned our package.json to 1.13.0 to fix the issue, but it occurs on 1.14.1 (and other versions > 1.13.0).

node `v0.10.28`

Minimal example:

``` javascript
var sinon = require('sinon');
var jsdom = require('jsdom').jsdom;


global.document = jsdom('<html><body></body></html>');
global.window = document.parentWindow;

var sinonSandbox = sinon.sandbox.create();
sinonSandbox.stub(window, 'confirm', function() { return true; });
```

With stacktrace: 

```
~/sinonex/node_modules/sinon/lib/sinon/util/core.js:114
                    throw error;
                          ^
TypeError: Attempted to wrap undefined property confirm as function
    at Object.wrapMethod (~/sinonex/node_modules/sinon/lib/sinon/util/core.js:105:29)
    at Object.stub (~/sinonex/node_modules/sinon/lib/sinon/stub.js:60:26)
    at Object.stub (~/sinonex/node_modules/sinon/lib/sinon/collection.js:117:44)
    at Object.<anonymous> (~/sinonex/test.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at ~/sinonex/node_modules/mocha/lib/mocha.js:185:27
    at Array.forEach (native)
    at Mocha.loadFiles (~/sinonex/node_modules/mocha/lib/mocha.js:182:14)
    at Mocha.run (~/sinonex/node_modules/mocha/lib/mocha.js:394:31)
    at Object.<anonymous> (~/sinonex/node_modules/mocha/bin/_mocha:394:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

(Mocha is only involved because I ran the "test" with Mocha, for whatever reason.)

**Comment by mroderick** [comment]
I can't get `jsdom@4.0.5` to play nice at all.

I've set up a little repository to quickly reproduce this issue: https://github.com/mroderick/sinon-719

When I run a minimal file with only `var jsdom = require('jsdom');` I get an error:

```
$ node issue.js

/Users/mroderick/code/sinon-719/node_modules/jsdom/lib/jsdom/level2/html.js:405
var nonInheritedTags = new Set([
                           ^
ReferenceError: Set is not defined
    at Object.<anonymous> (/Users/mroderick/code/sinon-719/node_modules/jsdom/lib/jsdom/level2/html.js:405:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mroderick/code/sinon-719/node_modules/jsdom/lib/jsdom/living/index.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Which version of `jsdom` are you using to reproduce this error?

**Comment by ihodes** [comment]
Hmm, it appears as though the newer version (v4+) of jsdom requires [io.js](https://iojs.org/en/index.html) to work. We're actually on jsdom 1.5.0. We may just try to move away from jsdom entirely.

**Comment by mroderick** [comment]
I've updated my test repository to use iojs, it doesn't fare well.

If you think this issue is still relevant, could you do a pull request into my test repository with a failing example? If not, can we close this ticket?

**Comment by ihodes** [comment]
If you use jsdom 1.5.0, you should be able to repo the problem. I've submitted a PR, [here](https://github.com/mroderick/sinon-719/pull/1).

**Comment by mroderick** [comment]
If I've done my `git bisect` correctly, then this is caused by https://github.com/cjohansen/Sinon.JS/pull/692, which introduced the use of [Object.getOwnPropertyDescriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor).

This would also have caused things to stop working in old IE.

**Comment by ihodes** [comment]
Super, thank you for looking into it, glad you could get it reproduced!

**Comment by mroderick** [comment]
> Super, thank you for looking into it, glad you could get it reproduced!

Me too! Thank you for reporting it :)

Now we just need to figure out how to make it go away :)

**Comment by mroderick** [comment]
It would be nice if we could construct a failing test case that didn't involve a specific version of `jsdom`, but would be reproducible in any environment (that supports ES5).

I am too tired to wrap my head around all the prototype magic they do in `jsdom` to do that tonight, so if someone else could take a stab at that, I'd be most grateful

**Comment by skinnybrit51** [comment]
I also had the same issue with window.print().

After debugging I determined the introduction of following code in 1.14.0 was the cause.

```
sinon.getPropertyDescriptor = function getPropertyDescriptor(object, property) {
            var proto = object, descriptor;
            while (proto && !(descriptor = Object.getOwnPropertyDescriptor(proto, property))) {
                proto = Object.getPrototypeOf(proto);
            }
            return descriptor;
        }
```

This function is unable to find the print as a function on the window.  The previous approach of object[property] would.  I believe you still have this in ```core.js``` but the conditional ```hasES5Support``` is used to determine the appropriate approach to take. 

Hope this information is of some help.

**Comment by maiwald** [comment]
The same error occurs in phantom.js when trying to stub history.replaceState.

```
"foo": function() {
  var stub = sinon.stub(history, "replaceState");
  assert.isFunction(stub.restore);
},
```

This passes in 1.13.0, in 1.14.1 it does not.

**Comment by elsigh** [comment]
Same problem here (stubbing window.history) - all's fine for me in 1.13.0 but broken in 1.14.1

**Comment by dariocravero** [comment]
Hi all, until this gets solved, [this](https://github.com/UXtemple/panels-router/blob/master/__tests__/window-spy.es6) might come in handy :).

**Comment by mareksuscak** [comment]
Seems that it works for me with `jsdom 6.5.1` and `sinon 1.17.1` on `Node 4.1.1`. Please note that there are some properties that aren't stubbable in the usual way because these are defined as getters which cannot be changed without deleting before changing - for example `window.location`.
