### ISSUE TITLE
Faking Indirectly Called XHR Requests

### ISSUE THREAD

**Issue by ryneeverett** [sinonjs/sinon#724]
I didn't find it obvious how to fake XHR requests that aren't called directly by test code and I'd like to propose either documenting the pattern or adding a hook.
## A) Documenting the Pattern

Adding this example to the `onCreate` documentation would be better than nothing:

```
function spoofResponse (xhr) {
  // Allow `onCreate` to complete so `xhr` can finish instantiating.
  setTimeout(function() {
    xhr.respond(200, {"Content-Type": "application/json"}, getFakeResponse(xhr.url));
  }, 10);
}

xhr.onCreate = function (xhr) {
  spoofResponse(xhr);
};
```
## B) Adding a Hook

If we added a hook in the spirit of `xhr.onCreate`, it could be as simple as:

```
xhr.onOpen = function (xhr) {
  xhr.respond(200, {"Content-Type": "application/json"}, getFakeResponse(xhr.url));
};
```
## 

**(B)** would be my preference since it abstracts away asynchronous code and doesn't require a `setTimeout`. It also seems that I'm not the first person to want this functionality:
- https://groups.google.com/d/msg/sinonjs/Xjan2vByooU/8s2Is-DkjvsJ
- https://groups.google.com/d/msg/sinonjs/k5BaBXIdgaw/TxsyBdTRPOsJ

**Comment by ArnaudRinquin** [comment]
This would be super useful.

**Comment by crohde7707** [comment]
+1

**Comment by fatso83** [comment]
Now that the docs are easily editable, would you be able to push a small how to?
