### ISSUE TITLE
ability to reset mocks (feature req.)

### ISSUE THREAD

**Issue by amir-arad** [sinonjs/sinon#726]
add the ability to clear stubs configurations /  mock expectations the same way reset() clears spy statistics.

**Comment by sloncho** [comment]
+1

**Comment by Gudahtt** [comment]
Judging by issue #806, this feature has already been implemented for stubs, just not for mocks. Is that correct?

**Comment by amir-arad** [comment]
srsly

**Comment by mroderick** [comment]
@amir-arad would you like to work on this issue?

**Comment by amir-arad** [comment]
no, I've managed to work around this feature for a few years now.

still, there's a difference between something that doesn't get done, and something that is a "wontfix" or gets closed.

**Comment by mroderick** [comment]
https://github.com/sinonjs/sinon/pull/1658

**Comment by rosesonfire** [comment]
@amir-arad can you share your workaround for this?

**Comment by amir-arad** [comment]
as `spy.reset()` [has been deprecated in version 5](https://github.com/sinonjs/sinon/blob/next/docs/guides/migrating-to-5.0.md) this issue may be no longer relevant, or at least requires update.
