### ISSUE TITLE
sandbox.useFakeServer does not fake XMLHttpRequest in IE9

### ISSUE THREAD

**Issue by matz3** [sinonjs/sinon#732]
Sinon version: 1.14.1
Environment: Windows 7 IE9
Example URL: http://jsbin.com/gaxine

**What happens?**
The example alerts with `false` in IE9 because the XHR Request does not return the expected fake response.

When using the `sandbox` (together with sinon-qunit, but also standalone) to create a fake server by calling `sinon.sandbox.useFakeServer()` sinon fakes only `XDomainRequest` but not `XMLHttpRequest` as `sinon.xhr.supportsCORS` is set to `false` (see https://github.com/cjohansen/Sinon.JS/issues/584).

**What is expected to happen?**

The example should alert with `true` like it does in other browsers like IE10/11, Firefox, Chrome, Safari.

I would expect that XMLHttpRequest will be mocked as well as it is a valid scenario in IE9 even though it does not support CORS.

My suggested solution would be to remove the else clause [here](https://github.com/cjohansen/Sinon.JS/commit/e8de34b5ec92b622ef76267a6dce12674fee6a73#diff-2e4c83d83d3d96b1f41ec5b83a73881eR87) to always fake `XMLHttpRequest` regardless of the value of `sinon.xhr.supportsCORS`.

**Comment by matz3** [comment]
This is still not working with sinon 1.17.2.
Updated example: http://jsbin.com/nojojohaxo

**Comment by mroderick** [comment]
@matz3 thank you for updating with more information!

I like the idea of your suggestion, but I want to make sure I understand why there was a conditional to begin with. Perhaps there are reasons I don't yet know of.

I'll add a couple of labels, and perhaps I or someone else will find time to investigate this.

**Comment by NicoleRauch** [comment]
The same happens when testing with jsdom: sinon.xhr.supportsCORS is false, which basically disables the handling of xhr responses.

**Comment by zincli** [comment]
https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/fake_server.js#L87   

Why not make this an option to us the user? I use a lib for xhr, it's using XMLHttpRequest in IE9 nor XDomainRequest.

**Comment by zincli** [comment]
```
sinon.useFakeXDomainRequest = sinon.useFakeXMLHttpRequest
```

For now, I use this to fix the test case in IE9. It would be great to have a choice while create the server.

May looks like this:

```
this.server = sinon.fakeServer.create({xhr: sinon.useFakeXMLHttpRequest()})
```

Will try to make a PR lately
