### ISSUE TITLE
Capture stack trace for each spy invocation?

### ISSUE THREAD

**Issue by papandreou** [sinonjs/sinon#747]
While brainstorming possible future additions for unexpected-sinon I found out that I would like to display (parts of) the stack trace as part of the context for each invocation. From a cursory glance it seems like `sinon.spy` doesn't currently capture that information.

How would you feel about receiving a PR that captures the stack by creating a new `Error` object on each invocation and stores it on the spy instance alongside `spy.args`, `spy.exceptions`, `spy.returnValues` etc.? It seems to be the only missing piece of the context.

**Comment by mroderick** [comment]
That sounds interesting.

Could you give a (pseudo) code example of how it would look in use?

**Comment by papandreou** [comment]
I had something like this in mind when eg. asserting that a spy was never called:

```
expected spy was not called
  expected invocations[
    spy(42, { foo: 'bar' }) at someFile.js:100:33,
    spy('baz') at someOtherFile.js:134:33
  ] to be empty

  invocations[
    spy(42, { foo: 'bar' }) at someFile.js:100:33, // should be removed
    spy('baz') at someOtherFile.js:134:33 // should be removed
  ]
```

But basically whenever an invocation is mentioned, it would carry the call site along with it.

**Comment by lucasfcosta** [comment]
By seeing the merged PR I think this one can be closed. Right?

**Comment by papandreou** [comment]
Oh yes, thanks for the reminder!
