### ISSUE TITLE
Deprecations should always include information on the alternative

### ISSUE THREAD

**Issue by vertti** [sinonjs/sinon#765]
When adding deprecation warnings, the message should always include information on what should be used instead of the soon-to-be-removed-feature. Case in point: 64e316970f6b8639d65fa2ea0c5926725df4548c which is now really confusing with no additional info.

**Comment by mantoni** [comment]
Linking [the pull request that introduced the warning](https://github.com/cjohansen/Sinon.JS/pull/745) here since there is already some discussion about it.

**Comment by mroderick** [comment]
This has been silenced in v1.x branch since 9469e69895ec934e4e145d9b8a1c5a0165692036, 2015-05-27.

There is no deprecation warning in the `master` branch.

I am closing this.
