### ISSUE TITLE
Fake timers start infinite loop when setInterval is started

### ISSUE THREAD

**Issue by franza** [sinonjs/sinon#767]
It is reproduced with sinon 1.12.1 and node since v0.8.15 - v0.12. No test framework used. See example:

``` javascript
var sinon = require('sinon');

var clock = sinon.useFakeTimers();
console.log('start');
setInterval(function () {}, 0);
clock.tick(1);
console.log('finish');
```

Output:

```
start
```

Application hangs, probably in infinite loop, eating 100% of one CPU core.

Probably somehow connected with #283.

**Comment by franza** [comment]
It's reproduced with latest `lolex` version - 1.2.1.

**Comment by soramusoka** [comment]
Yeah, I have the same problem. It hapens when you start setInterval with ttl === 0

**Comment by franza** [comment]
Looks like it's quite obvious to do an infinite loop for zero interval. But I think that it should be mentioned in docs so guys like me won't fall in this issue.

**Comment by mantoni** [comment]
Maybe `setInterval` should even throw if it's called without a second argument or zero?

**Comment by franza** [comment]
It's not symmetric with setTimeout then. If you're doing `setTimeout(fn, 0)` then you'll get `fn` to be called immediately (I didn't check but I bet it is). 

But both points seems to be reasonable. Exception will just make programmer realize his mistake faster. Also, I don't think that there exist some good usages of `setInterval(fn, 0)`.

**Comment by franza** [comment]
@mantoni you know, I've just made up an example when you might need to use `setInterval(fn, 0)`:

```javascript
var clock = sinon.useFakeTimers();
console.log('start');
var interval = setInterval(function () { clearInterval(interval); }, 0);
clock.tick(1);
console.log('finish');
```
Example above works.

So if we want to test case when we want to stop interval later after several invocations with `0` then we don't need `setInterval(fn, 0)` to throw. Instead, just adding few lines in docs will be ok, I guess.
