### ISSUE TITLE
browser-sync failed together with sinon version 1.15.1

### ISSUE THREAD

**Issue by zzswang** [sinonjs/sinon#771]
It can work while I use sinon version 1.14.1

with such code:

``` javascripts
/**
 * Don't fake socket.io calls
 */
server.xhr.addFilter(function(method, url, async, username, password) {
    if ((new RegExp("browser-sync", "i")).test(url)) {
        return true;
    }
});
```

but after sinon is updated to 1.15.1, it failed

on the client, socket.io will attempt to connect the socket server forever.

**Comment by mroderick** [comment]
Could you provide a bit more context to allow someone to reproduce this issue?

Please see the [reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue) section of [CONTRIBUTING.md](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md)

**Comment by mroderick** [comment]
This has seen no updates for nearly two years, I assume that OP solved their problem
