### ISSUE TITLE
Proposal: be able to filter out fake XHR's based on their request header

### ISSUE THREAD

**Issue by brian-mann** [sinonjs/sinon#778]
Currently the callback functions stored in `filters` are looped over during the `open` method on `FakeXMLHttpRequest`.

Unfortunately at this time, the xhr's `requestHeaders` are not populated.

I want to be able to `defake` an xhr object based on it's request headers, but all I have access to is: `method`, `url`, `async`, `username`, `password`.

How feasible would it be to move the checks for `defaking` an XHR lower in the opening/sending process so that the `requestHeaders` are available at that time?

Also I noticed that the callback functions attached to `addFilter` do not have the correct context. I believe you want their context to be the `xhr` object, but instead their context is invoked with `window`.

The offending line is here:

``` javascript
var defake = some(FakeXMLHttpRequest.filters, function (filter) {
  return filter.apply(this, xhrArgs)
});
```

`this` refers to the context of the `some` method, and not the `xhr` object.

**Comment by mroderick** [comment]
Would you mind creating a separate issue for the bug report about context?

It looks like a fairly easy thing to fix, and might attract new contributors to the project :+1:
