### ISSUE TITLE
server.respondImmediately doesn't work with jQuery 1.x

### ISSUE THREAD

**Issue by Krinkle** [sinonjs/sinon#779]
See also https://github.com/jquery/jquery/issues/2453.

The basic test:
```js
QUnit.test( 'request', function (assert) {
    var i = 1;
    this.server.respondImmediately = true;
    this.server.respondWith( /mode=api/, function ( request ) {
        request.respond(
            200,
            { 'Content-Type': 'application/json' },
            '{ "value": "' + (i++) + '" }'
        );
    } );

    $.ajax('/foo&mode=api')
        .then(function (data) {
            assert.equal(data.value, '1', 'response'); 
            return $.ajax('/bar&mode=api');
        } )
        .then(function (data) {
            assert.equal(data.value, '2', 'response'); 
            return $.ajax('/quux&mode=api');
        } )
        .then(function (data) {
            assert.equal(data.value, '3', 'response'); 
        } );
} );  
```

JSFiddle (Sinon 1.15.4; jQuery 2.x): FakeServer http://jsfiddle.net/zc7drrcb/ (passing)
JSFiddle (Sinon 1.15.4; jQuery 1.11.3): FakeServer http://jsfiddle.net/en8pu6br/ (failing)

Using latest stable Chrome.

After figuring out the lack of event handling in jQuery 1.x, I added a fake timer to work around the problem. However this makes the test rather repetitive and less intuitive (putting a clock.tick after each request).

I found `sinon.fakeServerWithClock` but that doesn't seem to help in this case:

JSFiddle (Sinon 1.15.4; jQuery 1.11.3) FakeServerWithClock: http://jsfiddle.net/h66s57qw/ (failing)

**Comment by freethejazz** [comment]
Hey @Krinkle, `respondImmediately` cuts out any source of asynchrony within the sinon library but as you've discovered, other ajax libraries are designed to be asynchronous.

One possible fix for this is to use the `$.ajaxSetup` method at the top of your tests. You can specify `async: false` and it should make all of the ajax queries synchronous. In the docs it says the use of this method is not advisable, but I imagine that warning is geared more towards production code and less for tests.

**Comment by freethejazz** [comment]
@Krinkle Since this issue is intrinsic to the asynchronous nature of the jQuery library, would you be comfortable closing this issue?

**Comment by Krinkle** [comment]
Yes, thank you.
