### ISSUE TITLE
Add option to allow unmatched fakeServer requests to be handled by default Ajax

### ISSUE THREAD

**Issue by brettjonesdev** [sinonjs/sinon#802]
I am using `sinon.fakeServer` to stub out an as-yet-unfinished backend on a large project.  However, a number of endpoints are already complete, and for those which do not require a mocked response, I would like fakeServer to fall back to a normal Ajax request.  

I did not find a simple way to do this via a setting like I wished, but I was able to accomplish this with the following code:

``` javascript

//This method stolen from sinon.js - want to replicate logic to test whether an xhr will be faked or not
function matchOne(response, reqMethod, reqUrl) {
    var rmeth = response.method;
    var matchMethod = !rmeth || rmeth.toLowerCase() == reqMethod.toLowerCase();
    var url = response.url;
    var matchUrl = !url || url == reqUrl || (typeof url.test == "function" && url.test(reqUrl));

    return matchMethod && matchUrl;
}
...
server.autoRespond = true;
server.xhr.useFilters = true;
// By default, fakeServer is greedy and will fake _all_ xhrs, returning a 404.
// To change this behavior and make it only fake response which we have explicitly defined above, add a filter which checks our defined endpoints and allows requests which are not matched to be "unfaked"
server.xhr.addFilter(function(method, url) {
    //we have underscore as a dependency, can change this
    return !_.some(server.responses, function(response) {
        return matchOne(response, method, url);
    });
});
```

With this snippet I was able to achieve my goal of having my fakeServer only intercept ajax requests which matched a `server.respondWith()` call.  

It would be really quite helpful if fakeServer had an option like `fakeServer.interceptAll` which could be set to false to prevent the default 404 fake response from intercepting calls to working endpoints.  I could probably code this up without much effort but wanted to get some feedback on the idea first.  Thoughts?

**Comment by mroderick** [comment]
That seems like a good addition to fakeServer. I say go for it!
