### ISSUE TITLE
Stubs should have a `resolves` and `rejects` for setting promise results

### ISSUE THREAD

**Issue by mariusGundersen** [sinonjs/sinon#804]
This is very simple syntax sugar:

``` js
var stub = sinon.stub();
stub.resolves("hello");
//is the same as
stub.returns(Promise.resolve("hello"));

stub.rejects(new Error("oh noes!"));
//is the same as
stub.returns(Promise.reject(new Error("oh noes!"));
```

**Comment by mroderick** [comment]
That would be some nice sugar, thank you for the suggestion @mariusGundersen

**Comment by mkornblum** [comment]
Our team has a little library on npm which has been helping us with this kind of thing - https://github.com/substantial/sinon-stub-promise - although the way it's presently implemented it requires stub syntax like: `sinon.stub().returnsPromise()`. Thoughts? It looks like from the example above that this assumes synchronous evaluation, right?

**Comment by cjohansen** [comment]
I really like @mariusGundersen's suggestion. As far as I know, all promise libraries are async all the time, right? If so I think the stub promise should mirror this behavior.

**Comment by mariusGundersen** [comment]
I just figured it would use the globally available `Promise.resolve`, if one exists, and if not it wouldn't work. But letting it return an object with a `then` method is a much better solution:

```js
var stub = sinon.stub(); 
stub.resolves("hello"); 
//is the same as 
stub.returns({then: x => setTimeout(()  => x("hello"), 0)}); 
stub.rejects(new Error("oh noes!")); 
//is the same as 
stub.returns({then: x => setTimeout(()  => x(), 0), catch: x => setTimeout(() => x(new Error("oh noes!")), 0)});
```

(written on phone, might have errors)

**Comment by toddbluhm** [comment]
Our team wrote a little lib to provide similar functionality. Maybe this will help. It uses the bluebird library for promises. https://www.npmjs.com/package/sinon-bluebird

**Comment by screendriver** [comment]
+1 for native Promise support

**Comment by achingbrain** [comment]
There's also a project called [sinon-as-promised](https://github.com/bendrucker/sinon-as-promised) which [patches](https://github.com/bendrucker/sinon-as-promised/blob/master/index.js) your project's existing sinon module using [native-promise-only](https://libraries.io/npm/native-promise-only) to add resolves/rejects semantics to stubs.

It'd be ace if this or the changes from one of the other modules could be added to sinon itself.

**Comment by jnystrom** [comment]
Can I do a `sinon.stub().returnsArg(1)` where the stub returns a promise?  I am trying to just return the argument as the resolve of my promise. Does not seem to work.

**Comment by fatso83** [comment]
@jnystrom  usage questions belong on the mailing list, but this is not something sinon currently supports. Something like this should do what you want, and you don't need sinon for it.
```
stub = (arg) => Promise.resolve(arg);
```

**Comment by otroboe** [comment]
Same from here: #738

**Comment by lucasfcosta** [comment]
Hello everyone, first of all, thanks for the excellent work you guys have been doing on Sinon.
If you'd like to have this implemented I'd also love to give it a shot, just let me know and I'll start working at a PR for that.

**Comment by fatso83** [comment]
@lucasfcosta, thanks for that. I think @mroderick talked long ago about just integrating `sinon-as-promised` into Sinon, wasn't that so? That would be the easiest solution, and I have no objections.

**Comment by mroderick** [comment]
@lucasfcosta I would love to see a PR to integrate `sinon-as-promised` into Sinon's `master` branch
