### ISSUE TITLE
XHR: Not accepting 'Content-Transfer-Encoding' in request headers

### ISSUE THREAD

**Issue by ghost** [sinonjs/sinon#812]
We came across [this header blacklist](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/fake_xml_http_request.js#L52) when testing requests that set the `Content-Transfer-Encoding` header, why is it not accepted? It works in the browsers we are targeting so we want be able to set such header in XHR objects, is there a problem with it in any environment that justifies flagging it as unsafe?

**Comment by mroderick** [comment]
> why is it not accepted?

I don't know. It was implemented more than five years ago, and the commit message is not that descriptive.

Have you tried removing it and running tests in a bunch of different browsers? Perhaps you can see where it breaks

**Comment by mikehenrty** [comment]
> why is it not accepted?

I was looking into this myself today, here's what I found in the [W3 Draft](https://www.w3.org/TR/2009/WD-XMLHttpRequest-20091119/#the-setrequestheader-method):
> * Content-Transfer-Encoding
[snip]
>The above headers are not allowed to be set as they are better controlled by the user agent as it knows best what value they should have. Header names starting with Sec- are not allowed to be set to allow new headers to be minted in the future that are guaranteed not to come from XMLHttpRequest. (Older clients would however still be vulnerable as they allow such headers to be set.)
