### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'message' of error!

### ISSUE THREAD

**Issue by MichaelMcKechnie** [sinonjs/sinon#835]
I was seeing this error in my log, and found that it happened because of my bone-headed decision to throw a constant string :) like this:

var handler = function (xhr) {
                xhr.onerror();
                throw "error!";
            };

The sinon code causes a type error when the following code runs (because you can't set the message property on the constant string "error!":

        function logError(label, err) {
            var msg = label + " threw exception: ";

            sinon.log(msg + "[" + err.name + "] " + err.message);

            if (err.stack) {
                sinon.log(err.stack);
            }

            logError.setTimeout(function () {
                err.message = msg + err.message;
                throw err;
            }, 0);
        };

I've fixed my own code, but I'm happy to alter sinon as well so that it handles the exception if you like.

**Comment by mroderick** [comment]
> I've fixed my own code, but I'm happy to alter sinon as well so that it handles the exception if you like.

That would be most welcome :+1:
