### ISSUE TITLE
Remove condtional in timers-ie

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#840]
Remove the conditional in https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/timers_ie.js#L15.

It doesn't have any practical effect, since the functions are hoisted to the top of the scope anyway.

See https://github.com/cjohansen/Sinon.JS/pull/684#issuecomment-137636562

**Comment by timwienk** [comment]
It appears these conditionals do have practical effect, unfortunately (#848).

For completeness sake, this is the complete list of conditionals:
https://github.com/sinonjs/sinon/blob/v1.17.0/lib/sinon/util/timers_ie.js#L15
https://github.com/sinonjs/sinon/blob/v1.17.0/lib/sinon/util/xdr_ie.js#L10
https://github.com/sinonjs/sinon/blob/v1.17.0/lib/sinon/util/xhr_ie.js#L15
