### ISSUE TITLE
New defaults for next major release

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#841]
This ticket is for discussion and tracking of changes to defaults for the next major release.

| Property | Current Value |  New Value |
| --- | --- | --- |
| `sinon.useImmediateExceptions` | `false` | [`true`](https://github.com/cjohansen/Sinon.JS/issues/172#issuecomment-140542005) |

**Comment by fatso83** [comment]
Ref the linked issues, is this ticket really fulfilling it's intention? Looks like fluff to me :-)

**Comment by mroderick** [comment]
This was implemented in https://github.com/sinonjs/sinon/pull/891
