### ISSUE TITLE
Why += 1 rather than ++?

### ISSUE THREAD

**Issue by MetaMemoryT** [sinonjs/sinon#853]
just curious about the code here:

https://github.com/sinonjs/sinon/blob/master/lib/sinon/call.js#L43

why += 1 rather than the common ++?

**Comment by mroderick** [comment]
> why += 1 rather than the common ++?

I guess @mantoni just uses that style in his day job.

**Comment by mantoni** [comment]
@mroderick No, I actually go with `++` as well. Don't know where this is coming from.
