### ISSUE TITLE
.resetHistory

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#863]
With https://github.com/dotchev/Sinon.JS/commit/7078dd8c60273ddda97d868a57f02d73f0edf54e it is no longer possible to only reset the call history of a stub.

As discussed in https://github.com/sinonjs/sinon/issues/806#issuecomment-144327382, we could expand the api a tiny bit.

```javascript
// resets both call history and behaviour
stub.reset();

// NEW: reset call history 
stub.resetHistory();

// reset behaviour
stub.resetBehavior()
```

**Comment by fatso83** [comment]
Nice, I like it.
