### ISSUE TITLE
What's the best way to change the parameters of a mock?

### ISSUE THREAD

**Issue by pvencill** [sinonjs/sinon#871]
So, all the examples seem pretty straightforward, but I'm running into issues when I try and make more comprehensive tests; for example when I'm trying to test how my code handles various results that come from external things I'm mocking.  

For example, in one of my tests I'm mocking my mongoose User model (so that I can test how other code like my routes handle what queries return).  In order to do that, I need one test to yield one thing from User.find and another test to yield something else.  In all cases, I expect user.find to be called.

So it seems like if I define `var user = sinon.mock(User)` in a describe block in mocha, then each test can do things like `user.expects('find').yields(null, []);`  and stuff seems to work fine. 

When I tried doing the same thing in another describe block, I get the error that I'm attempting to wrap find which has already been wrapped.  I was calling user.restore() after each test to try and clean it up, but that doesn't seem to help in this case.  

So then I tried doing the whole mock sequence inside of each test (which feels wrong, but I wanted to eliminate scope issues), and the problem remains.  

I also tried setting the `sinon.mock(User).expects('find')` once at the top of the scope, but in that case I get errors that 'find' is being called too many times (i.e. once per test).

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
