### ISSUE TITLE
API design issue: withArgs conflicts between stubs and mocks

### ISSUE THREAD

**Issue by yang** [sinonjs/sinon#874]
Thanks for this library, first off!  This is a somewhat annoying wart in an otherwise nicely designed API.

Stubs use withArgs to dispatch to the correct behavior.

Mocks use withArgs as expectations.

Mocks implement stubs' interface.  They are largely non-overlapping except for this method.

I recommend naming these differently.

(Hoping that problematic scenarios are obvious but happy to spell them out here if nec.)

**Comment by mantoni** [comment]
To be honest, we're going to remove mocks from the sinon core entirely with the next major release. They might live on in a separate project. See https://github.com/sinonjs/sinon/pull/745.
