### ISSUE TITLE
How to replace stub function in a stub instance?

### ISSUE THREAD

**Issue by StevenRoan** [sinonjs/sinon#877]
If I have create a instance by  `var a = sinon.createStubInstance(MyContructor)`.

 How can I replace one of the stubbed function like `var stub = sinon.stub(object, "method", func);`.

The main reason I am doing this is want to achieve multiple callback workaround as [this mentioned](http://stackoverflow.com/questions/29818811/sinon-js-stub-can-you-call-more-than-one-callback-on-a-single-stubbed-function)

**Comment by fatso83** [comment]
This does not seem like a bug or issue with the code, but rather a usage oriented question, for which this is the wrong channel. [Try asking on the mailing lists or on IRC](http://sinonjs.org/#help).
