### ISSUE TITLE
Wrap ES5 getters and setters

### ISSUE THREAD

**Issue by rvagg** [sinonjs/sinon#88]
``` js
var o = {
  get foobar() { return 'foobar' },
  set foobar(s) { throw 'bzzt!' },
  foo: function() { return 'foo' },
  bar: 'bar'
}; // -> { foobar: [Getter/Setter], foo: [Function], bar: 'bar' }

sinon.mock(o).expects('foobar').returns('woohoo'); // doesn't because sinon.wrapMethod() does an object[property] which accesses the getter which returns a string
```

To support getters and setters you need to do a `Object.getOwnPropertyDescriptor(obj, prop)` for the object and then a recursive `Object.getPrototypeOf(obj)` if it doesn't exist, the descriptor has a `'get'` and `'set'` property where they are defined.

But, you may want to mock out just the getter or just the setter or both, so how do you specify that? Some options:

``` js
mock(o).expects('foobar'); // ambiguous, the setter? getter? or both?
mock(o).expects('get foobar'); // ambiguous, there may be a legitimate property named "get foobar"
mock(o).expectsGet('foobar'); // clear but more code in Sinon and more to document ?
mock(o).expectsSet('foobar'); // ditto
```

And also, do you have a convention in place already for dealing with features that may not be present in the current environment? If someone tries to do this in IE6 what should happen?

**Comment by nunofgs** [comment]
:+1: I also just felt the need for this feature.

**Comment by simonzack** [comment]
:+1: This needs to be re-opened. Especially with ES6 catching on, this is more important than ever.

**Comment by mkay581** [comment]
+1 I wholeheartedly agree with @simonzack

**Comment by machineghost** [comment]
+1

**Comment by mroderick** [comment]
> I'd also like to see this reopened. It'd be useful specifically for stubbing fields of a wrapped location object.

Does https://github.com/mroderick/wrapple plug that gap for you?

**Comment by qubyte** [comment]
Nowadays I use wrapple quite extensively, and I'd forgotten about commenting on this issue. That probably means that wrapple has plugged the gap as you say.

**Comment by derwaldgeist** [comment]
+1 just stumbled upon sinon not supporting getter mocking

**Comment by lucasfcosta** [comment]
Hi @derwaldgeist, are you using Sinon's latest version?

The latest one supports stubbing getters with both `sandboxes` and `sinon.stub`.

All you gotta do is use the `get` function, for example:

```js
var myObj = {
    prop: "foo"
};

createStub(myObj, "prop").get(function getterFn() {
    return "bar";
});

myObj.prop // "bar"
```

**Comment by derwaldgeist** [comment]
Thanks for coming back that quick, highly appreciated. BUT: I did not find how you can restore a getter that has been defined that way?

**Comment by lucasfcosta** [comment]
Hi @derwaldgeist,

It's indeed possible to restore getters, even if they were undefined before being stubbed. All you gotta do is call the `restore` method in the created stub, for example:

```js
var myObj = {
    prop: "foo"
};

var stub = createStub(myObj, "prop");

stub.get(function getterFn() {
    return "baz";
});

myObj.prop // "baz"

stub.restore();

myObj.prop // "foo"
```

We add this `restore` method that either in [the `stub` method itself (when stubbing a non-function property)](https://github.com/sinonjs/sinon/blob/d8dac848a8ad6edb7396a6927e8390d2b465bb4c/lib/sinon/stub.js#L47) or [in the `wrapMethod` utility](https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/wrap-method.js#L112).

**Comment by derwaldgeist** [comment]
Wow, that was fast. I tried this:
```js
  const stub = sinon.stub(myObj, 'prop').get(() => ({}));
  ...
 stub.restore();
```
but when executing restore() it says: `Cannot redefine property: prop`

**Comment by lucasfcosta** [comment]
@derwaldgeist I got that from a test, sorry, forgot to edit it. But anyway, it is the same as `sinon.stub`.

Can you tell me what version of sinon are you using so that I can check it?

I think that maybe you are not using the latest version yet in which we fixed a bug where you could not restore properties due to them being defined without `configurable: true`.

**Comment by jshado1** [comment]
I'm seeing the same as @derwaldgeist. I _think_ I'm using v4, but some other deps were using v1.7, so I'm not sure which is _actually_ getting used. I didn't see a `sinon.version` where i could check at run time.

**Comment by fatso83** [comment]
@jshado1 If you want to know which major version you are on, you can refer to the changelog or migration guide and test for the breaking changes. For version 4, you can assert that [`sinon.stub({}, 'nonExistingProperty')` throws](http://sinonjs.org/guides/migrating-to-4.0)
