### ISSUE TITLE
Named spies doesn't work if assigned to object properties

### ISSUE THREAD

**Issue by Reinmar** [sinonjs/sinon#880]
Similar as in #250:

> It would help with readability of assertion error messages if spies (other than the object property ones) could be created with names. For example, Jasmine spies allow this.

This works fine:

```
var spy1 = sinon.spy( function a() {} );
var spy2 = sinon.spy( function b() {} );

spy1();
spy2();

sinon.assert.callOrder( spy2, spy1 );
// AssertError: expected b, a to be called in order but were called as a, b
```

But this doesn't:

```
var obj1 = {
    spy: sinon.spy( function a() {} )
};
var obj2 = {
    spy: sinon.spy( function b() {} )
};

obj1.spy();
obj2.spy();

sinon.assert.callOrder( obj2.spy, obj1.spy );
// AssertError: expected spy, spy to be called in order but were called as spy, spy
```

I also tried setting spies names in this way, but no luck:

```
var obj1 = {
    spy: sinon.spy().named( 'a' )
};
```

**Comment by mroderick** [comment]
That would be very helpful indeed. Would you fancy making a PR to implement it?

**Comment by Reinmar** [comment]
Yeah, I could dig into Sinon's code – it would actually be helpful for me to better understand it. It may take me 1-3 weeks though due to other tasks.

BTW. Could you perhaps point me to a place in the code where you would start debugging this?

**Comment by fatso83** [comment]
Help is very much welcome. [This](https://github.com/sinonjs/sinon/blob/master/lib/sinon/assert.js#L94) might prove a good start for digging.
