### ISSUE TITLE
Stubbed getter called on restoring

### ISSUE THREAD

**Issue by vitalets** [sinonjs/sinon#897]
Let's take an example with subbed getter and restoring:
````js
        var obj = {
            get prop() {
                console.log('Getter content called!');
                return 42;
            }
        };
        var stub = sinon.stub(obj, 'prop', {get: function () {
            return 43;
        }});
        console.log('Stubbed output', obj.prop);
        // restoring
        stub.restore();
````
When running this code I'm getting correctly subbed `obj.prop`, but on restore getter content is called!
````
Stubbed output 43
Getter content called!
````
And in my real test I'm getting error as environment for getter is not mocked!
It is possible to not call stubbed getter on `restore()`?

Any help appreciated!

**Comment by acvetkov** [comment]
+1

**Comment by vitalets** [comment]
thank you!

**Comment by micheleDiSalvatoreLoveholidays** [comment]
I have the same issue on the version 1.17.6 how is it possible?

**Comment by fatso83** [comment]
@micheleDiSalvatoreLoveholidays : you are not having the same issue. Whatever is happening it is something else, as the test case provided by @vitalets is running fine. I just tested:

```shell
$ cd ~/dev/sinon

$ cat > test.js << EOF
> var sinon = require('./lib/sinon');
>
> var obj = {
>     get prop() {
>         console.log('Getter content called!');
>         return 42;
>     }
> };
> var stub = sinon.stub(obj, 'prop', {get: function () {
>     return 43;
> }});
> console.log('Stubbed output', obj.prop);
> // restoring
> stub.restore();
>
> EOF

$ node test.js
Stubbed output 43
```

If you want us to take a look at this you need to open an issue with a _reproducible test case_.
