### ISSUE TITLE
Investigate bithound.io integration

### ISSUE THREAD

**Issue by fearphage** [sinonjs/sinon#900]
https://www.bithound.io/github/fearphage/Sinon.JS

Bithound provides code insights about code complexity, outdated dependencies, code quality, etc. It's more of a passive relationship at present in that it doesn't have web hooks to block/show updates in pull requests. I've been toying with it lately and I like what it brings to the table. I'm not sure if everyone is aware of it though. Just thought it was worth bringing to your attention.

@cjohansen @mroderick

**Comment by fearphage** [comment]
This isn't a PR, because integrating it involves admin access and button clicking in the github and/or bithound interface. It's free also.

**Comment by mroderick** [comment]
That seems like a tool that can produce some valuable insights.

I've clicked some buttons:
https://www.bithound.io/github/sinonjs/sinon

**Comment by fearphage** [comment]
> I've clicked some buttons

Shweet! Aside from adding a badge (if desired), I think this ticket can be closed. Thank you.
