### ISSUE TITLE
It would be useful that yield, yieldTo, etc returns the return value of the yielded function

### ISSUE THREAD

**Issue by julienw** [sinonjs/sinon#903]
``` javascript
var stub = sinon.stub({
  hello: function(callback) {}
});

stub.hello(
  () => { console.log('hello !'); return 'world'; }
);

var value = stub.hello.yield();
console.log(value); // should be 'world', currently false
```

**Comment by fearphage** [comment]
What's the use case? Can you show a real world example?

**Comment by julienw** [comment]
We have an API that goes like this:

```javascript
MessageManager.getMessages({
  each: <function>
  done: <function>
});
```

It's an iterator that calls the `each` callback several times until there is no more items or until the `each` callback returns false.

When testing the caller, I mock getMessages, but I want to check that the `each` callback returns `false` in a specific situation.

So the test could go like this:

```
sinon.stub(MessageManager, 'getMessages');
callTestedMethod();
var result = MessageManager.getMessages.yieldTo('each');
assert.isFalse(result);
```

I don't think there is a way to do it currently, besides stubbing with a custom function.

**Comment by fearphage** [comment]
Aren't you passing the object to `getMessages`? It seems like you're tightly coupling two unrelated things.

```js
var object = {each: fn};

assert.isFalse(object.each(5));
// or
assert.isFalse(fn(5));
```

**Comment by julienw** [comment]
The tested code is passing the object to getMessages.

Yet I realize from your comment that I could do:
```
sinon.stub(MessageManager, 'getMessages');
callTestedMethod();
var object = callTestedMethod.lastCall.args[0];
var result = object.each();
assert.isFalse(result);
```

But this defeats the purpose of yieldTo IMO. Using `args` is not really expressive... If you tell me "ok, just use `args`", then why do we have all the useful methods in the API?

**Comment by tshelburne** [comment]
@fearphage This is also useful in the case of caching - cache-manager provides the following interface:

```javascript
cache.wrap('request-key', function() {
  return fetch('some/url')
})
.then(function(res) {...})
.catch(function(err) {...})
```

In this case, being able to stub `cache.wrap` to yield *and* return the value of that yield is essential to test.

**Comment by globetro** [comment]
This would also be helpful for testing asynchronous callbacks. Example:

```javascript
stub.onCallback(async () => { /* do some async stuff */});

it('executes the async stuff', async () => {
  await stub.onCallback.yield();
  // expect async callback to have happened
});
```

**Comment by julienw** [comment]
I think it would still be useful. How to make it move forward ?

**Comment by mroderick** [comment]
@julienw a pull request goes a long way :)

**Comment by fatso83** [comment]
Might make sense to test any such PR against #1586
