### ISSUE TITLE
Cannot spy on bare function

### ISSUE THREAD

**Issue by calebTomlinson** [sinonjs/sinon#905]
I'm on the latest version of sinon (1.17.2);

```
var sinon = require('sinon');

var foobar = function foobar () {
  console.log('foobar');
}

var spy = sinon.spy(foobar);

foobar();

console.log(spy.callCount);  //0
```

This seems like pretty basic functionality as described in the documentation. Am I missing something.

**Comment by mantoni** [comment]
You'd call `spy`. It's impossible to track invokations of `foobar` for Sinon.
