### ISSUE TITLE
Add gitter chat room

### ISSUE THREAD

**Issue by hellboy81** [sinonjs/sinon#906]
Please add gitter chat room to get live help on usage questions. 

IRC channel  seems to be inactive.

**Comment by fatso83** [comment]
There already exists a [Gitter chat room](https://gitter.im/sinonjs), but it needs people to help out. It's more than enough work working on the issues and pull requests here :-)

@mantoni @mroderick : would it make sense to add the link to the docs site or should we wait for user adoption (chicken/egg problem)?

**Comment by hellboy81** [comment]
I see 0 rooms, 0 people...

**Comment by fatso83** [comment]
aha, sorry about that. not really into Gitter, so I thought the room was already created, but I see that it only applies to people within the organization. If you have any experience with Gitter, is it a `#channel`  you want us to have or a `repository`? Not sure what the latter entails or what enabling "Integrations with GitHub" does.

**Comment by fatso83** [comment]
Added a room of type "repository": [sinonjs/sinon](https://gitter.im/sinonjs/sinon)
