### ISSUE TITLE
Improve testing process/structure

### ISSUE THREAD

**Issue by fearphage** [sinonjs/sinon#914]
Are there any plans to simplify the test running process? It's incredibly slow and convoluted. I have no idea how to run a single test (think TDD). In the majority of my other projects, test runs are measured in milliseconds. This test suite is very heavy (2 background processes among other things) and thus very slow. 
- Do you have any plans to switch to something lighter/faster? 
- Are you open to PR's for something like this?

**Comment by mantoni** [comment]
Related to the discussion here: https://github.com/sinonjs/sinon/issues/912
Yes, your help would be appreciated. The test suite should ideally run in headless browsers, real browsers and on Node. We're open for suggestions on how to move forward.

**Comment by mroderick** [comment]
Use the focus rocket to run fewer tests: http://docs.busterjs.org/en/latest/overview/
