### ISSUE TITLE
Match on request body

### ISSUE THREAD

**Issue by siancu** [sinonjs/sinon#916]
Hello,

I would like to know if it is possible for sinon to do matching on the body of the request and if yes, how to do it?

The scenario that I want to test involves two PUT requests to the same URL but with a different body (basically it is about conflict resolution). As far as I can see, with `respondWith()`, I can only match on the URL itself.

Thanks!

**Comment by mantoni** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by siancu** [comment]
Thanks, I didn't know the mailing list exists :-).
