### ISSUE TITLE
Add tool to catch drops in test coverage

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#919]
Ref the discussion in #918, we have a problem with catching regressions in test coverage. We can accidentally lower coverage by 90% in one module without noticing. Adding a tool such as  "coveralls" to integrate with GitHub would increase the likelyhood of catching something like this.

**Comment by fearphage** [comment]
Coveralls has a lot of different [node integrations](https://github.com/nickmerwin/node-coveralls).

If you can `lcov` test coverage results from buster-test, then I think we'll be in business.

**Comment by fearphage** [comment]
Google and I found this **unmaintained** [buster-coverage module](https://www.npmjs.com/package/buster-coverage). I don't have much experience with busterjs myself.

**Comment by mroderick** [comment]
We already produce `lcov`coverage analysis using [buster-istanbul](https://github.com/englishtown/buster-istanbul).

Try running the tests with `npm test` and then checking the contents of `coverage/`

**Comment by fearphage** [comment]
Good to know. Well then the majority of setup is clicking stuff in the coveralls.io UI (signu up, enable this repo, enable PR tracking, enable comments) and adding a key to travis-ci (`repo_token`).

Then there's a small PR (that will probably be added to the `ci-test` npm script)  that will be along the lines of `cat coverage/lcov.info | coveralls` and we're set.

**Comment by fearphage** [comment]
Actually that seems best served with the `after_success` callback in `travis.yml`

**Comment by fearphage** [comment]
*bump*

**Comment by GCheung55** [comment]
I've a project that uses buster-Istanbul and coveralls: https://github.com/GCheung55/metiri

It's pretty simple to setup.
