### ISSUE TITLE
stub().throws("TypeError") doesn't actually throw TypeError instance when called

### ISSUE THREAD

**Issue by isiahmeadows** [sinonjs/sinon#922]
This isn't the behavior I expected:

```
$ node
> var stub = require("sinon").stub().throws("TypeError")
undefined
> try { stub() } catch (e) { e instanceof TypeError }
false
```

I expected the type to actually be a TypeError instance, not just a renamed Error.

```
> try { stub() } catch (e) { e.constructor }
{ [Function: Error]
  captureStackTrace: [Function: captureStackTrace],
  stackTraceLimit: 10 }
```

Could this be fixed?

**Comment by fearphage** [comment]
Good catch. As far as I can tell, this has [never](https://github.com/sinonjs/sinon/commit/cc4940f35d2afca42190c690c5e379e464b3d1ad#diff-048fb1194de4b43f7f7e45758f900749R87) worked the way the documentation says. However the name of the error is the value that you passed in.

```js
e.name === 'TypeError'
```

I'll look into fixing this.

**Comment by mantoni** [comment]
Hm. Shouldn't the api use like this instead?

```js
var stub = require("sinon").stub().throws(new TypeError());
```

The above throws the string `"TypeError"` which is absolutely possible in JavaScript. If we changed that string to something else magically, I guess we'd break a valid use case, right?

**Comment by fearphage** [comment]
No, base on the code in the OP, it throws an instance of `Error` with the `name` set to `TypeError` .

```js
  function throwsException(error, message) {
    if (typeof error === "string") {
        this.exception = new Error(message || "");
        this.exception.name = error;
    } else if (!error) {
        this.exception = new Error("Error");
    } else {
        this.exception = error;
    }

    return this;
}
````

[source](https://github.com/sinonjs/sinon/blob/bcf16631e86691dcb0c679df5aa62c47d630c474/lib/sinon/behavior.js#L34-L45)

**Comment by impinball** [comment]
I would be willing to take a breaking change (function to `new`) here to rectify this. It makes little sense why that wasn't already done in the first place, and if you're throwing a function, you probably aren't throwing the right thing.

**Comment by MichaelPaulukonis** [comment]
I noticed that the documentation still says

```
stub.throws("TypeError");
Causes the stub to throw an exception of the provided type.
```

However, the above described functionality still holds true.
It is necessary to use `stub.throws(new FooError())` to obtain an error that will match `error instanceof FooError`

**Comment by fatso83** [comment]
@MichaelPaulukonis if you supply a small PR with a correct description we no longer have an issue ;-)

**Comment by MichaelPaulukonis** [comment]
Thanks, @fatso83 - [PR#1730](https://github.com/sinonjs/sinon/pull/1730) submitted!
