### ISSUE TITLE
Run source tests in browsers

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#924]
It would be great if we could somehow implement a `require` function that would understand CommonJS modules, so we can run the source tests in browsers again, and get coverage reports for those also.

```
$ buster-test
Running 1515 tests in 1 runtime ...

test
4 deferred tests
1189 tests, 1993 assertions, 1 runtime ... OK
```

That's some 326 tests skipped, because they rely on browser features. My bet is on fake XHR and friends.

I had a quick experiment with https://github.com/dfcreative/require-stub, but couldn't get it working. I have no idea if that is a good solution for it.

**Comment by jonnyreeves** [comment]
I find the testing structure a little confusing at present; what would the ideal structure look like?  Should we just run a single test-pass in Phantom/SlimerJS and remove the busterjs `node` pass?

**Comment by mantoni** [comment]
This has been addressed a while back.
