### ISSUE TITLE
calledOn accepting matcher is not documented

### ISSUE THREAD

**Issue by azizpunjani** [sinonjs/sinon#926]
https://github.com/sinonjs/sinon/blob/a97374641599ed2f451e9a22f784060cf7a38b3e/lib/sinon/call.js#L29
calledOn accepting a matcher is not documented.

**Comment by fatso83** [comment]
Thanks for noticing, and feel free to make a pull request with documentation updates. PRs are always most welcome :smile:

**Comment by azizpunjani** [comment]
@fatso83 done.

**Comment by fatso83** [comment]
Thank you!

**Comment by mroderick** [comment]
:star:
