### ISSUE TITLE
Improve `window` check in fake_server.js

### ISSUE THREAD

**Issue by IanVS** [sinonjs/sinon#939]
For unit testing our React code, we are overriding `window` with  `window = {}`, which is causing Sinon to blow up.  The relavant [portion of code](https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/fake_server.js#L34-L35) is:

```js
var wloc = typeof window !== "undefined" ? window.location : {};
var rCurrLoc = new RegExp("^" + wloc.protocol + "//" + wloc.host);
```

An error is being thrown because our fake window does not have a `location`.  Would you accept a PR changing the above code to something like:

```js
var wloc = (typeof window !== "undefined" && window.location) ? window.location : {};
var rCurrLoc = new RegExp("^" + wloc.protocol + "//" + wloc.host);
```

**Comment by fatso83** [comment]
To me this seems to target a too specific use case. Not sure what others think.

**Comment by fatso83** [comment]
To me this seems to target a too specific use case. Not sure what others think. I think the "fix" belongs in your own test code. Add the required attributes to your stubbed window object.

**Comment by IanVS** [comment]
Aside from my use case, you are making the assumption that if `window` exists, then it has a `location` property.  The change I proposed seems to be just good defensive programming.

**Comment by mantoni** [comment]
I'd argue we use `window` to feature detect whether we're in a browser and if that's the case, we assume `location` also exists.

I'm with @fatso83 here. The fix belongs elsewhere.

**Comment by mroderick** [comment]
https://github.com/mroderick/wrapple

**Comment by IanVS** [comment]
OK, I'm fine with that.  Just wanted to at least bring it up.  Thanks.

**Comment by alobaidizt** [comment]
@IanVS I'm having a similar problems to yours. Did you end up finding a different solution from the one you suggested?

**Comment by IanVS** [comment]
I ended up caving in and using jsdom.

**Comment by alobaidizt** [comment]
Thank you!
