### ISSUE TITLE
useFakeXMLHttpRequest is not defined in sinon.test sandbox

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#941]
The sinon docs mention `useFakeXMLHttpRequest` as one possible thing to use in sinon.test sandboxes, but I get a TypeError if I try to use it:

```
it('should not fail', sinon.test(function() {
    var stub = this.stub(); // fine 
    this.useFakeXMLHttpRequest();  // "TypeError: this.useFakeXMLHttpRequest is not a function"
});
```

Sinon 1.17 and Sinon 2.0-pre
Running in Chrome

**Comment by mroderick** [comment]
Does this belong to `sinonjs/sinon-test`? Can we move the issue there?

**Comment by fatso83** [comment]
Yeah, it belongs there. Is there a tool to move it across repos? Or do we just close and make a new one?

**Comment by mantoni** [comment]
A guick google reveiled this: https://github-issue-mover.appspot.com

It's an open source tool from Google: https://github.com/google/github-issue-mover

**Comment by mroderick** [comment]
> A guick google brought this to light: https://github-issue-mover.appspot.com
> 
> It's an open source tool from Google: https://github.com/google/github-issue-mover

Looks good. I'll create a new github user account just for this tool, as I am not comfortable with giving it access to private repositories.
