### ISSUE TITLE
Sinon fails to SPY methods called via Q.fcall

### ISSUE THREAD

**Issue by vadzappa** [sinonjs/sinon#942]
Here is the failing test:
```js
var sinon = require('sinon'),
    assert = require('assert'),
    _ = require('lodash'),
    Q = require('q');

describe('sinon fails to spy Q calls', function() {
    it('should spy correctly', function(done) {
        var MyClass = function() {

        };
        _.extend(MyClass.prototype, {
            methodToExecute: function methodToExecute() {
                // in this case spy doesn't work while the method is actually called
                Q.fcall(this.methodToSpy.bind(this)).done();

                // while this one could be called normally
                //this.methodToSpy();
            },
            methodToSpy: function methodToSpy() {
                console.log('methodToSpy');
            }
        });

        var impl = new MyClass(),
            sinonSpy = sinon.spy(impl, 'methodToSpy');

        impl.methodToExecute();

        assert(sinonSpy.called);

        done();
    });
});
```

So, the issue is once the method called directly, it's spied normally, while if method is called via Q, it fails to spy.

As result of this issue, mocking doesn't work correctly and reports assertation problems.

**Comment by fatso83** [comment]
This is not a bug in Sinon, but a usage problem. You are binding the original function before it has been wrapped by the spy. 

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
