### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined - when calling sinon.spy() on function that returns JSX

### ISSUE THREAD

**Issue by moroshko** [sinonjs/sinon#944]
When asserting:

```
expect(foo).to.have.been.calledWith(...);
```

I get the following error:

> TypeError: Cannot read property 'toLowerCase' of undefined
>      at Function.ascii.element (node_modules/sinon/node_modules/formatio/lib/formatio.js:170:37)
>      at ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:85:54)
>      at Object.ascii.object (node_modules/sinon/node_modules/formatio/lib/formatio.js:141:23)
>      at ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:99:29)
>      at Object.ascii.object (node_modules/sinon/node_modules/formatio/lib/formatio.js:141:23)
>      at ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:99:29)
>      at Object.ascii.object (node_modules/sinon/node_modules/formatio/lib/formatio.js:141:23)
>      at ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:99:29)
>      at Object.ascii.object (node_modules/sinon/node_modules/formatio/lib/formatio.js:141:23)
>      at ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:99:29)
>      at Object.ascii.object (node_modules/sinon/node_modules/formatio/lib/formatio.js:141:23)
>      at ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:99:29)
>      at Object.ascii.array (node_modules/sinon/node_modules/formatio/lib/formatio.js:115:25)
>      at ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:81:32)
>      at Object.Formatio.ascii (node_modules/sinon/node_modules/formatio/lib/formatio.js:208:20)
>      at Object.format (node_modules/sinon/lib/sinon/format.js:27:40)
>      at Object.callProto.toString (node_modules/sinon/lib/sinon/call.js:168:47)
>      at spyApi.formatters.C (node_modules/sinon/lib/sinon/spy.js:397:75)
>      at node_modules/sinon/lib/sinon/spy.js:301:42
>      at String.replace (native)
>      at Function.spyApi.printf (node_modules/sinon/lib/sinon/spy.js:297:39)
>      at printfArray (node_modules/sinon-chai/lib/sinon-chai.js:55:31)
>      at affirmative (node_modules/sinon-chai/lib/sinon-chai.js:60:24)
>      at Object.module.exports [as getMessage](node_modules/chai/lib/chai/utils/getMessage.js:42:39)
>      at Assertion.assert (node_modules/chai/lib/chai/assertion.js:105:22)
>      at Assertion.<anonymous> (node_modules/sinon-chai/lib/sinon-chai.js:95:18)
>      at Assertion.ctx.(anonymous function) [as calledWith](node_modules/chai/lib/chai/utils/addMethod.js:40:25)
>      at Context.<anonymous> (Autosuggest.test.js:243:45)

`foo` returns [JSX](https://facebook.github.io/jsx) and looks like this:

```
const foo = sinon.spy(args => {
  return <span>hey</span>;
});
```

**Note:** If I change `foo` to return a string instead:

```
const foo = sinon.spy(args => {
  return 'hey';
});
```

the error disappears.
### To reproduce:
1. `git clone git@github.com:moroshko/react-autosuggest.git`
2. `cd react-autosuggest`
3. `git checkout b9d9bccf3803465a1f6349798a25bc61b5feb515`
4. `npm install`
5. `npm test`

I'm using:
- sinon: 1.17.2
- sinon-chai: 2.8.0

Is this a known issue with JSX?
Is this an issue with `sinon` or `sinon-chai`?
Are there any workarounds?

**Comment by fatso83** [comment]
This has really nothing to do with Sinon. It is not an issue with JSX: it is the way it and React is designed to work.

JSX is converted to a hierarchical javascript structure. It is not a string. You need to convert it into a string by using something like [ReactDOMServer.renderToString](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostring). After that you can make meaningful comparisons.

**Comment by moroshko** [comment]
@fatso83 Sorry, I probably miss something here. Are you saying that `sinon` can `spy()` only functions that return a `String`? I just want to make sure that the function is called with the right parameters. I'm not interested in comparing its return value. What am I missing here?

**Comment by fatso83** [comment]
You are correct in wondering what I wrote: I misread the code. I thought you did some kind of string evaluation when looking at the stack trace. I am reopening it, as this might be a bug in Sinon when dealing with non-serializable objects or something like it.
