### ISSUE TITLE
Fork eslint-config-defaults for sinonjs/* repositories

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#946]
Create a fork of https://github.com/walmartlabs/eslint-config-defaults under sinonjs/ and in that fork create a shared configuration for all sinonjs/\* repositories.

**Comment by mantoni** [comment]
Yes, this is a great idea!

**Comment by mroderick** [comment]
This has been implemented with the [eslint-config-sinon](https://github.com/sinonjs/eslint-config-sinon) repository
