### ISSUE TITLE
Sandbox.reset doesn't work

### ISSUE THREAD

**Issue by madSimonJ** [sinonjs/sinon#947]
I've found that using the Sandbox the callcounts never reset between tests if I call sandbox.reset().  I have to call the individual resets for each stub I'm using.

**Comment by fatso83** [comment]
Seems important, but I am afraid this won't get much priority until more info is supplied.

[Try this](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue)

**Comment by fatso83** [comment]
@madSimonJ We never got any test data from you, but we have tried looking into this and as far as we can tell, this is not reproducible. We have made many tests in #985, and we'll probably close this unless you can supply some code showing that the problem actually exists in some cases.

**Comment by madSimonJ** [comment]
Hi,
      For sure the problem still exists.  Apologies for the lack of test data, I've not long had a daughter and I'm struggling to find any time for non-day-job IT stuff atm.  I'll try and get something for you asap.
Thanks,
Simon
 49 66 20 59 6F 75 20 43 61 6E 20 52 65 61 64 20 54 68 69 73 2C 20 59 6F 75 20 4E 65 65 64 20 41 20 4C 69 66 65 21 

    On Friday, February 12, 2016 2:54 PM, Carl-Erik Kopseng <notifications@github.com> wrote:
 

 @madSimonJ We never got any test data from you, but we have tried looking into this and as far as we can tell, this is not reproducible. We have made many tests in #985, and we'll probably close this unless you can supply some code showing that the problem actually exists in some cases. —

**Comment by fatso83** [comment]
@madSimonJ Thank you for getting back to us! When you have time try and add  code in this issue that triggers the problem. You can use the tests supplied in #985 as a template/inspiration.

I am closing this _for now_ until we see actual code, but feel free to reopen it as soon as you have some time to spare for this issue :-)

**Comment by fatso83** [comment]
P.S. #965 might be related, and it was reported that it worked fine in Sinon 1.16.1, so you might try out that version to see if we are facing a regression. It might as well not be related, but it could help in pinpointing when this happened.
