### ISSUE TITLE
returns a function that gets called

### ISSUE THREAD

**Issue by mmahalwy** [sinonjs/sinon#951]
Sinonjs only assigns a returnedValue but limits it to an object, string, number, etc. but not to functions to be invoked.

For example:
```
let myObj = {a: 1};
stub.onCall(1).returns(() => {myObj.a = 2});
```

or am I missing something?

**Comment by mmahalwy** [comment]
Bump^^

**Comment by mantoni** [comment]
It works for me. Tried it this way:

```js
var sinon = require('sinon‘);
var stub = sinon.stub();
stub.returns(function () {});
stub(); // returns [Function]
```

Maybe you could provide a more complete example or a jsfiddle?

**Comment by mmahalwy** [comment]
@mantoni forgive me, it does work to return a function, but my intent is to have the function be called when the stub is called. Example:

```
let myObj = {a: 1};
stub.onCall(1).returns(() => {myObj.a = 2}); // or on stub.onCall(1) it calls something else to change myObj

myObj === {a: 2} // true
```

So in essence, when the stub is called for the second time, it calls some function and I thought `.returns()` would work, but it does not.

**Comment by mantoni** [comment]
I see. No, that is not possible in that form. The only thing you can do is pass a custom function into your stub which will always be called:

```js
sinon.stub(obj, 'prop', function () {
  // your logic
});
```

If you have further questions on how you can achieve what you want, I'd recommend the Sinon mailing list: http://groups.google.com/group/sinonjs

**Comment by mmahalwy** [comment]
Okay thanks @mantoni
