### ISSUE TITLE
Broken link on site

### ISSUE THREAD

**Issue by Alexsey** [sinonjs/sinon#954]
From <a href="http://sinonjs.org">main page</a> move to link <a href="http://sinonjs.org/download/">More builds/versions</a> and from there to <a href="http://sinonjs.org/download/Changelog.txt">Changelog</a> - it will lead you to 404. Probably it should be <a href="http://sinonjs.org/Changelog.txt">Changelog</a> from main page

**Comment by mroderick** [comment]
This has been fixed in the new site, http://sinonjs.org/download/ is redirected to http://sinonjs.org/releases/index.html
