### ISSUE TITLE
Way To Create "Piggyback" Stub

### ISSUE THREAD

**Issue by machineghost** [sinonjs/sinon#956]
99% of the time when I want to stub something I don't want to call the original method.  But every once in awhile I want to create a stub that enhances, rather than replaces, an existing method.  In other words, I want to create a sort of  "piggyback" stub: a stub that acts like a spy, but lets you add logic before/after the stubbed method.

For example, consider the following class/test:

```
var MyClass = function() {
     this.initialize();
     this.doer.do('something');
};
MyClass.prototype.initialize = function() {
     this.doer = {do: doSomething};
     // initialize some other important stuff
});

var myTest = function() {
    var myObject = new MyClass();
    expect(myObject.doer.do.calledOnce).to.be.true;
});
```

To make the above work, I need to stub the `doer` property, which I can only do by stubbing `initialize`.  But if I stub `initialize` I lose all of the "other stuff" initialization that I need.  Thus, I have to do the following:

```
var myTest = function() {
    var originalInitialize = MyClass.prototype.initialize;
    sandbox.stub(MyClass.prototype, 'initialize', function() {
        originalInitialize.apply(this, arguments);
        sandbox.stub(this.doer, 'do');
    });
    var myObject = new MyClass();
    expect(myObject.doer.do.calledOnce).to.be.true;
});
```

While that's not the end of the world, it would be nice if Sinon could save me from that complexity, using the info it already has.  Imagine if Sinon kept the original version for me:

```
var myTest = function() {
    sandbox.stub(MyClass.prototype, 'initialize', function() {
        this.__PRE_STUB_VERSION.apply(this, arguments);
       sandbox.stub(this.doer, 'do');
    });
}
```

or what if instead Sinon gave me a way to provide before/after functions when I create a stub: 

```
var myTest = function() {
    sandbox.stub(MyClass.prototype, 'initialize', {
        after: function() {
            sandbox.stub(this.doer, 'do');
        }
        // (there could also be a "before" property for running code before the stub)
    });
}
```

Admittedly this isn't the most common case, but something like either of the above would be very handy when it comes up.

**Comment by fatso83** [comment]
Some kind of before/after should be doable. These could also give you access to the original function, avoiding the need to add props on the stub. A la `after : function(originalFunction) { ...} `

You can have a stab at it and submit a pull request.

**Comment by machineghost** [comment]
Will do ... as soon as I can find the time :)

**Comment by fearphage** [comment]
This is loosely related to #988 and #989.

**Comment by thebarty** [comment]
PLUS one for that feature

**Comment by fatso83** [comment]
@thebarty, if you want it you can just have a go at it 😎I think it's easier than it looks, but it's not happening until someone does it and supplies a PR.

**Comment by fearphage** [comment]
```js
MyClass.prototype.initialize = function() {
     this.doer = {do: doSomething};
     // initialize some other important stuff
};
```

Where is `doSomething` coming from? This feels like a code organization issue. In the above snippet, if you just pass `doSomething` to `initialize()` from the constructor (dependency injection). It's easy to stub.

**Comment by machineghost** [comment]
Sorry for the very late response, but just to answer your point @fearphage, dependency injection is a great way to make things mock/stub/spy-able.  However, if you're team doesn't use dependency injection normally, then it's not the most friendly thing to refactor the code with unfamiliar patterns ... especially when the only reason you're doing so is to add test coverage on a pre-existing legacy class that isn't your's.

Or, in short, it's the "win in Rome" principle, as well as the "you ideally shouldn't have to change your production code to support it's testing" principle.

**Comment by fearphage** [comment]
> "you ideally shouldn't have to change your production code to support it's testing" principle

I've never heard of this principle honestly. People don't often write code with testing in mind. It's common to write code that is difficult to test. To me it sounds like the problem you're facing is a result of writing tests *after* the code is complete. Speaking from experience (on both sides), it's a rare occurrence in a test-driven development environment. I'm all for sinon helping to test in all environments, but sometimes the way the code is written makes it difficult to test. Sometimes it is a good idea to refactor legacy code to make it (more) easily testable.

PS. It's [_when_ in Rome](https://en.wikipedia.org/wiki/When_in_Rome,_do_as_the_Romans_do).

**Comment by machineghost** [comment]
LOL I have corrected the typo in my quote.

As for the rest ... I think it's great that you've spent your career only working at TDD shops with no legacy code, and where new hires are welcome to come and refactor perfectly working existing classes (potentially introducing bugs) because they want to test them differently than everyone else at the company ... but not everyone does.

I have been doing this for over a decade, at seven different companies, and none of them were like that.  Or if you don't believe me, consider the 5th best selling software testing book on Amazon, Working Effectively with Legacy Code: if  everyone had codebases like yours no one would have bought that book..

So, all I'm saying is that, it's great if you don't need this feature because of how things are at your shop, but please don't assume that everyone's shop is like your's.

**Comment by mroderick** [comment]
> As for the rest ... I think it's great that you've spent your career only working at TDD shops with no legacy code, and where new hires are welcome to come and refactor perfectly working existing classes (potentially introducing bugs) because they want to test them differently than everyone else at the company ... but not everyone does.
> 
> I have been doing this for over a decade, at seven different companies, and none of them were like that. Or if you don't believe me, consider the 5th best selling software testing book on Amazon, Working Effectively with Legacy Code: if everyone had codebases like yours no one would have bought that book..
> 
> So, all I'm saying is that, it's great if you don't need this feature because of how things are at your shop, but please don't assume that everyone's shop is like your's.

Being snarky with maintainers that give their time to you for free is not going to win people to your side of the argument. Please try again.

**Comment by machineghost** [comment]
My apologies.  As soon as I re-read it realized that it could be taken the wrong way and edited it to its current form.

It was never intended to be insulting at all, I was just trying to highlight that different people have different experiences and that doesn't make them invalid.

**Comment by fearphage** [comment]
> I think it's great that you've spent your career only working at TDD shops with no legacy code, and where new hires are welcome to refactor existing code so that they can test it differently from their co-workers ... but not everyone does.

I addressed this directly. I said I've been on **both** sides of this argument. I've even written the hard-to-test legacy code that myself and others then have to circle back to and figure out how to test. My preference is to write tests (as best I can) without changing any code to ensure the interface stays intact. Then as I break things apart and make the code more test-accessible, I add more tests using TDD. This won't necessarily work for everyone, but I'm just sharing my experiences.

Also I've never been at a company where new hires could only work on X or were forbidden from working on Y. That seems strange to me. Either you're a dev or you're not. If you can access the repo, you can submit a PR. It may not get merged, but I feel like you should be able to make an attempt at least.

> I have been doing this for over a decade, at seven different companies, and none of them were like that.

Not that length of time is an indicator of much, but I've been doing this for almost 20 years. None of the companies that I've worked at started out that way for me either. I've had the pleasure of working at places where I've had the ability (and responsibility) to improve the development process and not merely the code. I understand this may not always be the case for me nor everyone else.

> Many of us do have to test code after it's been written, and when we are new at a company we don't want to rock the boat by changing our boss's code to fit our testing style.

This makes sense for legacy code, but it shouldn't be the normal day-to-day in my opinion. If it is business as usual, this seems like a company/culture problem. "Throwing stuff over the wall" that is consistently difficult to test is a problem.
---

That being said none of this has to do with Sinon at all and as I said previously, I'm not standing in the way of any PRs. If someone writes the code, we'll be more than happy to check it out.

**Comment by machineghost** [comment]
> If someone writes the code, we'll be more than happy to check it out.

While I appreciate that, after all this drama I just don't see how any PR I could submit would be well-received.  Plus even before a maintainer attacked the idea (and I made things much worse with my defense of it) the ticket had only a single person express any actual desire for it in the five months that I failed to write a patch.

I think a better solution is to let an unpopular idea, whose defense only irked the people I'm trying to help, die off.
