### ISSUE TITLE
Stub with func

### ISSUE THREAD

**Issue by kuraga** [sinonjs/sinon#959]
Good day!

```js
'use strict';

var sinon = require('sinon');

var g = function () { return 2; };

var obj1 = {};
obj1.f = function () { return 1; };
var stub1 = sinon.stub(obj1, 'f');
obj1.f.returns(3);  // ok
stub1.returns(3);  // ok

var obj2 = {};
obj2.f = function () { return 1; };
var stub2 = sinon.stub(obj2, 'f', g);
obj2.f.returns(3);  // not a function
stub2.returns(3);  // not a function
```

Question 1: Why?
Question 2: What does `obj.f()` do just after `sinon.stub(obj, 'f')`?

Thanks!

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).
