### ISSUE TITLE
Commit distribution files as part of a release

### ISSUE THREAD

**Issue by tylerbhughes** [sinonjs/sinon#975]
I was going to add sinon to the jsDelivr CDN. However, I was told that the way sinon is being released currently there is no way for the jsDelivr bot to automatically add new releases.

Per jsdelivr/jsdelivr#9467 the production files `sinon.js` and `sinon.min.js` would need to be included each time a new tag is made. Can this be added in the future?

---

edit (fatso83): Changed title to reflect what actually needs to be done. Might depend on changes related to #981

**Comment by mroderick** [comment]
This is done for every release now, they're stored in https://github.com/sinonjs/sinon/tree/master/docs/releases
