### ISSUE TITLE
Fix defake responseType and attribute updates.

### ISSUE THREAD

**Issue by randym** [sinonjs/sinon#976]
Sinon version: 1.17.2 
Environment OSX Chrome 48.0.2564.97 (64-bit) 
Exmaple URL: http://jsbin.com/soxibo/edit?html,js,console,output

**Bug Description** 
When using sinon.useFakeXMLHttpRequest, it is possible to specify
filters to allow specific requests to be sent via a working XHR.

Unfortunately, the implementation ignores the configured responseType
and the mapping of attribute updates from the working XHR to the
exposed fake XHR on state change are not inline with the specification.

I need this working for a client now, and have forked/fixed this issue here:
https://github.com/randym/sinon/commit/7cca0fbb2a05e3e34d425addd33767d3d4560ed5

Please advise if you would like a PR.

**Comment by fatso83** [comment]
Cannot see why we wouldn't want a working fix for an existing problem. Seems like a great candidate for a pull request

**Comment by randym** [comment]
Is there a particular branch/commit would you like to see a PR against?

Assuming 2.0.0 will come with some non-backwards compatible changes, I would love to see a 1.17.4 release with this fixed. I am also intimately familiar with the work/effort that comes with every release of an open source project and am happy to follow your lead.

**Comment by fatso83** [comment]
Sorry for keeping you waiting...  Preferably two pull requests :
- one against the master branch
- one against the 1.17 branch (backport) 

Squash smaller commits and try to keep commits in as few logical units as makes sense.

**Comment by randym** [comment]
No worries. 

I'll get a PR in for master and do the backport when I have a bit of free time.
