### ISSUE TITLE
Calling same mocked method/parameters multiple times?

### ISSUE THREAD

**Issue by gRoberts84** [sinonjs/sinon#977]
Hi there,

Sorry if this is something that shouldn't be posted here however I'm struggling to find the reason or a solution to my error that I get if I call my mocked method multiple times.

Basically I'm doing a rate limiting integration test, which simply needs to send the same http request multiple times.

    it('Too many invalid login attempts', sinon.test(function(done) {
    
        var self = this, attempt = 0;
    
        helpers.hash.create('password').then(function(hash) {
    
            self.mock(userModel)
                .expects('findOne').withArgs({email: 'test@test.com'})
                .chain('select').withArgs('_id password')
                .chain('exec')
                .resolves({
                    _id: 1,
                    password: hash
                });
    
            while (attempt < 15) {
                chai.request(server)
                    .post('/api/user/login')
                    .send({
                        email: 'test@test.com',
                        password: 'abc123',
                        attempt: attempt++
                    })
                    .end(function (err, res) {
    
                        console.log(err);
    
                        var req = res.request.toJSON();
    
                        if (req.data.attempt < 15) {
                            expect(err).to.have.status(403);
                            expect(err).to.not.be.null;
    
                            var body = JSON.parse(res.error.text);
    
                            expect(body).to.have.status('authentication failed');
                        } else {
                            console.log('xxxx');
                            done();
                        }
    
                    });
            }
    
        });
    }));

As I haven't explicitly stated that the method should be called once, I assumed it could be called as many times as I like, so when trying to call `userModel.findOne(...)` for subsequent times, it fails with

`{"code":"InternalError","message":"Unexpected call: findOne({ email: \\"test@test.com\\" })\\n    Expectation met: findOne({ email: \\"test@test.com\\" }[, ...]) once"}`

Am I doing something wrong here? 

I'm using chai/chai-http and sinon-as-promised to test this and all other attempts work nicely. Trying to re-mock the same method within the loop fails too.

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [Sinon.JS mailinglist](http://groups.google.com/group/sinonjs), so the bigger community can help answer your questions. [StackOverflow](http://stackoverflow.com) might also be a source of help (tag with `sinon`).

If you feel that your topic is an issue with Sinon.JS, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/cjohansen/Sinon.JS/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by fatso83** [comment]
Just a tip from me when trying to get help on this issue: I am not well versed in the usage of mocks, and the mock functionality is going away with the 2.0 branch, so I will not invest any time in getting to know them either. But if you are trying to find how to use something it usually makes sense to scope down the problem to the essentials. Your code is too complex for any passer-by to dig into. Better to create a succinct and short example that highlights the problem. What do you expect and what is actually happening. My two cents. Good luck!
