### ISSUE TITLE
Create a new build script

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#981]
The issue is meant as a focal point for discussions on a new build script. Following are some earlier discussions:
- [Discussion](https://github.com/sinonjs/sinon/issues/834#issuecomment-145987100) on a new build script. The point of platform neutrality was raised.
- [Discussion that discusses NPM as the basis of build scripts](https://github.com/sinonjs/sinon/issues/893#issuecomment-150784819)
- [Suggestion for a NPM build script](https://github.com/grassator/Sinon.JS/commit/fabc40f22ad21e951530721c032592b5021e9aa9). Problems with platform neutrality
- [My initial first attempt](https://github.com/fatso83/sinon/commit/8b074877ac4ffd93054d1aea548f701bd209c7e4) at a cross-platform build script based on ShellJS

_Some things I would like to discuss:_
- Is it necessary that the build process must work on all operating systems? Maybe it suffices to build it on *nix systems, which is how it is today.
- Although the first stab at a pure NPM based build solution (such as [the one](https://github.com/grassator/Sinon.JS/commit/fabc40f22ad21e951530721c032592b5021e9aa9) proposed by @grassator) did not work on Windows out of the box, it probably _can_ be made to work: just avoid `sh` syntax, use `&&` instead of semicolons, don't call Bash scripts, avoid shebangs (`#!`), and avoid `.`' and `..`.
- [shelljs](http://github.com/shelljs/shelljs) writes Makefile like scripts in javascript and thus avoid platform centricity. But a straight up Bash script is perhaps simpler? It's probably down to visual preference, but it's hard to avoid a Node-based solution if one tries to keep the scripts working everywhere

**Comment by mroderick** [comment]
I have been mostly absent from Sinon.JS for awhile, so bear with me if I haven't read all the discussions in all the issues and have missed something.

While it's admirable to consider catering for Windows users, I don't think we have that many Windows users as contributors to the project. I tried to search the issues tracked here, and haven't been able to find anything recent involving contributors using Windows. If there are contributors using Windows, then they're uncharacteristically quiet about it.

For my 2px, I think it is sufficient to support Unix based systems, at least for the time being.

My preference would be to have a `Makefile` that uses unix tools and makes calls to node tools (browserify, uglifyjs).

**Comment by mantoni** [comment]
I agree that unix is good enough when it comes to the more advanced scripts like the release process. It would be nice to have Windows support for linting and running tests on node, just to not scare them away entirely ;-)

**Comment by fatso83** [comment]
Good, that aligns with my thoughts as well. I am thinking that everyone should be able to _contribute_ (tests and linting), but we don't need to cater for everyone to _release_ the best. And really; if one is doing any js development one probably has Cygwin or a Linux VM close by anyhow, so Bash scripts and Makefiles are not show stoppers (big at least).

I am also very much for keeping complexity in a Makefile, simply delegating out from npm scripts. I could have a stab at it? I just did not want to invest energy in keeping absolutely everything platform agnostic, if a simpler solution was fine.

I'll try a Makefile solution, with a handful of the targets callable from `npm`. Any other ideas, things that I should consider putting into it? I am not entirely sure what to do with the various existing scripts . I might rip of fabc40f22ad21e951530721c032592b5021e9aa9, which removes the Ruby script in favor of a short version, and use some cross platforms tools (like `rimraf`) to make it work on both BSD and GNU, but otherwise I thought we could just stuff it in `./scripts` and call it from the makefile.

**Comment by mroderick** [comment]
I am considering building the new documentation website using Jekyll, but I don't think that should affect our decision to get rid of ruby for the build process that builds the JavaScript files.

**Comment by mantoni** [comment]
The build script as well as the website have been replaced. Closing.
