### ISSUE TITLE
Mock's behavior with connected once functions is surprising

### ISSUE THREAD

**Issue by yaronyg** [sinonjs/sinon#984]
``` Javascript
  var foo = { m: function () {}};
  var mock = sinon.mock(foo);
  mock.expects('m').once().withExactArgs(23).returns(23).once().withExactArgs(45).returns(45);
  console.log(foo.m(45));
  console.log(foo.m(23));
  mock.verify();
```

This test fails, but for the wrong reason. What seems to be happening is that if one strings together multiple once's in the same call then only the last one is remembered. So this test fails because I get an unexpected call on m(23).

Just to be complete I also tried:

``` Javascript
  var foo = { m: function () {}};
  var mock = sinon.mock(foo);
  mock.expects('m').once().withExactArgs(23).returns(23).once().withExactArgs(45).returns(45);
  console.log(foo.m(23));
  console.log(foo.m(45));
  mock.verify();
```

And it also fails because the m(23) call was unexpected. Again confirming that the last once overwrites the first once.

Personally I found this very surprising. Is this the intended behavior?

**Comment by launchcg-ztonia** [comment]
Yea, withArgs are not chainable as they do not return a reference to the 'root' of the method, they return a branched path defined with the conditional. So for example you could do
mock.expects('m').once().withArgs(5).withArgs(7)
And I'm PRETTY sure, what you really get is something that needs both a 5 and a 7 as args. Spot check me on that.

But I am certain that do do what you want, gotta declare them separately. Don't know if there's conversations around that, but I've been working with that for some time.
