### ISSUE TITLE
Add fakeServer.respondTo method for responding to single request only

### ISSUE THREAD

**Issue by carljm** [sinonjs/sinon#990]
The `fakeServer` request matching code is very nice, but with fakeServer (AFAICT) you lose the flexibility to respond to different requests at different times (on your own schedule, not according to a timer). Whenever `respond()` is called, the server will respond to all requests, responding with `404` to any request you haven't set up a specific response for.

In our tests, we sometimes have more than one pending XHR, and we want to test cases where the response to one occurs first, or the response to the other occurs first. It would be great to have a `respondTo` method on the fake server, with the same signature as `respondWith`, but that would respond only to whichever already-pending request it matches (and would raise an error if there is no matching pending request), and would ignore all other pending requests (not responding to them at all).

This isn't hard at all to implement; if the idea is accepted I would be happy to submit a PR with the implementation.

**Comment by fearphage** [comment]
I like the idea. Submit the code and tests and let's see what we can make happen.

**Comment by mroderick** [comment]
This hasn't seen any activity for more than a year. I am closing it.

If someone wants to work on the feature, they're welcome to re-open it when starting discussion.
