### ISSUE TITLE
Sinonjs.org Lacks Site Icon

### ISSUE THREAD

**Issue by machineghost** [sinonjs/sinon#999]
Here's a screenshot from my browser tab bar:

![icons](https://cloud.githubusercontent.com/assets/448908/13509169/fd3a170e-e13e-11e5-8ea7-4e54a24c473b.png)

As you can see, Backbone, Knockout, Chai, etc. all have their own unique web icons, but Sinon (second from the right) does not.  Surely a library as wonderful as Sinon deserves to be a first class web citizen with its own unique icon?

**Comment by fatso83** [comment]
Absolutely agree, but without intending to hurt anyone's feelings, I am quite confident that most of the maintainers skills are lacking in the design department. Maybe we could have a little logo design compo?

**Comment by graingert** [comment]
FYI:
> from Sinon, a relative of Odysseus described in the Aeneid (epic poem by Vergil †19 b.c. Roman poet) as the Greek who by a false tale induced the Trojans to drag the wooden horse into Troy, from Latin, from Greek Sinōn

I'm thinking a wooden pony?

**Comment by fatso83** [comment]
Ooooh, I always wondered about that name. Clever naming, @cjohansen :-) I really like the suggestion, but this is definitively not my call.

**Comment by cjohansen** [comment]
If someone comes up with a nice little wooden pony favicon, I'd be all for it!

**Comment by mroderick** [comment]
A while back, I recruited a friend to work with me on a new site ... he created some artwork.

<img width="1101" alt="messages image 3459743484" src="https://cloud.githubusercontent.com/assets/20321/13616886/12488b8a-e57c-11e5-8ea9-80a8058f55c0.png">

**Comment by mroderick** [comment]
On the new site for Sinon.JS, I meant to say

**Comment by cjohansen** [comment]
Hah, that's awesome!

**Comment by mantoni** [comment]
Nice artwork!

**Comment by machineghost** [comment]
That artwork is great!  I whipped up two favicons based on the green image (the first one includes the whole image, while the second zooms in on the face).  Both are 16x16, which is a little conservative, but I imagine the Sinon site would still want to support IE9.  If not I could make higher resolution (32x32) versions instead.

I'm no graphic artist though, so I would welcome any feedback.

![sinon favicon](https://cloud.githubusercontent.com/assets/448908/13830495/3962f7fa-eb8a-11e5-8740-444d6a871e69.png)
![sinon favicon2](https://cloud.githubusercontent.com/assets/448908/13830494/3962a944-eb8a-11e5-9235-5754d0f6d3c4.png)

The relevant HTML (assuming a favicon URL of `sinon.com/images/favicon.png`) would be:

    <link rel="icon" type="image/png" href="http://sinon.com/images/favicon.png">

**Comment by cjohansen** [comment]
http://sinonjs.org/

**Comment by mantoni** [comment]
I hope it's fine for everyone that I added the same logo to the [Sinon.js](https://github.com/sinonjs/) org page 🎈

**Comment by dexter0323** [comment]
![image](https://github.com/sinonjs/sinon/assets/14128083/05e32a01-846b-4aff-88f1-3cdbb061ae36)

**Comment by fatso83** [comment]
@dexter0323 Not sure what you meant by posting the SVG, Juan? The icon is present on the homepage as https://sinonjs.org/assets/images/favicon.png

**Comment by dexter0323** [comment]
Don't mind, thank you.
